site_name: Embroidermodder 2.0.0-alpha
site_description: Free machine embroidery software supporting a variety of formats.
copyright: Copyright (C) 2011-2024 The Embroidermodder Team
site_url: https://www.libembroidery.org/
repo_url: https://github.com/embroidermodder/embroidermodder
edit_uri: edit/main/docs/
nav:
  - 'Home': 'index.md'
  - 'Downloads': 'downloads/index.md'
  - 'About': 'about.md'
  - 'User Manual':
    - 'Introduction': 'user/intro.md'
    - 'Editing Designs': 'user/editing-designs.md'
    - 'Using Raster Images': 'user/image.md'
    - 'Batch': 'user/batch.md'
    - 'Mobile': 'user/mobile.md'
    - 'PET': 'user/pet.md'
    - 'UNIX Manpage': 'user/embroider.md'
    - 'Contributing': 'user/contributing.md'
    - 'License': 'user/license.md'
  - 'Reference Manual':
    - 'Home': 'refman/index.md'
    - 'Dedication': 'refman/dedication.md'
    - 'About': 'refman/about.md'
    - 'To Do': 'refman/todo.md'
    - 'Commands': 'refman/cad.md'
    - 'Formats': 'refman/formats.md'
    - 'Thread Tables': 'refman/thread_tables.md'
  - 'Contact': 'contact.md'
  - 'Donate': https://opencollective.com/embroidermodder
  - 'Github': https://github.com/Embroidermodder
theme:
  name: material
  language: en
  favicon: "refman/icons/app.png"
  logo: "refman/icons/app.png"
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  custom_dir: theme
  font:
    text: 'Source Serif 4'
plugins:
  - search
#  - bibtex
#    bib_file: "references.bib"
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - markdown_grid_tables
