
[about_command]
MenuName="None"
MenuPosition=0
ToolBarName="None"
ToolBarPosition=0
ToolTip="&About"
StatusTip="Displays information about this product:  ABOUT"
Alias = ["ABOUT"]

[circle_command]
MenuName=Draw
MenuPosition=8
ToolBarName=Draw
ToolBarPosition=8
ToolTip="Circle"
StatusTip="Creates a circle:  CIRCLE"
Alias=["C", "CIRCLE"]

[day_command]
MenuName=None
MenuPosition=0
ToolBarName=None
ToolBarPosition=0
ToolTip="&Day"
StatusTip="Updates the current view using day vision settings:  DAY"
Alias = ["DAY"]

[new_file_command]
MenuName="None"
Position=0
ToolBarName="None"
ToolBarPosition=0
ToolTip="&New"
StatusTip="Create a new file:  NEW"
Alias = ["NEW"]

[window_tile_command]
MenuName="None"
MenuPosition=0
ToolBarName="None"
ToolBarPosition=0
ToolTip="&Tile"
StatusTip="Tile the windows:  TILE"
Alias = ["TILE", "WINDOWTILE"]

[zoom_extents_command]
MenuName="None"
MenuPosition=0
ToolBarName="None"
ToolBarPosition=0
ToolTip="Zoom &Extents"
StatusTip="Zooms to display the drawing extents:  ZOOMEXTENTS"
Alias = ["ZOOMEXTENTS"]

[zoom_in_command]
MenuName="None"
MenuPosition=0
ToolBarName="None"
ToolBarPosition=0
ToolTip="Zoom &In"
StatusTip="Zooms to increase the apparent size of objects:  ZOOMIN"
Alias = ["ZOOMIN"]

[zoom_out_command]
MenuName="None"
MenuPosition=0
ToolBarName="None"
ToolBarPosition=0
ToolTip="Zoom &Out"
StatusTip="Zooms to decrease the apparent size of objects:  ZOOMOUT"
Alias = ["ZOOMOUT"]

[heart_command]
MenuName = "Draw"
MenuPosition = 100
ToolBarName = "Draw"
ToolBarPosition = 100
ToolTip = "&Heart"
StatusTip = "Creates a heart:  HEART"
Alias = ["HEART"]

[distance_command]
MenuName = "Tools"
MenuPosition = 7
ToolBarName = "Inquiry"
ToolBarPosition = 0
ToolTip = "&Distance"
StatusTip = "Measures the distance and angle between two points:  DIST"
Alias = ["DI", "DIST", "DISTANCE"]

[dolphin_command]
MenuName = "Draw"
Position = 100
ToolBarName = "Draw"
Position = 100
ToolTip = "&Dolphin"
StatusTip = "Creates a dolphin:  DOLPHIN"
Alias = ["DOLPHIN"]

[ellipse_command]
MenuName = "Draw"
MenuPosition = 8
ToolBarName = "Draw"
ToolBarPosition = 8
ToolTip = "Ellipse"
StatusTip = "Creates a ellipse:  ELLIPSE"
Alias = ["EL", "ELLIPSE"]

[delete_command]

[Menu]
Name=Modify
Position=5

[ToolBar]
Name=Modify
Position=0

[Tips]
ToolTip=D&elete
StatusTip=Removes objects from a drawing:  DELETE

[Prompt]
Alias=E, ERASE, DEL, DELETE


[exit_command]

[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

[Tips]
ToolTip=E&xit
StatusTip=Exit the application:  EXIT

[Prompt]
Alias=EXIT, QUIT

[help_command]
MenuName="None"
MenuPosition=0
ToolBarName="None"
Position=0
ToolTip="&Help"
StatusTip="Displays the help file:  HELP"
Alias=["?", "HELP"]

[icon128_command]

[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

[Tips]
ToolTip=Icon12&8
StatusTip=Sets the toolbar icon size to 128x128:  ICON128

[Prompt]
Alias=ICON128

[icon16_command]

[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

[Tips]
ToolTip=Icon&16
StatusTip=Sets the toolbar icon size to 16x16:  ICON16

[Prompt]
Alias=ICON16

[icon24_command]

[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

[Tips]
ToolTip=Icon&24
StatusTip=Sets the toolbar icon size to 24x24:  ICON24

[Prompt]
Alias=ICON24

[icon32_command]

[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

[Tips]
ToolTip=Icon&32
StatusTip=Sets the toolbar icon size to 32x32:  ICON32

[Prompt]
Alias=ICON32

[icon48_command]

[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

[Tips]
ToolTip=Icon&48
StatusTip=Sets the toolbar icon size to 48x48:  ICON48

[Prompt]
Alias=ICON48

[icon64_command]


[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

[Tips]
ToolTip=Icon&64
StatusTip=Sets the toolbar icon size to 64x64:  ICON64

[Prompt]
Alias=ICON64

[line_command]

[Menu]
Name=Draw
Position=0

[ToolBar]
Name=Draw
Position=0

[Tips]
ToolTip=&Line
StatusTip=Creates straight line segments:  LINE

[Prompt]
Alias=L, LINE

[locate_point_command]

[Menu]
Name=Tools
Position=11

[ToolBar]
Name=Inquiry
Position=0

[Tips]
ToolTip=&Locate Point
StatusTip=Displays the coordinate values of a location:  ID

[Prompt]
Alias=ID, LOCATEPOINT

[move_command]

[Menu]
Name=Modify
Position=10

[ToolBar]
Name=Modify
Position=5

[Tips]
ToolTip=&Move
StatusTip=Displaces objects a specified distance in a specified direction:  MOVE

[Prompt]
Alias=M, MOVE


[night_command]

MenuName="None"
MenuPosition=0
ToolBarName="None"
ToolBarPosition=0
ToolTip="&Night"
StatusTip="Updates the current view using night vision settings:  NIGHT"
Alias=["NIGHT"]


[open_command]

[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

[Tips]
ToolTip=&Open
StatusTip=Open an existing file:  OPEN

[Prompt]
Alias=OPEN


[pan_down_command]

[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

[Tips]
ToolTip=&Pan Down
StatusTip=Moves the view down:  PANDOWN

[Prompt]
Alias=PANDOWN


[pan_left_command]


[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

[Tips]
ToolTip=&Pan Left
StatusTip=Moves the view to the left:  PANLEFT

[Prompt]
Alias=PANLEFT


[pan_right_command]

[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

[Tips]
ToolTip=&Pan Right
StatusTip=Moves the view to the right:  PANRIGHT

[Prompt]
Alias=PANRIGHT

[pan_up_command]


[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

[Tips]
ToolTip=&Pan Up
StatusTip=Moves the view up:  PANUP

[Prompt]
Alias=PANUP

[path_command]


[Menu]
Name=Draw
Position=4

[ToolBar]
Name=Draw
Position=4

[Tips]
ToolTip=&Path
StatusTip=Creates a 2D path:  PATH

[Prompt]
Alias=PA, PATH

[platform_command]

[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

[Tips]
ToolTip=&Platform
StatusTip=List which platform is in use:  PLATFORM

[Prompt]
Alias=PLATFORM


[point_command]

[Menu]
Name=Draw
Position=10

[ToolBar]
Name=Draw
Position=10

[Tips]
ToolTip=&Point
StatusTip=Creates multiple points:  POINT

[Prompt]
Alias=PO, POINT

[polygon_command]


[Menu]
Name=Draw
Position=4

[ToolBar]
Name=Draw
Position=4

[Tips]
ToolTip=Pol&ygon
StatusTip=Creates a regular polygon:  POLYGON

[Prompt]
Alias=POL, POLYGON

[polyline_command]


[Menu]
Name=Draw
Position=4

[ToolBar]
Name=Draw
Position=4

[Tips]
ToolTip=&Polyline
StatusTip=Creates a 2D polyline:  PLINE

[Prompt]
Alias=PL, PLINE, POLYLINE

[quickleader_command]

[Menu]
Name=Dimension
Position=12

[ToolBar]
Name=Dimension
Position=12

[Tips]
ToolTip=&QuickLeader
StatusTip=Creates a leader and annotation:  QUICKLEADER

[Prompt]
Alias=LE, LEADER, QLEADER, QUICKLEADER

[rectangle_command]

[Menu]
Name=Draw
Position=6

[ToolBar]
Name=Draw
Position=6

[Tips]
ToolTip=&Rectangle
StatusTip=Creates a rectangular polyline: RECTANGLE

[Prompt]
Alias=REC, RECT, RECTANG, RECTANGLE

[redo_command]
//Command: Redo

[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

[Tips]
ToolTip=&Redo
StatusTip=Reverses the effects of the previous undo action:  REDO

[Prompt]
Alias=REDO

[rgb_command]

[Menu]
Name=Sandbox
Position=4

[ToolBar]
Name=Sandbox
Position=3

[Tips]
ToolTip=&RGB
StatusTip=Updates the current view colors:  RGB

[Prompt]
Alias=RGB

[rotate_command]

[Menu]
Name=Modify
Position=11

[ToolBar]
Name=Modify
Position=6

[Tips]
ToolTip=&Rotate
StatusTip=Rotates objects about a base point:  ROTATE

[Prompt]
Alias=RO, ROTATE

[sandbox_command]

[Menu]
Name=Sandbox
Position=100

[ToolBar]
Name=Sandbox
Position=100

[Tips]
ToolTip=Sandbox
StatusTip=A sandbox to play in:  SANDBOX

[Prompt]
Alias=SAND, SANDBOX

[scale_command]

[Menu]
Name=Modify
Position=12

[ToolBar]
Name=Modify
Position=7

[Tips]
ToolTip=Sca&le
StatusTip=Enlarges or reduces objects proportionally in the X, Y, and Z directions:  SCALE

[Prompt]
Alias=SC, SCALE

[SelectAll_command]

[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

[Tips]
ToolTip=&Select All
StatusTip=Selects all objects:  SELECTALL

[Prompt]
Alias=AI_SELALL, SELALL, SELECTALL

[single_line_text_command]

[Menu]
Name=Draw
Position=18

[ToolBar]
Name=Draw
Position=16

[Tips]
ToolTip=&Single Line Text
StatusTip=Creates single-line text objects:  TEXT

[Prompt]
Alias=DT, DTEXT, TEXT, SINGLELINETEXT

[snowflake_command]

[Menu]
Name=Draw
Position=100

[ToolBar]
Name=Draw
Position=100

[Tips]
ToolTip=&Snowflake
StatusTip=Creates a snowflake:  SNOWFLAKE

[Prompt]
Alias=SNOWFLAKE

[star_command]

[Menu]
Name=Draw
Position=100

[ToolBar]
Name=Draw
Position=100

[Tips]
ToolTip=&Star
StatusTip=Creates a star:  STAR

[Prompt]
Alias=*, STAR

[syswindows_command]

[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

[Tips]
ToolTip=&SysWindows
StatusTip=Arrange the windows:  SYSWINDOWS

[Prompt]
Alias=WINDOWS, SYSWINDOWS

//Command: TipOfTheDay

[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

[Tips]
ToolTip=&Tip Of The Day
StatusTip=Displays a dialog with useful tips:  TIPS

[Prompt]
Alias=TIPS, TIPOFTHEDAY

[Command: Undo]

[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

[Tips]
ToolTip=&Undo
StatusTip=Reverses the most recent action:  UNDO

[Prompt]
Alias=U, UNDO

[Command: WindowCascade]

[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

[Tips]
ToolTip=&Cascade
StatusTip=Cascade the windows:  CASCADE

[Prompt]
Alias=CASCADE, WINDOWCASCADE

[Command: WindowClose]

[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

[Tips]
ToolTip=Cl&ose
StatusTip=Close the active window:  CLOSE

[Prompt]
Alias=CLOSE, WINDOWCLOSE

[Command: WindowCloseAll]

[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

[Tips]
ToolTip=Close &All
StatusTip=Close all the windows:  CLOSEALL

[Prompt]
Alias=CLOSEALL, WINDOWCLOSEALL

[Command: WindowNext]

[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

ToolTip = "Ne&xt"
StatusTip = "Move the focus to the next window:  NEXT"
Alias = ["NEXT", "WINDOWNEXT"]

[Command: WindowPrevious]

[Menu]
Name=None
Position=0

[ToolBar]
Name=None
Position=0

ToolTip = "Pre&vious"
StatusTip = Move the focus to the previous window:  PREVIOUS"
Alias = ["PREV", "PREVIOUS", "WINDOWPREVIOUS"]
