#
#  Embroidermodder 2.
#
#  ____________________________________________________________
#
#  Copyright 2013_2022 The Embroidermodder Team
#  Embroidermodder 2 is Open Source Software.
#  See LICENSE for licensing terms.
#
#  ____________________________________________________________
#

version = "2.0.0-alpha"

translation_files = [
    "translations/afrikaans.toml",
    "translations/arabic.toml",
    "translations/chinese_traditional.toml",
    "translations/chinese_simplified.toml",
    "translations/czech.toml",
    "translations/dutch.toml",
    "translations/finnish.toml",
    "translations/hindi.toml",
    "translations/polish.toml",
    "translations/spanish.toml",
    "translations/danish.toml",
    "translations/french.toml",
    "translations/italian.toml",
    "translations/portuguese.toml",
    "translations/swedish.toml",
    "translations/german.toml",
    "translations/japanese.toml",
    "translations/romanian.toml",
    "translations/turkish.toml",
    "translations/english_gb.toml",
    "translations/greek.toml",
    "translations/korean.toml",
    "translations/russian.toml"
]
design_files = [
    "designs/dolphin.toml",
    "designs/heart4.toml",
    "designs/heart5.toml",
    "designs/snowflake.toml",
    "designs/star.toml",
    "designs/treble_clef.toml"
]
ui_files = [
    "ui/actions.toml",
    "ui/property_editor.toml",
    "ui/settings_editor.toml"
]

menu_layout = [
    ["File", "file_menu"],
    ["Open Recent", "open_recent_menu"],
    ["Edit", "edit_menu"],
    ["View", "view_menu"],
    ["Zoom", "zoom_menu"],
    ["Pan", "pan_menu"],
    ["Tools", "tools_menu"],
    ["Draw", "draw_menu"],
    ["Settings", "settings_menu"],
    ["Help", "help_menu"],
    ["Window", "window_menu"]
]

file_menu = [
    ["New", "new"],
    ["Open", "open"],
    ["Open Recent", "submenu"],
    ["---", "---"],
    ["Save", "save"],
    ["Save As...", "saveas"],
    ["Export", "export"],
    ["---", "---"],
    ["Print", "print"],
    ["---", "---"],
    ["Close", "close"],
    ["---", "---"],
    ["Details", "details"],
    ["---", "---"],
    ["Quit", "quit"]
]

open_recent_menu = [
    ["None", "donothing"]
]

edit_menu = [
    ["Undo", "undo"],
    ["Redo", "redo"],
    ["---", "---"],
    ["Cut", "cut"],
    ["Copy", "copy"],
    ["Paste", "paste"]
]

view_menu = [
    ["Zoom", "submenu"],
    ["Pan", "submenu"],
    ["---", "---"],
    ["Day", "day"],
    ["Night", "night"]
]

settings_menu = [
    ["Settings...", "settingsdialog"]
]

zoom_menu = [
    ["Zoom Real Time", "zoom realtime"],
    ["Zoom Previous", "zoom previous"],
    ["---", "---"],
    ["Zoom Window", "zoom window"],
    ["Zoom Dynamic", "zoom dynamic"],
    ["Zoom Scale", "zoom scale"],
    ["Zoom Center", "zoom center"],
    ["---", "---"],
    ["Zoom In", "zoom in"],
    ["Zoom Out", "zoom out"],
    ["---", "---"],
    ["Zoom Selected", "zoom selected"],
    ["Zoom All", "zoom all"],
    ["Zoom Extents", "zoom extents"]
]

pan_menu = [
    ["Pan Real Time", "pan realtime"],
    ["Pan Point", "pan point"],
    ["---", "---"],
    ["Pan Left", "pan left"],
    ["Pan Right", "pan right"],
    ["Pan Up", "pan up"],
    ["Pan Down", "pan down"]
]

help_menu = [
    ["Help", "help"],
    ["---", "---"],
    ["Changelog", "changelog"],
    ["---", "---"],
    ["Tip of the Day", "tip-of-the-day"],
    ["---", "---"],
    ["About", "about"],
    ["---", "---"],
    ["What's This?", "whatsthis"]
]

draw_menu = [
    ["Circle", "circle 10.0 10.0 50.0 0"],
    ["Ellipse", "ellipse"],
    ["Rectangle", "rectangle"],
    ["Polyline", "polyline"],
    ["Polygon", "polygon"],
    ["Dolphin", "dolphin"],
    ["Star", "star"],
    ["Treble Clef", "trebleclef"]
]

tools_menu = [
    ["Statistics", "statistics"],
    ["Distance", "distance"],
    ["Simulate", "simulate"],
    ["Text Editor", "editor"],
    ["Histogram", "histogram"],
    ["Real Render", "real-render"],
    ["Auto Stitch", "autostitch"],
    ["Stitch Fill", "stitch-fill"]
]

window_menu = [
    ["Close", "window close"],
    ["Close All", "window closeall"],
    ["---", "---"],
    ["Cascade", "window cascade"],
    ["Tile", "window tile"],
    ["---", "---"],
    ["Next", "window next"],
    ["Previous", "window previous"],
    ["---", "---"]
]

toolbar_layout = [
    ["File", "file_toolbar"],
    ["Edit", "edit_toolbar"],
    ["View", "view_toolbar"],
    ["Zoom", "zoom_toolbar"],
    ["Pan", "pan_toolbar"],
    ["Icon", "icon_toolbar"],
    ["Help", "help_toolbar"],
    ["Layer", "layer_toolbar"],
    ["Properties", "properties_toolbar"],
    ["Text", "text_toolbar"],
    ["Draw", "draw_toolbar"],
    ["Inquiry", "inquiry_toolbar"]
]

# ["icon", "command"]
file_toolbar = [
    ["new", "new"],
    ["open", "open"],
    ["save", "save"],
    ["saveas", "saveas"],
    ["print", "print"],
    ["designdetails", "designdetails"]
]

edit_toolbar = [
    ["undo", "undo"],
    ["redo", "redo"],
    ["cut", "cut"],
    ["copy", "copy"],
    ["paste", "paste"]
]

view_toolbar = [
    ["day", "day"],
    ["night", "night"]
]

zoom_toolbar = [
    ["zoomwindow", "zoom window"],
    ["zoomdynamic", "zoom dynamic"],
    ["zoomscale", "zoom scale"],
    ["zoomcenter", "zoom center"],
    ["zoomin", "zoom in"],
    ["zoomout", "zoom out"],
    ["zoomselected", "zoom selected"],
    ["zoomall", "zoom all"],
    ["zoomextents", "zoom extents"]
]

draw_toolbar = [
    ["arc", "arc"],
    ["circle", "circle 10.0 10.0 50.0 0"],
    ["ellipse", "ellipse"],
    ["rectangle", "rectangle"],
    ["dolphin", "dolphin"],
    ["trebleclef", "trebleclef"]
]

inquiry_toolbar = [
    ["details", "details"],
    ["distance", "distance"]
]

pan_toolbar = [
    ["panrealtime", "panrealtime"],
    ["panpoint", "panpoint"],
    ["panleft", "pan left"],
    ["panright", "pan right"],
    ["panup", "pan up"],
    ["pandown", "pan down"]
]

layer_toolbar = [
    ["layers", "layers"],
    ["make-layer-current", "make-layer-current"]
]

properties_toolbar = [
    ["make-layer-current", "make-layer-current"]
]

text_toolbar = [
    ["textbold", "toggle text-bold"],
    ["textitalic", "toggle text-italic"],
    ["textunderline", "toggle text-underline"],
    ["textoverline", "toggle text-overline"],
    ["textstrikeout", "toggle text-strikeout"]
]

icon_toolbar = [
    ["icon16", "icon16"],
    ["icon24", "icon24"],
    ["icon32", "icon32"],
    ["icon48", "icon48"],
    ["icon64", "icon64"],
    ["icon128", "icon128"]
]

help_toolbar = [
    ["help", "help"],
    ["changelog", "changelog"],
    ["about", "about"],
    ["whatsthis", "whatsthis"]
]

texture_list = [
    ["3dviews", "icons/default/3dviews.png"],
    ["about", "icons/default/about.png"],
    ["app", "icons/default/app.png"],
    ["arc", "icons/default/arc.png"],
    ["arc3points", "icons/default/arc3points.png"],
    ["changelog", "icons/default/changelog.png"],
    ["circle", "icons/default/circle.png"],
    ["copy", "icons/default/copy.png"],
    ["cut", "icons/default/cut.png"],
    ["day", "icons/default/day.png"],
    ["designdetails", "icons/default/designdetails.png"],
    ["dolphin", "icons/default/dolphin.png"],
    ["ellipse", "icons/default/ellipse.png"],
    ["icon16", "icons/default/icon16.png"],
    ["icon24", "icons/default/icon24.png"],
    ["icon32", "icons/default/icon32.png"],
    ["icon48", "icons/default/icon48.png"],
    ["icon64", "icons/default/icon64.png"],
    ["icon128", "icons/default/icon128.png"],
    ["help", "icons/default/help.png"],
    ["layerprevious", "icons/default/layerprevious.png"],
    ["layers", "icons/default/layers.png"],
    ["layerselector", "icons/default/layerselector.png"],
    ["new", "icons/default/new.png"],
    ["night", "icons/default/night.png"],
    ["open", "icons/default/open.png"],
    ["pandown", "icons/default/pandown.png"],
    ["panleft", "icons/default/panleft.png"],
    ["panpoint", "icons/default/panpoint.png"],
    ["panrealtime", "icons/default/panrealtime.png"],
    ["panright", "icons/default/panright.png"],
    ["panup", "icons/default/panup.png"],
    ["paste", "icons/default/paste.png"],
    ["print", "icons/default/print.png"],
    ["rectangle", "icons/default/rectangle.png"],
    ["redo", "icons/default/redo.png"],
    ["save", "icons/default/save.png"],
    ["saveas", "icons/default/saveas.png"],
    ["textbold", "icons/default/textbold.png"],
    ["textitalic", "icons/default/textitalic.png"],
    ["textoverline", "icons/default/textoverline.png"],
    ["textstrikeout", "icons/default/textstrikeout.png"],
    ["textunderline", "icons/default/textunderline.png"],
    ["undo", "icons/default/undo.png"],
    ["whatsthis", "icons/default/whatsthis.png"],
    ["zoom", "icons/default/zoom.png"],
    ["zoomall", "icons/default/zoomin.png"],
    ["zoomcenter", "icons/default/zoomcenter.png"],
    ["zoomdynamic", "icons/default/zoomdynamic.png"],
    ["zoomextents", "icons/default/zoomextents.png"],
    ["zoomin", "icons/default/zoomin.png"],
    ["zoomout", "icons/default/zoomout.png"],
    ["zoomprevious", "icons/default/zoomprevious.png"],
    ["zoomrealtime", "icons/default/zoomrealtime.png"],
    ["zoomselected", "icons/default/zoomselected.png"],
    ["zoomscale", "icons/default/zoomscale.png"],
    ["zoomwindow", "icons/default/zoomwindow.png"],
    ["texture-spirals", "images/texture-spirals.png"]
]

action_list = [
    
]

tips = [
    "we need more tips?",
    "you can change the color of the display through settings?",
    "you can hide the scrollbars to increase the viewable area through settings?",
    "you can change the icon size for increased visibility?",
    "you can toggle the grid on and off by pressing the button in the statusbar?",
    "the grid size can be changed to match your hoop size through settings?",
    "the crosshair size is based on a percentage of your screen size? Setting it to 100 may help you visually line things up better.",
    "you can pan by pressing the middle mouse button and dragging your mouse across the screen?",
    "you can open and edit multiple designs simultaneously?",
    "you that many embroidery machines support the .dst format?",
    "that you can zoom in and out using your mouse wheel?",
    "that you can use circular and isometric grids?",
    "about our command line format converter?",
    "that you can use the 'DAY' and 'NIGHT' commands to quickly switch the view colors to commonly used white or black?",
    "that you can quickly change the background, crosshair and grid colors using the 'RGB' command?"
]

# For these transformations, we need to store the relavant data that isn't
# in the command itself. For example if you delete an object then reference
# to the object is passed, not the object itself. So we need to put that object
# in a deleted objects buffer for later access. Therefore the opposite of
# delete is a new command restore.
#
undo_table = [
    ["pan left", "pan right"],
    ["pan right", "pan left"],
    ["pan up", "pan down"],
    ["pan down", "pan up"],
    ["zoom in", "zoom out"],
    ["zoom out", "zoom in"],
    ["scale $1", "scale 1.0/$1"],
    ["add $@", "remove $1"],
    ["delete $1", "restore $1"],
    ["restore $1", "delete $1"],
    ["move $1 $2", "move -$1 -$2"],
    ["rotate $1 $2 $3", "rotate $1 $2 -$3"],
    ["mirror $1 $2 $3 $4", "mirror $1 $2 $3 $4"],
    ["grip-edit $1 $2 $3 $4", "grip-edit $3 $4 $1 $2"]
]


[general]
window_position_x = 0
window_position_y = 0
window_size_x = 800
window_size_y = 600
language = "default"
icon_theme = "default"
icon_size = 16
mdi_bg_use_logo = true
mdi_bg_use_texture = true
mdi_bg_use_color = true
mdi_bg_logo = "./images/logo_spirals.png"
mdi_bg_texture = "./images/texture_spirals.png"
mdi_bg_color = [192, 192, 192]
tip_of_the_day = true
current_tip = 0
system_help_browser = true

[display]
use_opengl = false
renderhint_aa = false
renderhint_smooth_pix = false
renderhint_high_aa = false
renderhint_noncosmetic = false
show_scrollbars = true
scrollbar_widget_num = 0
crosshair_color = [0,  0,  0]
bg_color = [235, 235, 235]
selectbox_left_color = [0, 128, 0]
selectbox_left_fill = [0, 255,  0]
selectbox_right_color = [0, 0, 128]
selectbox_right_fill = [0, 0, 255]
selectbox_alpha = 32
zoomscale_in = 2.0
zoomscale_out = 0.5
crosshair_percent = 5
units = "mm"

[prompt]
color = [0,  0,  0]
bg_color = [255, 255, 255]
font_family = "Monospace"
font_style = "normal"
font_size = 12
save_history = true
save_history_as_html = false
save_history_filename = "./prompt.log"

[opensave]
custom_filter = "supported"
open_format = "*.*"
open_thumbnail = false
save_format = "*.*"
save_thumbnail = false

[recent]
max_files = 10
list_of_files = []
directory = "./samples"

[trimming]
trim_dst_num_jumps = 5

[printing]
printing_default_device = ""
printing_use_last_device = false
printing_disable_bg = true

[grid]
show_on_load = true
show_origin = true
color_match_crosshair = true
color = [0, 0, 0]
load_from_file = true
type = "Rectangular"
center_on_origin = true
center_x = 0.0
center_y = 0.0
size_x = 100.0
size_y = 100.0
spacing_x = 25.0
spacing_y = 25.0
size_radius = 50.0
spacing_radius = 25.0
spacing_angle = 45.0

[ruler]
ruler_show_on_load = true
ruler_metric = true
ruler_color = [210,210, 50]
ruler_pixel_size = 20

[qsnap]
enabled = true
locator_color = [255, 255, 0]
locator_size = 4
aperture_size = 10
endpoint = true
midpoint = true
center = true
node = true
quadrant = true
intersection = true
extension = true
insertion = false
perpendicular = true
tangent = true
nearest = false
apparent = false
parallel = false

[lineweight]
lwt_show_lwt = false
lwt_real_render = true
lwt_default_lwt = 0

[selection]
selection_mode_pickfirst = true
selection_mode_pickadd = true
selection_mode_pickdrag= false
selection_coolgrip_color = [0, 0, 255]
selection_hotgrip_color = [255, 0, 0]
selection_grip_size = 4
selection_pickbox_size = 4

[text]
font = "Arial"
size = 12.0
angle = 0.0
bold = false
italic = false
underline = false
strikeout = false
overline= false

crash_test = [
    "do-nothing",
    "debug-message File actions",
    "new-file",
    "# Need to set the filename here.",
    "open-file",
    "save-file",
    "save-file-as",

    "debug-message Edit actions",
    "# Place some objects to alter here.",
    "cut",
    "copy",
    "paste",

    "debug-message Configuring the UI.",
    "icon 24",
    "icon 32",
    "icon 48",
    "icon 64",
    "icon 128",
    "icon 16"
]
boot-message = """
 _____________________________________________________________
|                 EMBROIDERMODDER 2.0.0-alpha                 |
|                  http://libembroidery.org                   |
|-------------------------------------------------------------|
|        Copyright 2013-2022 The Embroidermodder Team         |
|       Distributed under the terms of the zlib license.      |
|_____________________________________________________________|
"""
greig-message = """\
Hi there. If you are not a developer, report this as a bug. \
If you are a developer, your code needs examined, \
and possibly your head too.\
"""
help-message = """
Usage: embroidermodder [options] files ...

Options:
  -d, --debug      Print lots of debugging information.
  -h, --help       Print this message and exit.
  -v, --version    Print the version number of embroidermodder and exit.
"""

[dolphin]
type = "design"
label = "Dolphin"
shape-def = "designs/dolphin.ps"
num-points = 512
scale-x = 0.04
scale-y = 0.04
description = "Adds a dolphin design to the vector layer."

[heart4]
type = "design"
label = "heart4"
num-points = 100
scale-x = 1.0
scale-y = 1.0
decorated-label = "&Heart4"
description = "Adds a heart to the vector layer: heart4."
shape-def = "designs/heart4.ps"

#  System Specific Overrides
#

[android]
type = "system-overrides"
em2_version = "Android Version"
assets_directory = "/usr/share/embroidermodder"
os_seperator = "/"

[ios]
type = "system-overrides"
em2_version = "iOS version"
assets_directory = "/usr/share/embroidermodder"
os_seperator = "/"

[linux]
type = "system-overrides"
em2_version = "X11 version"
assets_directory = "/usr/share/embroidermodder"
os_seperator = "/"

[macos]
type = "system-overrides"
em2_version = "Mac OS Cocoa version"
assets_directory = "/usr/share/embroidermodder"
os_seperator = "/"

[win32]
type = "system-overrides"
em2_version = "Win32 version"
assets_directory = "C:\\ProgramData\\embroidermodder"
os_seperator = "\\"
