site_name: Embroidermodder 2.0.0-alpha
site_description: Free machine embroidery software supporting a variety of formats.
copyright: Copyright (C) 2011-2024 The Embroidermodder Team
site_url: https://www.libembroidery.org/
repo_url: https://github.com/embroidermodder/embroidermodder
edit_uri: edit/main/docs/
nav:
  - 'Home': /
  - 'Downloads': downloads
  - 'About': about
  - 'User Manual':
    - 'Introduction': user/em2
    - 'UNIX Manpage': user/embroider
  - 'Reference Manual':
    - 'Home': refman
    - 'Dedication': refman/dedication
    - 'About': refman/about
    - 'To Do': refman/todo
    - 'CAD Commands': refman/cad
    - 'Thread Tables': refman/thread_table
  - 'Contact': contact
  - 'Donate': https://opencollective.com/embroidermodder
  - 'Github': https://github.com/Embroidermodder
theme:
  name: material
  custom_dir: theme
  font:
    text: 'Source Serif 4'
plugins:
  - search
#  - bibtex
#    bib_file: "references.bib"
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
