#  Embroidermodder 2.
#
#  ------------------------------------------------------------
#
#  Copyright 2013-2023 The Embroidermodder Team
#  Embroidermodder 2 is Open Source Software.
#  See LICENSE for licensing terms.
#
#  ------------------------------------------------------------

file_toolbar = [
    "new",
    "open",
    "save",
    "saveas",
    "print",
    "designdetails",
    "---",
    "undo",
    "redo",
    "---",
    "help"
]

edit_toolbar = "cut copy paste"
view_toolbar = "day night"
zoom_toolbar = "zoomwindow zoomdynamic zoomscale --- zoomcenter zoomin zoomout --- zoomselected zoomall zoomextents"
pan_toolbar = "panrealtime panpoint --- panleft panright panup pandown"
icon_toolbar = "icon16 icon24 icon32 icon48 icon64 icon128"
help_toolbar = "help --- changelog --- about --- whatsthis"

group_box_list = [
    "general",
    "geometry_arc",
    "misc_arc",
    "geometry_block",
    "geometry_circle",
    "geometry_dim_aligned",
    "geometry_dim_angular",
    "geometry_dim_arc_length",
    "geometry_dim_diameter",
    "geometry_dim_leader",
    "geometry_dim_linear",
    "geometry_dim_ordinate",
    "geometry_dim_radius",
    "geometry_ellipse",
    "geometry_image",
    "misc_image",
    "geometry_infinite_line",
    "geometry_line",
    "geometry_path",
    "misc_path",
    "geometry_point",
    "geometry_polygon",
    "geometry_polyline",
    "misc_polyline",
    "geometry_ray",
    "geometry_rectangle",
    "geometry_text_multi",
    "text_text_single",
    "geometry_text_single",
    "misc_text_single"
]

all_line_editors = [
    "general", "general_layer", "blank", "Layer", "combobox", "false",
    "general", "general_color", "blank", "Color", "combobox", "false",
    "general", "general_line_type", "blank", "LineType", "combobox", "false",
    "general", "general_line_weight", "blank", "LineWeight", "combobox", "false",

    "geometry_arc", "arc_center_x", "blank", "Center X", "double", "lineEditArcCenterX",
    "geometry_arc", "arc_center_y", "blank", "Center Y", "double", "lineEditArcCenterY",
    "geometry_arc", "arc_radius", "blank", "Radius", "double", "lineEditArcRadius",
    "geometry_arc", "arc_start_angle", "blank", "Start Angle", "double", "lineEditArcStartAngle",
    "geometry_arc", "arc_end_angle", "blank", "End Angle", "double", "lineEditArcEndAngle",
    "geometry_arc", "arc_start_x", "blank", "Start X", "double", "",
    "geometry_arc", "arc_start_y", "blank", "Start Y", "double", "",
    "geometry_arc", "arc_end_x", "blank", "End X", "double", "",
    "geometry_arc", "arc_end_y", "blank", "End Y", "double", "",
    "geometry_arc", "arc_area", "blank", "Area", "double", "",
    "geometry_arc", "arc_length", "blank", "Arc Length", "double", "",
    "geometry_arc", "arc_chord", "blank", "Chord", "double", "",
    "geometry_arc", "arc_inc_angle", "blank", "Included Angle", "double",  "",

    "misc_arc", "arc-clockwise", "blank", "Clockwise", "combobox", "true",

    "geometry_block", "block-x", "blank", "Position X", "double", "",
    "geometry_block", "block-y", "blank", "Position Y", "double", "",

    "geometry_circle", "circle_center_x", "blank", "Center X", "double", "lineEditCircleCenterX",
    "geometry_circle", "circle_center_y", "blank", "Center Y", "double", "lineEditCircleCenterY",
    "geometry_circle", "circle_radius", "blank", "Radius", "double", "lineEditCircleRadius",
    "geometry_circle", "circle_diameter", "blank", "Diameter", "double", "lineEditCircleDiameter",
    "geometry_circle", "circle_area", "blank", "Area", "double", "lineEditCircleArea",
    "geometry_circle", "circle_circumference", "blank", "Circumference", "double", "lineEditCircleCircumference",

    "geometry_dim_aligned", "dim-aligned-x", "blank", "Position X", "double", "",

    "geometry_dim_angular", "dim-angular-x", "blank", "Position X", "double", "",

    "geometry_dim_arc_length", "dim-arc-length-x", "blank", "Position X", "double", "",

    "geometry_dim_diameter", "dim-diameter-x", "blank", "Position X", "double", "",

    "geometry_dim_leader", "dim-linear-x", "blank", "Position X", "double", "",

    "geometry_dim_linear", "dim-linear-x", "blank", "Position X", "double", "",

    "geometry_dim_ordinate", "dim-ordinate-x", "blank", "Position X", "double", "",

    "geometry_dim_radius", "dim-radius-x", "blank", "Position X", "double", "",

    "geometry_ellipse", "ellipse_center_x", "blank", "Center X", "double", "lineEditEllipseCenterX",
    "geometry_ellipse", "ellipse_center_y", "blank", "Center Y", "double", "lineEditEllipseCenterY",
    "geometry_ellipse", "ellipse_semi_major_axis", "blank", "Semi-Major Axis", "double", "lineEditEllipseSemiMajorAxis",
    "geometry_ellipse", "ellipse_semi_minor_axis", "blank", "Semi-Minor Axis", "double", "lineEditEllipseSemiMinorAxis",
    "geometry_ellipse", "ellipse_major_axis", "blank", "Major Axis", "double", "lineEditEllipseMajorAxis",
    "geometry_ellipse", "ellipse_minor_axis", "blank", "Minor Axis", "double", "lineEditEllipseMinorAxis",

    "geometry_image", "image-x", "blank", "Position X", "double", "",
    "geometry_image", "image-y", "blank", "Position Y", "double", "",
    "geometry_image", "image-width", "blank", "Width", "double", "",
    "geometry_image", "image-height", "blank", "Height", "double", "",

    "misc_image", "image-name", "blank", "Name", "double", "",
    "misc_image", "image-path", "blank", "Path", "double", "",

    "geometry_infinite_line", "infinite-line-x1", "blank", "Start X", "double", "lineEditInfiniteLineX1",
    "geometry_infinite_line", "infinite-line-y1", "blank", "Start Y", "double", "lineEditInfiniteLineY1",
    "geometry_infinite_line", "infinite-line-x2", "blank", "2nd X", "double", "lineEditInfiniteLineX2",
    "geometry_infinite_line", "infinite-line-y2", "blank", "2nd Y", "double", "lineEditInfiniteLineY2",
    "geometry_infinite_line", "infinite-line-vector-x", "blank", "Vector X", "double", "",
    "geometry_infinite_line", "infinite-line-vector-y", "blank", "Vector Y", "double", "",

    "geometry_line", "line-start-x", "blank", "Start X", "double", "lineEditLineStartX",
    "geometry_line", "line-start-y", "blank", "Start Y", "double", "lineEditLineStartY",
    "geometry_line", "line-end-x", "blank", "End X", "double", "lineEditLineEndX",
    "geometry_line", "line-end-y", "blank", "End Y", "double", "lineEditLineEndY",
    "geometry_line", "line-delta-x", "blank", "Delta X", "double", "",
    "geometry_line", "line-delta-y", "blank", "Delta Y", "double", "",
    "geometry_line", "line-angle", "blank", "Angle", "double", "",
    "geometry_line", "line-length", "blank", "Length", "double", "",

    "geometry_path", "path_vertex_num", "blank", "Vertex #", "combobox", "",
    "geometry_path", "path_vertex_x", "blank", "Vertex X", "double", "",
    "geometry_path", "path_vertex_y", "blank", "Vertex Y", "double", "",
    "geometry_path", "path_area", "blank", "Area", "double", "",
    "geometry_path", "path_length", "blank", "Length", "double", "",

    "misc_path", "path_closed", "blank", "Closed", "combobox", "",

    "geometry_point", "point_x", "blank", "Position X", "double", "lineEditPointX",
    "geometry_point", "point_y", "blank", "Position Y", "double", "lineEditPointY",

    "geometry_polygon", "polygon_center_x", "blank", "Center X", "double", "",
    "geometry_polygon", "polygon_center_y", "blank", "Center Y", "double", "",
    "geometry_polygon", "polygon-radius-vertex", "blank", "Vertex Radius", "double", "",
    "geometry_polygon", "polygon-radius-side", "blank", "Side Radius", "double", "",
    "geometry_polygon", "polygon-diameter-vertex", "blank", "Vertex Diameter", "double", "",
    "geometry_polygon", "polygon-diameter-side", "blank", "Side Diameter", "double", "",
    "geometry_polygon", "polygon-interior-angle", "blank", "Interior Angle", "double", "",

    "geometry_polyline", "polyline-vertex-num", "blank", "Vertex #", "combobox", "false",
    "geometry_polyline", "polyline-vertex-x", "blank", "Vertex X", "double", "",
    "geometry_polyline", "polyline-vertex-y", "blank", "Vertex Y", "double", "",
    "geometry_polyline", "polyline-vertex-area", "blank", "Area", "double", "",
    "geometry_polyline", "polyline-vertex-length", "blank", "Length", "double", "",

    "misc_polyline", "polyline-vertex-closed", "blank", "Closed", "combobox", "false",

    "geometry_ray", "ray-x1", "blank", "Start X", "double", "",
    "geometry_ray", "ray-y1", "blank", "Start Y", "double", "",
    "geometry_ray", "ray-x2", "blank", "2nd X", "double", "",
    "geometry_ray", "ray-y2", "blank", "2nd Y", "double", "",
    "geometry_ray", "ray-vector-x", "blank", "Vector X", "double", "",
    "geometry_ray", "ray-vector-y", "blank", "Vector Y", "double", "",

    "geometry_rectangle", "rectangle_corner1_x", "blank", "Corner 1 X", "double", "",
    "geometry_rectangle", "rectangle_corner1_y", "blank", "Corner 1 Y", "double", "",
    "geometry_rectangle", "rectangle_corner2_x", "blank", "Corner 2 X", "double", "",
    "geometry_rectangle", "rectangle_corner2_y", "blank", "Corner 2 Y", "double", "",
    "geometry_rectangle", "rectangle_corner3_x", "blank", "Corner 3 X", "double", "",
    "geometry_rectangle", "rectangle_corner3_y", "blank", "Corner 3 Y", "double", "",
    "geometry_rectangle", "rectangle_corner4_x", "blank", "Corner 4 X", "double", "",
    "geometry_rectangle", "rectangle_corner4_y", "blank", "Corner 4 Y", "double", "",
    "geometry_rectangle", "rectangle_width", "blank", "Width", "double", "",
    "geometry_rectangle", "rectangle_height", "blank", "Height", "double", "",
    "geometry_rectangle", "rectangle_area", "blank", "Area", "double", "",

    "text_text_single", "text-single-contents", "blank", "Contents", "string", "lineEditTextSingleContents",
    "text_text_single", "text-single-font", "blank", "Font", "fontcombobox", "comboBoxTextSingleFont",
    "text_text_single", "text-single-justify", "blank", "Justify", "combobox", "comboBoxTextSingleJustify",
    "text_text_single", "text-single-height", "blank", "Height", "double", "lineEditTextSingleHeight",
    "text_text_single", "text-single-rotation", "blank", "Rotation", "double", "lineEditTextSingleRotation",

    "geometry_text_single", "text-single-x", "blank", "Position X", "double", "lineEditTextSingleX",
    "geometry_text_single", "text_single_y", "blank", "Position Y", "double", "lineEditTextSingleY",

    "misc_text_single", "text_single_backward", "blank", "Backward", "combobox", "comboBoxTextSingleBackward",
    "misc_text_single", "text_single_upside_down", "blank", "UpsideDown", "combobox", "comboBoxTextSingleUpsideDown",

    "geometry_text_multi", "text-multi-x", "blank", "Position X", "double", "",
    "geometry_text_multi", "text-multi-y", "blank", "Position Y", "double", ""
]
