image:
  - Visual Studio 2019

environment:
  SDL_VIDEODRIVER: dummy
  SDL_AUDIODRIVER: dummy
  SDL_RENDER_DRIVER: software
  matrix:
    - PYTHON: "C:\\Python38"
      PYSDL2_DLL_VERSION: 2.0.8


install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install -U pip"
  - "python .ci/getsdl2.py"
  - "set PYSDL2_DLL_PATH=C:\\projects\\py-sdl2\\dlls"
  - "pip install -U numpy pytest"
  - "pip install ."

build: off

test_script:
  - "python -B -m pytest -vvl -rxXP"
