# Property Editor Widgets
# -------------------------------------------------------
# This file is part of Embroidermodder.
# Copyright 2013-2022 The Embroidermodder Team
# See LICENSE for details.
# -------------------------------------------------------
#
