/*
 * Embroidermodder 2.
 *
 * Copyright 2011-2024 The Embroidermodder Team
 * Embroidermodder 2 is Open Source Software, see LICENSE.md for licensing terms.
 *
 * Read the reference manual (https://www.libembroidery.org/downloads/emrm.pdf)
 * for advice on altering this file.
 */
/* XPM */
static char *spool_top_bottom[] = {
/* columns rows colors chars-per-pixel */
"79 26 190 2 ",
"   c #865830",
".  c #8E6139",
"X  c #9A6E44",
"o  c #997046",
"O  c #9D7249",
"+  c #A0774D",
"@  c #A67A51",
"#  c #A97C54",
"$  c #AD8157",
"%  c #AC845A",
"&  c #AF885F",
"*  c #B68654",
"=  c #B98756",
"-  c #B78957",
";  c #BB8957",
":  c #B68C5A",
">  c #BC8C5A",
",  c #BC915E",
"<  c #B58961",
"1  c #BB8E64",
"2  c #B79263",
"3  c #BB9463",
"4  c #BE9865",
"5  c #BC946A",
"6  c #BE9A6B",
"7  c #C28D5B",
"8  c #C88C5A",
"9  c #C4925E",
"0  c #C29464",
"q  c #CB9561",
"w  c #C59966",
"e  c #CF9966",
"r  c #C39469",
"t  c #C9976E",
"y  c #C39C6D",
"u  c #CB9C6B",
"i  c #D49867",
"p  c #D39E6C",
"a  c #D99E6C",
"s  c #C79671",
"d  c #C99773",
"f  c #C49D73",
"g  c #CA9D73",
"h  c #CC9C78",
"j  c #D09F70",
"k  c #C4A06E",
"l  c #CAA16E",
"z  c #D4A26E",
"x  c #C6A173",
"c  c #CBA274",
"v  c #CBA877",
"b  c #C6A27A",
"n  c #CCA47B",
"m  c #CEAB7C",
"M  c #D1A574",
"N  c #DAA470",
"B  c #D4A976",
"V  c #D1A47C",
"C  c #D3AB7D",
"Z  c #D9AC7A",
"A  c #D2B17F",
"S  c #DCB17D",
"D  c #E2B57A",
"F  c #CEA780",
"G  c #C7AB83",
"H  c #CDAA83",
"J  c #C6AF8E",
"K  c #CDAC8A",
"L  c #D4A582",
"P  c #D3AC83",
"I  c #D9AE84",
"U  c #D3AE89",
"Y  c #D9AD8B",
"T  c #CFB087",
"R  c #CEB08E",
"E  c #D4B184",
"W  c #DBB384",
"Q  c #DEB986",
"!  c #D4B38B",
"~  c #DBB58B",
"^  c #D6B98E",
"/  c #DCB98B",
"(  c #CEAD92",
")  c #D1AE90",
"_  c #C9B190",
"`  c #D4B395",
"'  c #DAB694",
"]  c #D4B994",
"[  c #DCBA94",
"{  c #D5B59B",
"}  c #D5B99C",
"|  c #DBBC9B",
" . c #E1B482",
".. c #E2BA86",
"X. c #E9BE87",
"o. c #E3B68B",
"O. c #E3BB8B",
"+. c #EABE8B",
"@. c #E3BC93",
"#. c #E9BE91",
"$. c #E1BE9A",
"%. c #D6BBA2",
"&. c #DABDA2",
"*. c #D7BFA8",
"=. c #E2BFA0",
"-. c #DEC19C",
";. c #E5C08C",
":. c #ECC28D",
">. c #F1C38F",
",. c #E5C194",
"<. c #ECC394",
"1. c #E4C29C",
"2. c #EBC59C",
"3. c #E7CC9E",
"4. c #EBCB9B",
"5. c #F2C594",
"6. c #F4C995",
"7. c #F2C699",
"8. c #F5CC9B",
"9. c #F9CD9D",
"0. c #F9CD94",
"q. c #F5D09E",
"w. c #FCD29F",
"e. c #D4C0A5",
"r. c #DCC2A5",
"t. c #DDC5AC",
"y. c #DDC9AD",
"u. c #D6C4AB",
"i. c #DEC7B2",
"p. c #DECAB3",
"a. c #DDCCB8",
"s. c #E3C3A3",
"d. c #E9C6A3",
"f. c #E7C8A7",
"g. c #EDCBA3",
"h. c #E3C6AB",
"j. c #E4CAAD",
"k. c #EACCAB",
"l. c #F1CDA5",
"z. c #FACEA0",
"x. c #F2CDA8",
"c. c #EDD2AE",
"v. c #F1D1A6",
"b. c #F4D2AB",
"n. c #FBD6AF",
"m. c #E0C7B0",
"M. c #E3CCB4",
"N. c #E9CEB4",
"B. c #E3CDBA",
"V. c #E4D1B5",
"C. c #EBD2B5",
"Z. c #E6D1BA",
"A. c #EAD3BB",
"S. c #F2D6B3",
"D. c #F6D9B5",
"F. c #F9DAB5",
"G. c #F3D7BA",
"H. c #F5DBBC",
"J. c #FADEBC",
"K. c #F5E1BE",
"L. c #FEE0BB",
"P. c #DED5C2",
"I. c #E5D5C3",
"U. c #EAD7C2",
"Y. c #ECD9C3",
"T. c #E3D6CC",
"R. c #EDDCCA",
"E. c #E4D9C9",
"W. c #F3DCC2",
"Q. c #F9DEC2",
"!. c #E6D9D1",
"~. c #EADDD4",
"^. c #F4E2C4",
"/. c #F9E5C3",
"(. c #F2E3CC",
"). c #EDE1D4",
"_. c #EDE3D8",
"`. c #F2E4D4",
"'. c #F6E9D6",
"]. c #F1E6DA",
"[. c #F5EADB",
"{. c #F8EDDE",
"}. c #FBF2DF",
"|. c #F7EDE1",
" X c #F9EFE0",
".X c #FAF2E4",
"XX c #FBF4EB",
"oX c #FCF8EE",
"OX c #FFFBF2",
"+X c None",
/* pixels */
"+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+XV.C.M.M.C.M.M.M.M.M.M.M.M.m.M.M.M.m.M.m.M.M.M.+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X",
"+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+XZ.V.M.V.A.V.V.V.C.V.M.M.A.V.m.M.Z.p.M.V.B.p.M.V.m.m.m.m.M.M.i.B.M.M.i.i.p.+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X",
"+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+XN.N.N.U.C.Z.C.B.V.Z.V.B.B.M.N.m.M.N.M.m.m.M.t.j.N.j.h.M.m.y.y.M.m.m.y.m.M.i.B.i.i.B.a.i.p.B.B.+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X",
"+X+X+X+X+X+X+X+X+X+X+X+XY.{.{.].~.|.].~.~.!.!.T.I.N.M.j.h.m.h.} &.r.r.%.&.&.&.| &.} } } } ] } &.&.{ *.*.%.%.*.*.*.*.t.t.m.M.a.P.E.P.E.+X+X+X+X+X+X+X+X+X+X+X+X",
"+X+X+X+X+X+X+X+X+X[.[.`.`.`.R.E.I.U.R.I.I.I.B.B.M.N.N.k.h.h.f.r.&.=.$.' ' ' ' ' ' ` U U U U H ' [ ` %.&.{ { %.{ %.=.&.%.%.&.%.e.y.e.u.p.a.Z.+X+X+X+X+X+X+X+X+X",
"+X+X+X+X+X+X+X`.(.(.Y.Y.W.W.W.U.U.W.W.W.A.A.M.M.m.j.N.C.c.k.s.[ ! U f 5 3 5 < r r # X O @ @ % 5 y b ) ` ` ` ` ) ) { | { { { ' | 1.[ ] r.-.r.r.y.+X+X+X+X+X+X+X",
"+X+X+X+X+X'.(.^.^.^.^.H.H.H.W.W.G.G.Q.Q.Q.Q.G.C.G.C.H.H.S.k.1.E H h & % % # @ @ X     . X X + & 5 b { | { =.=.' { $.| ' | | [ | 1.| ,.-.-.-.-.-.-.t.+X+X+X+X+X",
"+X+X+X+XY.(.^.^./.K.^./.H.H.H.J.J.G.H.J.Q.Q.J.H.J.H.H.J.J.F.S.d.1.[ ! C P V n r < 1 5 f n U P E @.,.$.g.d.d.=.=.=.=.s.$.1.1.1.2.2.1.3.-.-.s.-.-.[ ! ] Z.+X+X+X",
"+X+X.XI.p.C.k.N.S.c.v.S.c.S.D.D.L.D.S.F.F.L.D.D.F.D.L.K.D.L.L.F.F.F.F.b.n.n.x.l.2.l.d.l.x.b.x.g.b.b.g.x.l.l.d.l.l.x.g.2.d.d.g.2.2.,.1.[ O.@.O.O.@.Q E | Y.+X+X",
"+XXX`.B.y.h.-.1.-.3.-.1.3.3.3.3.v.3.4.v.3.v.g.g.c.v.c.b.g.c.v.v.g.v.b.l.b.b.g.x.x.x.b.x.g.x.g.d.d.d.2.1.2.<.@.3.$.#.,.,.$.@.,.,.[ / O.Q Q Q Q O...o.W [ j.'.+X",
"+X|.Y.M.s.s.o./ Q Q m m m A A m m m A m v m m m E T T ] ! ! ! Q / ! W Q ~ ! ~ ' ' ' @.@.! ! ^ [ ~ ~ / Q E ~ ! W ~ Q ~ @.,.,.@.[ / Q O.Q Q X.O.#.;.O. .o.s.R.+X",
"oX{.I.j.1.@.~  .A v v v k 6 k k 6 6 4 2 , 5 : 2 4 2 2 6 6 4 5 4 k 6 6 5 6 f f f b F h F G b v m H m E A T C m U P Q W o.@.o.~ Q Q / ......;.X.:.X.:. .O.1.A..X",
"OX`.Z.s.$.#.Z Z A v v k 6 4 4 4 3 3 , : , 1 : 1 2 2 2 2 3 5 5 5 6 k 6 5 6 b f f n h f n n b V P n n m P C C P I W W E ../ ..Q O.:.......:.>.X.5.>.X.X.+.1.N..X",
"OX`.B.s.@.~ Z I B l l l w , : , , : - : : > : > : , , : 3 3 4 3 4 y r 0 t v c g V b v v v v E E m v Z Q I P I ..W W ..O.:.O.:.:.:...:.;.:.>.>.0.5.X.+.<.d.C.{.",
"oX].Z.s.@.o.S B l l l k k , , : > * * * : : ; = = > > * - , 9 9 , 0 u w u M u M B M c M v S A A C U W o.o.W W #.X...#.#.,.+.<.6.:.:.6.:.>.6.9.6.6.>.7.2.d.U.|.",
"+X].Z.k.,...D S B l l k 9 , , , ; * > 7 * ; > ; = > > = 7 9 9 9 9 u u u u z u M S M M W Z V W S S W Q o.+.O.o.#.O.O.<.5.#.<.8.6.>.:.6.6.6.6.z.8.6.5.4.g.S.`.+X",
"+X[.U.k.1.o.Q C B M c c w 0 , 0 , * 7 > = = 7 = ; 7 7 7 7 7 9 9 0 e q i z p z z Z B Z I B Z Q S ..o...#.5.<.#.#.5.#.7.9.7.7.6.6.6.6.q.6.q.q.q.q.q.8.g.c.Y..X+X",
"+X+X).I.t.| @.~ I V c M l w 0 w 9 > 7 > = > > 7 > 8 8 7 8 7 9 9 7 e p a a z z N D S  .D B Z ....O.X.o.@.<.,.2.9.5.7.7.z.8.9.9.z.6.6.6.q.q.6.q.6.<.1.t.(.XX+X+X",
"+X+X+X).I.e.| [ ~ I M n l y u y w 0 9 > 7 q > > , > 7 8 7 9 9 9 9 i a z p z z N D D +.W S ..<.O.@.@.@.5.2.#.7.7.7.7.7.7.z.z.9.l.,.,.4.,.,.;.;.[ | t.I.+X+X+X+X",
"+X+X+X+X+XI.y.&.' ~ U m c v v v y r 0 0 r 0 1 1 3 , , 3 9 l l w w z l u l u t z N Z W W I ..<.@.;.o.o.Q o.#.+.#.o.o.#.o.#.#.#.O./ E ;./ Q ^ T } Z.`.+X+X+X+X+X",
"+X+X+X+X+X+X+XA.y.} ' ` G b m H n f t f d t r r 3 3 3 3 6 6 4 2 y 6 4 y k l t u M p M c u M I B C C V V S W C P L I I P I I I E ~ E E / [ [ h.R.+X+X+X+X+X+X+X",
"+X+X+X+X+X+X+X+X+XI.i.&.! K ! ! K n b n V h d d g y f t y t 6 y u y y f g g y u c g g g g V L V M P n n P U P m P I I U Y I P ~ o.U ~ 1.h.Y.+X+X+X+X+X+X+X+X+X",
"+X+X+X+X+X+X+X+X+X+X+X+Xi.%.} { R R G G U H h L H h V g n n h n n c m V b V V n n n V h V Y Y L Y Y U T ! ^ U ! ~ / ~ ! ~ ~ ~ @.2.| 1.+X+X+X+X+X+X+X+X+X+X+X+X",
"+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X` K K J R K K K Y H ! H m U U P H n U U L P U L V Y P U Y ~ U H ! ! ! ! ^ ^ ! ! / ` / ' / ~ o.+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X",
"+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+XK K U K U U K K U K H H H U U K K ] E K ^ ! H ! / ' ! ^ / ^ ^ ^ [ ^ ^ [ [ +X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X",
"+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+XU U U U U Y U U U U ! U U U ! U U ^ ~ E ~ ' ~ +X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X"
};
