/*
 * Embroidermodder 2.
 *
 * Copyright 2011-2024 The Embroidermodder Team
 * Embroidermodder 2 is Open Source Software, see LICENSE.md for licensing terms.
 *
 * Read the reference manual (https://www.libembroidery.org/downloads/emrm.pdf)
 * for advice on altering this file.
 */
/* XPM */
static char *text_about[] = {
/* columns rows colors chars-per-pixel */
"141 39 201 2 ",
"   c black",
".  c #040404",
"X  c #0B0B0B",
"o  c gray6",
"O  c #101010",
"+  c #111111",
"@  c gray7",
"#  c #131313",
"$  c gray8",
"%  c #191919",
"&  c gray10",
"*  c #1B1B1B",
"=  c #1D1D1D",
"-  c gray12",
";  c #202020",
":  c gray13",
">  c #222222",
",  c #232323",
"<  c #272727",
"1  c #2A2A2A",
"2  c gray17",
"3  c #2C2C2C",
"4  c gray18",
"5  c #2F2F2F",
"6  c gray19",
"7  c #313131",
"8  c #323232",
"9  c gray20",
"0  c #393939",
"q  c #3A3A3A",
"w  c gray23",
"e  c #3C3C3C",
"r  c gray24",
"t  c #3E3E3E",
"y  c #3F3F3F",
"u  c gray25",
"i  c #414141",
"p  c gray26",
"a  c #434343",
"s  c #494949",
"d  c gray29",
"f  c #4B4B4B",
"g  c #4C4C4C",
"h  c gray30",
"j  c #4E4E4E",
"k  c gray31",
"l  c gray34",
"z  c #585858",
"x  c #5B5B5B",
"c  c #5D5D5D",
"v  c #606060",
"b  c gray38",
"n  c #646464",
"m  c #656565",
"M  c gray40",
"N  c #676767",
"B  c #686868",
"V  c #6A6A6A",
"C  c gray42",
"Z  c #6D6D6D",
"A  c gray43",
"S  c #6F6F6F",
"D  c gray44",
"F  c #717171",
"G  c #727272",
"H  c gray45",
"J  c #747474",
"K  c gray46",
"L  c #767676",
"P  c #777777",
"I  c gray47",
"U  c #797979",
"Y  c gray48",
"T  c #7B7B7B",
"R  c #7C7C7C",
"E  c gray49",
"W  c #7E7E7E",
"Q  c gray50",
"!  c #808080",
"~  c #818181",
"^  c gray51",
"/  c #838383",
"(  c gray52",
")  c #868686",
"_  c gray54",
"`  c #8B8B8B",
"'  c gray55",
"]  c #8D8D8D",
"[  c #8E8E8E",
"{  c gray56",
"}  c #909090",
"|  c gray57",
" . c #929292",
".. c #939393",
"X. c gray58",
"o. c #959595",
"O. c gray59",
"+. c #979797",
"@. c gray60",
"#. c #9A9A9A",
"$. c #9B9B9B",
"%. c gray61",
"&. c #9D9D9D",
"*. c gray62",
"=. c #9F9F9F",
"-. c #A0A0A0",
";. c gray63",
":. c #A2A2A2",
">. c gray64",
",. c #A4A4A4",
"<. c #A5A5A5",
"1. c gray65",
"2. c #A7A7A7",
"3. c gray66",
"4. c #A9A9A9",
"5. c #AAAAAA",
"6. c gray67",
"7. c #ACACAC",
"8. c gray68",
"9. c #AEAEAE",
"0. c #AFAFAF",
"q. c gray69",
"w. c #B1B1B1",
"e. c #B2B2B2",
"r. c gray70",
"t. c #B4B4B4",
"y. c gray71",
"u. c #B6B6B6",
"i. c #B7B7B7",
"p. c gray72",
"a. c #B9B9B9",
"s. c gray73",
"d. c #BBBBBB",
"f. c #BCBCBC",
"g. c gray74",
"h. c gray",
"j. c gray75",
"k. c #C0C0C0",
"l. c #C1C1C1",
"z. c gray76",
"x. c #C3C3C3",
"c. c gray77",
"v. c #C5C5C5",
"b. c #C6C6C6",
"n. c gray78",
"m. c #C8C8C8",
"M. c gray79",
"N. c #CACACA",
"B. c #CBCBCB",
"V. c gray80",
"C. c #CDCDCD",
"Z. c #CECECE",
"A. c gray81",
"S. c #D0D0D0",
"D. c gray82",
"F. c #D2D2D2",
"G. c LightGray",
"H. c gray83",
"J. c #D5D5D5",
"K. c gray84",
"L. c #D7D7D7",
"P. c #D8D8D8",
"I. c gray85",
"U. c #DADADA",
"Y. c gray86",
"T. c gainsboro",
"R. c #DDDDDD",
"E. c gray87",
"W. c #DFDFDF",
"Q. c gray88",
"!. c #E1E1E1",
"~. c #E2E2E2",
"^. c gray89",
"/. c #E4E4E4",
"(. c gray90",
"). c #E6E6E6",
"_. c #E7E7E7",
"`. c gray91",
"'. c #E9E9E9",
"]. c #EAEAEA",
"[. c gray92",
"{. c #ECECEC",
"}. c gray93",
"|. c #EEEEEE",
" X c #EFEFEF",
".X c gray94",
"XX c #F1F1F1",
"oX c gray95",
"OX c #F3F3F3",
"+X c #F4F4F4",
"@X c gray96",
"#X c #F6F6F6",
"$X c gray97",
"%X c #F8F8F8",
"&X c #F9F9F9",
"*X c gray98",
"=X c #FBFBFB",
"-X c gray99",
";X c #FDFDFD",
":X c #FEFEFE",
">X c None",
/* pixels */
">X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X`.`._.~._._._.>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X~.:X:X:X:X:X:X:XOX>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>XG.:XR / R / / :X`.>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X>X>X>X>X>X>X>X$X:X:X:X:X:X:X:X:X:X|.>X>X>X>X>X>X>X>X>X>Xm.:X/       i :X_.>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X>X>X>X>X>X>X>X:XE.h.h.h.h.h.h.h.:XOX>X>X>X>X>X>X>X>X>X>Xm.*XR       r *X~.>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X:X:X:X:X:X:X_.>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X>X>X>X>X>X>X>X:X;.              Z.*X>X>X>X>X>X>X>X>X>X>Xm.:X/       i :X~.>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>XY.:Xh.h.x.h.*XJ.>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X>X>X>X>X>X>X~.*Xb               ] :XG.>X>X>X>X>X>X>X>X>Xv.:XR       r :X_.>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X_.*Xi     R *Xm.>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X>X>X>X>X>X>X*X*X$     6 D 6     i *X|.>X>X>X>X>X>X>X>X>Xv.*XR       r *X~.>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X$X:X#     R *Xv.>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X>X>X>X>X>X>X*Xh.    6 *X$X*X6     Y.*X>X>X>X>X>X>X>X>X>Xv.*X/       r *X~.>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X*X`.      R *Xv.>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X>X>X>X>X>XY.*XS   . Z.|.q.OXD     =.$X>X>X>X>X>X>X>X>X>Xv.$XR       r *XE.>X>X>X>X~.~.~.>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X~.~.~.~.>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X*Xs.      R *Xx.>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X>X>X>X>X>XOX$X>   r $XG.R OX7.    b *XE.>X>X>X>X>X>X>X>Xv.*XR       i $X~.>XY.$X*X*X*X*X*X*X|.>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X~.OX*X*X*X*X*X*X*X$X`.>X>X>X>X>X>X>X>X>X>X_.*X*X*X*X*X*X*X|.>X>X>X>X>X>X*X*X*X*X*X*X*X*X>X>X>X>X>XOX|.|.*X*X*X$XR       i *X*X*X*X*X*X*X*X*X*X*X>X>X>X",
">X>X>X>X>X>X>X>X>X$Xm.    S OXi.>XOX_.    # `.$X>X>X>X>X>X>X>X>Xx.OXU       - *X`._.*X$Xh.R R R ] Z.*X$XE.>X>X>X>X>X>X>X>X>X>X>XY.$X$X$Xm.] R R R R s.$X*X$X~.>X>X>X>X>X>X>X>XG.$X$X$X$X$X$X$X_.>X>X>X>X>X>XOX$X$X$X$X$X$XOX>X>X>X>XJ.*X*X$X$X*Xh.R           i h.$X$X$X$X$X$X$X$XOX>X>X>X",
">X>X>X>X>X>X>X>XG.$X]     4.OX` >X_.OX>     7.$X>X>X>X>X>X>X>X>Xx.$XR         7.$X$Xh.i           . R $X$XY.>X>X>X>X>X>X>X>X>X_.$X$X4.i               < =.$X$X|.>X>X>X>X>X>X>Xv.$XU       r $XE.>X>X>X>X>X>XOX$X        s.OX>X>X>X>Xv.$XR r                                     $XOX>X>X>X",
">X>X>X>X>X>X>X>X_.$X6     G.|.>X>Xm.|.x     S OXJ.>X>X>X>X>X>X>Xx.OXU           > 4                   i OX$X>X>X>X>X>X>X>X>X~.$X_.l                       6 h.$X`.>X>X>X>X>X>Xx.OXR       r OXY.>X>X>X>X>X>XOXOX        i.OX>X>X>X>Xx.OXR                                       OX|.>X>X>X",
">X>X>X>X>X>X>X>XOXJ.    # OX`.>X>X7.|.]     > OXOX>X>X>X>X>X>X>Xh.$XU             6 U i.i.1.S           U OX_.>X>X>X>X>X>XJ.OX`.2       # ` v.OXJ.=.i       * s.$X_.>X>X>X>X>Xh.OXU       r OXY.>X>X>X>X>X>X|.OX        i.|.>X>X>X>Xh.OXU U R U i             . i R U U U U U U OXOX>X>X>X",
">X>X>X>X>X>X>Xx.OX$.    g |.Z.>X>X>X|.v.      x.OX>X>X>X>X>X>X>Xx.|.U           ` |.`.~.~.`.`.4.*       . m.OX>X>X>X>X>X>XOXOXi       2 Y.`.~.~.~._.|.g       * m.$X>X>X>X>X>Xx.OXU       r OXJ.>X>X>X>X>X>X|.|.        i.OX>X>X>X>Xh.`._._._._.`.7.        . m.|._._._._._._._._._.>X>X>X",
">X>X>X>X>X>X>XJ.OXg     U |.s.>X>X>X|.|..     ` |.G.>X>X>X>X>X>Xh.|.U         =.`._.1.N B K Y.`.4.        U OXJ.>X>X>X>XJ.OX$.      . m._.h.>X>X>X=._.`.l       c |.`.>X>X>X>Xh.OXU       r OXJ.>X>X>X>X>X>X|.OX        q.|.>X>X>X>X>X4.;.=.=.=.Y.|.-       r |.v.=.=.=.$.=.=.=.;.i.>X>X>X",
">X>X>X>X>X>X>XOX~.#     s.`.>X>X>X>XG.`.i     6 OX~.>X>X>X>X>X>Xh.|.U       # |.~.>X>X>X>X>X>XE.|.6       > |._.>X>X>X>XOX_.>       U `.m.>X>X>X>X>X$._.i.        s.OX>X>X>X>Xh.|.U       r |.Y.>X>X>X>X>X>X|.|.        i.|.>X>X>X>X>X>X>X>X>X>XZ.|.r       U |.1.>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X>X>X>X|.1.      |.`.>X>X>X>Xi.`.U       Z.|.>X>X>X>X>X>Xh.|.U       w `.Z.>X>X>X>X>X>Xi.`.B         |.|.>X>X>X>X|.1.        i._.>X>X>X>X>X>X>X_.`.#       B |.G.>X>X>Xh.|.U       r |.J.>X>X>X>X>X>X`.|.        q.`.>X>X>X>X>X>X>X>X>X>XG.|.w       U |.i.>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X>X>XG.|.B     6 `.Y.>X>X>X>X>X`.1.      O.|.h.>X>X>X>X>Xh.`.U       r |.J.>X>X>X>X>X>X} `.1.        i.|.>X>X>Xx.|.K       . `._.>X>X>X>X>X>X>Xm.`.g       4 |.E.>X>X>Xs.|.K       r |.J.>X>X>X>X>X>X`.|.        q.|.>X>X>X>X>X>X>X>X>X>XJ.|.r       K |.s.>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X>X>X`.|.>     B `.h.>X>X>X>X>X|.E.      g |.J.>X>X>X>X>Xs.|.K       r `.J.>X>X>X>X>X>X>X`.q.        q.`.>X>X>XG.|.g       r `.G.>X>X>X>X>X>X>Xq.`.K         `.|.>X>X>Xs.`.U       r `.J.>X>X>X>X>X>X`.|.        q.|.>X>X>X>X>X>X>X>X>X>XJ.`.w       U `.s.>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X>X>X`.h.      6 `.OXOX$XOXOX|.|.;.      # E.|.>X>X>X>X>Xs.`.K       w `.G.>X>X>X>X>X>X>X`.q.        q.`.>X>X>XJ.`.r       r `.J.>X>X>X>X>X>X>Xi.|.K         `.`.>X>X>Xs.`.U       r `.G.>X>X>X>X>X>X`.|.        q.`.>X>X>X>X>X>X>X>X>X>XG.`.r       K `.s.>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X>Xm.|.)         6 q._.`.`.`.E.;.*         ;.`.>X>X>X>X>Xs.`.K       w _.G.>X>X>X>X>X>X>X`.q.        q.`.>X>X>XG.`.w       w `.G.>X>X>X>X>X>X>Xs.`.K         `._.>X>X>Xs.`.K       w _.G.>X>X>X>X>X>X`.`.        7.`.>X>X>X>X>X>X>X>X>X>XG.`.r       U `.s.>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X>XY.`.6                                   B `.Z.>X>X>X>Xi._.D       w _.G.>X>X>X>X>X>X>X`.7.        7._.>X>X>Xm._.s       w `.G.>X>X>X>X>X>X>Xs._.K         _.~.>X>X>Xi._.K       w _.G.>X>X>X>X>X>X_._.        7._.>X>X>X>X>X>X>X>X>X>XG._.w       K _.i.>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X>X`.m.                                    > _.~.>X>X>X>Xi._.K       w _.Z.>X>X>X>X>X>Xq.`.)         Y.~.>X>X>Xq.~.K       . _._.>X>X>X>X>X>X>XZ._.s       4 ~.G.>X>X>Xi._.D       w _.Z.>X>X>X>X>X>X_._.        7._.>X>X>X>X>X>X>X>X>X>XZ._.w       K _.i.>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>Xs._.O.        r K D K D K D D K s #         s._.>X>X>X>Xi._.K       w _.Z.>X>X>X>X>X>XY._.g       > ~.J.>X>X>X>X~.;.        7.`.>X>X>X>X>X>X>X~._.#       N ~.h.>X>X>Xi._.K       2 _.Y.>X>X>X>X>X>X_.J.        7._.>X>X>X>X>X>X>X>X>X>Xv._.s       r _.J.>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>XG._.s       O.E.E.Y.Y.Y.Y.E.Y.E.~.m.#       / _.v.>X>X>Xq._.K       2 _.Y.>X>X>X>X>X>X`.q.        N E.h.>X>X>X>XE.Y.>       K _.Y.>X>X>X>X>Xs.`.7.        7.~.>X>X>X>Xi.~.K         s._.>X>X>X>X>XE._.;.        7.~.>X>X>X>X>X>X>X>X>X>X7.~.D       . m.`.>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X_.J..     o ~.J.O.O.O.O.O.O.O.} i.E.K       4 _.E.>X>X>Xi.~.D         q._.E.>X>X>XZ._._.N         7.E.>X>X>X>X>Xs.E.}       . h.`.Y.>X>X>Xm.`._.s       x E.G.>X>X>X>X;.E.]         ) _._.G.G.J._._.7.*         4.~.>X>X>X>X>X>X>X>X>X>X>X~.=.        } _.~.>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X~.=.      w E.x.>X>X>X>X>X>X>X>XB E.7.        v.~.>X>X>Xq.~.D         < q._.`.`.`._.~.}         N E.G.>X>X>X>X>X>XY.E.w       < Z._.`.`.|.`._.s       * s.Y.} >X>X>X>X>XE.s.          } ~._._._._.=.*           4.~.>X>X>X>X>X>X>X>X>X>X>XE.J.>       o ;._.`.|._.~.|.`.|.~.>X>X>X",
">X>X>Xv.~.l       K E.1.>X>X>X>X>X>X>X>X>XE.~.        } ~.i.>X>Xi.~.D       . w o x ] 4.4.K r         * v.Y.) >X>X>X>X>X>X;.Y.J.<       # / i.~.v.} r       * 7.Y.x.>X>X>X>X>X>XJ.E.4           4 b D N 4 } ~.}         4.~.>X>X>X>X>X>X>X>X>X>X>Xi.E.]           l 7.~.~._.~.J.J.~.>X>X>X",
">X>X>XE.~.>       4.E.>X>X>X>X>X>X>X>X>X>Xv.E.r       s ~.G.>X>Xq.~.D     . s.E.E.}                 * 7.Y.s.>X>X>X>X>X>X>X>Xq.J.J.s                       4 7.Y.x.>X>X>X>X>X>X>Xq.Y.=.                  } Y.G.Y.;.      4.E.>X>X>X>X>X>X>X>X>X>X>X>XJ.E.l               * 0 .   =.~.>X>X>X",
">X>X>X~.4.        E.Y.>X>X>X>X>X>X>X>X>X>X4.E.D       . G.~.>X>Xq.~.D     l E.s.G.Y.=.4           l s.Y.x.>X>X>X>X>X>X>X>X>X>X7.J.Y.=.w               - ] E.J.x.>X>X>X>X>X>X>X>X>XG.Y.N             w 7.Y.Z.s Z.E.-     4.E.>X>X>X>X>X>X>X>X>X>X>X>X` J.E.} -                   N ~.h.>X>X",
">X>Xx.~.E.E.~.E.E.E.Z.>X>X>X>X>X>X>X>X>X>X>XY.E.E.~.E.E.E.~.1.>X7.~.E.E.E.E.Y.R s x.J.E.=.D D / q.Y.J.i.>X>X>X>X>X>X>X>X>X>X>X>X] m.G.Y.i./ D D D K 4.E.J.G.=.>X>X>X>X>X>X>X>X>X>X] G.Y.4.K D D D 7.E.J.h.>X>Xx.E.E.E.E.~.E.>X>X>X>X>X>X>X>X>X>X>X>X>X) m.Y.E.4.R D D D K D $.i.Y.Y.G.>X>X",
">X>XZ.Z.Z.Z.m.Z.Z.Z.7.>X>X>X>X>X>X>X>X>X>X>XG.Z.m.Z.Z.Z.Z.Z.h.>X4.Z.Z.Z.Z.Z.Z.>X>X>X=.Z.G.J.G.G.G.x./ >X>X>X>X>X>X>X>X>X>X>X>X>X>X>XO.x.Z.G.G.J.J.J.Z.v.1.>X>X>X>X>X>X>X>X>X>X>X>X>XU x.G.G.G.J.J.G.v.O.>X>X>X;.Z.Z.m.Z.m.G.>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X1.v.G.G.G.J.J.J.J.G.Z.v.q.;.>X>X",
">X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>XR } } O.>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X` O.} O.} N >X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>XN } O.} O.D >X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>Xb ` O.} } } O.D >X>X>X>X>X>X",
">X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X",
">X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X>X"
};
