#
#  Embroidermodder 2.
#
#  ____________________________________________________________
#
#  Copyright 2013_2022 The Embroidermodder Team
#  Embroidermodder 2 is Open Source Software.
#  See LICENSE for licensing terms.
#
#  ____________________________________________________________
#

version = "2.0.0-alpha"

menu_layout = [
    ["File", "file_menu"],
    ["Open Recent", "open_recent_menu"],
    ["Edit", "edit_menu"],
    ["View", "view_menu"],
    ["Zoom", "zoom_menu"],
    ["Pan", "pan_menu"],    
    ["Draw", "draw_menu"]
]

file_menu = [
    ["New", "new"],
    ["Open", "open"],
    ["Open Recent", "submenu"],
    ["---", "---"],
    ["Save", "save"],
    ["Save As...", "saveas"],
    ["Export", "export"],
    ["---", "---"],
    ["Print", "print"],
    ["---", "---"],
    ["Close", "close"],
    ["---", "---"],
    ["Details", "details"],
    ["---", "---"],
    ["Quit", "quit"]
]

open_recent_menu = [
    ["None", "donothing"]
]

edit_menu = [
    ["Undo", "undo"],
    ["Redo", "redo"],
    ["---", "---"],
    ["Cut", "cut"],
    ["Copy", "copy"],
    ["Paste", "paste"]
]

view_menu = [
    ["Zoom", "submenu"],
    ["Pan", "submenu"],
    ["---", "---"],
    ["Day", "day"],
    ["Night", "night"]
]

zoom_menu = [
    ["Zoom Realtime", "zoom realtime"],
    ["---", "---"],
    ["Zoom In", "zoom in"],
    ["Zoom Out", "zoom out"],
    ["Zoom Extents", "zoom extents"],
    ["---", "---"]
]

pan_menu = [
    ["Pan Left", "pan left"],
    ["Pan Right", "pan right"],
    ["Pan Up", "pan up"],
    ["Pan Down", "pan down"]
]

draw_menu = [
    ["Circle", "circle"],
    ["Ellipse", "ellipse"],
    ["Rectangle", "rectangle"],
    ["Polyline", "polyline"],
    ["Polygon", "polygon"],
    ["About", "about"],
    ["Editor", "editor"]
]

toolbar_layout = [
    ["File", "file_toolbar"],
    ["Edit", "edit_toolbar"],
    ["View", "view_toolbar"],
    ["Zoom", "zoom_toolbar"],    
    ["Draw", "draw_toolbar"]
]

file_toolbar = [
    ["New", "new"]
]

edit_toolbar = [
    ["Cut", "cut"]    
]

view_toolbar = [
    ["Day", "day"]    
]

zoom_toolbar = [
    ["Zoom In", "zoomin"]    
]

draw_toolbar = [
    ["Circle", "circle"]    
]

action_list = [
    [
        "donothing",
        "&Do Nothing",
        "Does Nothing"
    ],
    [
        "windowcascade",
        "&Cascade",
        "Cascade the windows."
    ],
    [
        "windowtile",
        "&Tile",
        "Tile the windows."
    ],
    [
        "windowclose",
        "Cl&ose",
        "Close the active window."
    ],
    [
        "windowcloseall",
        "Close &All",
        "Close all the windows."
    ],
    [
        "windownext",
        "Ne&xt",
        "Move the focus to the next window."
    ],
    [
        "windowprevious",
        "Pre&vious",
        "Move the focus to the previous window."
    ],
    [
        "new",
        "&New",
        "Create a new file."
    ],
    [
        "open",
        "&Open",
        "Open an existing file."
    ],
    [
        "save",
        "&Save",
        "Save the design to disk."
    ],
    [
        "saveas",
        "Save &As",
        "Save the design under a new name."
    ],
    [
        "print",
        "&Print",
        "Print the design."
    ],
    [
        "designdetails",
        "&Details",
        "Details of the current design."
    ],
    [
        "exit",
        "E&xit",
        "Exit the application."
    ],
    [
        "cut",
        "Cu&t",
        "Cut the current selection's contents to the clipboard."
    ],
    [
        "copy",
        "&Copy",
        "Copy the current selection's contents to the clipboard."
    ],
    [
        "paste",
        "&Paste",
        "Paste the clipboard's contents into the current selection."
    ],
    [
        "help",
        "&Help",
        "Displays help."
    ],
    [
        "changelog",
        "&Changelog",
        "Describes new features in this product."
    ],
    [
        "tipoftheday",
        "&Tip Of The Day",
        "Displays a dialog with useful tips"
    ],
    [
        "about",
        "&About Embroidermodder 2",
        "Displays information about this product."
    ],
    [
        "whatsthis",
        "&What's This?",
        "What's This? Context Help!"
    ],
    [
        "undo",
        "&Undo",
        "Reverses the most recent action."
    ],
    [
        "redo",
        "&Redo",
        "Reverses the effects of the previous undo action."
    ],
    [
        "icon16",
        "Icon&16",
        "Sets the toolbar icon size to 16x16."
    ],
    [
        "icon24",
        "Icon&24",
        "Sets the toolbar icon size to 24x24."
    ],
    [
        "icon32",
        "Icon&32",
        "Sets the toolbar icon size to 32x32."
    ],
    [
        "icon48",
        "Icon&48",
        "Sets the toolbar icon size to 48x48."
    ],
    [
        "icon64",
        "Icon&64",
        "Sets the toolbar icon size to 64x64."
    ],
    [
        "icon128",
        "Icon12&8",
        "Sets the toolbar icon size to 128x128."
    ],
    [
        "settingsdialog",
        "&Settings",
        "Configure settings specific to this product."
    ],
    [
        "makelayercurrent",
        "&Make Layer Active",
        "Makes the layer of a selected object the active layer"
    ],
    [
        "layers",
        "&Layers",
        "Manages layers and layer properties:  LAYER"
    ],
    [
        "layerselector",
        "&Layer Selector",
        "Dropdown selector for changing the current layer"
    ],
    [
        "layerprevious",
        "&Layer Previous",
        "Restores the previous layer settings:  LAYERP"
    ],
    [
        "colorselector",
        "&Color Selector",
        "Dropdown selector for changing the current thread color"
    ],
    [
        "linetypeselector",
        "&Stitchtype Selector",
        "Dropdown selector for changing the current stitch type"
    ],
    [
        "lineweightselector",
        "&Threadweight Selector",
        "Dropdown selector for changing the current thread weight"
    ],
    [
        "hidealllayers",
        "&Hide All Layers",
        "Turns the visibility off for all layers in the current drawing:  HIDEALL"
    ],
    [
        "showalllayers",
        "&Show All Layers",
        "Turns the visibility on for all layers in the current drawing:  SHOWALL"
    ],
    [
        "freezealllayers",
        "&Freeze All Layers",
        "Freezes all layers in the current drawing:  FREEZEALL"
    ],
    [
        "thawalllayers",
        "&Thaw All Layers",
        "Thaws all layers in the current drawing:  THAWALL"
    ],
    [
        "lockalllayers",
        "&Lock All Layers",
        "Locks all layers in the current drawing:  LOCKALL"
    ],
    [
        "unlockalllayers",
        "&Unlock All Layers",
        "Unlocks all layers in the current drawing:  UNLOCKALL"
    ],
    [
        "textbold",
        "&Bold Text",
        "Sets text to be bold."
    ],
    [
        "textitalic",
        "&Italic Text",
        "Sets text to be italic."
    ],
    [
        "textunderline",
        "&Underline Text",
        "Sets text to be underlined."
    ],
    [
        "textstrikeout",
        "&StrikeOut Text",
        "Sets text to be striked out."
    ],
    [
        "textoverline",
        "&Overline Text",
        "Sets text to be overlined."
    ],
    [
        "zoomrealtime",
        "Zoom &Realtime",
        "Zooms to increase or decrease the apparent size of objects in the current viewport."
    ],
    [
        "zoomprevious",
        "Zoom &Previous",
        "Zooms to display the previous view."
    ],
    [
        "zoomwindow",
        "Zoom &Window",
        "Zooms to display an area specified by a rectangular window."
    ],
    [
        "zoomdynamic",
        "Zoom &Dynamic",
        "Zooms to display the generated portion of the drawing."
    ],
    [
        "zoomscale",
        "Zoom &Scale",
        "Zooms the display using a specified scale factor."
    ],
    [
        "zoomcenter",
        "Zoom &Center",
        "Zooms to display a view specified by a center point and magnification or height."
    ],
    [
        "zoomin",
        "Zoom &In",
        "Zooms to increase the apparent size of objects."
    ],
    [
        "zoomout",
        "Zoom &Out",
        "Zooms to decrease the apparent size of objects."
    ],
    [
        "zoomselected",
        "Zoom Selec&ted",
        "Zooms to display the selected objects."
    ],
    [
        "zoomall",
        "Zoom &All",
        "Zooms to display the drawing extents or the grid limits."
    ],
    [
        "zoomextents",
        "Zoom &Extents",
        "Zooms to display the drawing extents."
    ],
    [
        "panrealtime",
        "&Pan Realtime",
        "Moves the view in the current viewport."
    ],
    [
        "panpoint",
        "&Pan Point",
        "Moves the view by the specified distance."
    ],
    [
        "panleft",
        "&Pan Left",
        "Moves the view to the left."
    ],
    [
        "panright",
        "&Pan Right",
        "Moves the view to the right."
    ],
    [
        "panup",
        "&Pan Up",
        "Moves the view up."
    ],
    [
        "pandown",
        "&Pan Down",
        "Moves the view down."
    ],
    [
        "day",
        "&Day",
        "Updates the current view using day vision settings."
    ],
    [
        "night",
        "&Night",
        "Updates the current view using night vision settings."
    ]
]

tips = [
    "we need more tips?",
    "you can change the color of the display through settings?",
    "you can hide the scrollbars to increase the viewable area through settings?",
    "you can change the icon size for increased visibility?",
    "you can toggle the grid on and off by pressing the button in the statusbar?",
    "the grid size can be changed to match your hoop size through settings?",
    "the crosshair size is based on a percentage of your screen size? Setting it to 100 may help you visually line things up better.",
    "you can pan by pressing the middle mouse button and dragging your mouse across the screen?",
    "you can open and edit multiple designs simultaneously?",
    "you that many embroidery machines support the .dst format?",
    "that you can zoom in and out using your mouse wheel?",
    "that you can use circular and isometric grids?",
    "about our command line format converter?",
    "that you can use the 'DAY' and 'NIGHT' commands to quickly switch the view colors to commonly used white or black?",
    "that you can quickly change the background, crosshair and grid colors using the 'RGB' command?"
]

[general]
type = "meta"
languages = [
    "translations/default.csv",
    "translations/english_us.csv",
    "translations/english_gb.csv",
    "translations/french.csv",
    "translations/spanish.csv",
    "translations/hindi.csv",
    "translations/chinese_traditional.csv",
    "translations/chinese_simplified.csv",
    "translations/arabic.csv",
    "translations/russian.csv"
]
crash_test = [
    "do-nothing",
    "debug-message File actions",
    "new-file",
    "# Need to set the filename here.",
    "open-file",
    "save-file",
    "save-file-as",

    "debug-message Edit actions",
    "# Place some objects to alter here.",
    "cut",
    "copy",
    "paste",

    "debug-message Configuring the UI.",
    "icon 24",
    "icon 32",
    "icon 48",
    "icon 64",
    "icon 128",
    "icon 16"
]
boot-message = """
 _____________________________________________________________
|                 EMBROIDERMODDER 2.0.0-alpha                 |
|                  http://libembroidery.org                   |
|-------------------------------------------------------------|
|        Copyright 2013-2022 The Embroidermodder Team         |
|       Distributed under the terms of the zlib license.      |
|_____________________________________________________________|
"""
greig-message = """\
Hi there. If you are not a developer, report this as a bug. \
If you are a developer, your code needs examined, \
and possibly your head too.\
"""
help-message = """
Usage: embroidermodder [options] files ...

Options:
  -d, --debug      Print lots of debugging information.
  -h, --help       Print this message and exit.
  -v, --version    Print the version number of embroidermodder and exit.
"""

[draw-menu]
type = "top-menu"
label = "Draw"
position = 8

[ellipse-menu]
type = "menu-item"
menu = "Draw"
icon = "ellipse"
command = "add ellipse"
label = "Add Ellipse"
position = 9
tooltip = "Ellipse"
statustip = "Creates a ellipse:  ELLIPSE"

[circle-menu]
type = "menu-item"
menu = "Draw"
icon = "circle"
command = "add circle"
label = "Add Circle"
position = 8
tooltip = "Circle"
statustip = "Creates a circle:  CIRCLE"

[dolphin]
type = "design"
label = "Dolphin"
shape-def = "designs/dolphin.ps"
num-points = 512
scale-x = 0.04
scale-y = 0.04
description = "Adds a dolphin design to the vector layer."

[heart4]
type = "design"
label = "heart4"
num-points = 100
scale-x = 1.0
scale-y = 1.0
decorated-label = "&Heart4"
description = "Adds a heart to the vector layer: heart4."
shape-def = "designs/heart4.ps"

#  System Specific Overrides
#

[android]
type = "system-overrides"
em2_version = "Android Version"
assets_directory = "/usr/share/embroidermodder"
os_seperator = "/"

[ios]
type = "system-overrides"
em2_version = "iOS version"
assets_directory = "/usr/share/embroidermodder"
os_seperator = "/"

[linux]
type = "system-overrides"
em2_version = "X11 version"
assets_directory = "/usr/share/embroidermodder"
os_seperator = "/"

[macos]
type = "system-overrides"
em2_version = "Mac OS Cocoa version"
assets_directory = "/usr/share/embroidermodder"
os_seperator = "/"

[win32]
type = "system-overrides"
em2_version = "Win32 version"
assets_directory = "C:\\ProgramData\\embroidermodder"
os_seperator = "\\"
