# Embroidermodder 2.
#
# Copyright 2011-2024 The Embroidermodder Team
# Embroidermodder 2 is Open Source Software, see LICENSE.md for licensing terms.
# Visit https://www.libembroidery.org/refman for advice on altering this file,
# or read the markdown version in embroidermodder2/docs/refman.
#

# List of all configuration files necessary to load the program.
config_files = [
    "data/commands.toml",
    "data/menus.toml",
    "data/testing.toml",
    "data/toolbars.toml"
]

