name: Build and Test on Major Systems

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Build and test library and command-line program.
      run: |
        git clone https://github.com/Embroidermodder/libembroidery
        cd libembroidery
        . qa_test.sh
        cmake_build
        all_tests
      shell: bash
        
