# Postscript functions and configuration for the heart5 design.
# -------------------------------------------------------
# This file is part of Embroidermodder.
# Copyright 2013-2022 The Embroidermodder Team
# See LICENSE for details.
# -------------------------------------------------------
#

command = "heart5"
range = [0.0, 2.0]
num_points = 512
scale = [0.04, 0.04]
variable = "t"
x = "16 t sin dup dup mul mul mul"
y = """
    13 t cos mul
    5 2 t mul cos mul sub
    2 3 t mul cos mul sub
    4 t mul cos sub
"""
