#
#  Embroidermodder 2.
#
#  ____________________________________________________________
#
#  Copyright 2013_2022 The Embroidermodder Team
#  Embroidermodder 2 is Open Source Software.
#  See LICENSE for licensing terms.
#
#  ____________________________________________________________
#


[do-nothing-action]
command = "donothing"
label = "&Do Nothing"
tooltip = "Does Nothing"

[window-cascade-action]
command = "windowcascade"
label = "&Cascade"
tooltip = "Cascade the windows."

[window-tile-action]
command = "windowtile"
label = "&Tile"
tooltip = "Tile the windows."

[window-close-action]
command = "windowclose"
label = "Cl&ose"
tooltip = "Close the active window."

[window-close-all-action]
command = "windowcloseall"
label = "Close &All"
tooltip = "Close all the windows."

[window-next-action]
"windownext"
label = "Ne&xt"
tooltip = "Move the focus to the next window."

[window-next-action]
"windowprevious"
label = "Pre&vious"
tooltip = "Move the focus to the previous window."

[window-next-action]
"new"
label = "&New"
tooltip = "Create a new file."

[window-next-action]
"open"
label = "&Open"
tooltip = "Open an existing file."

[window-next-action]
"save"
label = "&Save"
tooltip = "Save the design to disk."

[window-next-action]
command = "saveas"
label = "Save &As"
tooltip = "Save the design under a new name."

[window-next-action]
command = "print"
label = "&Print"
tooltip = "Print the design."

[window-next-action]
command = "designdetails"
label = "&Details"
tooltip = "Details of the current design."

[window-next-action]
command = "exit"
label = "E&xit"
tooltip = "Exit the application."

[window-next-action]
command = "cut"
label = "Cu&t"
tooltip = "Cut the current selection's contents to the clipboard."

[window-next-action]
command = "copy"
label = "&Copy"
tooltip = "Copy the current selection's contents to the clipboard."

[window-next-action]
command = "paste"
label = "&Paste"
tooltip = "Paste the clipboard's contents into the current selection."

[help-action]
command = "help"
label = "&Help"
tooltip = "Displays help."

[changelog-action]
command = "changelog"
label = "&Changelog"
tooltip = "Describes new features in this product."

[tip-of-the-day-action]
command = "tipoftheday"
label = "&Tip Of The Day"
tooltip = "Displays a dialog with useful tips"

[about-action]
command = "about"
label = "&About Embroidermodder 2"
tooltip = "Displays information about this product."

[window-next-action]
command = "whatsthis"
"&What's This?"
tooltip = "What's This? Context Help!"

[window-next-action]
command = "undo"
"&Undo"
tooltip = "Reverses the most recent action."

[window-next-action]
command = "redo"
"&Redo"
tooltip = "Reverses the effects of the previous undo action."

[]
"icon16"
"Icon&16"
tooltip = "Sets the toolbar icon size to 16x16."

[]
"icon24"
"Icon&24"
tooltip = "Sets the toolbar icon size to 24x24."

[]
"icon32"
"Icon&32"
tooltip = "Sets the toolbar icon size to 32x32."

[icon-48-action]
"icon48"
"Icon&48"
tooltip = "Sets the toolbar icon size to 48x48."

[icon-64-action]
"icon64"
"Icon&64"
tooltip = "Sets the toolbar icon size to 64x64."

[icon-128-action]
"icon128"
"Icon12&8"
tooltip = "Sets the toolbar icon size to 128x128."

[settings-dialog-action]
command = "settingsdialog"
label = "&Settings"
tooltip = "Configure settings specific to this product."

[make-layer-current-action]
command = "makelayercurrent"
label = "&Make Layer Active"
tooltip = "Makes the layer of a selected object the active layer"

[layers-action]
command = "layers"
label = "&Layers"
tooltip = "Manages layers and layer properties:  LAYER"

[layer-selector-action]
command = "layerselector"
label = "&Layer Selector"
tooltip = "Dropdown selector for changing the current layer"

[layer-previous-action]
command = "layerprevious"
label = "&Layer Previous"
tooltip = "Restores the previous layer settings:  LAYERP"

[color-selector-action]
command = "colorselector"
label = "&Color Selector"
tooltip = "Dropdown selector for changing the current thread color"

[line-type-selector-action]
command = "linetypeselector"
label = "&Stitchtype Selector"
tooltip = "Dropdown selector for changing the current stitch type"

[settings-dialog-action]
"lineweightselector"
label = "&Threadweight Selector"
"Dropdown selector for changing the current thread weight"

[settings-dialog-action]
"hidealllayers"
label = "&Hide All Layers"
"Turns the visibility off for all layers in the current drawing:  HIDEALL"

[settings-dialog-action]
"showalllayers"
label = "&Show All Layers"
"Turns the visibility on for all layers in the current drawing:  SHOWALL"

[settings-dialog-action]
"freezealllayers"
label = "&Freeze All Layers"
"Freezes all layers in the current drawing:  FREEZEALL"

[settings-dialog-action]
"thawalllayers"
label = "&Thaw All Layers"
"Thaws all layers in the current drawing:  THAWALL"

[settings-dialog-action]
"lockalllayers"
label = "&Lock All Layers"
"Locks all layers in the current drawing:  LOCKALL"

[settings-dialog-action]
"unlockalllayers"
label = "&Unlock All Layers"
"Unlocks all layers in the current drawing:  UNLOCKALL"

[settings-dialog-action]
"textbold"
label = "&Bold Text"
"Sets text to be bold."

[settings-dialog-action]
"textitalic"
label = "&Italic Text"
"Sets text to be italic."

[settings-dialog-action]
"textunderline"
label = "&Underline Text"
"Sets text to be underlined."

[settings-dialog-action]
"textstrikeout"
label = "&StrikeOut Text"
"Sets text to be striked out."

[settings-dialog-action]
"textoverline"
label = "&Overline Text"
"Sets text to be overlined."

[settings-dialog-action]
"zoomrealtime"
label = "Zoom &Realtime"
"Zooms to increase or decrease the apparent size of objects in the current viewport."

[settings-dialog-action]
"zoomprevious"
"Zoom &Previous"
"Zooms to display the previous view."

[settings-dialog-action]
"zoomwindow"
"Zoom &Window"
"Zooms to display an area specified by a rectangular window."

[settings-dialog-action]
"zoomdynamic"
"Zoom &Dynamic"
"Zooms to display the generated portion of the drawing."

[settings-dialog-action]
"zoomscale"
"Zoom &Scale"
"Zooms the display using a specified scale factor."

[settings-dialog-action]
"zoomcenter"
"Zoom &Center"
"Zooms to display a view specified by a center point and magnification or height."

[zoom-in-action]
"zoomin"
"Zoom &In"
"Zooms to increase the apparent size of objects."

[zoom-in-action]
"zoomout"
"Zoom &Out"
"Zooms to decrease the apparent size of objects."

[zoom-in-action]
"zoomselected"
"Zoom Selec&ted"
"Zooms to display the selected objects."

[zoom-in-action]
"zoomall"
"Zoom &All"
"Zooms to display the drawing extents or the grid limits."

[zoom-in-action]
"zoomextents"
"Zoom &Extents"
"Zooms to display the drawing extents."

[zoom-in-action]
"distance"
"_Distance"
"Measures the distance and angle between two points: DIST"

[zoom-in-action]
"dolphin"
"Dolp_hin"
"Adds a dolphin design to the vector layer."

[zoom-in-action]
"trebleclef"
"Treble Clef"
"Adds a treble clef design to the vector layer."

[zoom-in-action]
"panrealtime"
"&Pan Realtime"
"Moves the view in the current viewport."

[zoom-in-action]
"panpoint"
"&Pan Point"
"Moves the view by the specified distance."

[zoom-in-action]
"panleft"
"&Pan Left"
"Moves the view to the left."

[zoom-in-action]
"panright"
"&Pan Right"
tooltip = "Moves the view to the right."

[pan-up-action]
command = "panup"
label = "&Pan Up"
tooltip = "Moves the view up."

[pan-down-action]
command = "pandown"
label = "&Pan Down"
tooltip = "Moves the view down."

[day-action]
command = "day"
label = "&Day"
tooltip = "Updates the current view using day vision settings."

[night-action]
command = "night"
label = "&Night"
tooltip = "Updates the current view using night vision settings."

[delete-action]
menu = "Modify"
toolbar = "Modify"
tooltip = "D&elete"
statustip = "Removes objects from a drawing:  DELETE"
alias = ["E" "ERASE" "DEL" "DELETE"]

[quit-action]
menu = "None"
toolbar = "None"
tooltip = "E&xit"
statustip = "Exit the application: EXIT"
alias = "EXIT, QUIT"

[help-action]
menu = "None"
toolbar = "None"
tooltip = "&Help"
statustip = "Displays the help file:  HELP"
alias = "?, HELP"

[move-action]
menu = "Modify"
toolbar = "Modify"
tooltip = "&Move"
statustip = "Displaces objects a specified distance in a specified direction:  MOVE"
alias = "M, MOVE"

[locate-point-action]
menu = "Tools"
toolbar = "Inquiry"
tooltip = "&Locate Point"
statustip = "Displays the coordinate values of a location:  ID"
alias = "ID, LOCATEPOINT"

[heart-action]
menu = "Draw"
toolbar = "Draw"
tooltip = "&Heart"
statustip = "Creates a heart:  HEART"
alias = "HEART"

[path-action]
menu = "Draw"
toolbar = "Draw"
tooltip = "&Path"
statustip = "Creates a 2D path:  PATH"
alias = "PA, PATH"

[platform-action]
menu = "None"
toolbar = "None"
tooltip = "&Platform"
statustip = "List which platform is in use:  PLATFORM"
alias = "PLATFORM"

[point-action]
menu = "Draw"
toolbar = "Draw"
tooltip = "&Point"
statustip = "Creates multiple points:  POINT"
alias = "PO, POINT"

[polygon-action]
menu = "Draw"
toolbar = "Draw"
tooltip = "Pol&ygon"
statustip = "Creates a regular polygon:  POLYGON"
alias = "POL, POLYGON"

[polyline-action]
menu = "Draw"
toolbar = "Draw"
tooltip = "&Polyline"
statustip = "Creates a 2D polyline:  PLINE"
alias = ["PL" "PLINE" "POLYLINE"]

[dimension-action]
menu = "Dimension"
toolbar = "Dimension"
tooltip = "&QuickLeader"
statustip = "Creates a leader and annotation:  QUICKLEADER"
alias = ["LE" "LEADER" "QLEADER" "QUICKLEADER"]

[rectangle-action]
command = "rectangle"
menu = "Draw"
toolbar = "Draw"
tooltip = "&Rectangle"
statustip = "Creates a rectangular polyline: RECTANGLE"
alias = ["REC" "RECT" "RECTANG" "RECTANGLE"]

[redo-action]
menu = "None"
toolbar = "None"
tooltip = "&Redo"
statustip = "Reverses the effects of the previous undo action: REDO"
alias = ["REDO"]

[rgb-action]
menu = "Sandbox"
toolbar = "Sandbox"
tooltip = "&RGB"
statustip = "Updates the current view colors: RGB"
alias = ["RGB"]

[rotate-action]
menu = "Modify"
toolbar = "Modify"
tooltip = "&Rotate"
statustip = "Rotates objects about a base point:  ROTATE"
alias = ["RO" "ROTATE"]

[sandbox-action]
menu = "Sandbox"
toolbar = "Sandbox"
tooltip = "Sandbox"
statustip = "A sandbox to play in: SANDBOX"
alias = ["SAND" "SANDBOX"]

[scale-action]
command = "scale"
menu = "Modify"
toolbar = "Modify"
tooltip = "Sca&le"
statustip = "Enlarges or reduces objects proportionally in the X, Y, and Z directions:  SCALE"
alias = ["SC" "SCALE"]

[select-all-action]
command = "selectall"
menu = "None"
toolbar = "None"
tooltip = "&Select All"
statustip = "Selects all objects:  SELECTALL"
alias = ["AI_SELALL" "SELALL" "SELECTALL"]

[single-line-text-action]
command = "single-line-text"
menu = "Draw"
toolbar = "Draw"
tooltip = "&Single Line Text"
statustip = "Creates single-line text objects:  TEXT"
alias = ["DT, DTEXT, TEXT, SINGLELINETEXT"]

[snowflake-action]
command = "snowflake"
menu = "Draw"
toolbar = "Draw"
tooltip = "&Snowflake"
statustip = "Creates a snowflake:  SNOWFLAKE"
alias = ["SNOWFLAKE"]

[star-action]
command = "star"
menu = "Draw"
toolbar = "Draw"
tooltip = "&Star"
statustip = "Creates a star:  STAR"
alias = ["*" "STAR"]

[syswindows-action]
command = "syswindows"
menu = "None"
toolbar = "None"
tooltip = "&SysWindows"
statustip = "Arrange the windows:  SYSWINDOWS"
alias = ["WINDOWS" "SYSWINDOWS"]

[tip-of-the-day-action]
command = "tipoftheday"
menu = "None"
toolbar = "None"
tooltip = "&Tip Of The Day"
statustip = "Displays a dialog with useful tips:  TIPS"
alias = ["TIPS" "TIPOFTHEDAY"]
