# -*- coding: utf-8 -*-
#
# Embroidermodder 2 documentation build configuration file, created by
# sphinx-quickstart on Sun May 11 02:34:28 2014.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
import sys

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.append(os.path.abspath('.'))
sys.path.append('..')
sys.path.insert(0, os.path.abspath('..'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
## needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.todo',
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.coverage',
    'availability'
    ]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.txt'

# The encoding of source files.
## source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Embroidermodder 2'
copyright = u'2014, Embroidermodder 2 Team'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '2.0.0'
# The full version, including alpha/beta/rc tags.
release = '2.0.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
## language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The reST default role (used for this markup: `text`) to use for all
# documents.
## default_role = None
## default_role = 'autolink'

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
## add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
## show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
## modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
## keep_warnings = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
## html_theme = 'default'
## html_theme = 'sphinxdoc'
## html_theme = 'agogo'
## html_theme = 'basic'
## html_theme = 'epub'
## html_theme = 'haiku'
## html_theme = 'nature'
## html_theme = 'pyramid'
## html_theme = 'scrolls'
## html_theme = 'traditional'
html_theme = 'embroidertheme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
## html_theme_options = {}
html_theme_options = dict()

# Add any paths that contain custom themes here, relative to this directory.
## html_theme_path = []
html_theme_path = ['.']

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
## html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
## html_short_title = None
html_short_title = 'Embroidermodder 2 Docs'

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
## html_logo = None
html_logo = '_static/images/sphinxdocs/logo-spirals.png'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
## html_favicon = None
## html_favicon = '_static/images/sphinxdocs/favicon.ico'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_style = 'css/embroidermodder.css'

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
## html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
## html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
## html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
## html_sidebars = {}
html_sidebars = {'index': 'indexsidebar.html'}

# Additional templates that should be rendered to pages, maps page names to
# template names.
## html_additional_pages = {}

# If false, no module index is generated.
## html_domain_indices = True

# If false, no index is generated.
html_use_index = True

# If true, the index is split into individual pages for each letter.
html_split_index = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
## html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
## html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'Embroidermodder2doc'


# This value selects what content will be inserted into the main body of an autoclass directive.
# "class"
#     Only the class’ docstring is inserted. This is the default.
#     You can still document __init__ as a separate method using automethod or the members option to autoclass.
# "both"
#     Both the class’ and the __init__ method’s docstring are concatenated and inserted.
# "init"
#     Only the __init__ method’s docstring is inserted.
autoclass_content = 'both'

# This value selects if automatically documented members
# are sorted alphabetical (value 'alphabetical'),
# by member type (value 'groupwise') or
# by source order (value 'bysource'). The default is alphabetical.
# Note that for source order, the module must be a Python module with the source code available.
autodoc_member_order = 'bysource'

# This value is a list of autodoc directive flags that should be automatically
# applied to all autodoc directives.
# The supported flags are 'members', 'undoc-members', 'private-members',
#                         'special-members', 'inherited-members' and 'show-inheritance'.
# If you set one of these flags in this config value, you can use a negated form,
# 'no-flag', in an autodoc directive, to disable it once.
# For example, if autodoc_default_flags is set to ['members', 'undoc-members'],
# and you write a directive like this:
#
# .. automodule:: foo
#    :no-undoc-members:
#
# the directive will be interpreted as if only :members: was given.
## autodoc_default_flags = []

# Functions imported from C modules cannot be introspected, and therefore the
# signature for such functions cannot be automatically determined.
# However, it is an often-used convention to put the signature into the first line of the function’s docstring.
#
# If this boolean value is set to True (which is the default), autodoc will look at
# the first line of the docstring for functions and methods, and if it looks like
# a signature, use the line as the signature and remove it from the docstring content.
## autodoc_docstring_signature = True

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#'papersize': 'letterpaper',

# The font size ('10pt', '11pt' or '12pt').
#'pointsize': '10pt',

# Additional stuff for the LaTeX preamble.
#'preamble': '',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
  ('index', 'Embroidermodder2.tex', u'Embroidermodder 2 Documentation',
   u'Embroidermodder 2 Team', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
## latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
## latex_use_parts = False

# If true, show page references after internal links.
## latex_show_pagerefs = False

# If true, show URL addresses after external links.
## latex_show_urls = False

# Documents to append as an appendix to all manuals.
## latex_appendices = []

# If false, no module index is generated.
## latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'embroidermodder2', u'Embroidermodder 2 Documentation',
     [u'Embroidermodder 2 Team'], 1)
]

# If true, show URL addresses after external links.
## man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'Embroidermodder2', u'Embroidermodder 2 Documentation',
   u'Embroidermodder 2 Team', 'Embroidermodder2', 'One line description of project.',
   'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
## texinfo_appendices = []

# If false, no module index is generated.
## texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
## texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
## texinfo_no_detailmenu = False
