/*
 * Embroidermodder 2.
 *
 * Copyright 2011-2024 The Embroidermodder Team
 * Embroidermodder 2 is Open Source Software, see LICENSE.md for licensing terms.
 *
 * Read the reference manual (https://www.libembroidery.org/downloads/emrm.pdf)
 * for advice on altering this file.
 */
/* XPM */
static char *circlecenterdiameter[] = {
/* columns rows colors chars-per-pixel */
"128 128 125 2 ",
"   c #000000",
".  c #0C0C0C",
"X  c #140000",
"o  c #1A0000",
"O  c #151515",
"+  c #1A1A1A",
"@  c #351010",
"#  c #242424",
"$  c #2D2D2D",
"%  c #343434",
"&  c #3B3B3B",
"*  c #440000",
"=  c #4B0000",
"-  c #5D0101",
";  c #500B0B",
":  c #5F0A0A",
">  c #491616",
",  c #630000",
"<  c #6C0000",
"1  c #670F0F",
"2  c #730000",
"3  c #7E0000",
"4  c #760C0C",
"5  c #7C0B0B",
"6  c #671C1C",
"7  c #771010",
"8  c #7E1111",
"9  c #6C2222",
"0  c #6E2E2E",
"q  c #702323",
"w  c #762D2D",
"e  c #723737",
"r  c #733B3B",
"t  c #7D3C3C",
"y  c #434343",
"u  c #4A4A4A",
"i  c #555555",
"p  c #5C5C5C",
"a  c #764242",
"s  c #794545",
"d  c #794949",
"f  c #7E5454",
"g  c #646464",
"h  c #6B6B6B",
"j  c #757575",
"k  c #7D7D7D",
"l  c #800101",
"z  c #850A0A",
"x  c #841212",
"c  c #8A1414",
"v  c #831C1C",
"b  c #8F1F1F",
"n  c #8A2D2D",
"m  c #912222",
"M  c #962D2D",
"N  c #993232",
"B  c #9F3F3F",
"V  c #934141",
"C  c #835E5E",
"Z  c #A34646",
"A  c #A44F4F",
"S  c #A35656",
"D  c #AE5D5D",
"F  c #896767",
"G  c #8C6D6D",
"H  c #946666",
"J  c #8E7272",
"K  c #927B7B",
"L  c #9E7979",
"P  c #A76060",
"I  c #AE6A6A",
"U  c #B26464",
"Y  c #B47474",
"T  c #B47979",
"R  c #BF7F7F",
"E  c #858585",
"W  c #8C8C8C",
"Q  c #9D8C8C",
"!  c #939393",
"~  c #9C9393",
"^  c #9B9999",
"/  c #BB8282",
"(  c #BD8B8B",
")  c #A29595",
"_  c #A49E9E",
"`  c #A5A4A4",
"'  c #A9A4A4",
"]  c #ACACAC",
"[  c #BFAAAA",
"{  c #B4B4B4",
"}  c #B9B2B2",
"|  c #BCBCBC",
" . c #C28484",
".. c #C38E8E",
"X. c #C69595",
"o. c #CA9494",
"O. c #CC9D9D",
"+. c #C0ABAB",
"@. c #D3A7A7",
"#. c #D3ABAB",
"$. c #C5BCBC",
"%. c #C8BFBF",
"&. c #D5B5B5",
"*. c #D8B1B1",
"=. c #D3BDBD",
"-. c #DEBEBE",
";. c #C5C5C5",
":. c #CEC5C5",
">. c #CDCDCD",
",. c #D0C7C7",
"<. c #DEC5C5",
"1. c #D1C8C8",
"2. c #D3D3D3",
"3. c #DCDCDC",
"4. c #E4CCCC",
"5. c #EAD6D6",
"6. c #EADBDB",
"7. c #E3E3E3",
"8. c #EBEBEB",
"9. c #F2E6E6",
"0. c #F6EFEF",
"q. c #F4F4F4",
"w. c #FAF5F5",
"e. c #FFFFFF",
"r. c None",
/* pixels */
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.                    .                 r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.        + & i p u %           . $ u i i y $             r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.      % p p %               + + % % % + O           . % & +           r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.      u g y         + + % % % $ y E { ;.;.;.{ E & $ $ % + O         # +           r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.    y h y       + + % y E { ;.;.;.;.;.2.2.2.2.2.2.2.;.;.| | ] k & $ O +       O O         r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.  + h h .     + % y E { ;.>.2.2.2.2.2.2.>.2.>.2.2.2.2.2.2.2.2.2.>.>.;.{ ` k & $ +       +         r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.  $ j g       + y k { >.3.2.2.2.2.2.2.>.>.2.2.>.2.2.2.2.2.2.3.2.2.2.2.2.>.2.>.>.| ` j % $ O     O         r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.  # j i     + % y E ;.3.3.2.2.2.2.>.2.>.>.2.2.2.2.2.3.2.3.3.7.7.7.3.7.3.3.3.2.2.2.>.2.>.;.;.` h & O     .         r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.    g g     + y k | >.3.2.2.>.2.>.>.>.2.2.2.3.2.3.3.3.7.7.7.7.8.7.8.8.8.8.7.7.7.7.7.3.3.3.2.2.2.2.>.{ j & O             r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.  y k     + y W >.3.3.2.2.>.>.>.>.>.2.2.3.3.3.7.7.8.8.8.8.q.8.8.q.q.q.q.q.q.q.q.8.8.8.8.8.7.7.3.2.2.2.2.>.| j % +             r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.  . j i     % k >.3.3.2.2.2.>.>.2.>.2.3.3.3.7.7.8.8.8.q.q.q.q.q.q.w.w.e.w.w.e.e.q.w.q.w.q.q.q.q.8.8.8.7.3.3.2.2.>.| j % +           r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.  & E     + y ] 7.3.2.2.2.>.>.2.2.2.3.3.7.7.8.8.q.q.q.w.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.w.q.q.q.q.8.8.8.8.7.3.3.2.2.| h $             r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.  g j     % k >.3.2.2.2.2.>.>.2.2.3.3.7.7.8.q.q.q.w.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.e.e.q.q.8.8.7.3.3.2.>.! & O           r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.  k &   + y ] 3.3.2.2.2.>.>.2.2.3.7.7.8.q.q.q.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.q.q.q.q.q.8.8.7.3.2.| h $           r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.. k     % k 2.3.3.2.>.>.>.2.2.3.7.7.8.q.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.q.q.8.8.7.7.3.2.^ &           r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.  O k     y ] 7.3.3.2.2.>.2.2.3.3.7.8.q.w.w.w.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.q.e.q.q.8.7.7.2.` % O         r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.  + E     y ] 7.3.2.2.>.>.2.2.3.7.8.8.q.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.q.q.q.8.7.3.;.h #         r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.+ k     y ] 7.3.2.2.>.>.2.3.3.7.8.q.q.w.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.w.q.8.7.7.+.; o         r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.. k     y ] 7.3.2.2.>.2.2.3.7.8.8.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.e.q.q.=.7 < = o   .     r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.  k     y ] 7.3.2.>.>.>.2.3.7.8.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.<.x 2 M < * X         r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.  k     y ] 7.3.2.>.>.2.2.7.7.8.q.q.e.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 2 T 2 < - > #         r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.  g &   y ] 7.3.2.>.2.>.2.7.8.q.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3 R 3 < - 6 } g O       r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.  & j   % ] 7.3.2.>.>.>.3.3.7.8.w.e.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3 R 3 2 , 9 %.;.] %   O     r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.  k   + k 7.3.2.>.>.2.2.7.7.q.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3 R 3 2 , q :.>.;.| W %         r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.  k     y 2.3.3.2.>.2.2.7.7.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x l R l 2 , q ,.2.;.;.| | E $         r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.  y i   % ] 3.3.2.>.2.3.3.7.q.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x l R 3 2 , q 1.2.>.;.;.;.;.;.h + +     r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.  k   + k 7.3.2.>.>.2.3.7.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x l R 3 2 , q ,.2.>.;.;.;.;.>.2.| &         r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.  g     y >.3.2.>.>.2.3.7.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x l R 3 2 , q ,.2.;.;.;.;.>.2.3.7.3.E O       r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.+ h   % ] 3.2.2.>.2.2.7.8.q.w.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x l R 3 2 , q ,.2.>.;.;.;.>.2.7.8.8.8.2.&         r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.  j   + k 7.3.2.>.2.2.7.8.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3 R 3 2 , q ,.2.>.;.;.;.>.2.6.7.8.q.q.q.] $         r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.$ p   y >.3.2.>.>.2.3.7.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x l R l 2 , q >.2.>.;.;.;.>.2.7.7.q.e.q.e.q.8.k +       r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.  j   + W 7.2.2.2.2.3.7.8.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3 R 3 2 , q >.2.>.;.;.;.>.2.7.7.q.q.w.e.e.w.w.2.&         r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.+ g   y >.3.2.>.>.2.3.8.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x l R l 2 , q ,.2.>.;.;.;.>.2.3.8.q.q.e.e.e.e.e.e.q.W + O     r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.  h   + k 3.2.>.2.2.3.7.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x l R 3 2 , q ,.2.>.;.;.;.>.2.7.7.8.w.e.e.e.e.e.e.e.q.2.y         r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.  j   % | 3.2.2.>.2.7.8.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3 R l 2 , 9 >.2.>.;.;.;.>.2.7.8.q.q.e.e.e.e.e.e.e.e.q.q.k O O     r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.  y O   y >.2.2.>.2.3.7.q.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3 R 3 2 , q >.2.>.;.;.;.>.2.7.7.8.w.w.e.e.e.e.e.e.e.e.e.w.;.%       r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.  g   + E 3.2.>.2.2.7.8.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x l R l 2 , q ,.2.>.;.;.;.>.2.6.7.q.q.e.e.e.e.e.e.e.e.e.e.e.e.7.y         r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.  y   y ;.2.2.2.2.3.7.8.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3  .l 2 , q ,.2.>.;.;.;.>.2.7.7.q.q.q.e.e.e.e.e.e.e.e.e.e.e.e.q.W + .     r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.  y   O k 3.2.>.>.2.7.8.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3 R l 2 , q ,.2.>.;.;.;.>.2.7.7.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.3.y       r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.  g   % { 3.2.>.2.2.7.8.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x l R 3 2 , q 1.2.>.;.;.;.>.2.7.7.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.q.k +       r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.  y   & 2.2.>.>.2.3.8.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x l R 3 2 , q 1.2.;.;.;.;.>.2.7.7.q.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.;.+ +     r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.$   + E 3.2.>.>.2.7.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x l R 3 2 , q ,.2.>.;.;.;.>.2.3.8.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.3.% O     r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.  i   + { 3.>.2.2.3.7.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3 R l 2 , 9 >.2.>.;.;.;.>.2.7.8.0.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.8.y       r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.  p   % ;.2.2.2.2.7.8.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3 R 3 2 , q >.2.>.;.;.;.>.2.7.7.8.w.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.W + .     r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.  y   & 2.2.>.2.2.7.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.w.w.w.e.e.e.e.4.x l R l 2 , q ,.2.>.;.;.;.>.2.7.7.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.;.+ #     r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.O . + E 2.2.2.2.3.7.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.9.4.O./ T / O.<.9.w.4.x 3 R l 2 , q ,.2.>.;.;.;.>.2.7.7.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.3.% +     r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.  &   O { 3.2.>.2.3.8.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.9.@.S v 5 5 5 5 4 v S ( x 2 R 3 2 , q ,.2.>.;.;.;.>.2.3.8.q.q.e.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.7.% .     r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.  i   % ;.2.2.2.2.7.8.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.5.Y x l 3 3 3 2 2 2 2 4 2 2 I 2 2 , 9 ,.2.>.;.;.;.>.2.7.7.8.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.8.y       r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.  i   % ;.2.2.2.3.7.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.5.P z 3 3 3 l l l l l 3 2 < 4 < < , 9 :.2.;.;.;.;.>.2.7.7.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.! +       r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.  u   % ;.2.>.2.3.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.9.Y z 3 3 A ..o. .D N 3 3 2 2 < < , 6 $.;.;.;.;.;.>.2.7.8.8.e.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.;.+       r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.  %   % ;.2.>.2.3.7.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.@.x 2 3  .-.*. .D Z N b 3 l 2 2 < , L | | $.;.;.;.2.3.8.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.3.% +     r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.  O   & >.2.2.2.7.8.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.9.S 3 3 D -.@.D N c z z z 3 l 3 2 < , t ` { { ;.;.2.3.8.q.q.e.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.7.% &     r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.    + E 2.>.>.2.7.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.-.x 2 l o.*.U m z l l l l l l 3 2 2 < 1 K ' ] | >.3.8.8.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.7.% y     r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.    + { 2.2.2.3.7.8.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.o.3 l z O.R M z l l l l l l l 3 2 2 , , F _ ] ;.>.7.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.7.% u     r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.    % ;.2.>.2.3.7.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.Y 2 2 z  .D c l l l l l l l l l 3 2 < - s ^ { ;.2.7.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.7.% u     r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.  O % ;.2.2.2.2.7.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.0.I 2 3 l U B z l 3 l l l l l l 3 2 2 , , a ^ { ;.2.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.7.% y     r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.  % O ] 2.2.2.3.8.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.q.Y 2 3 3 B N l l l l 3 l l l l 3 3 2 , - d ` { ;.3.8.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.7.% &     r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.  u + E 2.2.2.3.7.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w...2 2 l l m l l l l l l l l l 3 2 < , - C ' { ;.3.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.7.% &     r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.  i   & ;.2.3.7.8.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.&.4 2 2 3 l l l l l l l l 3 l 3 2 < - 1 K ] | >.2.8.8.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.7.% &     r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.  i   % | 2.2.3.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.6.V 2 2 3 l 3 l l l l 3 3 3 3 2 < , - 0 ^ { ;.;.3.8.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.7.% y     r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.  y   $ ;.2.2.3.8.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.q.T 2 2 2 2 3 3 l l l 3 3 3 2 < < - - G ] } ;.>.3.7.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.3.% &     r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.  $   $ ;.>.2.3.7.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.5 2 < < 2 2 3 2 l 2 3 2 2 < , - - s _ { { ;.>.7.8.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.;.% $     r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.  O   $ | 2.2.3.7.8.e.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3 P < < < < < 2 2 2 2 < < , , - r Q ] { | ;.>.3.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.! i     r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.      O ] >.2.3.7.8.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3 R 2 < , , < < < < < < , , - - s Q ] { | ;.>.2.7.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.q.y p     r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.  O O k >.2.2.7.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3 R l 2 - 6 H e , - - - - - : 0 F ) ] { | | ;.2.3.8.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.7.% h     r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.  %   & ;.>.2.7.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x l R 3 2 , 9 $.} ) G f r r a f J ~ ` { | | | ;.2.3.7.8.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.7.& p     r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.  %   $ | >.2.7.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3 R l 2 , q ;.;.| ] ` ^ Q ~ ^ ` ] ] { | | ;.;.>.2.7.8.w.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.;.# &     r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.  O   + ` >.2.3.8.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3 R 3 2 , q ;.2.;.| { ] ] ] ] } { | | ;.;.;.;.2.3.7.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.! i     r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.      O k >.2.3.7.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x l R l 2 , q ,.2.;.;.| | | ;.;.;.;.>.;.>.;.>.2.3.3.7.8.q.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.8.y h     r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.  $   & ;.>.3.7.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3  .l 2 , q ,.2.>.;.;.;.;.>.>.2.2.3.3.2.3.3.3.3.7.8.8.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.>.% h     r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.  +   $ ' >.2.7.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3 R l 2 , q ,.2.>.;.;.;.>.2.3.7.7.8.7.7.7.7.7.7.8.8.q.w.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.! u $     r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.      + j >.2.3.8.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x l R 3 2 , q 1.2.>.;.;.;.>.2.3.7.8.q.q.q.q.q.8.q.q.q.q.e.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.8.y h     r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.    +   & | 2.3.7.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x l R 3 2 , q 1.2.;.;.;.;.>.2.7.8.8.q.q.w.w.e.w.e.q.e.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.>.& h     r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.  .   $ ' >.3.7.8.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x l R 3 2 , q ,.2.>.;.;.;.>.2.7.8.8.w.e.e.e.e.e.e.e.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.E i #     r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.      O h >.2.7.8.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3 R l 2 , 9 ,.2.>.;.;.;.>.2.7.8.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.3.y k     r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.  +   & { 2.3.7.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3 R 3 2 , q >.2.>.;.;.;.>.2.3.7.8.w.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.! & p     r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.      O j >.2.7.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x l R l 2 , q ,.2.>.;.;.;.>.2.7.8.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.7.y j       r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.    O   & { 2.3.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3  .l 2 , q ,.2.>.;.;.;.>.2.7.7.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.e.! $ h     r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.      O j 2.2.7.q.w.w.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3 R l 2 , q ,.2.>.;.;.;.>.2.7.7.q.q.e.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.7.y h       r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.    .   & { 2.7.8.q.e.e.e.e.e.e.e.e.e.e.e.e.4.x 3 R 3 2 , q 1.2.>.;.;.;.>.2.7.7.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.! # h     r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.      + j 2.3.7.q.q.e.e.e.e.e.e.e.e.e.e.4.x l R l 2 , q 1.2.;.;.;.;.>.2.3.8.q.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.7.y h       r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.        & { 2.7.8.w.w.e.e.e.e.e.e.e.e.4.x 3 R l 2 , q ,.2.>.;.;.;.>.2.7.7.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.! % p     r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.      O h 2.3.7.q.q.e.e.e.e.e.e.e.4.x 3 R 3 2 , q ,.2.>.;.;.;.>.2.7.7.q.q.e.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.7.y j       r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.        $ ! 2.7.8.q.w.e.e.e.e.e.4.x l R l 2 , q ,.2.;.;.;.;.>.3.7.7.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.E g &     r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.        & | 3.7.q.q.e.e.e.e.4.x l R 3 2 , q ,.2.>.;.;.;.>.2.3.7.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.| y k     r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.      O h 2.7.8.q.e.e.e.4.x 3 R 3 2 , q ,.2.>.;.;.;.>.2.7.7.q.q.e.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.;.y k       r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.        $ ! 2.7.q.q.w.4.x 3 R l 2 , q ,.2.>.;.;.;.>.2.7.8.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.7.y g &     r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.        & ^ 3.7.q.<.x 3 R 3 2 , q >.2.>.;.;.;.>.2.3.8.8.w.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.E u j     r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.        & ;.7.%.8 3 R l 2 , q ,.2.>.;.;.;.>.2.3.8.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.| y k       r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.      O j +.7 2 R 3 2 , q ,.2.;.;.;.;.>.2.7.8.q.q.e.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.| y E       r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.        # ; < n 2 < , q >.2.>.;.;.;.>.2.7.7.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.{ y k       r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.        o = < < - 9 >.2.>.;.;.;.>.2.7.7.q.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.| y k #     r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.        o * - 6 %.>.;.;.;.;.1.2.7.7.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.{ y j %     r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.        X @ ` ;.;.| ;.;.>.2.3.7.q.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.| y k %     r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.    .   O % W | | ;.;.2.3.8.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.| y E #       r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.      .   % E | ;.>.3.8.q.q.e.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.7.W y k       r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.      +   # g { >.7.8.w.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.| y u k       r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.      O   O % ^ 7.8.q.e.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.7.E % g h       r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.            $ j 2.8.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.q.| y % k #       r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.          O & ] 8.q.q.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.7.W % p j         r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.            % k | 7.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.7.! y y k #       r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.            O % y W 2.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.7.! y % j p         r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.        +     + y W 3.w.e.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.8.>.E y $ h g         r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.        O     + & k ;.8.q.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.3.! y % y h p           r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.                + % y W ;.3.8.w.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.8.7.;.E y # i j y           r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.            .   + + % y W ;.3.7.8.w.e.w.e.e.e.e.e.e.e.e.e.w.q.7.7.;.! u % + p j g             r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.            . # .   + + % % y ! ;.3.7.7.7.7.7.7.7.7.;.! y % % + & i h p               r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.                . + +     + + % % % % % % % % % % i p h g u O               r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.                        O $ & y y y y y y % .                   r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.                                                r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.                        r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.",
"r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r."
};
