/*
 * Embroidermodder 2.
 *
 * Copyright 2011-2024 The Embroidermodder Team
 * Embroidermodder 2 is Open Source Software, see LICENSE.md for licensing terms.
 *
 * Read the reference manual (https://www.libembroidery.org/downloads/emrm.pdf)
 * for advice on altering this file.
 */
/* XPM */
static char *drawing2[] = {
/* columns rows colors chars-per-pixel */
"128 128 97 2 ",
"   c #000000",
".  c #0E0404",
"X  c #0E0E0E",
"o  c #130505",
"O  c #131313",
"+  c #1C1C1C",
"@  c #270B0B",
"#  c #280B0B",
"$  c #2A1B1B",
"%  c #3D1010",
"&  c #232323",
"*  c #2B2B2B",
"=  c #333333",
"-  c #3C3C3C",
";  c #421212",
":  c #4C1414",
">  c #521616",
",  c #6F1E1E",
"<  c #422525",
"1  c #472A2A",
"2  c #424242",
"3  c #4B4B4B",
"4  c #525252",
"5  c #5C5C5C",
"6  c #646464",
"7  c #6C6C6C",
"8  c #747474",
"9  c #7E7E7E",
"0  c #822323",
"q  c #8A2525",
"w  c #902727",
"e  c #962828",
"r  c #9D2A2A",
"t  c #A22C2C",
"y  c #AC2E2E",
"u  c #B12F2F",
"i  c #B53131",
"p  c #BB3232",
"a  c #C43535",
"s  c #C93636",
"d  c #945353",
"f  c #9A5757",
"g  c #AF4E4E",
"h  c #A45D5D",
"j  c #BC5151",
"k  c #966262",
"l  c #9C6767",
"z  c #AE6464",
"x  c #A56D6D",
"c  c #AC6F6F",
"v  c #B16464",
"b  c #B46B6B",
"n  c #BA6B6B",
"m  c #AD7272",
"M  c #B47272",
"N  c #BB7272",
"B  c #B67A7A",
"V  c #BA7C7C",
"C  c #C55353",
"Z  c #CC5656",
"A  c #CD5A5A",
"S  c #D45C5C",
"D  c #C16F6F",
"F  c #C57171",
"G  c #CB7474",
"H  c #C47A7A",
"J  c #CE7979",
"K  c #D57C7C",
"L  c #9E9E9E",
"P  c #BE8383",
"I  c #A3A3A3",
"U  c #ACACAC",
"Y  c #B6B6B6",
"T  c #BDBDBD",
"R  c #C28181",
"E  c #C98484",
"W  c #C68989",
"Q  c #CD8989",
"!  c #D48383",
"~  c #DB8383",
"^  c #D48A8A",
"/  c #DA8C8C",
"(  c #C29C9C",
")  c #DE9191",
"_  c #E19292",
"`  c #D2A9A9",
"'  c #D6B1B1",
"]  c #EEBEBE",
"[  c #C3C3C3",
"{  c #CACACA",
"}  c #D4D4D4",
"|  c #DCDCDC",
" . c #E4E4E4",
".. c #ECECEC",
"X. c #F3F3F3",
"o. c #FDFDFD",
"O. c None",
/* pixels */
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.                                                                                                                                                                                                                  O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.                + & * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * = * +               O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.    5 6                                                                                                                                                                                         + 5 9 9 &         O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.      8                                                                                                                                                                                                 O 4         O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.        o # # # # # # @ @ @ @ @ @ @ @ @ @ # # # # # # @ @ @ @ @ $ = = * * $ @ @ @ @ @ @ @ # # # # # # @ @ @ @ # # # # # # # # # @ # # @ @ @ @ # # # # # # # # # @ # # @ @ @ @ @ @ @ @ @ # # # # # # #             O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.        ; t t r r r r t t r t t t t r t t t r t r t t t r t t t c [ { [ U l r e r r r r t r t t t t r t t t r t t t r r t r t t r t t t t t r t t t r r t r t t r t t t t r t t t t r t r t r r t t t             O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.        ; r r r r r r r r r r r r r r r r r r r r r r r r r r r c [ [ [ I l e e e e r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r             O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  O     ; r r e r r t t r t t t t t t t t t t t r t t t t t t t m [ { [ U k w e e e r r t t t t t t r t t r t t t r t t t t t t t t t t t r t t t r t t t t t t t t t t r t t t t t t r t t t t r t t             O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  &     ; r r r r r t y y y y y y y y y y y y y y y y y y y y y M { } { U l r e r r t t y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y u y     &       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  -     ; r r r t y u i i i i p i i i p i i p p i i i i i i i i H |  .| T x r r t t y u i p p i i p i i i i p i p i i p p p p i p p p i i i p i p i i p p p p i p p p p i i i p i i i p p i p i p i i     -       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     % r r r t u i p p a p a p a p a p p a p p a a p a p a a E  .X. .[ m t t y u i p p p p a p a p p a a p p a p a p p p p p p p p p a a p p a p a p p p p p p p p p p a p a p a p p a p a p p p a     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; r r t y i C K ! K K A a s a s s A ! K K K A a a s s a ^ ..X...{ m y y y i p A ! ! J K A a a a s a S ~ K K K A a a a s a S ! ! K J A s a s a a S ~ ! K K A a s s s a A ! ~ K K A a a a s s s     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t r t y i ^ X.X.X. .^ s s s s s ) o.o.X. .Q s s s s s ^ X.o.X.} V y y y p p ) o.o.X. .^ s s s s s _ o.o.X. .^ s s s s s ) o.o.X. .^ s s s s s / o.o.X. .^ s s s s s ) o.o.X. .^ s s s s s s     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  -     ; r t t y p ^ X.o.o. .Q a s a s s ) o.o.o. .Q s s s s s / o.o.X.} V y y u p p ) o.o.o. .Q s a s s s _ o.o.o. .Q s s s s s _ o.o.o. .^ s s a a s _ o.o.o. .Q s s s s s _ o.o.o. .Q s s s s s s     3       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t r t y p ! X.o.o.| E a a a s s / o.o.X. .E a a a a s / X.o.X.} V y u u p p ) o.o.X.| E a a a s s / o.o.X.| E a a a s s / o.o.X.| E a a a a s / o.o.X.| R a a a s s / o.o.X.| E a a a s s s     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t t t y i ! .... .} R a p a a s / ..X...} R p a p a s / X.o.X.} P u y u p a ^ ......} H p a a a a / X.X. .} R p a p a s / ..X. .} R a a p a s / X.X. .} R a p a a a / ..X...} R p p a a a s     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; r r t u i E | | } { V p p p p a ^ | } } { H i p i a a ^ o.o.X.} B y u i i p ^  .| } { R i p p p a ! | | } { P p p p p a !  .| } { R p p p a a ! | | } { R p i p a a ^  .} } { H p p i a a a     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  -     ; t t t u i C J F D D j i i p p a Z K G D D j i i i a a ^ X.o.X.} V y y i i a Z J G F D j i i p p a A J G G D j p i i p a Z K G F D j i i i p a Z J J F D j i i i p a Z K G F D j i i i a a a     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t t t y i a a a a p p i i i p a s a s a a i i i i i a ^ o.o.X.} B u y u p a a a a a p p i i i p a a a a a p i u i i p a a a s a p i i i i p a a a a a p i i i i i a a s a a p p i i i i a s     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t t t y i a s a a p p i i i p a s s a a p p i i i a a / X.o.X.| V y u i i p a s a a p i i i p p a s a a a p i i i p p a s s a a p u p u p p a s s s a p p i i i p a a s a a a i i i p p a a     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; r r t y p p a a s p p p p p a a s s a a a p p p i a a / o.o.X.| P y u u p a a s a a a p p p p p a s s s a a p p p p p a s s s a a p p p p p s s s a a p p p p a a a s s s a p p p p p p a s     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  -     ; t t t y p a a s a a p p p a a a s s s a a p a a p a s ) o.o.o. .W y y u i p a s s s a p a p a a a s s s a a a p p a a s s s s a a a a p a a s s s s s a a p a a a a s s s s a a a p a a s s     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; r r t u p a a s s s a s a a a s s s s s s a a a a a s _ o.o.o. .E y y i i a a s s s a s a a a a s s s s s a a a a a a s s s s s a a a a a a s s s s s a a a a a a a s s s s a a a a s s s s     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t r t y p A ! ~ ~ K A s s s s s S ~ ~ ~ K K K K ~ ~ ~ ] o.o.o.X.` H H H H K K K K K K A a a s s s S ~ ~ ~ K A s a s s s S ~ ~ ~ ! A a a s s s S ~ ~ ~ ~ A a a a s s S ~ ~ K K A s a s s s s     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; r t t y i ^ X.o.X. .^ s s s s s _ o.X.X.X.......X.o.o.o.o.o.o.X.X............... .| | ^ a s s s s _ o.o.X. .^ s s s s s _ o.o.X. .^ s s s s s _ o.o.X. .^ s s s s s _ o.o.X. .^ s s s s s s     3       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  -     ; t t t u i ^ o.o.o. .Q a a s s s _ X.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.X... .} Q a a s s s _ o.o.o. .Q a s s s s _ o.o.o. .Q s s s s s _ o.o.o. .Q s a s s s _ o.o.o. .Q s a s s s s     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; r t t y i ! X.o.X. .E a a a s s / X.o.o.o.o.o.o.o.o.o.X.X.X.......X.o.o.o.o.o.o.X.| { R a a a s s / o.o.o.| E a a s s s / o.o.o.| E a a a a s / o.o.X.| E a a a a s _ o.o.o. .R a a a s s s     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t r t y p ! ......} H p p a a a / X.o.o.o.X... . . . .| | } } | | |  . .X.X.o.o.X.| { V p p a a s / ..X...} H a p a a a / X.X. .} R a p p a s / ..X. .} H p a p a a / ..X. .} R p a a a a s     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t r t y p E | } } { P p i p a a / ..o.o.X.| } { [ [ [ [ T T ' T T [ { { }  ...X.X. .{ B i i p p a ^ | | } { R i p p p a ^ | | } { H p p p a a ^  .| } { R p i p a a ~  .| } { V p p i a a s     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t t t u i C G G F F j p i p p a ~ X.o.o. .( b v v z z z z z x z z z z b M N ` ..X. .{ B u i u p a Z J G D D j i i p p a Z K G D D j i i i p a Z G J D D C i i p p a Z K G D D j i p i a a a     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  -     ; r r t y u a a a a p i i i i p a ^ X.o.X.| N y y y y y y y y y y t y y t y y R X.o. .{ M t u u p a a a s a p i i i i p a a a a a p p i i i p a a a a a a u i u i p a a a a a p p u i i i a a     3       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t r t y p a a s a p i i i i p a / X.o.o.} N y y t y y t y y y y y y y y y y R X.o.X.} B y y i p p a s a a p i i i i p a a s a a p i i i p p a a s s a a i i i p p a s s s a p u p u p p a a     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t t t u u a a a a p p p p p a a / o.o.X.} M y y y y u u i i i u i i i i i u Q X.o.o.| B y y u p a a a s a a p p p i a a a s s a a p p p p p a a s s a p p i p p p a s s a a a p p p p p a s     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  -     ; t r t y p a a s a a a p p a a a _ o.o.X.{ M y y y u i i i p i p i p p p i p Q X.o.o. .P y y u p p a s s s a a a a a a a s s s s a p p a a a a s s s a a a a p a a a s s s a a p p a a a s s     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t t t y u a a s s s a a a a a s _ o.o...{ M u y y i i p a p p a a a p a p a ^ X.o.o...E y y i i a a s s s a a a s a a s s s s s a a a a a a s s s s s a a a a a s s s s s s s a a a a a s s     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     1 z z x c n J J K K K K K K ~ ~ ~ ] o.o...[ N u u u i p A ~ ~ ~ K A s a a s a ^ X.o.o.X.' H H H H J K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     4 T T ' { }  . ...X.....X.X.X.o.o.o.o.X. .[ M u y y p p ) o.o.X. .^ s s s s s / X.o.o.o.X...........X.......X.......X.......X...X.....X.....X.X.....X.......X.......X.......X...X......... . .    2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     4 [ [ { |  .X.o.o.o.o.o.o.o.o.o.o.o.o.X.| [ b y y u p p ) o.o.o. .Q s a s s s ^ X.o.o.o.o.X.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.X...|     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  -     4 { [ { }  .X.X.o.o.o.o.o.o.o.o.o.o.o.X.} [ M u y u p a / o.o.X.| W a a a s s ~ ..o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o... .}     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     3 Y Y Y [ } }  . . . . . . ...X.X.X.o...| [ b y y u p p ) X.X. .} H p p a a a ^ ..X.o.o... . . . . . . . . . . . . . . . ... . . . . . . . . . . ... . . . . . . . . . . ... . . . . . .| } {     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     3 I L L I U Y T T [ [ [ [ { { } | ..X...| [ m y y u p p Q | | } { P p p p p a ^ X.o.o...| { { [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ T [ ' T     3       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     < f d d f h h z v v v v v b b n N ` ..X. .[ M y y u i a A J G G N j i i p p a ^ ..o.o. .( b z z v v v z v v v v v v z v z v v v v v v v v z v v z v v z v v v v v v v v z v v z v z z x z z b     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  -     ; r w e e r t t y y y y y y y y y E X.X...{ M y y u p p s a a a p p i i i p a ^ X.o.X.| V y y t t y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y y u     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; r e e r t t y y y y y y y y y y E X.o.X.} M t y i p a a a s a p p i i u p a / X.o.X.} V y y y y y y y y y y y y y y y y y y y y u y y u y y u y y u y y u y u y y y u y y u y y y y y y y y     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     % r e e r t t y u i u i i u u u i Q X.o.X.| M u y u p a a s a a p p p p p a a ) o.o.X.} B y y y y y y i i i u i i i i i i y i u u u u u u u i u u u u u i u u i u u u u u i u i i i u u i i i     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  -     ; r e r r t i i p p p p p p p p i ^ X.o.o. .V y u u i p a s s s a a p a p a a ) o.o.X.} B y y y y i i i p p p i p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; r r r t u i p p a a p p a a a a ^ X.o.o...H y y i p a a a s s a a a a a a s _ o.o...} B u y u i i p p a p a a p a p p a p a a a p a p a p a a p a p p a a p p a p a p a p p p a p a a p a p     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; r r r y i Z ! ! ! K A a a a a a ^ X.o.o.o.` H H H J K K K K K K K K K ~ ~ ~ ] o.o...{ B u y u i p A ~ ~ ! K A a a a a a S ~ ~ ! K A a a a a s D ~ ~ K K A a a a a s S / ~ ! ! A s a a s a s     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t r t y i ^ X.o.X. .^ s s s a s / ..o.o.o.X.........................X.X.o.o.o.o.o. .[ B y u i i p ) o.o.X. .^ s s s s s _ o.o.X. .^ s s s s s _ o.o.X. .^ s s s s s _ o.o.X. .^ s s s s s s     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; r t t y i ^ o.o.o. .Q a s a s s / ..X.o.o.o.o.o.o.o.o.o.o.o.X.o.o.o.o.o.o.o.o.o...} [ B y u u i p ) o.o.o. .Q s s s s s _ o.o.o. .Q s a s s s _ o.o.o. .Q s s s s s _ o.o.o. .Q a s s s s s     2       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  -     ; t r t u i ! X.o.X. .E a a a s s !  .....X.X.X.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o.o...| { T B y y i i a / o.o.X. .E a a a s s / o.o.X. .E a a a s s / o.o.o.| E a a a s s / o.o.X.| E a a a a s s     3       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t r t y p ! ......} E p p a a s ^ |  .| | | |  ...X.o.o.o.o.o.o.X..... . .| | } { [ T B y y i i a / ..X. .} R p p a a a / X.X. .} R a p p a a / ..X. .} R p p a a a / ..X...} W p p a a a s     5       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t r t y p E | } } [ P p p p p a ! | } { [ [ [ [ { } | ..X.X.X...} } { [ [ [ [ T T Y T V y y i p p !  .| } { P p p p p a !  .| } { H p p p a a ^  .} } { R p p p p a !  .| } [ R p p p p a s     5       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t t t u i C J F F F j i i p p a Z G F D n v v v b b N ` ..X...| I v v z v v z z z z z g y y y p a Z J G D D j i i p p a Z J G D D j i i i p a Z K G F D j i i p p a Z G G F D j i i p p a a   * 4       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  -     ; r r t y u a a a a p i i i i p a s a a a p u y y y y y R ..o...} G y y y y y y y y y y y y y i p a a a a a p i i i i p a a a a a p p i i i p a a a s a p p u i i p a s s a a p p u i i p a s   7 *       O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t r t y p a a s a p i i i p a a s s a a a u u y y y y E X.o...} B t t t y y y y y y y y y i i p a s s a a p i i u p p a a s a a p i i i p p a a s 0 > : : : : : : : > > > > : : : : : : : >   9         O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t t t u u a a s a p p p p p p a s s s a a p i u i i i E X.o.X.} B y y y y y y u i i u i i i p p a a s s a a p p p p a a a s s a a p p p p p > %                                           O 6 9         O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  -     ; t r t y p a a s a a p a a p a a s s s a a p p p p i i Q X.o.X.} B t y y y i i p i p p p p p p a s s s s s a a p p a a s s s s a a p p a a a #             O & * = = = = = = = - = - 3 4 6 9 9 2         O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t t t y u a a s s a s a a a s a s s s s a a a a a a a ^ X.o.X.} B y y y i i p p a a p a a a a s s s s s s a a a a a s s s s s s s a a a a a #     7 7                             = 6 9 9 9 8           O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t t t u i Z ~ ~ ~ K A a a s s s S ~ ~ ~ K A s s a a a ^ X.o.X.} V y y u i p A ! ! ~ ! A s a s s s S ~ ~ ~ K A s a s s s S ~ ~ ~ ! A a s s s #   & 7                                     * 3 -           O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; r r t u p ^ X.o.X. .^ s s s s s _ o.o.X. .^ s s s s s ^ o.o.X.} B y u u p p ) o.o.X. .^ s s s s s _ o.o.X...^ s s s s s _ o.o.X. .^ s s s s #                                                           O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  -     ; r t t y i ^ X.o.o. .Q s a a s s _ o.o.o. .Q a a s s s / X.o.X.} V y y u p p ) o.o.o. .Q a s s s s _ o.o.o. .Q a a s s s ) o.o.o. .Q a s a s #         q t r r r r e r r r r r r r e r q .               O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t r t u i ^ X.o.o.| E a a a s s / o.o.o.| E a a a s s / X.o.X.} B y u u p p ) o.o.X.| E a a a a s / o.o.o.| E a s a s s ) o.o.o.| E a a a s #         q r r r e r r e r r r r r r r 0 . + O             O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t t t y p ! ..X...} R a p a a a / ..X. .} E p p a a s ^ X.o.X.} P y y u p a ^ X.X. .} R p p p a a / ..X. .} H p p a a a / X.X...} R a p a a @   X     q r e e r r r r t r t r r r q o X 3             O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; r r t u i H | } { { V p p p a a ~  .| } [ H p p p p a / o.o.X.} B y y u p p ^ | | } { R p p p a a ~  .| } { P p p p p a ! | | } { V i p p p @   +     , r e e r t t t y y t t y w o   5 *           O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  -     ; r t t u p C J G D D j i i p p a Z J G D D j i i p p a ^ X.o.X.} P y u u p p Z G G F D j i p p p a Z J G D D j p i i p a Z K G D D j i i p p @   *     0 r r r t y y u i u u u r o   3 8           O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t r t y p p a a a p p i i i p a a a s a p p i i i p a / X.o.X.} B u y u p a a s s a p i u i i p a a a s a p i i i p p a a s a a p p i i i p #   *     0 r r t y i i p p a a t o   & 9           O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t t t y i a a a s p i i p i p a s s a a p p p i p p a ^ X.o.X.} V y u u p p a s a a p i i i p p a s s s a p p i i p p a a a a a a i i i p p #   *     0 r r t y i a a a a y o   + 9           O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; r r t y p p s a s p p p p p a a a s a a a p i p p p a / o.o.X.} V y y u p p a a s a p p p p p p a a s s a p p p i p a a s s a a a p p p p p #   =     0 r t y u p a a s y o   O l X         O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  -     ; r t t y p a a s s p p p p a a a s s s s a p p a p a s / X.o.X.} V y u u p p a s s s a a p a p a s s s s a a p a a p a s s s s a a p p p a a @   *     0 r r t i p a s i o   + L           O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t r t u p a a s s s a s a a a s s s s s s a a a a s s / X.o.X.} B u y i p p a s s s a a a a a s s s s s s s a a a a s s s s s s a a a a a a #   =     0 r t t i p a y o   $ 9           O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t t t y p Z ! ~ ~ K A a s s s s S ~ ~ ~ K A s a s s s / X.o.X.} V y u i p p S ~ ~ ~ ~ A a s s s s S ~ ~ ~ K A s a s s s S ~ ~ K ! A s a s s #   =     0 r t y u p t o   + 9           O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; r r t y u / X.o.X. .^ s s s s s _ o.o.X. .^ s s s s s / X.o.X.} B y y i i a ) o.o.X. .^ s s s s s _ o.o.X. .^ s s s s s _ o.o.X. .^ s s s s #   -     0 r t t i t o   & 9           O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  -     ; t r t u u ^ o.o.o. .Q s a s s s _ o.o.o. .Q a s s s s / o.o.X.} V y u u p p ) o.o.o. .Q a a s s s _ o.o.o. .Q a s s s s _ o.o.o. .Q s a s s #   3     0 r r t r o   + 9           O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t t t u p Q X.o.X. .E a a s s s / o.o.o.| E a a a s s / X.o.X.} V y u u p p / o.o.o.| E a a a s s / o.o.o.| E a a a s s ) o.o.o.| E a a a s #   6     0 r t w o   X L           O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  -     ; t r t u p ! ......} H p p a a a / ..X. .} R a p a a s / X.o.X.} B u y i i p / ..X. .} R p a p a a / ..X. .} R p p a a s / X.X. .} H p p a a @   8     q r q o   & L           O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t t t y i J | | } { P p p p a a !  .| } { V p i p p a ^ X.o.X.} B u u i i a / | | } { R p p p a a !  .| } { R p p p p a ! | | } { P p p p p @   7 2   , q o   3 9           O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; r t t u p C J F F n j i i i p a Z J G F D j p i p p a ^ o.o.X.} B y y u p p Z J G F D j i i p p a Z J G F F j i i p p a Z J J D D j i i p p @   3 8   , o O 5 8           O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  2     ; t r t y u p a a a p p i i i p a s a a a p p u i i p a ^ X.o.o.} B y u i p a a a a a p p u i i p a a s a a p i i i i p a s a a a p p i i p p @   + L * o + 2 &           O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  3     ; r t t y p a a s a p i i i p p a a s a a p p i i p p a ^ X.o...} V y y u p p a s a a p p i i p p a s s s a p p i i i p a a s s a p p i i i p @   O L 5 O X             O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  3     ; t r t y i a a s a p p p p p a a a s s a p p p p p p a ^ ..X...} B y u u p p a s s a p p i p p p a a s s a p p p p p a a a s a a p p p p p p @   + 6 3               O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  - -   ; t t t y p a a s a a a p p a a s s s s s a p p a p a s / .... .{ V u y u p p a s s a a a p a a a s s s s a a a p p a a a s s s a a a a p a a @   - 6               O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.  + 8   % e e r t y i p p p p p i p i p p p a p p p p p i p p p H } } { T m t t y y p p p p p p p p i p p p p p p p p p p i p p p a p p p p p i p i a o = 8 *             O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.    6                                                                                                                                                 3 8 =             O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.                        X X     X X   X     X X   X     X   X     X     X X   X     X   X X   X     X X   X     X X   X     X X   X     .   + 2 7 9 9 -               O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.                                                                                                                                                                    O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.                                                                                                                                                                  O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.                                                                                                                                                                O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.",
"O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O."
};
