/*
 * Embroidermodder 2.
 *
 * Copyright 2011-2024 The Embroidermodder Team
 * Embroidermodder 2 is Open Source Software, see LICENSE.md for licensing terms.
 *
 * Read the reference manual (https://www.libembroidery.org/downloads/emrm.pdf)
 * for advice on altering this file.
 */
/* XPM */
static char *heart_2[] = {
/* columns rows colors chars-per-pixel */
"128 128 124 2 ",
"   c #000000",
".  c #0C0101",
"X  c #0C0C0C",
"o  c #130000",
"O  c #1C0101",
"+  c #120C0C",
"@  c #1D0B0B",
"#  c #121212",
"$  c #191010",
"%  c #1B1B1B",
"&  c #230000",
"*  c #2A0000",
"=  c #260A0A",
"-  c #2D0C0C",
";  c #330000",
":  c #3C0000",
">  c #320F0F",
",  c #3B0C0C",
"<  c #2C1313",
"1  c #2A1A1A",
"2  c #371111",
"3  c #3F1313",
"4  c #351A1A",
"5  c #242424",
"6  c #2E2727",
"7  c #2C2C2C",
"8  c #312020",
"9  c #343434",
"0  c #3C3C3C",
"q  c #450000",
"w  c #4C0101",
"e  c #470909",
"r  c #4E0E0E",
"t  c #540202",
"y  c #5C0000",
"u  c #5B0B0B",
"i  c #411414",
"p  c #4E1010",
"a  c #421A1A",
"s  c #501414",
"d  c #5D1414",
"f  c #640000",
"g  c #6C0000",
"h  c #6C0C0C",
"j  c #740101",
"k  c #7D0000",
"l  c #740C0C",
"z  c #7C0C0C",
"x  c #641212",
"c  c #6E1515",
"v  c #6B1A1A",
"b  c #741515",
"n  c #7B1414",
"m  c #741A1A",
"M  c #7B1D1D",
"N  c #4B2626",
"B  c #4D2A2A",
"V  c #5B2323",
"C  c #522D2D",
"Z  c #413030",
"A  c #4C3535",
"S  c #4B3D3D",
"D  c #513636",
"F  c #553B3B",
"G  c #5C3B3B",
"H  c #6D2424",
"J  c #6C2A2A",
"K  c #752323",
"L  c #7B2323",
"P  c #742D2D",
"I  c #7B2C2C",
"U  c #6F3333",
"Y  c #7D3232",
"T  c #723A3A",
"R  c #454545",
"E  c #4C4C4C",
"W  c #554545",
"Q  c #5C4C4C",
"!  c #535353",
"~  c #5B5B5B",
"^  c #794242",
"/  c #645252",
"(  c #665A5A",
")  c #755757",
"_  c #646464",
"`  c #6C6C6C",
"'  c #737373",
"]  c #797272",
"[  c #7C7C7C",
"{  c #800000",
"}  c #810B0B",
"|  c #831515",
" . c #821C1C",
".. c #822525",
"X. c #822C2C",
"o. c #8B2B2B",
"O. c #843333",
"+. c #853C3C",
"@. c #893E3E",
"#. c #864444",
"$. c #8A4343",
"%. c #874C4C",
"&. c #8C4C4C",
"*. c #914E4E",
"=. c #8E5252",
"-. c #8F5A5A",
";. c #915454",
":. c #935C5C",
">. c #826B6B",
",. c #966363",
"<. c #9A6363",
"1. c #9B6C6C",
"2. c #947171",
"3. c #9D7272",
"4. c #A07575",
"5. c #A47C7C",
"6. c #A58181",
"7. c #A98585",
"8. c #A58B8B",
"9. c #AB8C8C",
"0. c #AE9292",
"q. c #B19696",
"w. c #B49898",
"e. c None",
/* pixels */
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.X X         e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.9 0 R ! ! ! ! E R 0 5 #       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.5 7 7 7 5 % #           e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.0 E _ ` ' ` ~ E 0 9 7 7 9 R R 0 7 X       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.R E ~ _ ' ' ` ` _ ~ ! R 9 %         e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.R ~ ` [ ` R X                       X 7 7 #       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.R ! _ ' [ _ R 5             # 5 9 9 9 #       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.! ' [ ` #             . .   . . o           X 6       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.! ` [ ` 0                               # 5 #       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.E _ 6.' %       @ = - H P P K c y f t * & o o       # %       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.! ` 6.` %         O o * * * O o . .               %         e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.E ` [ R       @ i U &.:.1.1.1.,.=.T I h f f y q * o       #       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e._ [ ' 5       @ - 3 J Y Y I K H v d e q : ; o .         X       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.E ' [ #     @ a ^ ,.5.7.8.8.5.5.3.,.:.;.#.Y K f f f w * o             e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.R ` [ ~       @ i U -.,.1.1.1.,.:.-.:.=.#.Y c y t q * o               e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.E ' '       < T <.5.9.0.9.7.1.:.;.#.@.@.$.#.$.$.O.b f y y q &             e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.R ` 6.7     = a ^ <.5.7.8.7.6.3.3.1.1.1.,.:.;.%.I c y y t * .             e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.R ' '     @ a &.5.0.0.0.5.:.#.I m l l j j z n ..o.O.X.M g f f t * o           e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.R ` [ X     < U <.5.0.0.9.5.1.:.&.#.+.@.+.O.+.$.+.@.+.L f f y q O             e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.9 _ [     > U <.7.q.0.3.:.+.M l j j j j j j j j j j z |  .M j g f y q O           e.e.e.e.e.e.e.e.e.e.e.e.e.0 ` [       3 +.1.9.w.9.4.:.$.I m l j g j j j j j l n X.L M h f f t ;             e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.! ' %   O H <.9.w.7.1.#.L b j j j j j j j j k k k k j z z |  .l g g f t *           e.e.e.e.e.e.e.e.e.e.e.0 ~ '       3 #.3.0.w.6.:.+.L l j j j j j k j j j j j j j z n n l g f y q .           e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.9 ` E     , *.7.0.5.;.O.m l j j k j k k k k k k { k k k k k z | | | j g g t *           e.e.e.e.e.e.e.e.e.e.! ' X     3 +.3.0.0.3.&.L b j j j j k j j k k k k k k k j k z | n l j f y : o         e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.% ! _     * I 3.9.5.&.L l k j j j k k { { { k { { { { { { { k { { } |  .z j f y O           e.e.e.e.e.e.e.e.R ' 7     3 #.3.9.9.1.@.M j j j j k k k { { k k k k { k k k k k { z | j j f y *           e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.9 ` #   O d =.5.5.&.K l j j j j k k { { { { { { { { { { { { { { k { } |  .z j g t o         e.e.e.e.e.e.e.9 _ E     i #.4.9.9.1.@.M l j j k k k k { { { { { { { { { k { { { k k { j j j f t O           e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.# ! !     ; O.3.5.:.X.l j j k k { { { { { { { { { { { { { { { { { { { { { } } j j f :           e.e.e.e.e.e.! `     < &.5.0.9.1.@.m l j k j k k k { { { { { { { { { { { { { { { z { { j j j f q o         e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.5 ~     O d ;.5.1.@.m j j { { k { { { { { { { { { { { { { { { { { { { { { k { z k j f *           e.e.e.e.~ ` #   = ^ 7.w.8.1.@.M l j j k { k { { { { { { { { { { { { { { { { { { { k { k j g y *           e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.  R E     ; Y 1.4.;.L z j j k { { { { { { { { { { { { { { { { { { { { { { { k { } { j g y O         e.e.e.` [ E     D 9.w.9.<.@.M l j j k k { { { { { { { { { { { { { { { { { { { { { { { k j j g q o         e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.# !     o t %.3.,.O.b j j k k k { { { { { { { { { { { { { { { { { { { { { { { { k } z j j q .   # # X e.e.[ _     1 6.w.7.:.+.M l j j k k { { { { { { { { { { { { { { { { { { { { { { { { { k j g f *           e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.7 E     ; L ,.1.&.M j j k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k j g *     E ! e._ _       ) w.6.=.Y n l j k k k { { { { { { { { { { { { { { { { { { { { { { { { { { k k j f q o         e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.  0 7   o t +.1.,.O.b j k k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { j j y o   # ( ~ E       A 9.5.&.L l g j j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { j g y O         e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.  E     O h #.1.&.m k j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k { { j j t .     5       $ 2.5.*.K h g j j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { j j f *           e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.# R     ; c -.<.+.z j k k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k j g ;           X / 7.<.Y h g j j k k { k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k j g w o         e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.  7 7   o t I :.;.L j j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k k j g &     X   6 9.3.#.m g j j j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { j g f O         e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.  9 X   o y Y :.$.n j j k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k { k k j u +     + ] 3.=.P h g j j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k j j f *         e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.  9     & f +.;.O.z j k k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k }  .o.4     Z ,.%.Y m g j j j { { k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k j f w o X       e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.  9     ; h &.;.X.j j k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { } | o.J + @ T Y K c h g j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k j g y o #       e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.  7   o t c &.*...j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { } n * , c h h h g j j j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k j g y O #       e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.X 5   o f c #.@.n j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k k k j y f g g g g g j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { j g y O # #     e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.  % %   O f c $.+.z j { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k k j j g g g j j j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k j g y O # %     e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.  % #   & f h @.O.j j k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k k j j j j j j j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { j g y o X %     e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.  % #   & y f O...j k k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k k j j j j j k k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { j g y O   %     e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.  5 X   O f g X...k k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k k j k k k k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k j g f *   %     e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.  % X   & f f O...j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k k k k k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k j g y *   %     e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.  #     & y f X...j k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k k k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { j g y *   %     e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.  X #   O f g M  .j k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { j g y O # #     e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.    %   O y f b  .j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k j g y O % X     e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.    %   o y f g M k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { j j f y O 7       e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.  5   o w y g n z k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { j j f t . 0       e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.  %     * y g z z k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k g f q @ R       e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.        O y g j z j { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k k j g y * 7 R       e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.    X   o t f j j k k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k j j f t O E %     e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.    X   o q y g j j k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k j g y q 1 ~       e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.        * y f j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { j j f t * 0 E       e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.        o q f g j { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k k j g y q 1 ~       e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.          * y g j j k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k k j f t - R E       e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.        o q f j j { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k j j g y q 4 _       e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.          * y f j j k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k { { j g f t 2 ! E       e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.        o q y g j j k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k k j j f y e A _       e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.        O t y g j k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k k j g f y e Z ` 5       e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.          * t f g j k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k j j f y t N ` !       e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.          * t f j j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { j j j f y e C ` _       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.          * t f g j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k k j j g f y t B ' '       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.          * t f g j j k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k { j j g f t e C ] `       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.            * t f g j j k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k j j j f y t p F [ `         e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.            O q y g j j j k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k { k j j g f y t B ( 6.~       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.        X   o * t f g j k { { k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k j j j f y t r D ' [ 9       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.      %     O q y g j j j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k { j j g f y t N W [ '         e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.      X #   o * t f g j j k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k j j g f y t p D ` 6.~         e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.        %     O q y g j j j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { j j g f y t N W [ [ #         e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.        X X   o * t f g j j j { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k j j g f f t p A _ 6.~         e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.        #     O q y g g j j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k k k j j h f y t N W [ [ %         e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.          #   o * q y g j j j { k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k k j j j f f y s A ` [ ~         e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.        %     o * t f g j j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k k k j g g f t t N Q [ [ %         e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.          %     O q f f g j j k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k { j j g f y t p F ' [ !         e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.        # #   . * w f g j j k k { { { { { { { { { { { { { { { { { { { { { { { { { { { { { { k k j j g f y r N Q [ ' X         e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.          %     o * y f j j k { { k { { { { { { { { { { { { { { { { { { { { { { { { { k { k j j f y u 6 W ' [ E         e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.          #     * t f g j j k { { { { { { { { { { { { { { { { { { { { { { { { { { k j j g f t t N ~ 6.`           e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.        X     O q f g j j k k { { { { { { { { { { { { { { { { { { { { { k k j k j g f t t B ' [ R         e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.              o * y f g j k k { { { { { { { { { { { { { { { { { { { { { k j j g y t p F [ ' X         e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.              * t f g j j k { { { { { { { { { { { { { { { { { k k k j g g y t N E [ _         e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.              O q y g j j k { { { { { { { { { { { { { { { { { k j j h t t N _ 6.R         e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.        X   o * y f j j k { { { { { { { { { { { { { { k k j j f t t B ` [ 5       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.        #     * y f g j { { { { { { { { { { { { k k k j j f t t B ' '         e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.      X     * t g j j k k { { { { { { { { { k k j g f y t B ' '         e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.            * y f j j k k { { { { { { { k k j j f y t C ' `       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.            * t f j j k k { { { { { { k j j f y e C ' _       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.            * t f j j k { { { { k { j g f y t C [ _       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.          * y f j j k { k { k j j f y e C [ _       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.          * t f j j { k k j j f y t C ' _       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.          * t g j j k k j g y t D [ _       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.          * y g j j j g f t C [ _       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.    X     * y g j g f t C ' `       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.    #     O t g f u G [ `       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.    %     ; y y V ] '       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.      7 9 @ e s ( _       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.      E ~ S A 9       e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.      9 0           e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.                e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.            e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.          e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.        e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.      e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.    e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.  e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.",
"e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e."
};
