/*
 * Embroidermodder 2.
 *
 * Copyright 2011-2024 The Embroidermodder Team
 * Embroidermodder 2 is Open Source Software, see LICENSE.md for licensing terms.
 *
 * Read the reference manual (https://www.libembroidery.org/downloads/emrm.pdf)
 * for advice on altering this file.
 */
/* XPM */
static char *list[] = {
/* columns rows colors chars-per-pixel */
"128 128 238 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c #1B1B1B",
"9  c gray11",
"0  c #1D1D1D",
"q  c #1E1E1E",
"w  c gray12",
"e  c #202020",
"r  c gray13",
"t  c #222222",
"y  c #232323",
"u  c gray14",
"i  c #252525",
"p  c gray15",
"a  c #272727",
"s  c #282828",
"d  c gray16",
"f  c #2A2A2A",
"g  c gray17",
"h  c #2C2C2C",
"j  c #2D2D2D",
"k  c gray18",
"l  c #2F2F2F",
"z  c gray19",
"x  c #323232",
"c  c gray20",
"v  c #343434",
"b  c #353535",
"n  c gray21",
"m  c #373737",
"M  c gray22",
"N  c #393939",
"B  c #3A3A3A",
"V  c gray23",
"C  c #3C3C3C",
"Z  c gray24",
"A  c #3E3E3E",
"S  c #3F3F3F",
"D  c gray25",
"F  c #414141",
"G  c gray26",
"H  c #434343",
"J  c #444444",
"K  c gray27",
"L  c #464646",
"P  c gray28",
"I  c #494949",
"U  c gray29",
"Y  c #4B4B4B",
"T  c #4C4C4C",
"R  c gray30",
"E  c #4E4E4E",
"W  c gray31",
"Q  c #505050",
"!  c #515151",
"~  c gray32",
"^  c #535353",
"/  c gray33",
"(  c #555555",
")  c #565656",
"_  c gray34",
"`  c #585858",
"'  c gray35",
"]  c #5A5A5A",
"[  c #5B5B5B",
"{  c gray36",
"}  c #5D5D5D",
"|  c gray37",
" . c #5F5F5F",
".. c gray38",
"X. c #626262",
"o. c gray39",
"O. c #646464",
"+. c #656565",
"@. c gray40",
"#. c #676767",
"$. c #686868",
"%. c DimGray",
"&. c #6A6A6A",
"*. c gray42",
"=. c #6C6C6C",
"-. c #6D6D6D",
";. c gray43",
":. c #6F6F6F",
">. c gray44",
",. c #717171",
"<. c #727272",
"1. c gray45",
"2. c #747474",
"3. c gray46",
"4. c #767676",
"5. c #777777",
"6. c gray47",
"7. c #797979",
"8. c gray48",
"9. c #7B7B7B",
"0. c #7C7C7C",
"q. c gray49",
"w. c #7E7E7E",
"e. c gray50",
"r. c #808080",
"t. c #818181",
"y. c gray51",
"u. c #838383",
"i. c #848484",
"p. c gray52",
"a. c #868686",
"s. c gray53",
"d. c #898989",
"f. c gray55",
"g. c #8E8E8E",
"h. c #909090",
"j. c gray57",
"k. c #929292",
"l. c #939393",
"z. c gray59",
"x. c #979797",
"c. c #989898",
"v. c #9A9A9A",
"b. c #9B9B9B",
"n. c gray61",
"m. c gray62",
"M. c #9F9F9F",
"N. c gray63",
"B. c #A2A2A2",
"V. c gray64",
"C. c #A5A5A5",
"Z. c gray65",
"A. c gray66",
"S. c #A9A9A9",
"D. c #AAAAAA",
"F. c #ACACAC",
"G. c gray68",
"H. c #AEAEAE",
"J. c #AFAFAF",
"K. c gray69",
"L. c #B1B1B1",
"P. c gray70",
"I. c #B4B4B4",
"U. c gray71",
"Y. c #B7B7B7",
"T. c gray72",
"R. c #B9B9B9",
"E. c gray73",
"W. c #BBBBBB",
"Q. c #BCBCBC",
"!. c gray74",
"~. c gray",
"^. c gray75",
"/. c #C0C0C0",
"(. c #C1C1C1",
"). c gray76",
"_. c #C3C3C3",
"`. c gray77",
"'. c #C5C5C5",
"]. c #C6C6C6",
"[. c gray78",
"{. c #C8C8C8",
"}. c gray79",
"|. c #CACACA",
" X c #CBCBCB",
".X c gray80",
"XX c #CDCDCD",
"oX c #CECECE",
"OX c gray81",
"+X c #D0D0D0",
"@X c gray82",
"#X c #D2D2D2",
"$X c LightGray",
"%X c gray83",
"&X c #D5D5D5",
"*X c gray84",
"=X c #D7D7D7",
"-X c #D8D8D8",
";X c gray85",
":X c #DADADA",
">X c gray86",
",X c gainsboro",
"<X c #DDDDDD",
"1X c gray87",
"2X c #DFDFDF",
"3X c gray88",
"4X c #E1E1E1",
"5X c #E2E2E2",
"6X c gray89",
"7X c #E4E4E4",
"8X c gray90",
"9X c #E6E6E6",
"0X c #E7E7E7",
"qX c gray91",
"wX c #E9E9E9",
"eX c #EAEAEA",
"rX c gray92",
"tX c #ECECEC",
"yX c gray93",
"uX c #EEEEEE",
"iX c #EFEFEF",
"pX c gray94",
"aX c #F1F1F1",
"sX c gray95",
"dX c #F3F3F3",
"fX c #F4F4F4",
"gX c gray96",
"hX c #F6F6F6",
"jX c gray97",
"kX c #F8F8F8",
"lX c #F9F9F9",
"zX c gray98",
"xX c #FBFBFB",
"cX c gray99",
"vX c #FDFDFD",
"bX c #FEFEFE",
"nX c white",
"mX c None",
/* pixels */
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX                                                                                                                                                                                      mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmX                                                                                                                                                                                              mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmX        D { ..( Q Q { #...( B 4               - r s z n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n B A D D A s             mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmX    q 2.:.4                   B #.<.' k                                                                                                                                                                     mXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmX      <.%.                                                                                                                                                                                              %         mXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmX    s e.      , q n ( { ..{ T n 8 , %           % #.9.2.2.9.2.9.2.9.9.2.2.9.9.2.9.2.2.9.2.9.9.2.9.2.2.9.2.9.9.2.2.9.9.2.9.2.2.9.9.2.9.2.2.9.9.2.9.2.2.9.9.2.9.2.2.9.9.2.9.2.2.9.9.2.2.9.2.9.2.' T n q q -             mXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmX    n e.    , k ..C.'.{.{.'.(.(.T.m.e.T 8           r L.^.^.(.(.(.(.(.(.(.(.(.(.'.(.(.(.(.(.(.'.(.(.(.(.(.(.(.'.(.'.(.(.(.(.'.'.(.(.(.(.'.'.(.(.(.(.'.'.(.(.(.(.'.'.(.(.(.(.'.'.(.(.(.(.(.(.(.'.(.(.T.m.r.T q             mXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmX  r e.    r ' C.{..X'.'.'.(.(.(.(.(.^.L.:.a           A T.T.^.^.(.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.(.'.'.'.'.'.(.'.'.'.'.'.(.'.'.'.'.'.(.'.'.'.'.'.(.'.'.'.'.'.'.'.'.'.'.'.'.'.(.L.<.a             mXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmX    r.    k p.{.+X{.'.(.'.'.'.{.{.{.{.{.'.^.<.s           2.T.^.'.'.{..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X{..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X{.(.<.s           mXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmX    #.%   r p.+X+X{.'.'.'.{.{..X*X*X*X;X*X*X+X'.2.s         4 U.(.{..X*X*X;X;X;X;X;X;X;X;X;X;X;X;X;X;X;X;X;X;X;X;X;X;X,X;X;X;X;X;X,X;X;X;X;X;X,X;X;X;X;X;X,X;X;X;X;X,X;X;X;X;X,X;X;X;X;X;X;X;X;X;X;X;X;X;X;X;X*X+X{.2.s           mXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmX    <.  , ' {..X{.'.'.{.{.+X*X,X,X6X7X7X7X6X6X,X.X9.q         :.(..X*X,X7X7XwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwX7XwXwXwXwXwX7XwXwXwXwXwX7XwX7XwX7XwXwXwXwXwX7XwXwXwXwXwXwXwXwXwXwXwXwXwX7X7X7X7X6X,X+X9.q           mXmXmXmXmXmXmXmXmX",
"mXmXmXmX    {     k A.+X.X'.'.{..X*X,X6XwXwXyXpXpXpXyXyXwX7X.X( ,       r '..X;X6XwXyXpXpXjXpXpXjXpXpXjXpXpXpXjXjXpXpXjXpXpXpXjXpXpXjXpXpXjXpXpXpXjXpXjXpXpXpXjXpXjXpXjXpXjXpXpXpXjXpXjXpXpXpXjXjXpXpXjXpXpXpXjXjXpXpXpXyXyXwX7X.XQ , 4       mXmXmXmXmXmXmXmXmX",
"mXmXmXmX    %.  , ' {.{.'.'.{..X;X6XwXyXpXjXlXlXlXlXlXlXjXyXwXz.r         B..X*X6XyXpXjXlXlXcXcXlXcXlXlXcXcXlXcXlXcXlXlXcXcXlXcXlXcXcXcXcXcXlXcXcXcXlXcXlXcXcXcXlXcXcXcXcXcXcXlXcXcXlXcXlXcXcXcXlXcXlXlXcXcXlXcXlXlXlXlXlXlXpXyXwXz.r 8       mXmXmXmXmXmXmXmXmX",
"mXmXmXmX  , a   r j..X{.'.'..X;X6XwXpXjXlXlXcXcXcXcXcXcXlXjXpX(.k   z     %..X*X6XyXjXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlXpX(.k r a       mXmXmXmXmXmXmXmX",
"mXmXmXmX  B     k H.{.'.'..X*X6XwXpXlXcXcXcXcXcXcXcXcXcXcXcXlXwX#.- B     A {.+X;XwXpXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlXlXwX#.U U       mXmXmXmXmXmXmXmX",
"mXmXmX    U   , { (.'.'.'.+X,X7XpXjXcXcXcXcXcXcXcXcXcXcXcXcXcXjXm., , T   8 '..X*X6XyXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlXb.%.T       mXmXmXmXmXmXmXmX",
"mXmXmX    U   , d.{.'.'..X*X6XyXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXT.a   <.    T Q ( ' { ....#.#.#.%.#.#.#...#.#...#.#...#.#...#.#.%.#.#.#.#.#...#.#.#...#.#.#...#.%.#.#.#.#.#...#.#.#.#...#.#...#.%.#.#.#...#.#...#.#...#.#...#.#.#.#.{ p.8       mXmXmXmXmXmXmXmX",
"mXmXmX    T   q m.{.'.'..X,X7XpXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcX(.r     4                                                                                                                                                       A <.9.{         mXmXmXmXmXmXmXmX",
"mXmXmX    Q   q m.'.'.{.*X6XwXjXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcX(.r               4 B L L D L D L L D L L L L D L L D L L L D L D L D L L L D L L L L D L L D L L T ' #...T q             4 k B D L L L L L L D L L D L L U ( ..( a             mXmXmXmXmXmXmXmX",
"mXmXmX    (   r b.{.'..X*X7XyXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcX(.a                                                                                                       L e.9.U O                                                             mXmXmXmXmXmXmXmX",
"mXmXmX    L     T '.'..X;X7XpXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcX^.r                                                                                                                                                                             mXmXmXmXmXmXmXmX",
"mXmXmX    %     - T.'.+X,XwXpXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXB.b.j.f.p.e.9.2.<.<.2.9.9.9.9.9.9.9.9.e.9.9.9.9.9.9.9.9.9.9.9.e.9.e.9.e.9.9.9.e.9.9.9.e.9.9.9.9.9.9.9.9.9.' %                                                                   mXmXmXmXmXmXmXmX",
"mXmXmXmX    D     <.{..X;XwXjXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXjXyX6X+X{.'.^.^.(.(.'.'.'.'.'.'.'.'.{.'.'.'.'.{.'.'.'.'.'.'.'.'.{.'.'.'.{.'.'.'.{.'.'.{.'.{.'.'.'.'.'.A.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmX    s     q ^..X;X7XpXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlXjXyX7X;X.X{.'.'.'.'.'.'.{.{.{.'.{.'.{.'.{.'.'.{.{.{.{.'.{.{.'.'.{.'.'.'.{.'.'.'.{.'.'.'.{.'.'.{.{.{.'.'.B           mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmX            r.{.*X6XyXjXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlXpXwX6X*X+X.X.X.X.X+X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.Xf.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmX    O     a '.+X6XwXjXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlXlXyXwX6X,X,X,X;X;X;X,X;X,X;X;X,X;X,X,X;X;X,X;X,X,X;X;X,X;X,X;X,X;X,X;X;X;X,X;X,X;X,X;X;X;X,X;X;X;X,X;X*X8           mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmX            ^..X;X7XpXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlXpXpXyXwXwXwXwXwXwXwXwXwXwXwXwX7XwXwXwXwXwX7XwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwX7X9.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmX          e.{.+X6XyXjXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlXlXjXjXjXjXpXpXpXpXpXjXpXpXjXpXjXpXpXpXjXpXjXpXpXpXjXpXpXpXpXpXpXjXpXpXjXpXpXpXpXjXpXpXjXjXpXpXjXpXpXpX;X%   4       mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmX          k '.+X,XwXpXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlXcXcXcXlXcXlXcXcXcXlXcXlXcXcXcXcXlXcXcXlXlXcXcXcXcXcXlXcXcXlXcXcXcXcXlXcXcXlXcXlXcXlXlXcXcXlXjX'           mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmX          m.{.*X7XyXjXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlX'.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmX          U '.+X6XyXjXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlXn   %       mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmX        O U..X;XwXpXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlXb.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmX    ,     #.{.*X6XyXjXcXcXcXcXcXcX(.n z z n z n n z n z n z n z n n n z n z n z n z n z n z z n z n z n z n z n n n n z n z n z n z n z n z .XcXcXcXcXcXcXcXcXcXcXpX4   4       mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmX          8 '..X,XwXpXlXcXcXcXcXcXU.    q -                                                                                                 ^.lXlXcXcXcXcXcXcXcXcXcX2.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmX    -     d..X*X7XyXjXcXcXcXcXcXU.    T <.Q z k z k z k z k z k k z k z k z z z k k z z z k z z k z k z k z k k k z k z k z z k           T.pXjXpXlXlXcXcXcXcXcXcX;XO   -     mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmX          n {.+X6XwXjXcXcXcXcXcXU.                                                                                                        H.7XwXyXjXjXcXcXcXcXcXcXlXQ           mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmX          C..X;XwXpXlXcXcXcXcXU.                                                                                                        C.;X,X7XyXjXlXcXcXcXcXcXcXT.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmX    -     ( {.*X6XyXjXcXcXcXcXpX{.{.(.T.L.A.C.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.C.B.B.B.B.(.+X*X,X7XpXlXcXcXcXcXcXcXlXs   -       mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmX        % ^..X,XwXpXlXcXcXcXcXcXjXyX7X,X+X.X{.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.{..X+X,X7XpXlXcXcXcXcXcXcXlXj.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmX    4     2.{.*X7XyXlXcXcXcXcXcXlXpX7X,X+X.X{.'.{.{.{.'.{.{.'.{.{.'.{.{.'.{.'.{.{.'.{.{.'.{.{.'.{.{.'.{.{.{.'.{.{.'.{.{.'.'.{.{.'.{.'.{..X+X,X7XpXlXcXcXcXcXcXcXlXyX-   4       mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmX          r {.+X,XyXjXlXcXcXcXcXlXpXwX6X;X*X+X+X+X+X+X+X+X+X+X+X+X+X+X.X+X+X+X+X+X+X+X+X.X+X+X+X+X+X+X.X+X+X+X+X.X+X+X+X+X+X+X+X+X+X+X+X*X;X6XwXpXlXcXcXcXcXcXcXcXlX%.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmX    %     j.{.;X7XpXlXcXcXcXcXcXjXpXwX7X6X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X6X7XyXpXjXlXcXcXcXcXcXcXcXlX*X    %     mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmX          A {.*X6XwXpXcXcXcXcXcXlXjXpXyXyXyXwXwXwXwXwXyXwXwXwXwXyXwXwXwXwXwXwXwXwXwXyXwXwXwXwXwXyXwXwXwXwXwXyXwXwXwXwXwXwXwXwXwXwXwXwXyXyXpXjXcXcXcXcXcXcXcXcXcXcXcXL           mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmX          L..X;XwXpXlXcXcXcXcXcXlXlXjXjXpXjXpXjXjXpXjXpXjXjXjXjXpXjXjXjXjXjXpXjXpXjXjXpXjXjXjXjXpXjXjXjXpXjXjXpXjXjXjXjXjXjXpXjXjXpXjXlXlXlXcXcXcXcXcXcXcXcXcXcXlXA.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmX    ,     { {.+X6XyXjXcXcXcXcXcXcXcXcXcXcXcXcXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlXcXcXcXcXcXcXcXcXcXcXcXlXcXcXcXcXcXcXcXcXcXcXcXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXjXq   ,       mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmX        , (.+X,XwXpXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlXp.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmX    4     e..X;X7XyXjXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcX7X%   ,       mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmX          s {.+X,XwXjXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcX{           mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmX          b.{.;X7XpXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcX{.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmX    %     U {.*X,XyXjXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlXn   %       mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX        O T..X;XwXpXlXcXcXcXcXcXcX(.n n z n z n n z n n n z z n n z n n z n n z n z n n z n n z n n z n n n z n n n z n n z n n z n n z n n .XcXcXcXcXcXcXcXcXcXlXB.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX    4     #..X*X6XyXlXcXcXcXcXcXcXU.    q -                                                                                                 ^.jXlXcXcXcXcXcXcXcXcXpX4   4       mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX          8 '.+X,XwXjXlXcXcXcXcXcXU.    T 2.Q z k z z k z k z k k z k z k z k z k z k z k z k z k k z k k z k z z k z k k z k z z           T.pXjXpXlXlXcXcXcXcXcXcX2.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX    -     p..X*X7XyXlXcXcXcXcXcXU.                                                                                                        H.7XwXyXpXlXcXcXcXcXcXcX,XO   -     mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX          z {.+X6XwXjXcXcXcXcXcXU.                                                                                                        C.;X,X7XyXjXlXcXcXcXcXcXlXQ           mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX          C..X;X7XpXlXcXcXcXcXpX.X'.(.T.L.A.C.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.(..X*X,XwXyXlXcXcXcXcXcXcXT.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX    -     Q {.*X6XyXjXcXcXcXcXcXlXjXpX7X;X+X{.{.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.{..X+X;X7XpXjXcXcXcXcXcXcXlXk   -       mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX        % ^..X;XwXpXcXcXcXcXcXcXlXpX7X,X+X.X{.{.{.{.'.{.{.{.'.{.{.{.'.{.{.{.'.{.{.{.'.{.{.{.'.{.{.{.{.{.'.{.{.{.{.{.{.{.'.{.{.'.{.'.{.{..X*X;X7XpXlXcXcXcXcXcXcXcXj.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX    4     <.{.*X7XyXlXcXcXcXcXcXlXpXwX6X;X*X+X.X+X+X.X+X+X+X.X.X+X+X.X+X+X+X.X.X+X+X.X+X+X+X.X.X+X+X+X+X.X.X+X+X+X+X.X+X.X+X+X+X+X+X+X+X*X;X6XyXpXlXcXcXcXcXcXcXcXyX-   4       mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX          q {.+X,XyXpXlXcXcXcXcXlXjXpXwX7X6X,X,X6X,X,X,X,X,X,X,X6X,X,X,X,X,X,X,X6X,X,X,X,X,X6X,X,X,X,X,X,X,X,X,X,X,X6X,X,X,X,X,X,X,X,X,X6X7XwXpXjXcXcXcXcXcXcXcXcXlX%.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX    %     f..X;X7XpXlXcXcXcXcXcXlXlXpXyXyXwXwXwXwXwXwXwXyXwXwXwXwXwXwXwXyXwXwXwXwXwXwXwXwXyXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXwXyXyXpXlXlXcXcXcXcXcXcXcXcXlX*X    %     mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX          A {.+X,XyXjXlXcXcXcXcXcXcXlXjXjXjXpXjXjXjXjXpXjXjXpXjXjXjXjXpXjXjXpXjXjXjXjXpXpXjXjXjXjXjXjXjXpXjXjXjXjXjXpXjXjXjXjXpXpXjXjXjXlXlXcXcXcXcXcXcXcXcXcXcXcXlXL           mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX        O H..X;X7XpXlXcXcXcXcXcXcXcXcXcXcXcXlXcXcXcXcXcXcXlXcXcXcXcXcXcXcXlXcXcXcXcXcXlXcXcXcXlXcXcXcXcXcXcXcXcXcXcXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlXH.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX    ,     ' .X*X6XyXjXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXjXr   ,       mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX        , (..X,XwXpXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXp.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX    4     9..X*X7XyXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXwX%   ,       mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX          a {.+X,XyXjXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlX..          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX          b..X;X7XpXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcX{.    O     mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX    %     L {.+X6XyXjXcXcXcXcXcXcXcX'.n z z n n z z n z n n n z n z n z n n z n z n n z n n z n z z n z n n n z n n z n z z n z n n n z n n z .XcXcXcXcXcXcXcXcXcXlXB   %       mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX        O U.+X;XwXpXlXcXcXcXcXcXcXU.    q %                                                                                                 ^.lXlXcXcXcXcXcXcXcXlXB.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX    ,     #.{.*X6XyXjXlXcXcXcXcXcXU.    T <.Q z z k z k k z k k k z z k k z k z k z k k z k k z z k z k k z k k z k k z z k z k k           U.pXjXpXlXlXcXcXcXcXlXpX8   4       mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX          4 '.+X,XwXjXcXcXcXcXcXcXU.                                                                                                        H.7XwXyXjXjXcXcXcXcXcXlX2.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX    ,     p..X*X7XpXlXcXcXcXcXcXU.                                                                                                        C.;X,X7XwXjXcXcXcXcXcXcX6XO   ,     mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX          k {.+X,XwXjXcXcXcXcXcXpX{.'.(.T.L.H.C.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.(.+X*X,XwXpXlXcXcXcXcXcXlX(           mXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX          C..X;X7XpXlXcXcXcXcXcXcXjXpX7X;X+X.X{.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.{..X+X;X7XpXjXcXcXcXcXcXcXT.          mXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX    -     Q {.*X6XyXjXcXcXcXcXcXcXlXpX7X;X*X.X{.{.{.{.{.'.{.{.{.'.{.{.{.'.{.{.'.{.{.'.{.{.'.{.'.{.{.{.'.{.{.'.{.{.'.{.'.{.{.{.'.{.{.{.'.{..X*X,X7XpXjXcXcXcXcXcXcXjXk   -       mXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX        % T.+X;XwXpXlXcXcXcXcXcXlXpXwX6X*X*X+X.X+X+X+X+X.X.X+X+X+X+X+X+X+X+X.X.X+X+X+X+X+X+X+X+X+X+X+X.X+X+X+X+X+X+X+X+X.X+X+X+X+X+X+X+X+X;X6XwXpXlXcXcXcXcXcXcXcXz.          mXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX    4     <..X*X6XyXjXcXcXcXcXcXcXjXpXwX7X6X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X6X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X6X6XwXpXjXcXcXcXcXcXcXcXcXyX-   4       mXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX          8 {.+X,XwXjXlXcXcXcXcXcXlXjXpXyXyXwXwXwXyXwXwXwXyXwXyXwXwXwXwXwXwXyXwXwXwXwXyXwXwXwXwXwXyXwXwXwXyXwXwXwXwXwXyXwXwXwXwXwXyXwXwXyXpXpXjXlXcXcXcXcXcXcXcXcXlX:.          mXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX    %     f..X;X7XpXjXlXcXcXcXcXcXlXlXjXjXpXjXjXpXjXjXjXjXpXjXpXjXjXjXpXpXjXjXpXjXjXpXjXpXjXjXpXjXjXjXjXpXjXpXjXjXpXjXjXpXjXjXpXjXjXjXjXjXlXlXcXcXcXcXcXcXcXcXcXcX+XO   -     mXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX          B {.+X,XyXjXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXL           mXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX          H.+X,X7XpXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXL.          mXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX    ,     { {.*X6XyXjXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlXr   ,       mXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX        - (..X;XwXpXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlXd.          mXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX    4     9..X*X7XpXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXwX%   8       mXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX    %     a {.+X,XwXjXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlX..          mXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX    q     z..X;X7XyXlXcXcXcXcXcXcXcX'.n z n n z n n z n n z n n z n n z n n n z n n n z n n n z n n n z n n n z n n n z n n n z n n n z n n z +XcXcXcXcXcXcXcXcXcX{.    ,     mXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX    #.    L {.+X6XwXjXcXcXcXcXcXcXcXU.    q %                                                                                                 ^.lXlXcXcXcXcXcXcXcXlXA   q       mXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX  e.    O U..X,XwXpXlXcXcXcXcXcXcXU.    T 2.Q z z z k z k z k z k z k z k z k z z k z k z k z k k z k z k z k z z k z k z k z k k           U.pXpXjXlXlXcXcXcXcXcX9.          mXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXr e.      #.{.*X6XyXjXcXcXcXcXcXcXU.                                                                                                        H.wXwXyXpXlXcXcXcXcXcX7X%   q       mXmXmXmXmXmXmXmX",
"mXmXmXmX                                                        T e.      O '.+X,XwXpXlXcXcXcXcXcXU.                                                                                                        B.;X,X7XwXjXlXcXcXcXcXlXT   8       mXmXmXmXmXmXmXmX",
"mXmXmX                                                    a ( %.9.<.      4 '.{.*X7XpXlXcXcXcXcXcXpX.X'.(.T.L.A.C.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.C.B.B.B.B.B.B.B.B.B.B.B.B.B.B.B.C.B.B.B.B.B.C.(..X*X,XwXpXlXcXcXcXcXcXT.r         mXmXmXmXmXmXmXmX",
"mXmXmX      , O     % a n D D L L D L D L L L D L L L Q %.2.:.( L z         (.'.+X6XyXjXlXcXcXcXcXcXlXjXpX7X;X+X.X{.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.{.{.+X;X7XpXlXcXcXcXcXcX^.r         mXmXmXmXmXmXmXmX",
"mXmXmX    8 e.L                                                             U.'..X;XwXpXcXcXcXcXcXcXcXlXpX7X,X*X.X{.'.{.{.'.{.{.{.'.{.{.{.{.'.{.'.{.'.{.{.'.{.'.{.'.{.{.{.{.'.{.'.{.'.{.{.'.{.'.'.{.{.{.'.{.{..X*X;X7XpXlXcXcXcXcXcX(.r O       mXmXmXmXmXmXmXmX",
"mXmXmX      T                                                               U.^.{.*X7XpXlXcXcXcXcXcXcXlXpXwX6X;X*X+X+X.X+X.X+X+X+X+X.X+X+X+X+X+X+X+X+X+X.X+X+X.X+X+X.X+X+X+X+X+X+X+X+X+X.X+X+X.X+X+X+X+X+X+X+X*X;X6XyXpXlXcXcXcXcXcX'.r r       mXmXmXmXmXmXmXmX",
"mXmXmX        % Q e.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.{ ,         T.^.{.*X7XyXlXcXcXcXcXcXcXlXjXyXwX6X6X,X,X6X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X6X,X,X,X,X,X,X,X,X,X,X,X,X,X,X,X6X,X,X,X,X,X,X,X,X,X,X6X7XwXpXjXlXcXcXcXcXcX^.a D       mXmXmXmXmXmXmXmX",
"mXmXmX        , { (.'.(.(.'.'.'.{.'.{.'.'.'.'.{.'.'.'.{.'.'.'.'.e.-       8 T.^.{.+X6XyXlXcXcXcXcXcXcXcXlXlXpXyXyXyXwXwXwXwXwXwXyXwXwXwXwXwXyXwXwXwXwXwXwXyXwXwXyXwXwXwXwXwXyXwXwXwXwXwXwXyXwXwXwXwXwXwXwXwXwXwXyXpXjXlXcXcXcXcXcXcXB., {       mXmXmXmXmXmXmXmX",
"mXmXmXmX        s B.^.^.(.(.'.'.'.'.{.{.{.{.{.{.{.'.{.{.{.{.'.^.( ,       B T.^.'.+X,XyXlXcXcXcXcXcXcXcXcXcXlXjXjXpXjXjXjXjXjXpXpXjXjXjXjXpXpXjXjXjXjXpXpXjXjXjXpXjXjXjXjXpXpXjXjXjXjXpXpXjXjXjXjXjXpXjXjXjXjXjXlXlXlXcXcXcXcXcXcXpX<., ..      mXmXmXmXmXmXmXmX",
"mXmXmXmX        q r.T.^.(.'.{.{..X.X.X.X.X.X.X.X.X.X+X.X.X.X.XA.s         #.T.^.{.+X6XyXjXcXcXcXcXcXcXcXcXcXcXcXcXcXlXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXlXcXcXcXcXcXcXcXcXcXcXcXcXcX*Xz 4 z       mXmXmXmXmXmXmXmX",
"mXmXmXmX        - T L.^.'.{.+X*X;X,X,X;X;X,X;X,X;X;X;X;X;X;X;Xj.q (       m.^.^.'.*X6XyXjXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXA.a %.      mXmXmXmXmXmXmXmXmX",
"mXmXmXmX          a j.(.{.+X;X6X7XwXwXwX7XwXwXwXwX7XwX7XwX7X*X{ , #.    r '.(.(.{.*X6XyXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXwX.., :.      mXmXmXmXmXmXmXmXmX",
"mXmXmXmXmX        - U U.{.;X6XwXyXpXpXpXjXpXpXpXpXjXpXjXpXwXf.r <.      9.'.(.'..X;X7XpXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXjXz.a 2.        mXmXmXmXmXmXmXmXmX",
"mXmXmXmXmX          q <.'.*X6XyXpXlXlXcXcXcXcXcXcXlXcXlXpXf.z r e.    8 '.'.(.'..X,XwXpXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXjXj.n D '       mXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmX          a 2.'.,XyXjXcXcXcXcXcXcXcXcXcXcXpXj.n   <.      f..X'.'.{.*X,XyXjXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXjXj.n r e.      mXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmX          q Q C.;XpXjXlXcXcXcXcXcXcXcXwXj.n   n ..    U *X{.'.'..X*X6XyXjXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXwXz.z a r.        mXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmX            - k ..L.7XjXcXcXcXcXjX+XH...a   , :.8   a .X.X'.'.'.+X,XwXpXlXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXcXpX+XA.#.r L e.        mXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmX        ,     , 8 n { <.2.<...D r 4 %   q :...  - <.e.2.2.2.e.r.d.f.j.b.b.z.z.b.b.b.b.z.b.b.b.z.b.b.b.z.b.b.b.z.z.b.b.b.b.z.z.b.b.b.b.b.z.b.b.b.b.z.b.b.b.b.b.b.b.z.b.b.b.z.z.b.b.b.b.z.b.<.2.2.#.D a a , <.(         mXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmX          r                     % U 9.e.%.,                                                                                                                                                       , ' {           mXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmX            - z A A L ( %.2.9.:.D                     , r s s k k s k s k s s k k s k k s k k k s s s k s k k s s k k s k k k s k s s k k s s k k s k k s k s k s k s k s k k z z B A L U T Q D               mXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmX                                                                                                                                                                                                      mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmX                                                                                                                                                                                                mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX                                                                                                                                                                                      mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX",
"mXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmXmX"
};
