/*
 * Embroidermodder 2.
 *
 * Copyright 2011-2024 The Embroidermodder Team
 * Embroidermodder 2 is Open Source Software, see LICENSE.md for licensing terms.
 *
 * Read the reference manual (https://www.libembroidery.org/downloads/emrm.pdf)
 * for advice on altering this file.
 */
/* XPM */
static char *locator_snaptonearest[] = {
/* columns rows colors chars-per-pixel */
"128 128 203 2 ",
"   c #747500",
".  c #747600",
"X  c #757700",
"o  c #767700",
"O  c #777900",
"+  c #787900",
"@  c #787A00",
"#  c #7A7B00",
"$  c #7C7D00",
"%  c #808100",
"&  c #808200",
"*  c #818300",
"=  c #848500",
"-  c #868700",
";  c #868800",
":  c #878800",
">  c #878900",
",  c #888A00",
"<  c #898A00",
"1  c #898B00",
"2  c #8A8B00",
"3  c #8B8B00",
"4  c #8A8C00",
"5  c #8B8D00",
"6  c #8C8D00",
"7  c #8D8E00",
"8  c #8E8F00",
"9  c #8E9000",
"0  c #8F9000",
"q  c #8F9100",
"w  c #909100",
"e  c #919200",
"r  c #919300",
"t  c #929300",
"y  c #929400",
"u  c #939400",
"i  c #939500",
"p  c #949500",
"a  c #949600",
"s  c #959700",
"d  c #969700",
"f  c #969800",
"g  c #979800",
"h  c #979900",
"j  c #989A00",
"k  c #999A00",
"l  c #999B00",
"z  c #9A9B00",
"x  c #9A9C00",
"c  c #9B9C00",
"v  c #9B9D00",
"b  c #9C9E00",
"n  c #9D9E00",
"m  c #9D9F00",
"M  c #9E9F00",
"N  c #9EA000",
"B  c #9FA000",
"V  c #9FA100",
"C  c #A0A100",
"Z  c #A0A200",
"A  c #A1A200",
"S  c #A1A300",
"D  c #A2A400",
"F  c #A3A400",
"G  c #A4A500",
"H  c #A4A600",
"J  c #A5A700",
"K  c #A6A800",
"L  c #A7A800",
"P  c #A7A900",
"I  c #A8AA00",
"U  c #A9AB00",
"Y  c #AAAB00",
"T  c #AAAC00",
"R  c #ABAC00",
"E  c #ABAD00",
"W  c #ACAE00",
"Q  c #ADAE00",
"!  c #ADAF00",
"~  c #AEB000",
"^  c #AFB100",
"/  c #B0B100",
"(  c #B0B200",
")  c #B1B200",
"_  c #B1B300",
"`  c #B2B400",
"'  c #B3B500",
"]  c #B4B500",
"[  c #B4B600",
"{  c #B5B700",
"}  c #B6B800",
"|  c #B7B800",
" . c #B7B900",
".. c #B8BA00",
"X. c #B9BB00",
"o. c #BABC00",
"O. c #BBBD00",
"+. c #BCBE00",
"@. c #BDBF00",
"#. c #B4B52F",
"$. c #BEC000",
"%. c #BFC100",
"&. c #C0C200",
"*. c #C1C300",
"=. c #C2C400",
"-. c #C2C401",
";. c #C2C402",
":. c #C3C503",
">. c #C3C504",
",. c #C3C505",
"<. c #C3C506",
"1. c #C4C607",
"2. c #C4C608",
"3. c #C4C609",
"4. c #C5C70B",
"5. c #C5C70C",
"6. c #C5C70D",
"7. c #C6C70F",
"8. c #C6C810",
"9. c #C6C811",
"0. c #C6C812",
"q. c #C7C813",
"w. c #C7C914",
"e. c #C7C915",
"r. c #C7C916",
"t. c #C8C917",
"y. c #C8CA18",
"u. c #C8CA19",
"i. c #C8CA1A",
"p. c #C8CA1B",
"a. c #C9CA1C",
"s. c #C9CB1D",
"d. c #C9CB1E",
"f. c #C9CB1F",
"g. c #CACB20",
"h. c #CBCC24",
"j. c #CBCD25",
"k. c #CBCD27",
"l. c #CCCD28",
"z. c #CCCD29",
"x. c #CCCE2A",
"c. c #CCCE2B",
"v. c #CDCE2C",
"b. c #CDCE2D",
"n. c #CDCF2E",
"m. c #CDCF2F",
"M. c #CDCF30",
"N. c #CECF31",
"B. c #CED033",
"V. c #CED034",
"C. c #CFD035",
"Z. c #CFD036",
"A. c #CFD137",
"S. c #D0D139",
"D. c #D0D13A",
"F. c #D0D23B",
"G. c #D0D23C",
"H. c #D1D23D",
"J. c #D1D23E",
"K. c #D1D33F",
"L. c #D1D340",
"P. c #D2D443",
"I. c #D2D444",
"U. c #D3D445",
"Y. c #D3D446",
"T. c #D3D447",
"R. c #D3D548",
"E. c #D4D54A",
"W. c #D4D54B",
"Q. c #D4D64C",
"!. c #D5D64E",
"~. c #D5D64F",
"^. c #D5D750",
"/. c #D6D752",
"(. c #D6D753",
"). c #D6D754",
"_. c #D7D857",
"`. c #D7D959",
"'. c #D8D95A",
"]. c #D8D95B",
"[. c #D8DA5E",
"{. c #D9DA60",
"}. c #D9DA61",
"|. c #D9DB62",
" X c #DADB64",
".X c #DADB65",
"XX c #DADC66",
"oX c #DBDC67",
"OX c #DBDC68",
"+X c #DBDC69",
"@X c #DBDD6A",
"#X c #DCDD6C",
"$X c #DCDD6D",
"%X c #DCDD6E",
"&X c #DDDE6F",
"*X c #DDDE72",
"=X c #DEE077",
"-X c #DFE078",
";X c #DFE079",
":X c #DFE07B",
">X c #E0E17E",
",X c #E0E17F",
"<X c None",
/* pixels */
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X@.o.| ' _ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ W W T P <X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<Xo.@.@.@.o...................................................................................................................................X.| X.X.o.| X.| | o.| X.| o.X.| X.X.| o.| X.X.| X.X.| o.| X.X.| | | ' W P V <X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X| @.*.=.*.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.] ^ D f <X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X' @.=.+X|.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.=.| ^ V t <X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X_ o.*.|.#XA.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.S.S.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.%.| T V q <X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X^ ..%.n.A.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.%.| T c 6 <X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X^ | %.k.A.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.%.' P f 4 <X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X^ | @.9.n.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.%.' D d 1 <X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<XW ] o.*.d.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.%.*.o.T V t 1 <X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<XT ^ | @.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.*.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.%.%.%.] D f 4 ; <X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<XI I _ | %.*.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.*.*.*.%.*.%.%.%.%.%.%.%.%.%.%.%.%.%.%.*.%.%.%.%.%.%.%.*.%.%.%.%.%.%.%.%.%.%.%.*.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.=.%.%.*.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.%.=.$.] T c q - <X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<XP I ^ | %.*.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.*.%.%.@.o...| | ] ] ] ] | ] ] ] ] ] | ] ] ] ' ] ] ] | ] ] ] ' ] ] ] ] ] ] ] ' | ] ] ' ] ] ] ] ] ] ] ' ' ] ] | | | o.%.%.%.*.=.=.=.=.=.=.=.=.=.=.=.=.=.=.%.%.$.| T m q ;   <X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<Xm D P ^ | %.*.=.=.=.=.=.=.=.=.=.=.=.=.=.=.*.%.@...] _ W I I P P P P P P P P P P P J I P P P P P P I L J P P P P P P P P P J I P P P P P P P P P P P P P T ^ ' | @.*.=.>.2.=.=.=.=.=.=.=.=.=.=.=.=.%.$.| T V t ;   <X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<Xf C P ^ | %.*.=.=.=.=.=.=.=.=.=.=.=.=.*.*.@...] W P C m c c j j f j j j f c f f j j j j f c f f j j j j j j j j j j j f j j j j j j j j j j c f j c c D P ^ | @.%.=.q.6.>.=.=.=.=.=.=.=.=.=.=.%.$.| ~ V t ; . <X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<Xq C P ^ X.%.%.=.=.=.=.=.=.=.=.=.=.=.*.%.o.| W P V j d t q 6 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 6 t r c D T ] o.*.6.d.q.>.=.=.=.=.=.=.=.=.%.%.$.| T V r 1   <X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X6 C P ^ | %.%.=.=.=.=.=.=.=.=.=.=.*.%.o.] j <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<Xr *.M.M.d.>.=.=.=.=.=.=.=.=.%.%.| T V q 4   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V P ^ | %.=.=.=.=.=.=.=.=.=.=.*.*.o.| W r <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<Xf =.H.`.U.g.3.=.=.=.=.=.=.=.%.%.| W V r ,   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X, V P ^ | %.=.=.=.=.=.=.=.=.=.=.%.%..._ I t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<Xj *.s.|..XU.d.>.=.=.=.=.=.=.%.%.| T V q , X <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V P ^ | %.=.=.=.=.=.=.=.=.=.*.%.o.] W J q <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<XC %.=.!.:X+XD.w.>.=.=.=.=.%.=.$.| W V r 1   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J ^ | %.*.=.=.=.=.=.=.=.=.*.*...' I D t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<XJ o.%.g.:X,X`.n.6.>.=.=.=.%.=.$.| T m r ;   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V P ^ ..%.*.=.=.=.=.=.=.=.=.*.%..._ I C 6 <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<XT ..%.=..X,X$XH.u.4.=.=.=.=.%.$.{ ~ V t 1   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V P ^ | @.*.=.=.=.=.=.=.=.*.*.*..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X_ ..@.*..X:X#XH.u.>.=.=.=.%.%.$.{ T N t ; . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J _ ..@.*.=.=.=.=.=.=.=.=.*.*..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X] ..@.=.XX,X$XG.i.3.=.=.=.%.%.$.{ ~ N q 1 . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J ^ ..@.*.=.=.=.=.=.=.=.=.*.%..._ I C u <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XG.i.3.=.=.=.=.%.$.{ T N q ,   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 C J _ ..@.*.=.=.=.=.=.=.=.=.*.*..._ J C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XG.i.>.=.=.=.=.%.$.{ ~ V r , X <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 C J ^ ..%.*.*.=.=.=.=.=.*.*.*.*..._ L C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XG.i.3.=.=.=.=.%.%.| ~ N q , . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J _ | %.*.=.=.=.=.=.=.=.=.*.$..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XH.i.2.=.=.=.=.%.o.| T V t 4 . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J ^ ..@.*.=.=.=.=.=.=.=.*.*.*..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X:X$XH.p.1.=.=.=.=.%.%.| T V t ; . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 C J _ ..%.*.=.=.=.=.=.=.=.=.*.*..._ I C d <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X| @.=..X,X$XH.u.2.=.=.=.=.%.%.| T V r 1 . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J ^ ..@.*.=.=.=.=.=.=.=.*.*.*..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<Xo.%.=..X,X#XH.u.2.=.=.=.=.*.o.| ^ V r ;   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 C J ^ ..%.*.=.=.=.=.=.=.=.=.*.*..._ L C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..o.=..X,X#XH.p.1.=.=.=.=.%.o.| ~ V r 4   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J ^ ..@.*.=.=.=.=.=.=.=.=.*.$..._ L C u <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X| %.=..X,X#XD.p.1.=.=.=.=.%.%.| T N r ; . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 C P _ | %.*.=.=.=.=.=.=.=.=.*.*..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X| %.=..X,X#XH.p.1.=.=.=.=.%.%.| T V r , . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J _ ..@.*.=.=.=.=.=.=.=.*.*.*..._ L C u <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X$XH.p.1.=.=.=.*.*.o.| ^ V q , X <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J _ | @.*.=.=.=.=.=.=.=.=.*.*..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..%.=.XX:X$XH.u.2.=.=.=.*.*.@.| W V r 1   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J _ ..@.*.=.=.=.=.=.=.=.=.*.*..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X| @.=..X,X$XH.u.2.=.=.=.*.%.@.| T m t ; . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 B J / ..$.*.=.=.=.=.=.=.*.=.*.*..._ P C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X..%.*.XX:X$XH.u.2.=.=.=.=.%.%.| T V t 1   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 C J / ..$.*.=.=.=.=.=.*.*.*.*.*..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X..@.=.XX,X$XH.u.2.=.=.=.%.%.%.| T V t ; . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J ^ ..@.*.=.=.=.=.=.=.=.=.*.*..._ P C r <X<X<X<X<X<X<X<X<X<X..@.=..X,X#XH.p.1.=.=.=.=.%.o.| ~ V r 4 . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 C J _ ..@.*.=.=.=.=.=.=.=.=.*.*..._ P C r <X<X<X<X<X<X<X<X..@.=..X,X#XD.p.1.=.=.=.=.%.%.| T N r ; . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 m L W ..*.*.*.=.=.=.=.=.=.=.*.@.o._ P C f <X<X<X<X<X<X..@.=.XX,X#XH.p.1.=.=.=.=.%.%.| T V r , . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V I _ ..@.*.*.=.=.=.=.=.=.*.*.%.| ' T P c <X<X<X' o.@.=.XX,X#XH.p.1.=.=.*.*.*.o.| ^ V q , X <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J ^ ..@.*.=.=.=.=.=.=.=.=.*.%.o.' ^ W J <XT @.%.>.+X,X#XH.u.2.=.=.=.*.*.@.| W V r 1   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J _ ..@.*.=.=.=.=.=.=.=.=.=.%.o.| | | ] @.*.M.*X,X#XD.p.2.=.=.=.*.*.%.] T m t ; . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 C J ^ ..*.*.=.=.=.=.=.=.=.=.=.%.%.%.%.*.p.).:X,X+XH.p.1.=.=.=.*.%.%.] W V t 1   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 C J _ ..@.*.=.=.=.=.=.=.=.=.=.=.2.u.N.'.#X#X].D.p.1.=.=.=.=.%.@.| W V t ; . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J _ ..*.*.=.=.=.=.=.=.=.1.6.d.l.G.R.R.S.c.u.2.=.=.=.*.%.$.| T V q 1 . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J W ..@.*.*.=.=.=.=.=.*.4.6.w.u.u.w.q.6.>.=.=.=.=.%.%.| T V r ,   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 C I _ ..@.*.=.=.=.=.=.=.=.>.=.=.>.*.=.=.*.=.=.=.%.o.| T V r , . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 C J W ..*.*.*.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.%.%.| ^ V q 4   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 C T ] @.*.1.4.*.=.=.=.=.=.=.=.=.=.=.=.=.*.%..._ J r 4   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<Xq I _ o.*.q.t.1.=.=.=.=.=.=.=.=.=.=.=.=.*.@.| T c q O <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<Xd _ ..=.g.d.1.=.=.=.=.=.=.=.=.=.=.=.=.*.o.' P j $ <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<Xm @.=.Z.l.4.=.=.=.=.=.=.=.=.=.=.=.=.*.o.' J ; <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<XP *.l.^.B.6.=.=.=.=.=.=.=.=.=.=.=.=.%.@.' I 1 <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X_ @.=.'.|.A.6.=.=.=.=.=.=.=.=.=.=.=.=.=.@...W C - <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X| o.%.L.:X|.c.2.=.=.=.=.=.=.=.=.=.=.=.=.=.%.o.] I C 4 <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.p.*X:X^.g.>.=.=.=.=.=.=.=.=.=.=.=.=.=.*.*...' P C 6 <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=.$X:X+XA.q.>.=.=.=.=.=.=.=.=.=.=.=.=.=.=.*.@..._ P C q <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X:X$XH.u.2.*.=.=.=.=.=.=.=.=.=.=.=.=.=.=.*.*.*..._ P C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X$XH.u.2.=.=.=.=.*.*.*.=.*.=.=.=.=.=.=.=.*.=.*.*..._ P C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XH.u.2.=.=.=.*.*.%.%.%.%.%.%.*.=.=.=.=.=.=.=.*.*.*..._ P C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XH.p.1.=.=.=.=.%.%.o.| | | | @.*.*.=.=.=.=.=.=.=.=.*.*..._ L C u <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XD.p.1.=.=.=.%.%.%.| ' ^ T T ^ ] ..@.*.=.=.=.=.=.=.=.=.*.*..._ I C u <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XH.p.1.=.=.=.=.%.%.| ^ J V m f C I _ ..%.*.=.=.=.=.=.=.=.=.*.$..._ I C u <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XH.p.1.=.=.*.*.*.%.| T C f r & <X  C J _ ..@.*.=.=.=.=.=.=.=.*.*.$..._ L C u <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=.XX:X$XH.u.2.=.=.=.*.%.@.| W V r 4 # <X<X<X# C P ^ ..@.*.=.=.=.=.=.=.=.=.*.*..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X$XH.u.2.=.=.=.*.*.@.| T m r 1 O <X<X<X<X<X$ V J _ ..@.*.=.=.=.=.=.=.=.=.*.*..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=.XX,X#XH.u.2.=.=.=.%.%.%.| T V t 1   <X<X<X<X<X<X<X% m J / ..$.*.=.=.=.=.=.=.=.=.*.*..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=.XX,X#XH.p.2.=.=.=.=.%.%.| T V t ; . <X<X<X<X<X<X<X<X<X- C J _ ..$.*.=.=.=.=.=.*.*.*.*.*..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XH.p.1.=.=.=.=.%.o.| ~ V r 4 . <X<X<X<X<X<X<X<X<X<X<X; C P ^ ..@.*.*.=.=.=.=.=.=.=.*.*..._ L C u <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XD.p.1.=.=.=.=.%.%.| T N r ; . <X<X<X<X<X<X<X<X<X<X<X<X<X1 V J _ ..%.*.=.=.=.=.=.=.=.=.*.*..._ I C u <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=.XX,X#XH.p.1.=.=.=.=.%.%.| T V r , . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J ^ | %.*.=.=.=.=.=.=.=.=.*.@..._ I C u <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XH.p.1.=.=.*.*.*.o.| ^ V q , X <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 C J _ ..@.*.=.=.=.=.=.=.=.*.*.$..._ L C u <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XH.u.2.=.=.=.*.*.@.| W V r 1   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J ^ ..@.*.=.=.=.=.=.=.=.=.*.*..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XD.p.2.=.=.=.*.*.%.] T m t ; . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J _ ..@.*.=.=.=.=.=.=.=.=.*.*..._ I C u <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XH.p.1.=.=.=.*.%.%.] W V t 1   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 C J ^ ..%.*.=.=.=.=.=.=.=.=.*.*..._ J C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XH.p.1.=.=.=.=.%.@.| W V t ; . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 C J _ ..@.*.=.=.=.=.=.*.*.*.*.*..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=.XX,X#XG.i.2.=.=.=.*.%.$.| T V q 1 . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J _ | @.*.=.=.=.=.=.=.=.=.*.*..._ I C u <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XG.i.2.=.=.=.=.%.%.| T V r ,   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J _ ..%.*.=.=.=.=.=.=.=.=.*.%..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=.XX,X#XG.i.2.=.=.=.%.%.%.| T V q , X <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V P ^ ..@.*.=.=.=.=.=.=.=.=.*.*..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XG.i.2.=.=.=.%.%.%.] T V r 4   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 C J ^ ..%.*.*.=.=.=.=.=.*.*.*.*..._ L C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=.XX,X#XD.i.2.=.=.=.%.=.$.| T V r ;   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J _ | %.*.=.=.=.=.=.=.=.=.*.$..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XH.p.1.=.=.=.%.%.$.| ^ V r ;   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J ^ ..@.*.=.=.=.=.=.=.=.*.*.*..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XH.u.4.=.=.=.=.%.$.| T V q 4 . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 C J _ ..%.*.=.=.=.=.=.=.=.=.*.*..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XH.p.>.=.=.=.=.=.$.| ^ V r ;   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V J ^ ..@.*.=.=.=.=.=.=.=.*.*.*..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XH.p.1.=.=.=.*.%.%.| T V r 1   <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 V P ^ X.%.=.=.=.=.=.=.=.=.=.*.*..._ L B u <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XD.p.1.=.=.=.*.%.%.] T V r ; . <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X1 C P ^ | %.%.=.=.=.=.=.=.=.=.*.$..._ L B u <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=.XX,X#XH.p.1.=.=.=.=.=.%..._ J d 6 # <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X6 J T ' o.%.=.>.>.=.=.=.=.=.=.*.*.o._ I C u <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XH.p.1.=.=.=.=.=.%.@.| W V f * <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<Xf ^ | o.%.3.q.2.>.*.=.=.=.=.*.*.$..._ L C u <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XH.p.4.=.=.=.=.=.*.%.o.' T C 1 <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<XV ..%.=.w.g.q.>.=.=.=.=.=.=.=.*.$..._ I B u <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XD.p.1.=.=.=.=.=.=.*.%.o.' T r <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<XP %.=.n.c.w.>.=.=.=.=.=.=.=.=.*.*..._ I C u <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XH.p.1.*.=.=.=.=.=.=.*.%.%.| m <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X#._._.H.d.>.=.=.=.=.=.=.=.=.=.*.*..._ L C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=..X,X#XH.p.1.=.=.=.=.=.=.=.=.*.%.%.o.| | ] ] ] _ _ _ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ _ ' ] o.%.=.H.$X:X$XT.d.4.=.=.=.=.=.=.=.=.=.*.*.$..._ I C t <X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X..@.=.XX,X#XD.p.4.=.=.=.=.=.=.=.=.=.=.*.*.*.@.o.@.............................| ..........................................................| ....o.o.%.*.k.+X,X,X.XS.u.>.=.=.=.=.=.=.=.=.=.=.=.*.*...) P C t <X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X..@.*..X,X#XH.p.1.=.=.=.=.=.=.=.=.=.=.=.*.*.*.*.*.%.%.*.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.t.E.*X:X#X^.n.q.>.*.=.=.=.=.=.=.=.=.=.=.=.*.$..._ J V t <X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X| ..*.`.,X#XH.p.1.*.=.=.=.=.=.=.=.=.=.=.=.*.1.6.p.d.k.k.l.l.n.n.n.n.n.n.n.n.n.M.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.B.H.!.`.|.|.!.A.d.6.=.=.=.=.=.=.=.=.=.=.=.=.=.=.*.$...^ J m t <X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X| ..@.k.,X#XD.p.1.=.=.=.=.=.=.=.=.=.=.=.=.=.*.1.6.w.g.k.n.M.A.S.A.A.A.A.A.A.A.A.A.S.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.S.A.A.A.A.A.A.A.D.N.M.l.d.w.4.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.*.*.] T C j <X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X' ..%.E.=XH.p.1.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.*.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.*.@._ F j d <X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X' ..*.R.`.p.1.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.*.%.] J j t <X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X_ ..%.D.P.1.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.*.%.] I j t <X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X^ | %.B.D.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.*.*...I m 6 <X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X^ ..%.n.D.*.=.*.*.*.*.=.=.*.*.=.*.*.=.*.*.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.=.%.] I j 6 <X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X^ | @.*.*.%.*.*.%.*.%.*.*.%.%.*.%.*.*.%.%.*.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.%.*.%.%.%.%.%.%.%.%.%.%.%.*.%.%.%.%.%.*.%.%.%.*.%.%.%.*.%.%.%.*.*.@.] I j 6 <X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<XW ] | | ..] ] ] ] ] ] ] ] ] ' ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ' ] | ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ' I C d 1 <X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<XT W W W I I I I J P L J I I J I I J I I J P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P P J P P P P P P P P P P P P P P J P P P P P P P P P P P J P P P P P J P P P J P P P J P P P J I I J C m d 4 <X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<XI P C V c j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j f d r t 6 <X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<XP m j t 6 4 1 1 4 4 4 4 4 4 4 4 4 4 1 1 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 6 4 4 4 1 1 4 6 q <X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X",
"<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X<X"
};
