/*
 * Embroidermodder 2.
 *
 * Copyright 2011-2024 The Embroidermodder Team
 * Embroidermodder 2 is Open Source Software, see LICENSE.md for licensing terms.
 *
 * Read the reference manual (https://www.libembroidery.org/downloads/emrm.pdf)
 * for advice on altering this file.
 */
/* XPM */
static char *mirror[] = {
/* columns rows colors chars-per-pixel */
"128 128 237 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c #060606",
"@  c #070707",
"#  c #090909",
"$  c gray4",
"%  c #0B0B0B",
"&  c #0C0C0C",
"*  c #0E0E0E",
"=  c #101010",
"-  c #111111",
";  c gray7",
":  c #151515",
">  c #161616",
",  c gray9",
"<  c #181818",
"1  c #191919",
"2  c gray10",
"3  c #1B1B1B",
"4  c gray11",
"5  c #1D1D1D",
"6  c #1E1E1E",
"7  c gray12",
"8  c #202020",
"9  c gray13",
"0  c #232323",
"q  c gray14",
"w  c #252525",
"e  c gray15",
"r  c #282828",
"t  c gray16",
"y  c #2A2A2A",
"u  c gray17",
"i  c #2C2C2C",
"p  c #2D2D2D",
"a  c gray18",
"s  c #2F2F2F",
"d  c gray19",
"f  c #313131",
"g  c #323232",
"h  c gray20",
"j  c #343434",
"k  c #353535",
"l  c gray21",
"z  c #373737",
"x  c gray22",
"c  c #393939",
"v  c gray23",
"b  c #3C3C3C",
"n  c gray24",
"m  c #3E3E3E",
"M  c #3F3F3F",
"N  c #530000",
"B  c #580000",
"V  c #590000",
"C  c #5A0000",
"Z  c #5B0000",
"A  c #5C0000",
"S  c #5D0000",
"D  c #5F0000",
"F  c #620000",
"G  c #630000",
"H  c #650000",
"J  c #670000",
"K  c #680000",
"L  c #6A0000",
"P  c #6D0000",
"I  c #6E0000",
"U  c #6F0000",
"Y  c #700000",
"T  c #720000",
"R  c #730000",
"E  c #740000",
"W  c #750000",
"Q  c #760000",
"!  c #780000",
"~  c #790000",
"^  c #7A0000",
"/  c #7B0000",
"(  c #7C0000",
")  c #7D0000",
"_  c #7E0000",
"`  c #7F0000",
"'  c gray25",
"]  c #414141",
"[  c gray26",
"{  c #434343",
"}  c #444444",
"|  c gray27",
" . c #484848",
".. c #494949",
"X. c gray29",
"o. c #4C4C4C",
"O. c gray30",
"+. c #4E4E4E",
"@. c #515151",
"#. c gray32",
"$. c #535353",
"%. c gray33",
"&. c #555555",
"*. c #585858",
"=. c #5A5A5A",
"-. c #5B5B5B",
";. c gray36",
":. c #5D5D5D",
">. c gray37",
",. c #5F5F5F",
"<. c gray38",
"1. c #626262",
"2. c gray39",
"3. c #646464",
"4. c #656565",
"5. c gray40",
"6. c #676767",
"7. c #686868",
"8. c DimGray",
"9. c #6A6A6A",
"0. c gray42",
"q. c #6C6C6C",
"w. c #6D6D6D",
"e. c gray43",
"r. c gray44",
"t. c #717171",
"y. c #727272",
"u. c gray45",
"i. c #747474",
"p. c gray46",
"a. c #767676",
"s. c #777777",
"d. c gray47",
"f. c #797979",
"g. c gray48",
"h. c #7B7B7B",
"j. c #7C7C7C",
"k. c gray49",
"l. c #7E7E7E",
"z. c gray50",
"x. c #902121",
"c. c #A04040",
"v. c #A64C4C",
"b. c #AE5D5D",
"n. c #808080",
"m. c gray51",
"M. c #848484",
"N. c #868686",
"B. c #888888",
"V. c #898989",
"C. c gray54",
"Z. c #8E8E8E",
"A. c gray57",
"S. c #929292",
"D. c gray59",
"F. c #979797",
"G. c gray60",
"H. c #9B9B9B",
"J. c gray61",
"K. c gray62",
"L. c #A0A0A0",
"P. c gray63",
"I. c gray64",
"U. c #A5A5A5",
"Y. c gray65",
"T. c #A7A7A7",
"R. c gray67",
"E. c gray68",
"W. c gray69",
"Q. c gray70",
"!. c gray71",
"~. c #B6B6B6",
"^. c #B7B7B7",
"/. c gray72",
"(. c #B9B9B9",
"). c gray73",
"_. c #BCBCBC",
"`. c gray74",
"'. c gray",
"]. c gray75",
"[. c #D0A0A0",
"{. c #D3A6A6",
"}. c #C0C0C0",
"|. c #C1C1C1",
" X c gray76",
".X c #C3C3C3",
"XX c gray77",
"oX c #C5C5C5",
"OX c #C6C6C6",
"+X c gray78",
"@X c #C8C8C8",
"#X c gray79",
"$X c #CACACA",
"%X c #CBCBCB",
"&X c #CDCDCD",
"*X c #CECECE",
"=X c gray81",
"-X c #D0D0D0",
";X c LightGray",
":X c gray83",
">X c #D5D5D5",
",X c gray84",
"<X c #D7D7D7",
"1X c gray85",
"2X c #DADADA",
"3X c gray86",
"4X c gainsboro",
"5X c #DDDDDD",
"6X c #DFDFDF",
"7X c gray88",
"8X c #E1E1E1",
"9X c #E2E2E2",
"0X c gray89",
"qX c #E4E4E4",
"wX c gray90",
"eX c #E6E6E6",
"rX c #E7E7E7",
"tX c gray91",
"yX c #EAEAEA",
"uX c gray92",
"iX c #ECECEC",
"pX c gray93",
"aX c #EEEEEE",
"sX c #F1F1F1",
"dX c gray95",
"fX c #F3F3F3",
"gX c #F4F4F4",
"hX c gray96",
"jX c gray97",
"kX c #F8F8F8",
"lX c #F9F9F9",
"zX c gray98",
"xX c #FBFBFB",
"cX c #FDFDFD",
"vX c #FEFEFE",
"bX c white",
"nX c None",
/* pixels */
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX_ _ ~ Q nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX_ _ ~ Q P nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX_ v._ T K nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX_ {._ T G nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX_ [._ T D nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX~ b._ P D nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX0 nXnXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnXnX0 nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX1     nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX    1 nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX      nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX    O nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX1       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      : nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXp       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      g nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  $.      nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      $.  nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  1.      nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      1.  nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  ] z       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z ]   nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  z.        nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX        z.  nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    s.        nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX        s.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    1.          nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX          1.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    s.          nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX          h.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    >.            nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX            >.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    y.            nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX            y.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    1.      :       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      :       1.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    w.      e       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      e       w.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    4.        r       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      r         4.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    7.    *   g       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      g   ;     7.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    7.      $.  g       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      g   $.      7.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    4.    1 N.  g       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      g   N.1     4.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    7.      G.m.  p       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      p   m.G.      7.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  # 1.    5 @Xz.  p       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      p   z.@X5     1.O   nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    w.      J. Xh.  r       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      r   h. XJ.      y.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  # >.    r @X`.h.  r       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      r   h.`.@Xr     >.#   nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    y.      P. X).h.  r       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      r   h.). XP.      y.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  ; *.    r @X`.~.h.  p       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      p   h.~.`.@Xr     *.;   nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    y.      T. X).~.z.  p       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      p   h.~.). XT.      y.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  1 $.    z +X`.~.).m.  p       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      p   m.).~.`.@Xz     $.:   nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    s.      E. X).~.`.N.  p       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      p   m.`.~.). XE.      s.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  5 O.    M +X`.~.). XN.  g       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      g   B. X).~.`.+XM     O.5   nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    s.      ~.`.).~.`.+XZ.  g       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      g   Z.+X`.~.). XQ.      s.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  0  .    } +X`.).). X&XS.  g       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      g   S.&X X).).`.+X}      .0   nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    h.      ~.`.).~.`.+X<XF.  g       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      h   F.<X+X`.~.). X~.      h.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  r ]     O.+X).).). X&X6XG.  z       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      h   G.6X&X X).).`.+XO.    ] r   nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    h.      ~. X).).`.@X<XeXJ.  g       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   J.eX<X@X`.~.).`.~.      h.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  p M     $.+X`.~.). X&X6XuXP.  z       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      z   P.uX6X&X X).).`.+X$.    M p   nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    h.      `. X).).`.@X<XeXdXP.  g       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   P.dXeX<X+X`.~.). X`.      h.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  g z     *.@X`.~.). X&X6XuXhXT.  g       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      g   T.dXuX6X&X X).~.`.+X*.    z g   nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    h.       X`.).).`.@X<XeXdXlXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      z   T.lXdXeX1X@X`.).). X`.      h.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  z p     1.+X`.).). X-X6XuXhXlXR.  g       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   T.lXhXuX6X-X X).~.`.+X1.    p z   nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    h.       X`.).~.`.@X1XeXdXlXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   T.vXlXdXeX<X@X`.).). X X      z.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  v r     7.@X).).).+X-X6XuXhXlXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      g   T.vXvXhXuX6X&X+X).~.`.+X7.    r v   nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    h.       X X).).`.@X1XeXdXlXvXvXT.  g       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   T.vXvXlXdXeX1X@X`.).). X X      h.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  M 0     w.+X`.).).+X&X7XiXhXlXvXvXT.  g       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   T.vXvXlXhXiX7X-X X`.).`.+Xw.    0 M   nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    h.      +X`.).~.`.@X1XeXdXlXvXvXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      z   T.vXvXvXlXdXeX1X@X`.~.).`.+X      h.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  } 1     s.+X`.).). X-X7XiXhXlXvXvXvXR.  g       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      g   T.vXvXvXvXhXiX7X&X+X).~.`.+Xs.    1 }   nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    h.      +X`.).~.`.&X1XeXdXlXvXvXvXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   R.vXvXvXvXlXdXeX1X@X`.).).`.+X      h.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  } ;     h.+X).).). X-X7XiXhXvXvXvXvXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   T.vXvXvXvXvXhXiX7X-X+X).).).+Xz.    ;  .  nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    h.    O @X`.).).`.@X1XeXhXlXvXvXvXvXvXT.  g       nXnXnXnXnXnXnXnXnX~ c._ T Z nXnXnXnXnXnXnXnXnX      z   T.vXvXvXvXvXlXdXeX1X@X`.~.).`.@XO     h.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  O.#     z.+X`.~.). X-X7XiXhXlXvXvXvXvXvXT.  g       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      g   T.vXvXvXvXvXvXhXiX7X-X+X).).).+Xm.    # O.  nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    h.    O +X X).). X@X1XuXdXlXvXvXvXvXvXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   R.vXvXvXvXvXvXlXdXeX1X@X`.~.). X+XO     h.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  $.      N. X).~.`. X-X7XiXlXvXvXvXvXvXvXvXR.  g       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      z   T.vXvXvXvXvXvXvXlXiX7X-X+X`.).).+XN.      $.  nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    h.    * @X X).).`.@X6XeXhXlXvXvXvXvXvXvXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   T.vXvXvXvXvXvXvXlXhXuX1X&X`.~.).`.@X*     s.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  &.      B.+X`.~.`.+X<X7XiXhXvXvXvXvXvXvXvXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      g   T.vXvXvXvXvXvXvXvXhXiX7X-X+X).).`.+XB.      &.  nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    s.    ; &X`.).).`.@X1XeXhXlXvXvXvXvXvXvXvXvXT.  g       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      z   R.vXvXvXvXvXvXvXvXlXhXeX1X&X`.).).`.@X;     s.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  *.      S.+X).).).+X-X7XiXhXvXvXvXvXvXvXvXvXvXT.  g       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   T.vXvXvXvXvXvXvXvXvXlXiX7X<X+X).~.).+XS.      *.  nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    s.    1 @X`.).).`.@X6XuXdXvXvXvXvXvXvXvXvXvXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   T.vXvXvXvXvXvXvXvXvXlXhXeX1X@X X).).`.@X1     y.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  >.      F.+X`.~.`.+X-X7XiXlXvXvXvXvXvXvXvXvXvXvXR.  g       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      g   T.vXvXvXvXvXvXvXvXvXvXhXiX7X-X+X`.~.`.+XF.      1.  nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    y.    0 @X`.).).`.&X6XeXhXlXvXvXvXvXvXvXvXvXvXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   R.vXvXvXvXvXvXvXvXvXvXlXdXuX6X@X`.).).`.&X5     w.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  1.      J.+X).).).+X-X7XiXhXvXvXvXvXvXvXvXvXvXvXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   T.vXvXvXvXvXvXvXvXvXvXvXlXiX7X<X+X`.~.).+XG.      4.  nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    w.    0 @X`.).). X&X6XuXhXlXvXvXvXvXvXvXvXvXvXvXvXT.  g       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      z   T.vXvXvXvXvXvXvXvXvXvXvXlXdXuX1X&X`.).). X@Xe     w.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    4.      P.+X`.~.`.+X-X7XiXlXvXvXvXvXvXvXvXvXvXvXvXvXT.  g       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      g   T.vXvXvXvXvXvXvXvXvXvXvXvXlXiX7X<X+X`.~.`.+XJ.      4.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    7.    p @X`.).). X@X6XuXhXlXvXvXvXvXvXvXvXvXvXvXvXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   R.vXvXvXvXvXvXvXvXvXvXvXvXlXhXuX1X&X X).).`.@Xp     7.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    7.      T. X`.).`.+X<X7XiXlXvXvXvXvXvXvXvXvXvXvXvXvXvXR.  g       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      g   T.vXvXvXvXvXvXvXvXvXvXvXvXvXlXiX7X<X+X`.).). XT.      7.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  O 1.    z @X`.).~. X&X6XuXdXlXvXvXvXvXvXvXvXvXvXvXvXvXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   R.vXvXvXvXvXvXvXvXvXvXvXvXvXlXhXuX6X&X`.).). X@Xv     1.O   nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    w.      E. X).~.`.+X<X7XiXlXvXvXvXvXvXvXvXvXvXvXvXvXvXvXT.  g       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   T.vXvXvXvXvXvXvXvXvXvXvXvXvXvXlXiX7X<X+X).).). XR.      w.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  * >.    ] @X X).). X&X1XuXhXlXvXvXvXvXvXvXvXvXvXvXvXvXvXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      g   T.vXvXvXvXvXvXvXvXvXvXvXvXvXvXlXdXuX6X&X`.).).`.@XM     1.#   nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnX    y.      Q. X).).`.@X<XeXiXlXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXR.  g       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   R.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXlXiXeX<X+X`.).).+XQ.      y.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnX  : *.    } @X`.).). X&X6XuXhXlXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      g   T.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXlXhXuX6X&X X).).`.@X}     *.;   nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnX    y.      ~. X).).).@X<X7XdXlXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXT.  g       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      g   T.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXlXiXeX<X+X).).).+XQ.      s.    nXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnX  1 &.    O.@X`.).). X&X6XuXdXlXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   T.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXlXhXuX6X&X X).).`.@XO.    $.:   nXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnX    s.      ~.+X).).`.@X<X7XdXlXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXR.  g       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   T.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXlXdX7X<X@X`.).). X~.      s.    nXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnX  5 O.    $.@X`.~.). X&X6XuXhXlXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      g   T.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXhXiX7X&X X).~.`.@X&.    O.5   nXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnX    s.      `. X).).`.@X1XeXdXlXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXT.  g       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   R.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXlXdXeX1X@X`.).).+X`.      h.    nXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnX  e  .    >.@X`.).). X&X6XuXhXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      g   T.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXlXhXiX7X&X X).).`.@X>.     .0   nXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnX    h.      `. X).).`.@X<XeXdXhXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXR.  g       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      g   T.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXlXdXeX<X@X`.).). X`.      h.    nXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnX  r ]     1.+X`.).).+X&X6XuXhXlXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   T.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXlXhXuX6X&X+X).).`.+X1.    ] r   nXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnX    h.      +X X).).`.@X<XeXdXlXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXT.  g       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   T.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXlXdXeX<X@X`.).). X+X      h.    nXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnX  r M     4.@X`.).). X-X6XuXhXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      g   T.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXlXhXuX6X&X+X).).`.+X4.    M p   nXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnX    h.      +X X).).`.@X1XeXdXlXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXR.  z       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   R.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXlXdXeX1X@X`.).). X+X      h.    nXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnX  g z     7.@X`.).). X-X6XiXhXlXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      g   T.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXlXhXiX7X-X X).).`.+X7.    z g   nXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnX    h.      +X X).). X@X1XeXdXlXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXT.  g       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      g   T.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXlXdXeX1X@X`.).). X+X      h.    nXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnX  v p     y.@X`.).`. X-X7XiXhXlXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXT.  g       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   T.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXhXiX7X-X+X).).`.@Xy.    p v   nXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnX    h.    O +X X).).`.@X1XeXdXlXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXT.  z       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      z   T.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXlXdXeX1X@X`.).). X+XO     h.    nXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnX  M e     h.+X`.~.`. X-X6XiXhXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXT.  v       nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      v   T.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXhXuX7X-X X).).`.+Xh.    e M   nXnXnXnXnXnXnXnX",
"nXnXnXnXnXnX    z.    O @X X).).`.@X1XuXdXlXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXR.  $.      nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      &.  R.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXlXdXeX1X&X`.).). X@XO     z.    nXnXnXnXnXnXnX",
"nXnXnXnXnXnX  } 1     z.@X`.).).+X&X7XiXlXlXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXT.  y.      nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      y.  T.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXlXlXiX7X-X+X`.).`.+Xz.    1 ]   nXnXnXnXnXnXnX",
"nXnXnXnXnX    h.    * @X X).). X@X6XeXdXlXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXT.  z.      nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX      m.  T.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXlXdXeX1X@X`.).). X@X*     h.    nXnXnXnXnXnX",
"nXnXnXnXnX   .;     m.@X`.).). X-X7XiXhXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXT.e y.      nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      y.e T.vXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXvXlXlXiX7X<X X`.).`.+Xm.    ;  .  nXnXnXnXnXnX",
"nXnXnXnX    >.      ] w.4.7.7.y.h.z.N.N.B.B.B.B.B.Z.B.B.B.B.B.Z.Z.B.B.B.B.Z.B.B.B.Z.B.B.B.Z.>.7.p       nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX      p 7.>.B.B.Z.B.B.B.Z.Z.B.B.B.B.Z.B.B.B.B.B.Z.Z.B.B.B.Z.B.B.B.N.z.s.y.7.4.4.w.]       >.    nXnXnXnXnX",
"nXnXnXnX                                                                                  v w.z.        nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX        z.w.v                                                                                   nXnXnXnXnX",
"nXnXnX          # 1 # ; 1 0 p z v M M M ] M ] ] M ] M ] ] ] ] ] ] M ] ] M ] M ] ] } *.y.h.4.5           nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX          5 4.z.y.*.} ] ] ] M ] ] M ] M ] ] ] ] ] ] M ] M ] M ] M M M v z g 0 1 ; # 1 #           nXnXnXnX",
"nXnXnX                                                                                                  nXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnX                                                                                                  nXnXnXnX",
"nXnX                                                                                                    nXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnX                                                                                                    nXnXnX",
"nXnXnX                                                                                                nXnXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnXnX                                                                                                nXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX~ c._ P D nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX~ c._ P Z nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX~ x._ P Z nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX~ _ ~ P Z nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXQ ~ Q K Z nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXT T T K Z nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXT P K H D nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXG D B Z N nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX",
"nXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnXnX"
};
