/*
 * Embroidermodder 2.
 *
 * Copyright 2011-2024 The Embroidermodder Team
 * Embroidermodder 2 is Open Source Software, see LICENSE.md for licensing terms.
 *
 * Read the reference manual (https://www.libembroidery.org/downloads/emrm.pdf)
 * for advice on altering this file.
 */
/* XPM */
static char *orthosettings[] = {
/* columns rows colors chars-per-pixel */
"128 128 129 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #060606",
"#  c #070707",
"$  c gray3",
"%  c #090909",
"&  c gray4",
"*  c #0B0B0B",
"=  c #0C0C0C",
"-  c gray5",
";  c #0E0E0E",
":  c gray6",
">  c #101010",
",  c #111111",
"<  c gray7",
"1  c #131313",
"2  c gray8",
"3  c #151515",
"4  c #161616",
"5  c gray9",
"6  c #181818",
"7  c #191919",
"8  c gray10",
"9  c #1B1B1B",
"0  c gray11",
"q  c #1D1D1D",
"w  c #1E1E1E",
"e  c gray12",
"r  c #202020",
"t  c gray13",
"y  c #222222",
"u  c #232323",
"i  c gray14",
"p  c #252525",
"a  c gray15",
"s  c #272727",
"d  c #282828",
"f  c gray16",
"g  c #2A2A2A",
"h  c gray17",
"j  c #2C2C2C",
"k  c #2D2D2D",
"l  c gray18",
"z  c #2F2F2F",
"x  c gray19",
"c  c #313131",
"v  c #323232",
"b  c gray20",
"n  c #343434",
"m  c #353535",
"M  c gray21",
"N  c #373737",
"B  c gray22",
"V  c #393939",
"C  c #3A3A3A",
"Z  c gray23",
"A  c #3C3C3C",
"S  c gray24",
"D  c #3E3E3E",
"F  c #3F3F3F",
"G  c gray25",
"H  c #414141",
"J  c gray26",
"K  c #434343",
"L  c #444444",
"P  c gray27",
"I  c #464646",
"U  c gray28",
"Y  c #484848",
"T  c #494949",
"R  c gray29",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c gray30",
"!  c #4E4E4E",
"~  c gray31",
"^  c #505050",
"/  c #515151",
"(  c gray32",
")  c #535353",
"_  c gray33",
"`  c #555555",
"'  c #565656",
"]  c gray34",
"[  c #585858",
"{  c gray35",
"}  c #5A5A5A",
"|  c #5B5B5B",
" . c gray36",
".. c #5D5D5D",
"X. c gray37",
"o. c #5F5F5F",
"O. c #606060",
"+. c gray38",
"@. c #626262",
"#. c gray39",
"$. c #646464",
"%. c #656565",
"&. c gray40",
"*. c #676767",
"=. c #686868",
"-. c DimGray",
";. c #6A6A6A",
":. c gray42",
">. c #6C6C6C",
",. c #6D6D6D",
"<. c gray43",
"1. c #6F6F6F",
"2. c gray44",
"3. c #717171",
"4. c #727272",
"5. c gray45",
"6. c #747474",
"7. c gray46",
"8. c #767676",
"9. c #777777",
"0. c gray47",
"q. c #797979",
"w. c gray48",
"e. c #7B7B7B",
"r. c #7C7C7C",
"t. c gray49",
"y. c #7E7E7E",
"u. c gray50",
"i. c None",
/* pixels */
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.* = = 1 = = *                         i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.7 e p N H ( } +.$.$.+...] E F N N B F B B x p 1           i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.p x H ( +.<.<.-...( I E W ..<.5.+.( N 7 = * * 4 p N H I H l 1         i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.h x E ..<.8.-.( p                   e h *                       r B F l 1         i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.x H } 5.0.-.F                                                               h N h O       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.F ( -.0.8.W                       i.    i.            i.i.                          O l l =       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.F ] 5.u.<.h                   i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.                  1 r *       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.B ( 5.u.-.=               i.i.i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.i.i.i.i.                e O       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.N E -.u.-.1               i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.                e         i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.H ..u.0.l             i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  4       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            = 4       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.B W <.u.]           i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  r       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            4         i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.F ..u.5.=           i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            *       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.I -.u.]           i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          O       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.W 5.u.r         i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  p       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.                  i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.( 0.5.          i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.                i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.( 0.-.        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          O       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.( 0.+.        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  p       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.        O       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.W 0...        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.                i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.I 8...        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  p       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.              i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.H 5.$.        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.              i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.B -.<.        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  l       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.              i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.h ..8.        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  F       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.      O       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.r E 8.e       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  }       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.      =       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.N 5.E       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.h -.1     i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.r ..$.      i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.] 8.h     i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.4 I <.        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.( 8.0.B     i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.      O       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.l $.F       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.7 p B ] $.8.u.-.B               i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.4 W +.      i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.l N I ] -.0.u.u.5.+.I e                     i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.x $.1       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.B W +.5.8.-...W B h e e =             4 x l 1       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.              i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.4 ( (       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.B ] <.u.<.F                                     e l 4       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.x $.        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.B W -.u.-.4                                             O h =       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.    O       i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.= W E       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.N E $.u.5.e               i.i.i.i.          i.i.i.              * p         i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.h +.        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.H ..0.u.N             i.i.i.i.i.i.i.          i.i.i.i.i.i.            = *       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.    O       i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.  I W       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.I $.u.}             i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.                  i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.4 ..*       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.E <.u.p           i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.i.                  i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.  x ]       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.I 5.8.          i.i.i.i.i.i.i.i.i.i.i.i.i.  4       i.i.i.i.i.i.i.i.i.i.i.i.                i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.  E l       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.F <.8.        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  p       i.i.i.i.i.i.i.i.i.i.i.i.i.i.              i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.4 ]       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.x +.0.        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  p       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.      *       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.  h I       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.r ( 0.7       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.      1       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.  F e       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.B 5.I       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.      *       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.  I       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.p ..$.      i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  p       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.    O       i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.  4 F       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.= F <.        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.      =       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.  l r       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.e } I       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.  F       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  B +.      i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  p       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.  H       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.1 ( B       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.    1       i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.  * H       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  p }       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.    =       i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.  4 x       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  F H       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  p       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  O       i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.  r e       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.O (       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.  h         i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  7 E       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  p       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  x N       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  l       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.  l       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  I p     i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  F       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.    =     i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.    7       i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.  B       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.4 +.7     i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.* }       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  4 B       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.7 B       i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.  H *     i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.F <.4     i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.x -.4     i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.F }       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.I E       i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.  I N     i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.F $.8.7     i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.} 0.l     i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.+.<.4     i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.<.W       i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.    I ..    i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i...u.8.p     i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i...8.8.B     i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.+.8.5.N     i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.$.u.B       i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.    x ..r         1 e r r r r r r r r h F ] -.8.u.0...r           1 e r r r r r r r r r r r r r p B ( $.8.u.u.-.B           * e p r r r r r r r r r r r r h F ] <.0.u.0.$.B           * e r p r r r r r r r h B ( -.0.u.8.        i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.    1 E p     O h H ( ] } } } } } } } ..-.8.0.5.$.] N           p H ( } } } } } } } } } } } } } ..$.5.8.8.$.] F 7         7 B W } } ] } } } } } ] } } } ] ..$.<.8.5.+.} F e         7 B W ] } } ] } } } } } ..$.5.0.8.-.I         i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.    p                                         = =                                                       O = O                                                     O = O                                           1 7           i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.                                                                                                                                                                                                                                i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.                                                                                                                                                                                                                                i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.    O       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  4 O       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  p       i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.    4       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.    O     i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  7       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  I O     i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  F       i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.    7       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.    1       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.7 }       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  1 I       i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.    =       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  H E       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  p N       i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.    O     i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  p       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.4 } 4       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  B 7       i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.    =       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.    *       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  B ..      i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  I       i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.    1       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.7 } l       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  1 E       i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  p       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.* F +.      i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  x N       i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.p ..h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  E =     i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.    =       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.7 W ..      i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.7 (       i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.              i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  p       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.B -.*       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  F H       i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.    =       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.N +.I       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.1 ] *       i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.    =       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.N ..+.        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  l ]       i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.      O       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.              i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  p       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i...<.        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.O E h       i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.    =       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.              i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.$.0.=       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.p ]       i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.              i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.      *         i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.W <.u.e       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.* I F       i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.      * 4       i.i.i.i.i.i.i.i.i.i.i.i.i.  B       i.i.i.i.i.i.i.i.i.i.i.i.i.] 8.u.=       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.l ..      i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.              i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.        e         i.i.i.i.i.i.i.i.i.i.i.  (       i.i.i.i.i.i.i.i.i.i.i.I +.u.-.        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.7 ] I       i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.        = =       i.i.i.i.i.i.i.i.i.i.l $.1     i.i.i.i.i.i.i.i.i.F ] 8.u.H         i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.7 H -.      i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.              i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          7 =         i.i.i.i.i.i.i.} 5.h     i.i.i.i.i.i.x F ] <.u...          i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.x -.F       i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            p h =         i.i.i.i.8.8.B     i.i.i.i.l I +.8.0...            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.r } -.      i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.              i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            e x l r h H +.8.0.u.<.H         r W -.0.5.H             i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.7 I <.=       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.                7 F ..5.0.8.<.( l       * l H N                 i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.x $.E       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.                    4 p h e                             i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.p ] +.        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.              i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.                                            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.e I <.        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.              i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.                                i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.B -.x       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.N $.(       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.              i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.B +.$.        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.              i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.H +.5.        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.              i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.I $.0.1       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.              i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  4       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.E -.u.7       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.      = O       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  r       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.W 5.u.4       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.      * 1       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.F ] 0.0.        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.        e       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.I ..u.-.        i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.        4         i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  p       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.E -.u.W         i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          1       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.H } u.0.e         i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          e         i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  p       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.B W <.u...          i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.        * r         i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  h       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.E $.u.8.7         i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.          7 r         i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  l       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.x I ..0.u.H           i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            e e         i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.  H       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.N I +.8.0.E             i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            4 7           i.i.i.i.i.i.i.i.i.i.i.i.i.i.4 }       i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.N W -.0.0.I             i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.            = e 1           i.i.i.i.i.i.i.i.i.i.i.F <.4     i.i.i.i.i.i.i.i.i.i.i.e h F ] <.u.5.N             i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.                p x r =           i.i.i.i.i.i.i.$.8.l     i.i.i.i.i.i.i.1 e l F ( -.8.8.] =               i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.              = x B N h 7 O       r E i.-.u.8.N           1 p N H ] +.<.5.<.W 7               i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.                  7 x F F F I ..8.u.0.$.H 1       1 B ] <.5.<.$.W p                   i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.                        = h x h *               7 p r                         i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.                                                                  i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.                                                  i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.                          i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.",
"i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i."
};
