/*
 * Embroidermodder 2.
 *
 * Copyright 2011-2024 The Embroidermodder Team
 * Embroidermodder 2 is Open Source Software, see LICENSE.md for licensing terms.
 *
 * Read the reference manual (https://www.libembroidery.org/downloads/emrm.pdf)
 * for advice on altering this file.
 */
/* XPM */
static char *quickselect[] = {
/* columns rows colors chars-per-pixel */
"128 128 186 2 ",
"   c #000000",
".  c #0B0B0B",
"X  c #151515",
"o  c #1C1C1C",
"O  c #242424",
"+  c #2B2B2B",
"@  c #343434",
"#  c #3C3C3C",
"$  c #424242",
"%  c #4C4C4C",
"&  c #545454",
"*  c #5B5B5B",
"=  c #646464",
"-  c #6B6B6B",
";  c #747474",
":  c #7B7B7B",
">  c #7C8301",
",  c #848C01",
"<  c #888F0C",
"1  c #8B9300",
"2  c #8F9800",
"3  c #8E940C",
"4  c #939C00",
"5  c #959C0C",
"6  c #8D9310",
"7  c #909512",
"8  c #97A000",
"9  c #9AA301",
"0  c #9FA900",
"q  c #9BA10D",
"w  c #9FA612",
"e  c #9EA31D",
"r  c #A2AC00",
"t  c #A8AF04",
"y  c #A5AD0A",
"u  c #A7B100",
"i  c #AAB500",
"p  c #AEB900",
"a  c #B2BD00",
"s  c #A6AA1D",
"d  c #B6BB18",
"f  c #ABAF26",
"g  c #AEB22A",
"h  c #B3B82C",
"j  c #BBBE33",
"k  c #B6C200",
"l  c #BAC500",
"z  c #BECA00",
"x  c #B8C209",
"c  c #C0C000",
"v  c #C2CE00",
"b  c #C9C900",
"n  c #C7CC0E",
"m  c #C6D200",
"M  c #CBD502",
"N  c #CED900",
"B  c #C9D40B",
"V  c #D2D603",
"C  c #D2DA01",
"Z  c #D6DF0B",
"A  c #D9DD07",
"S  c #C5CC12",
"D  c #C2C61C",
"F  c #CAD513",
"G  c #CCD71B",
"H  c #CED814",
"J  c #D6DB18",
"K  c #DBE201",
"L  c #DBE30E",
"P  c #DDE318",
"I  c #E2E901",
"U  c #EAED02",
"Y  c #EBEE0B",
"T  c #F2F503",
"R  c #F7F800",
"E  c #FCFD02",
"W  c #F4F60B",
"Q  c #F7F909",
"!  c #FCFC0B",
"~  c #EBEF15",
"^  c #E5EB1C",
"/  c #EAEE1A",
"(  c #E6EB17",
")  c #EEF112",
"_  c #F3F411",
"`  c #FEFE17",
"'  c #FBFC1A",
"]  c #F0F11A",
"[  c #C2C723",
"{  c #C3C62D",
"}  c #C9CC2C",
"|  c #CED925",
" . c #CFD928",
".. c #D2DB2C",
"X. c #DADC2F",
"o. c #C3C635",
"O. c #C3C639",
"+. c #C7CA39",
"@. c #CACD3B",
"#. c #CCCF35",
"$. c #CDD037",
"%. c #CED13D",
"&. c #D3DC34",
"*. c #D3D63C",
"=. c #D4DD3B",
"-. c #DADD39",
";. c #DDE424",
":. c #D9E12C",
">. c #E0E620",
",. c #E9EC24",
"<. c #E2E72E",
"1. c #E4EA2C",
"2. c #FDFE27",
"3. c #F7F72F",
"4. c #FFFE2F",
"5. c #F6F82D",
"6. c #ECEF36",
"7. c #E2E639",
"8. c #F2F333",
"9. c #F6F837",
"0. c #FFFE32",
"q. c #F8F939",
"w. c #CBCD42",
"e. c #D6DE44",
"r. c #D7DF4A",
"t. c #D5D749",
"y. c #DBDD51",
"u. c #D7E042",
"i. c #D7E04E",
"p. c #D8E04F",
"a. c #D9E153",
"s. c #DAE25B",
"d. c #EDEE43",
"f. c #FFFE45",
"g. c #FFFE4E",
"h. c #E7E955",
"j. c #FFFE55",
"k. c #FEFD5B",
"l. c #F5F656",
"z. c #DCE464",
"x. c #DEE56A",
"c. c #DFE670",
"v. c #EDED60",
"b. c #F3F364",
"n. c #FFFE62",
"m. c #F6F668",
"M. c #FDFC6C",
"N. c #E0E775",
"B. c #E1E779",
"V. c #E2E87D",
"C. c #E9EE7D",
"Z. c #FFFE74",
"A. c #FFFE7A",
"S. c #848484",
"D. c #8C8C8C",
"F. c #949494",
"G. c #9C9C9C",
"H. c #A4A4A4",
"J. c #ABABAB",
"K. c #B4B4B4",
"L. c #BCBCBC",
"P. c #E4E984",
"I. c #E5EB8B",
"U. c #FFFD84",
"Y. c #FFFD8C",
"T. c #E7EC93",
"R. c #E8ED96",
"E. c #E8ED9B",
"W. c #FFFC92",
"Q. c #FFFC99",
"!. c #EAEFA3",
"~. c #ECF0AB",
"^. c #EDF1A1",
"/. c #F1F3A6",
"(. c #EEF2B5",
"). c #EFF3B9",
"_. c #F0F4BD",
"`. c #C3C3C3",
"'. c #CCCCCC",
"]. c #D4D4D4",
"[. c #DBDBDB",
"{. c #E3E3E3",
"}. c #EBEBEB",
"|. c #F4F4F4",
" X c #FBFBFB",
".X c None",
/* pixels */
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X$ + .                                                                                                                                                                                         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X$ $ # + O O @ # # $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ # @ + .       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.XO % - ; & # # # # # $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ & * - ; - % .       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X    # ; : #                                                                                                                                                                           @ = = o         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X      # +                                                                                                                                                                                 o           .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X            + % * * & % % % % % & & & & & & * * * * * * = = = = = - - - - - ; - ; ; ; ; ; ; : : : : : : ; ; ; ; ; ; ; ; - - - - - - = = = = = = * * * * * & & & & % & % % % % % $ # # @ O             .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X          . = ; D.F.F.D.D.D.D.F.F.F.F.G.F.G.G.G.H.H.H.J.J.J.J.J.K.K.K.K.L.K.L.L.L.`.L.`.`.`.`.`.'.`.`.`.`.L.`.L.L.L.L.L.L.K.K.K.J.J.J.J.H.J.H.H.H.G.G.G.F.F.F.F.F.F.F.D.D.S.: - = * % .           .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X          + = - D.F.F.F.F.F.F.F.F.G.G.G.G.H.H.H.H.J.J.J.J.J.K.K.K.K.K.L.L.L.L.L.L.`.`.`.'.`.`.`.`.`.`.`.`.`.`.L.L.L.L.L.K.K.K.K.K.K.J.J.J.J.H.H.H.H.H.G.G.G.F.F.F.F.F.F.S.; = * & +           .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X            % * - ; S.S.D.D.D.D.F.F.F.G.G.G.G.G.H.H.H.J.J.J.K.J.K.K.L.L.L.L.`.`.`.`.'.'.'.'.'.'.'.'.'.'.`.`.`.`.`.L.L.L.L.K.K.K.K.J.J.J.H.H.H.G.G.G.F.G.F.F.F.D.D.S.S.: ; - * & $   O         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X          o * = - : : : S.S.D.D.D.D.F.F.F.G.G.H.H.J.J.J.K.K.L.L.L.L.`.`.`.'.'.].'.].].].].[.[.[.[.].].].'.'.'.'.'.`.`.L.L.L.K.K.K.J.J.J.H.H.H.G.G.F.F.D.D.D.S.S.S.S.: ; = * % o @ #       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X            $ = - : S.S.D.D.D.F.G.G.G.H.H.H.J.J.K.K.K.L.L.L.`.`.'.'.].].].].[.[.[.[.{.{.{.{.{.{.{.{.{.{.[.[.[.].].].'.'.'.`.`.`.L.L.K.K.J.J.J.J.H.G.G.G.F.F.F.F.D.S.: ; - * # + = X       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X          . = - : S.D.F.F.F.G.G.G.H.H.J.K.K.K.K.L.L.`.`.'.'.'.].].].[.[.{.{.{.}.{.}.}.}.|.|.|.|.}.}.{.}.{.{.[.[.[.[.].].'.'.`.`.`.L.L.L.K.K.J.J.J.H.H.G.G.F.F.D.D.S.; = & o % *       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X          @ - : S.F.F.G.G.G.H.J.J.J.J.K.K.L.L.`.`.'.'.].].].[.[.[.{.{.{.}.}.|.|.|.|.|. X X X|.|.|.|.}.}.}.}.{.{.[.[.[.].].].'.`.`.`.L.L.K.K.J.J.J.H.H.G.G.F.F.D.: - = @ # -         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X          . * ; S.D.F.G.H.H.H.H.J.J.K.K.L.L.L.`.`.'.'.].].].[.[.{.{.}.}.}.}.|.|.|. X X X X X X X|.|.|.|.}.}.{.{.{.{.[.].].].'.'.'.`.L.L.L.K.K.K.J.J.H.H.G.G.F.D.: - & O * $       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X          O - : D.F.G.G.H.H.J.J.K.K.L.L.`.`.`.'.'.'.].].[.[.{.{.{.}.}.}.}.|. X X X X X X X X X|. X|.|.}.}.}.{.{.{.[.[.[.].'.'.'.`.`.L.L.K.K.J.J.J.H.H.G.G.F.: ; = + $ -       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X            & ; S.D.G.G.H.H.J.J.K.K.K.K.L.`.`.`.'.].].].].[.{.{.{.}.}.|.|.|.|.|. X X X X X X X X|.|.}.|.}.}.}.{.[.[.[.].].'.'.'.`.`.L.L.K.K.K.J.J.H.H.G.F.D.: - % + = +       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X          X - : D.F.G.H.H.J.J.J.K.K.L.L.`.`.'.'.'.].].].[.{.{.}.{.}.}.|.|.|. X X X X X X X X X|.|.|.}.}.}.{.{.{.[.[.].].].'.'.`.`.L.L.K.K.K.J.J.H.H.G.F.S.; = O % *       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X          $ ; S.F.G.H.H.J.J.K.K.L.L.L.`.`.`.'.].].[.[.[.{.{.{.}.}.}.|.|. X|. X X X X X X X|.|.|.|.}.}.}.{.{.[.[.[.].].'.'.'.`.`.L.L.K.K.J.J.J.H.G.F.D.: - # @ - .       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X          . = : D.G.G.H.J.J.J.K.K.L.L.`.`.'.'.'.].].[.[.[.{.{.}.}.}.|.|.|. X X X X X X X X|. X|.|.|.}.}.}.{.{.[.[.].].'.'.`.`.`.L.L.K.K.K.J.J.H.G.F.S.; = O & %       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X          @ : S.F.G.H.J.J.K.K.L.L.L.`.`.'.'.'.].[.[.[.{.{.{.}.}.}.|.|.|. X X X X X X X X X|.|.}.}.}.{.{.{.[.[.[.].].].'.'.`.`.L.L.K.K.J.J.J.H.G.D.S.- @ # -       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X            * : D.G.H.J.J.K.K.K.L.L.`.`.`.'.'.].].[.[.{.{.{.}.}.}.|.|.|.|. X X X X X X X X|.|.}.}.}.}.{.{.[.[.[.].].'.'.'.'.`.`.L.L.K.K.J.J.H.F.S.; * + = @       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X          o : D.F.G.H.J.K.K.K.L.L.`.`.'.'.'.].].[.[.{.{.{.}.}.}.|.|.|. X X X X X X X X X|.|.|.|.}.}.{.{.{.[.[.[.].'.'.`.`.L.L.L.K.K.J.J.H.G.F.: ; + $ =       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X            & : F.G.H.J.K.K.K.L.L.`.`.'.'.].].].[.[.{.{.{.}.}.}.|.|.|. X X X X X X X X X|.|.|.|.}.}.{.{.{.[.].].].].'.'.`.`.L.L.K.K.J.J.H.G.S.; % @ = X       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X          . ; S.G.H.J.J.K.L.L.L.`.`.`.'.'.].].[.[.{.{.{.}.}.}.|.|.|.|. X X X X X X X X|.|.|.}.}.}.{.{.{.[.[.].].'.'.`.`.`.L.L.L.K.K.J.G.F.S.- O & &       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          # : F.G.J.K.K.K.L.L.`.'.'.'.'.].].[.[.{.{.}.}.}.}.}.|.|. X X X X X X X X X|.|.}.}.}.}.{.{.[.[.[.[.].'.'.'.`.`.L.L.K.K.J.J.G.D.; # # -         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          . = D.F.H.J.K.K.L.L.L.`.'.'.'.].].[.[.{.{.{.{.}.|.|.|. X X X X X X X X X X|.|.|.}.}.}.}.{.{.[.[.].].].'.'.`.`.L.L.K.K.J.H.F.S.= O * $       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          + : F.G.J.K.K.L.L.L.`.`.'.'.].].[.[.{.{.{.{.}.}.|.|.|. X X X X X X X X|.|.|.|.}.}.}.{.{.{.[.[.[.].'.'.'.`.`.L.L.K.K.J.G.D.; + $ =       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X            * D.G.J.K.K.L.L.`.'.'.'.'.].].[.[.[.{.{.}.}.}.|.|.|.|. X X X X X X X|. X|.}.}.}.}.{.{.[.[.[.].].'.'.`.`.`.`.L.K.K.H.F.S.* + = O       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          X : F.H.J.K.L.`.`.`.`.'.'.].].[.[.{.{.}.}.}.}.}.|.|. X X X X X X X X X|.|.|.|.}.}.{.{.{.[.[.].].].'.'.`.`.L.L.K.J.G.D.; O & *       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          $ S.G.J.K.K.L.L.`.'.'.].].].[.[.{.{.{.}.}.|.|.|. X X X X X X X X X X|.|.|.}.}.}.{.{.[.[.[.].].'.'.`.`.`.L.K.K.J.G.S.% @ -         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          . : F.H.K.K.L.`.`.'.'.'.].].[.[.{.{.{.}.}.}.|.|.|. X X X X X X X X X|.|.|.}.}.}.{.{.[.[.[.].].].'.'.`.`.L.K.K.H.D.; O * %       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          @ D.G.J.K.L.`.`.`.'.'.].].[.[.[.{.}.}.}.}.|.|.|.|. X X X X X X X X|.|.}.}.}.}.}.{.{.[.[.].].'.'.'.`.`.L.K.J.G.S.@ $ =       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X            - F.H.K.L.`.`.'.'.].].].[.{.{.{.{.}.}.}.|.|.|. X X X X X X X X|.|.|.|.|.}.{.{.{.[.[.[.].].].'.`.`.L.L.K.H.D.= + = +       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          o D.G.J.L.L.`.'.'.'.].].[.[.[.{.{.}.}.}.|.|.|. X X X X X X X X|. X|.|.}.}.}.}.{.{.[.[.].].'.'.'.`.`.L.J.G.S.+ % =       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          & F.J.K.L.`.`.'.].].].[.[.{.{.{.}.}.|.|.|.|. X X X X X X X X X|.|.|.}.}.}.{.{.[.[.[.].].].'.`.`.L.K.H.F.& @ = .       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          . S.G.K.L.`.`.'.'.].].[.[.{.{.{.}.}.}.|.|.|.|. X X X X X X X X|.|.|.|.}.}.{.{.{.[.[.].].'.'.'.`.L.K.G.S.O * &       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          $ F.H.K.`.`.'.'.].].[.[.{.{.{.}.}.}.|.|.|. X X X X X X X X X|.|.}.}.}.}.{.{.{.[.[.].].].'.'.`.K.J.D.$ # -       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          . : G.K.L.`.'.].].].[.[.{.{.{.}.}.}.|.|.|. X X X X X X X X|.|.|.|.}.}.}.{.{.[.[.[.].].'.'.`.L.K.G.; + = @       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XP U .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          O G.J.L.`.'.'.].].].[.{.{.}.}.}.|.|.|.|. X X X X X X X X|. X|.|.}.}.}.{.{.[.[.[.].].].'.`.L.J.F.@ % =       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X7.C .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X            * G.K.`.`.'.].].[.[.{.{.{.{.}.}.}.|.|.|. X X X X X X X X|.|.}.|.}.}.}.{.{.[.[.].].'.'.`.K.G.* @ - X       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X' h.m U .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          . F.J.L.`.'.].].[.[.{.{.{.}.}.|.|.|.|. X X X X X X X X X|.|.}.}.}.}.{.{.{.[.[.].].'.'.L.J.D.O * &       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X! C.m C .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          $ H.K.`.'.].].[.[.[.{.{.}.}.}.|.|.|.|. X X X X X X X X|.|.|.}.}.}.{.{.{.[.[.].].'.`.K.G.% # -         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X2.^.| m Y .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X            S.J.L.`.].].[.[.{.{.{.}.}.}.}.|. X X X X X X X X X|.|.|.|.|.}.}.}.{.[.[.[.[.].'.L.J.S.O * #       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.Xq./.s.l A ` .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          + H.K.`.'.].[.[.[.{.{.}.}.|.|.|.|. X X X X X X X X X|.|.|.}.}.{.{.{.{.[.].].'.'.K.H.@ % =       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X5._.P.v a .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X            - J.L.'.].[.[.{.{.{.}.}.}.|.|.|.|. X X X X X X X X|.|.}.}.}.}.{.{.{.[.[.].'.`.J.- + = o       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X8.~.~.v i J .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          X H.K.`.'.].[.{.{.{.}.}.}.|.|.|. X X X X X X X X X|.|.|.|.}.}.{.{.[.[.[.].'.L.G.+ & *       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X6.T._.B p t 4..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          % J.L.'.].[.[.{.}.}.}.|.|.|.|.|. X X X X X X X X|.|.|.|.}.}.{.{.{.[.].'.`.K.& @ -         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XE 1.P._.i.a 9 J .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          . F.L.`.].[.{.{.{.}.}.}.}.|.|. X X X X X X X X X|.|.|.}.}.}.{.{.{.[.].'.L.F.O * $       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X1.B._.V.l 0 y f..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          @ J.L.'.[.[.{.{.{.}.|.|.|.|. X X X X X X X X X|.|.}.}.}.}.}.{.[.[.].`.K.$ $ -       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X:.x.(.!.z r 9 ...X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X            : L.`.].[.{.{.}.}.}.|.|.|. X X X X X X X X X|.|.|.}.}.}.{.{.{.[.].L.: + = O       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XQ :.z.~.(.m r 1 d k..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          o J.`.'.[.{.{.}.}.}.|.|.|.|. X X X X X X X|.|.|.|.}.}.}.{.{.[.].`.K.+ & *       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XQ &.s.!._.F p 4 5 d.Z..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          = K.'.].[.{.}.}.}.|.|. X X X X X X X X X X X|.}.}.}.}.{.{.[.].L.= @ =         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XQ &.s.E.).r.a 9 , } k.Z..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          . H.`.'.[.{.{.}.}.|.|.|.|. X X X X X X X|.|.|.|.|.}.}.{.{.[.'.H.O * %       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X_ &.s.E._.c.l r , 3 k.A..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          $ L.'.[.{.{.}.}.|.|.|. X X X X X X X X X|.|.|.}.}.}.{.[.].L.% # -         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X) &.z.E._.I.v i 2 , $.Z..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X            D.`.].[.{.}.}.}.|. X X X X X X X X X X|.|.|.}.}.}.{.[.'.F.O = @       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X~ =.x.E._.E.m p 8 , q M.U..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          + K.'.[.{.}.}.|.|.|. X X X X X X X X|.|.|.|.}.}.}.{.].L.@ % =       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X^ e.x.!.).!.F k 0 1 , w.Z.W..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X            ; `.'.[.{.}.|.|.|.|. X X X X X X X X|.|.}.|.}.{.[.'.; @ - .       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X;.e.c.!._.!.&.l u 4 , s Z.U..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          X K.'.[.{.}.|.|. X X X X X X X X X X|.|.|.}.}.{.].K.+ & &       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XE >.e.c.~.).!.i.v p 9 , 3 r.A..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          & `.].{.}.}.|.|.|. X X X X X X X X X|.|.|.}.[.'.* # -         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X:.i.B.~._.!.s.m k r 4 , h M.U..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X            G.'.[.{.}.|.|. X X X X X X X X|.|.|.}.}.{.].J.O = #       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.XE :.i.P.~._.!.z.m l i 8 , 3 b.U.Y..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          @ `.].{.}.|.|. X X X X X X X X X|.|.|.}.[.'.$ % =       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.XW :.a.P.(.).E.z.F z k 0 1 , @.A.Y..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X            S.'.[.{.}.|. X X X X X X X X X|.|.}.}.[.D.+ = o       .X.X.X.X.X.X.X.X.X.X.X.X.X.XQ &.a.I.(._.R.s.G m k i 4 , < Z.U..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          o L.].{.}.|.|. X X X X X X X|. X|.}.{.'.+ & *       .X.X.X.X.X.X.X.X.X.X.X.X.X.X_ &.s.I.).).T.s.| m l k r 2 , @.A.Y..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          = '.[.}.}.|. X X X X X X X X|.}.}.[.- # -         .X.X.X.X.X.X.X.X.X.X.X.X.X~ &.z.R._.).I.a. .m m l p 0 2 w Z.U..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          . J.].{.}.|. X X X X X X X X|.}.{.K.+ * $       .X.X.X.X.X.X.X.X.X.X.X.X.X/ =.z.E.).(.P.p.| F m m l p 0 0 e.A.W..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          $ '.[.}.|.|. X X X X X X|.|.}.[.% $ =         .X.X.X.X.X.X.X.X.X.X.X.X^ =.x.!._.(.P.i.| B m m z l k u [ M.U.U..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X            F.].{.}.|. X X X X X X X|.{.H.O = +       .X.X.X.X.X.X.X.X.X.X.X.X>.u.c.!.).(.V.u.G B m m m z z k x h.Z.M.n.k.f.0..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          O '.[.}.|. X X X X X X|.}.].+ % *       .X.X.X.X.X.X.X.X.X.X.XE ;.e.B.~.).~.c.u.G B m m m m m z z z F n F B B V M M M M N M M M M M M m v v m T .X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          ; ].{.}. X X X X X X|.{.: o * O       .X.X.X.X.X.X.X.X.X.XE ;.i.B.~.).~.c.e.G B m m m m m m m m m z v m M B G G G G G F G G H m m l a i p ` .X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X    .     . `.[.}.|. X X X X X|.].. O &       .X.X.X.X.X.X.X.X.X.X.X..i.V.~._.!.x.=.F B m m m m m m m m B F  .=.a.s.z.z.x.z.x.x.z.z.i.G v k i r p ] .X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X        . F.].{.}.|. X X X X}.H.. + @       .X.X.X.X.X.X.X.X.XQ :.i.P.(.).!.z.=.G m m m m m m m m m B G &.u.z.c.c.P.I.P.I.P.P.x.e.m z i r 4 y 3..X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          G.].[.}.|. X X X|.}.J.  + .     .X.X.X.X.X.X.X.X.XW X.a.I.(.).E.z.&.F m m m m m m m m m m B F |  .=.i.a.a.a.s.a.e.| m l a r 4 , q j.j..X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          G.'.[.{.|. X X X X{.J.  O       .X.X.X.X.X.X.X.XW &.s.I.).).T.z. .F m m m m m m m m m m m m m B B B B B F B B m m l a u 8 , > s l.M..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          G.`.].{.}. X X X|.{.J.  o       .X.X.X.X.X.X.X/ e.x.E.).!.c...m v z m m m z m m m m m m m m m m m m m m m m v v l k r 4 , > s M.A..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X    .     G.`.'.{.}. X X X|.}.J.  o       .X.X.X.X.X.X,.s.B.T.P.i.m z l l k k k k k l l l z m m m m m m m m m m m m m z l a r 4 , > f Z.A..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X    X     G.`.'.[.}.|. X X|.{.H.  O       .X.X.X.XU ,.i.i.&.m z k p i i u i u u i i i p k l l m m m m m m m m m m m v l a r 4 , > j Z.U.Q..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . X     G.`.'.[.}.|. X X|.{.J.  O       .X.X.X.XP m m v k i r 0 9 4 4 4 4 4 8 8 8 9 0 i k l m m m m m m m m m m z l a r 2 , > j A.U.W..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . X     G.`.'.[.{.|. X X X}.H.  O       .X.Xc C z k a r 9 4 1 , , , , , , , , , 1 2 8 u i k m m F B m m m m m z l p r 1 > > O.A.U..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . X     G.`.'.[.{.|. X X|.{.J.  O       .Xb C C C V B n S D [ { { o.O.O.O.O.O.O.@.$.*.=.-.F v F G F m m m m z l p 0 2 , > t.A.U..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X    X     G.`.'.[.{.|. X X|.{.H.  O       .X.X.X.X.X.X.X.X.Xk.n.M.Z.Z.Z.A.Z.A.Z.Z.A.A.A.Z.l.v F =.&.F m m m v l p 0 1 , > w.A.U..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . X     G.`.'.[.{.|. X X|.{.J.  O       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XA.l.J m r.a.=.F m m v k i 0 2 > > y.A.U..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . X     G.`.'.[.}.|. X X|.{.J.  O       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.Xn.1.B =.c.z.=.m m z k i 0 1 > > h.A.Y..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X    X     G.L.'.[.}.|. X X|.{.J.  O       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X9.m  .c.I.x.| v v l i 9 1 > < y.A.Y..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . X     G.`.'.[.{.|. X X|.{.J.  O       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XL F s.T.T.r.m z k i 9 1 , > b.U.Y..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . X     G.`.'.[.}.|. X X X{.J.  O       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X' m &.P.E.x.B z k i 8 , > 6 b.A.Y..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . X     G.`.'.[.{.|. X X|.{.H.  O       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XK F z.T.P.| v k u 9 1 > 7 v.A.Y..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . X     G.`.'.[.}.|.|. X|.{.J.  O       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XT m =.P.R.u.v k u 8 , > 3 A.A.W..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . X     G.`.'.[.{.|. X X|.{.H.  O       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XR K G x.E.x.m k u 8 , > e m.A.W..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . X     G.`.'.[.}.|. X X X{.J.  O       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XI B i.I.P.m k u 4 , > e M.U.W..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . X     G.`.'.[.{.|. X X|.{.J.  O       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XR M ..c.R. .l u 4 , > s Z.A.W..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . X     G.`.'.[.{.|. X X|.{.J.  O       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XK H s.R.p.l i 4 , > g M.A.Q..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X    X     G.`.'.[.}.|. X X|.{.H.  O       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XE m &.P.c.v i 4 , > g A.U.W..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . X     G.`.'.[.{.|. X X|.{.J.  O       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XK F x.V.m i 4 , > g A.U..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . X     G.`.'.[.}.|. X X|.{.J.  O       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XE m e.V.B a 8 , > o.M.U..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X    X     G.`.'.[.}.|. X X|.{.H.  O       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XK | x.=.k 9 , , j Z.U.W..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . X     G.L.'.[.{.|. X X|.}.J.  O       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.XR H s.s.l 0 , > +.Z.U..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . X     G.`.'.[.}.|. X X|.{.J.  O       .X.X.X.X.X.X.X.X.X.X.X.X.X.XE L i.x.z r 1 > t.Z.U..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . X     G.`.'.[.{.|. X X|.{.H.  O       .X.X.X.X.X.X.X.X.X.X.X.X.X.XY =.c.m i 2 , #.M.U..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . X     G.`.'.[.{.|. X X|.{.J.  O       .X.X.X.X.X.X.X.X.X.X.X.X.XE :.z.G a 4 , -.M.U..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . X     G.`.'.[.}.|. X X X{.J.  O       .X.X.X.X.X.X.X.X.X.X.X.X.X( y...a 9 , 7.n.U..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . o     G.`.'.].{.|.|. X|.{.J.  +       .X.X.X.X.X.X.X.X.X.X.X.X.X=.&.l r 5 X.k..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . O     G.`.'.[.}.|. X X|.{.J.  #       .X.X.X.X.X.X.X.X.X.X.X.X^ ..z i 4 6.k..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . #     G.`.'.[.{.|. X X|.{.H.. &       .X.X.X.X.X.X.X.X.X.X.X.X..v i r 8.j..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X    $     G.L.'.].{.}.|. X}.{.J.@ =       .X.X.X.X.X.X.X.X.X.XE / v a p ,.g..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X    # X   F.K.L.`.].[.[.{.[.'.J.- &       .X.X.X.X.X.X.X.X.X.X! N l a 2..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X      +   @ # $ $ % % & = : S.S.; .       .X.X.X.X.X.X.X.X.XE K z l ' .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X              X O @ $ & - : S.- o         .X.X.X.X.X.X.X.X.XT v v _ .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X                o @ $ $ $ @ .             .X.X.X.X.X.X.X.X.XC v .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X                                          .X.X.X.X.X.X.X.XI C Q .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X                              .X.X.X.X.X.X.X.X.X.X.XK .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X                            .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X"
};
