/*
 * Embroidermodder 2.
 *
 * Copyright 2011-2024 The Embroidermodder Team
 * Embroidermodder 2 is Open Source Software, see LICENSE.md for licensing terms.
 *
 * Read the reference manual (https://www.libembroidery.org/downloads/emrm.pdf)
 * for advice on altering this file.
 */
/* XPM */
static char *region[] = {
/* columns rows colors chars-per-pixel */
"128 128 217 2 ",
"   c black",
".  c #010101",
"X  c #020202",
"o  c gray1",
"O  c #040404",
"+  c gray2",
"@  c #070707",
"#  c gray3",
"$  c #090909",
"%  c gray4",
"&  c #0B0B0B",
"*  c #0C0C0C",
"=  c gray5",
"-  c #0E0E0E",
";  c gray6",
":  c #101010",
">  c #111111",
",  c gray7",
"<  c #131313",
"1  c gray8",
"2  c #151515",
"3  c #161616",
"4  c gray9",
"5  c #181818",
"6  c #191919",
"7  c gray10",
"8  c #1B1B1B",
"9  c gray11",
"0  c #1D1D1D",
"q  c #1E1E1E",
"w  c gray12",
"e  c #202020",
"r  c gray13",
"t  c #222222",
"y  c #232323",
"u  c gray14",
"i  c #252525",
"p  c gray15",
"a  c #272727",
"s  c #282828",
"d  c gray16",
"f  c #2A2A2A",
"g  c gray17",
"h  c #2C2C2C",
"j  c #2D2D2D",
"k  c gray18",
"l  c #2F2F2F",
"z  c gray19",
"x  c #313131",
"c  c #323232",
"v  c gray20",
"b  c #343434",
"n  c #353535",
"m  c gray21",
"M  c #373737",
"N  c gray22",
"B  c #393939",
"V  c #3A3A3A",
"C  c #3C3C3C",
"Z  c gray24",
"A  c #3F3F3F",
"S  c gray25",
"D  c #414141",
"F  c gray26",
"G  c #434343",
"H  c #444444",
"J  c gray27",
"K  c #464646",
"L  c gray28",
"P  c #484848",
"I  c #494949",
"U  c gray29",
"Y  c #4C4C4C",
"T  c gray30",
"R  c #4E4E4E",
"E  c gray31",
"W  c #505050",
"Q  c #535353",
"!  c gray33",
"~  c #555555",
"^  c #565656",
"/  c gray34",
"(  c #585858",
")  c gray35",
"_  c #5A5A5A",
"`  c gray36",
"'  c #5D5D5D",
"]  c #5F5F5F",
"[  c #606060",
"{  c gray38",
"}  c #626262",
"|  c #646464",
" . c #656565",
".. c gray40",
"X. c #676767",
"o. c #686868",
"O. c DimGray",
"+. c gray42",
"@. c #6C6C6C",
"#. c gray43",
"$. c #6F6F6F",
"%. c #717171",
"&. c #727272",
"*. c gray45",
"=. c #777777",
"-. c gray47",
";. c #797979",
":. c gray48",
">. c #7B7B7B",
",. c #7C7C7C",
"<. c #7E7E7E",
"1. c gray50",
"2. c #808080",
"3. c #818181",
"4. c gray51",
"5. c #838383",
"6. c #848484",
"7. c gray52",
"8. c gray53",
"9. c #898989",
"0. c gray54",
"q. c #8E8E8E",
"w. c gray56",
"e. c #929292",
"r. c gray58",
"t. c gray59",
"y. c #979797",
"u. c #989898",
"i. c gray60",
"p. c gray61",
"a. c gray62",
"s. c #9F9F9F",
"d. c #A0A0A0",
"f. c gray63",
"g. c #A2A2A2",
"h. c gray64",
"j. c #A4A4A4",
"k. c #A5A5A5",
"l. c gray66",
"z. c #A9A9A9",
"x. c #AAAAAA",
"c. c gray67",
"v. c gray69",
"b. c #B2B2B2",
"n. c #B4B4B4",
"m. c #B6B6B6",
"M. c gray72",
"N. c #B9B9B9",
"B. c gray73",
"V. c #BBBBBB",
"C. c gray74",
"Z. c gray75",
"A. c #C0C0C0",
"S. c #C1C1C1",
"D. c gray76",
"F. c #C3C3C3",
"G. c gray77",
"H. c #C5C5C5",
"J. c #C6C6C6",
"K. c gray78",
"L. c #C8C8C8",
"P. c gray79",
"I. c #CACACA",
"U. c #CBCBCB",
"Y. c gray80",
"T. c #CDCDCD",
"R. c #CECECE",
"E. c gray81",
"W. c #D0D0D0",
"Q. c gray82",
"!. c #D2D2D2",
"~. c LightGray",
"^. c gray83",
"/. c #D5D5D5",
"(. c gray84",
"). c #D7D7D7",
"_. c #D8D8D8",
"`. c gray85",
"'. c #DADADA",
"]. c gray86",
"[. c gainsboro",
"{. c #DDDDDD",
"}. c gray87",
"|. c #DFDFDF",
" X c gray88",
".X c #E1E1E1",
"XX c #E2E2E2",
"oX c gray89",
"OX c #E4E4E4",
"+X c gray90",
"@X c #E6E6E6",
"#X c #E7E7E7",
"$X c gray91",
"%X c #E9E9E9",
"&X c #EAEAEA",
"*X c gray92",
"=X c #ECECEC",
"-X c gray93",
";X c #EEEEEE",
":X c #EFEFEF",
">X c gray94",
",X c #F1F1F1",
"<X c gray95",
"1X c #F3F3F3",
"2X c #F4F4F4",
"3X c gray96",
"4X c #F6F6F6",
"5X c gray97",
"6X c #F8F8F8",
"7X c #F9F9F9",
"8X c gray98",
"9X c #FBFBFB",
"0X c gray99",
"qX c #FDFDFD",
"wX c #FEFEFE",
"eX c white",
"rX c None",
/* pixels */
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX                                                                                                          rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX                                                                                                                rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX    u K O     % 7 d l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l z n F R ~ A           rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX    @.@.                                                                                                7 n         rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX    l                                                                                                                   rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX        w z.j.f.s.s.f.f.f.f.f.j.f.f.f.j.f.j.f.f.j.f.f.f.j.f.f.f.j.f.f.f.j.f.f.f.f.j.f.f.j.f.j.f.f.f.f.,.;               rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX        u R.H.F.Z.F.F.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.H.b.z               rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX        u H.Z.Z.Z.Z.F.H.H.L.H.L.L.L.H.L.L.H.L.L.H.L.L.L.L.H.L.L.L.H.L.L.H.L.L.L.H.L.L.H.L.H.L.H.L.L.L.L.H.H._                 rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX        u H.Z.V.Z.F.L.R.R.R.W.R.R.W.R.W.R.R.R.R.R.R.R.R.R.W.R.W.R.R.R.R.R.R.R.R.R.W.R.R.W.R.R.R.W.R.R.W.W.R.R.9.%               rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  3     u H.F.Z.H.R.W._.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}._._.W.b.r               rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.F.H.L.^. X+X%X%X%X%X%X%X%X%X%X-X%X%X-X%X%X%X%X%X%X%X%X-X%X%X-X%X%X%X%X%X-X%X%X%X%X%X-X%X%X%X%X%X+X X}.R.U       O         rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.H.W.}.+X-X1X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X2X1X-X+X X^.:.O               rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.W. X-X2X6XeX6X6XeX6X6X6XeX6X6XeX6X6XeX6X6X6XeX6X6XeX6XeX6X6XeX6X6X6XeX6X6XeXeX6X6X6XeX6X6X6X6X2X1X-X+X_.f.7               rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^. X-X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6XeXeXeXeXeXeXeXeX6X6X2X-X+X}.F.n               rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^.+X-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X6X2X1X%X X^.+.                rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^.+X1X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X6X2X1X%X X_.e.;               rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u H.L.L.^. X-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X6X2X-X+X}.V.d               rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     d L.H.L.^.+X-X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X2X-X+X XR.W                 rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^. X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X2X1X%X X_.2.O               rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.H.L.^.+X1X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX2X2X-X+X}.c.7               rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^.+X-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X6X2X-X+X}.H.A               rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.L.L.^. X1X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6XeX2X1X%X X_.+.                rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^.+X-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X6X1X-X X_.i.<               rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.H.L.^.+X-X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X6X6X2X-X+X}.V.l               rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^.+X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X6X2X1X+X XW.~                 rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.H.L.^.+X1X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X2X1X%X X_.9.%               rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^. X-X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X6X6X1X-X+X}.b.w               rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.H.L.^.+X-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X2X-X+X}.L.F               rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^.+X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX-Xj...n n       d z ' e. XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X6X2X1X%X X_.*.                rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u H.H.L.^.+X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6Xt.K                           z ,.%X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X2X1X%X+X_.s.<               rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.H.L.^.+X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXf.w       n W U N d u z F K u         ; 2.-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X2X1X-X+X}.F.z               rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^. X-X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXL.z     r [ U                     O z         3 f.2X2X6XeX6XeXeXeXeXeXeXeXeXeXeXeXeXeX6X2X1X%X}.^.'                 rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.R.^. X-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXj.%   3 *.F                               r         *.1X2X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X6X1X%X X}.q.%               rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.H.L.^.+X1X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX:.    _ @.              rXrXrXrXrX              3       F  X1X2X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X2X2X%X+X}.n.r       <         rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^.+X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX[     ,.n           rXrXrXrXrXrXrXrXrXrXrX          O       z }.-X2X6X6XeXeXeXeXeXeXeXeXeXeXeXeX6XeX2X2X-X+X}.R.U       w         rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^. X-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX:.    ,.          rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX                N  X-X2X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX2X1X%X X^.:.O     ;       rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.H.L.^.+X-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXn.    2.          rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX              +. X-X1X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X6X2X-X+X_.j.7             rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.L.L.^.+X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX-X<   *.%       rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX              z. X%X1X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X6X6X1X-X+X}.H.n           rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^. X1X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX+.  F R       rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX            u ^. X-X2X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X2X1X+X X^.r         rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.H.L.^.+X-X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX^.    :.      rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX            6._. X-X2X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X2X1X-X XR         rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^.+X-X2X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX[   ~         rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX    O     r W.}.+X1X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X6X6X2X-XW   %       rXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.W.+X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX-X%   @.      rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX            t.W.}.%X2X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X6X2X~   u       rXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u H.H.R.^.+X1X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXs.  z ;       rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX    %     R R.^. X-X2X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X~   N       rXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     d L.H.L.^. X-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX~   _       rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX          3 L.W.}.%X2X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^.+X-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX<   U       rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX          z.R.^.+X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.H.L.^.+X1X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX+X    3     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX          6.L.W.}.%X2X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^. X-X2X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXZ.  7       rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX          ..H.R._.+X1X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^.+X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXz.  d       rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX  7     ~ H.L.^.+X-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.H.L.^. X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXs.  d       rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX  n     R H.L.W.}.-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.R.^.+X1X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXs.  d       rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX  ~     W H.L.R.}.%X2X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^. X-X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXz.  3       rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX  +.    _ H.H.R.}.%X1X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.H.L.^.+X-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXF.    %     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX    '     @.L.H.R._.+X1X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^.+X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX%X    n     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX  N l     q.H.L.R._.+X1X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.H.L.^.+X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX7   N       rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX  *.      b.L.H.W._.+X1X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^.+X-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_           rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX    :.    7 R.H.L.R._.+X2X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^. X1X2X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXf.    r       rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX  U 7     ~ L.H.L.R._.%X1X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.R.^. X1X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX1X;           rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX    ,.      j.H.H.L.W.}.%X2X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX~   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^.+X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X@.    3       rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX  R u     z R.H.H.L.W. X-X2X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^.+X-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX+X<           rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX    ,.      f.H.F.F.L.^.+X-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^. X-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X2.    ;       rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX    ,.      F R.H.F.H.R._.+X1X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^. X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X-X7     <       rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX  +.l     O b.L.F.F.H.W.}.%X2X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.H.L.^.+X1X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX2XV.O     %         rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX    [ ~       :.R.H.F.H.L._.+X1X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.R.^.+X-X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X2X2.      %         rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX    *.R       R W.H.F.F.H.W.}.%X1X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.H.L.^. X-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X1X@.                  rXrXrXrXrXrXrXrXrXrXrXrX    w ,.3       A R.L.F.F.F.L.^.+X-X2X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u H.L.L.^. X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X2X-X@.        O             rXrXrXrXrXrX        @.@.        F R.L.F.F.H.L.W. X%X2X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     d L.H.L.^.+X-X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X6X2X%X9.%                                 z *...          +.W.R.H.F.F.L.W.}.+X1X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^. X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX2X-X%XV.N                     7 n _ @.+.r           u f.W.R.H.F.H.H.W._.+X-X2X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.H.L.^.+X1X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X2X-X+X_.i.u                                   3 6.R.R.H.F.F.H.L.R._. X-X2X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^.+X1X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX2X2X-X+X_.W.9.N                           l :.L.R.L.H.F.H.H.L.W._. X-X2X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.L.L.^. X-X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X2X-X+X}.^.R.V.6.~ n u O     u z ~ 6.n.R.L.L.H.F.F.H.H.R.W._.+X%X2X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^.+X-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X6X1X-X+X}.^.R.L.H.H.H.H.F.H.H.L.L.L.H.H.H.H.F.H.H.L.R.^.}.+X-X2X6XeX6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.H.L.^.+X-X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X6X1X%X+X}.^.R.R.L.H.H.H.H.L.H.H.H.H.H.L.L.R.W.^.}. X%X-X2X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^.+X1X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X6X1X1X%X+X}.^.^.W.R.R.L.R.L.R.L.R.R.W.W._.}. X%X-X2X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.H.L.^.+X-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X6X2X1X-X%X+X X}._._.^.^.W.^.^.^._._. X+X%X-X1X2X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^. X-X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X6X2X2X1X-X%X+X+X+X X+X+X+X X%X%X-X1X1X2X2X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.H.L.^.+X-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6X2X2X1X1X1X-X-X-X-X-X1X1X1X2X2X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u H.H.L.^. X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX6XeX6X6X2X6X6X2X2X2X6X2X6X6X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.R.^.+X-X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w     u L.H.L.^. X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^.+X1X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^. X-X6X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   F     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  r     u L.H.L.^.+X-X2XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   K     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  u     u H.H.R.^.+X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   ~     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  w w   u L.H.L.^. X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_   '     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX  % R   u L.H.L.^.+X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX~ U U     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX    *.  u H.H.L.^. X-X6XeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeXeX_ :.%     rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX    _ % < R W W ~ _ [ [ ........[ ............................[ ..........................[ ..............................................................................................[ U ,.      rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX      <                                                                                                                                                                                 A *.2.%       rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrX                3 N F K F K K K F K K F K K F K F K K K F K K F K K F K K F K F K F K F K F K F K F F K F K F K F K K F K K F K F K F K F K F K F K K F K K F K F K F K K F K F K U ' [ ~ 7           rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX                                                                                                                                                                                                    rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX                                                                                                                                                                                                    rXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX                                                                                                                                                                                            rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX",
"rXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrXrX"
};
