/*
 * Embroidermodder 2.
 *
 * Copyright 2011-2024 The Embroidermodder Team
 * Embroidermodder 2 is Open Source Software, see LICENSE.md for licensing terms.
 *
 * Read the reference manual (https://www.libembroidery.org/downloads/emrm.pdf)
 * for advice on altering this file.
 */
/* XPM */
static char *sketch[] = {
/* columns rows colors chars-per-pixel */
"128 128 185 2 ",
"   c #000000",
".  c #0B0000",
"X  c #0C0C00",
"o  c #0B0B0B",
"O  c #130000",
"+  c #1B0000",
"@  c #140E06",
"#  c #1B1C01",
"$  c #161306",
"%  c #121212",
"&  c #1C1C1C",
"*  c #1B1C10",
"=  c #0F1000",
"-  c #240000",
";  c #2B0000",
":  c #340000",
">  c #3C0000",
",  c #291B0C",
"<  c #222400",
"1  c #292B00",
"2  c #363800",
"3  c #2C2210",
"4  c #232323",
"5  c #2B2B2B",
"6  c #343434",
"7  c #3C3C3C",
"8  c #450000",
"9  c #4B0000",
"0  c #550000",
"q  c #5C0000",
"w  c #630000",
"e  c #6C0000",
"r  c #730000",
"t  c #7D0000",
"y  c #611A1A",
"u  c #442E14",
"i  c #4A3217",
"p  c #553B18",
"a  c #793434",
"s  c #3D4100",
"d  c #434501",
"f  c #4D5101",
"g  c #555802",
"h  c #68491C",
"j  c #6C501C",
"k  c #785D1B",
"l  c #5C6100",
"z  c #656B03",
"x  c #6E7500",
"c  c #757C00",
"v  c #76780D",
"b  c #79601B",
"n  c #6B4721",
"m  c #744D24",
"M  c #794E25",
"N  c #745321",
"B  c #7B5325",
"V  c #7E5626",
"C  c #444444",
"Z  c #4C4C4C",
"A  c #484747",
"S  c #535353",
"D  c gray36",
"F  c #646464",
"G  c #6B6B6B",
"H  c #737373",
"J  c #7C7C7C",
"K  c #800000",
"L  c #850C0C",
"P  c #891313",
"I  c #8C1A1A",
"U  c #922424",
"Y  c #942929",
"T  c #9C3939",
"R  c #882A2A",
"E  c #836B18",
"W  c #857613",
"Q  c #927A17",
"!  c #80790C",
"~  c #815626",
"^  c #835B26",
"/  c #85552A",
"(  c #855B29",
")  c #8B5D2A",
"_  c #8A5D26",
"`  c #935F2E",
"'  c #8C632A",
"]  c #886326",
"[  c #93642C",
"{  c #99662E",
"}  c #956A2C",
"|  c #9C6B2D",
" . c #976F26",
".. c #9D6B30",
"X. c #986630",
"o. c #967225",
"O. c #A16E2F",
"+. c #A4732E",
"@. c #A9792E",
"#. c #A26C31",
"$. c #A86F35",
"%. c #A67232",
"&. c #AB7534",
"*. c #AD7A32",
"=. c #B37B35",
"-. c #B67937",
";. c #A24343",
":. c #A44D4D",
">. c #AA5454",
",. c #B36767",
"<. c #BE7D7D",
"1. c #B97575",
"2. c #7B8201",
"3. c #858804",
"4. c #928A0D",
"5. c #8B9400",
"6. c #8F9800",
"7. c #939B00",
"8. c #959606",
"9. c #9A8518",
"0. c #A59017",
"q. c #97A000",
"w. c #9BA400",
"e. c #9FA900",
"r. c #A3AC00",
"t. c #A9AB07",
"y. c #A7B100",
"u. c #AAB500",
"i. c #AEB900",
"p. c #B2BD00",
"a. c #B0B702",
"s. c #BA8236",
"d. c #B88236",
"f. c #C18936",
"g. c #B6C100",
"h. c #BAC500",
"j. c #BECA00",
"k. c #C2CD00",
"l. c #C5D100",
"z. c #C8D307",
"x. c #C9D40B",
"c. c #CAD513",
"v. c #CCD71C",
"b. c #CED823",
"n. c #CFD928",
"m. c #D0DA2D",
"M. c #D2DB35",
"N. c #D3DC3B",
"B. c #949676",
"V. c #D5DE43",
"C. c #D7DF4A",
"Z. c #D2DA53",
"A. c #D8E04F",
"S. c #D8E052",
"D. c #DAE25C",
"F. c #DCE463",
"G. c #DEE56C",
"H. c #DFE672",
"J. c #E1E779",
"K. c #E2E87E",
"L. c #E0E775",
"P. c #848484",
"I. c #8B8B8B",
"U. c #939393",
"Y. c #9B9B9B",
"T. c #ADADAD",
"R. c #A4A682",
"E. c #C48989",
"W. c #C99393",
"Q. c #D2A5A5",
"!. c #D6ADAD",
"~. c #DEBDBD",
"^. c #DAB4B4",
"/. c #E4E984",
"(. c #E5EB8B",
"). c #E6EC92",
"_. c #E8ED97",
"`. c #E9EE9C",
"'. c #EBEFA4",
"]. c #ECF0AC",
"[. c #EEF2B4",
"{. c #EFF3B9",
"}. c #F0F4BD",
"|. c #CACACA",
" X c None",
/* pixels */
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X                           X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X        o & 4 5 6 C Z C 5            X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X      S F 4                     5 5          X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    G P.        . O - - - O .           %          X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  5 I.4       . ; 9 w e r e e w 0 > - O       o        X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    D P.      O - q r L I I P t t t t t t e 9 - .            X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    H S     + > e :.<.W.E.E.<.1.,.>.;.U t t t t e 8 O     o        X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    J 5     - e ,.!.^.Q.<.,.;.T Y U U U Y Y I K t t r w -     o        X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    J &     - R Q.~.Q.1.;.U L L K K t K K K L L L K K t r r 8 .            X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    J 6     + T ~.~.E.:.U L K K K K K K K K K t K L K K K t t r 8 .            X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    D S     O a ~.~.<.T I L K K K K K K K t K K t K K K K K K t t r > .            X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  & J     O y ~.|.1.T P L K K K K K K K K K K K K K K K t K K K K t r 9 .          X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    P.    . 8 Q.~.<.T P K K K K K K K K K K K K K K K K K K K K K K K t r 0 O          X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  D %     ; 1.~.E.;.P K K K K K K K K K K K K K K K K K K K K K K K K t t r 8   %      X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    J     ; Y ~.Q.>.I K K K K K K K K K K K K K K K K K K K K K K K K K t t t e +          X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  H       r E.~.1.U L t K K K K K K K K K K K K K K K K K K K K K K K K K K t r >   5      X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  % H     : ;.~.W.T L K K K K K K K K K K K K K K K K K K K K K K K K K K K t t r q . o        X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    P.      e Q.^.,.I K K K K K K K K K K K K K K K K K K K K K K K K t K K K K t t e +          X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  % D     : >.~.E.T L K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K t r ;          X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    J     . r Q.!.>.I K K K K K K K K t K K K K K K K K K K K K K K K K K K K K K t t r >          X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    I.    8 :.^.<.T L K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K t t r 8          X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  7 F   . r :.1.T L K K K K K K K K K K K K K K K K K K K K t K K K K K K K K K K K t r 8          X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  H 4   9 t t K K K t K K K K K K K K K K K t K K K K K K K K K K K K K K K K K t t t r ; o        X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    I.    9 r r t t t t K K K K K K K K K K K K K K K K K K K K K K K K K K K K K K t r e + A        X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    6 I.      O 9 e r t t t t K K K K K K K K K K K K K K K K K K K K K K K K K K K t t r w O G        X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    o H o           + 0 r r r t t K t K K K K K K K K K K K K K K K K K K K K K K K t t r r 0   G      X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    o H                   - q r r t t t t K K K K K K K K K K K K K K K K K K K K K K t t r e > A 5      X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    J     %                   : e e r t t t K K K K K K K K K K K K K K K K K K K K K t t r q . P.       X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    S F     J G 4         o         > e r r t t t K K K K K K K K K K K K K K K K K K t t r e > o P.       X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    I.    A T.|.Y.D %         o       . 8 e r r t t K K K K K K K K K K K K K K K K K t r r q + G o      X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    I.  o I.Y.|.|.U.P.Z o                 O 0 r r r t t t K K K K K K K K K K K K K t t r e >   I.       X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  S H   6 I.I.I.Y.Y.U.U.U.C o                 + q e r t t t K t K K K K K K K K K t t r e 0 . F &        X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    P.S     & S H I.I.P.I.U.I.H 6                   ; w e r t t t t t K K K K K K t t t r w +   I.       X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    C G           4 F P.J P.U.U.P.P.J 4         o         : w r r t t t t K K K K K t t r e >   J        X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    C S                 6 G P.U.U.I.Y.Y.U.F &         o       . > e r r t t t K K K K t t r 0   4 J        X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  C G                       7 J P.P.U.Y.Y.I.U.F o         o       O 8 e r r t t t K t t r e +   I.       X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    P.    2 w.1         o       o C G J U.I.J U.U.P.C o                 + 0 e r t t t t r e 8   S 7        X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    J       r.l.F.R.*         o       % Z I.P.J I.Y.I.P.P.7                   - q r r r r e w O   I.       X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  6 S     g k.l.[.].S.v X                 & F J I.Y.U.U.Y.Y.J 5                   ; w e e e >   P.         X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    I.    X i.k.H.{.K.m.z.j.l X                 4 G I.P.P.U.Y.I.I.H 4         o         : w q   G S        X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  A 5     z k.c.[.'.A.c.l.l.k.r.d                   6 H H P.U.I.I.U.I.D %         &       . O D D        X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    I.    = h.l./.{.H.b.l.l.k.j.p.r.c <         o         7 J I.P.P.U.Y.P.P.D o       5 J S 6 S 5          X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  D       2.l.n.}.'.A.c.l.l.k.g.u.w.6.e.6.<         o       o S J P.U.Y.U.U.Y.I.A         H F            X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    P.    < j.l.).[.G.b.l.l.k.j.p.e.7.5.h.l.F.B.*         o       % S I.I.I.I.Y.Y.P.J 7                    X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  H       6.j.A.}._.N.x.l.l.k.g.y.q.5.r.j.l.].].Z.v X                 & G H J I.I.P.P.I.G 4            X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  o G     2 j.l.'.[.F.v.l.l.l.h.i.e.6.5.h.k.H.{./.n.z.g.g                   5 G I.I.P.P.I.P.C          X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    P.      e.l.D.{.(.M.x.l.l.j.g.y.7.5.u.k.c.[.'.A.c.z.l.l.e.s         o         7 P.P.I.I.J   C        X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  5 S     f j.l.].].D.c.l.l.k.h.i.e.6.6.j.l./.}.H.b.l.l.l.j.p.r.c #         o         C H J 6 H C        X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    I.    X u.k.G.{./.m.z.l.l.j.p.r.7.5.i.k.m.{.`.C.c.l.l.j.g.u.q.5.w.5.<         %       o C A I.         X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  C 6     z k.c.[.].S.c.z.l.k.h.u.w.6.7.j.l.).{.G.b.l.l.l.j.p.e.6.5.h.k.D.B.%       % G 7 % 6 D          X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    I.    = p.k.K.{.H.n.l.l.l.j.p.r.7.5.g.k.C.{._.N.x.l.l.k.g.y.q.5.y.j.l.].].Z.z X       J J 7            X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  D o     c k.b.{.`.C.c.l.l.k.g.y.w.6.w.j.l.`.[.F.v.l.l.k.h.i.e.6.5.h.l.H.}.K.n.l.p.g       &            X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    P.    # h.l.(.{.G.b.l.l.l.h.p.e.7.5.g.k.D.{.(.M.x.l.l.j.g.y.7.5.i.j.c.[.'.S.c.l.l.k.w.2              X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  G       5.k.N.{.`.V.x.l.l.k.g.u.q.5.r.k.l.].].D.v.l.l.j.h.u.w.6.6.j.l./.{.H.b.l.l.k.j.p.r.           X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    J     2 h.l.`.[.F.v.l.l.k.h.i.e.6.5.h.k.G.}./.m.l.l.l.h.g.y.7.5.p.j.n.{.'.C.c.l.l.k.g.u.f            X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    J       w.k.S.}.(.N.z.l.l.j.g.y.7.5.u.k.x.[.'.S.c.l.l.j.j.u.e.5.7.j.l.).{.G.b.l.l.k.j.i.e.  %          X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  & F     d j.l.].[.D.v.l.l.k.h.i.e.6.6.j.l.K.}.J.n.l.l.l.j.g.e.7.5.g.k.A.{._.N.z.l.l.k.g.y.2   H          X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    P.    X y.l.F.{./.M.z.l.l.j.g.y.7.5.i.j.b.{.`.C.c.l.l.l.h.u.w.5.e.h.l.'.[.F.v.l.l.k.h.i.6.  o G        X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  6 C     g j.z.].].S.c.l.l.j.h.u.w.6.7.j.l.(.}.L.b.l.l.l.h.i.e.7.5.h.l.D.}.(.N.z.l.l.j.g.y.<   J        X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    P.    X p.l.J.}.K.n.l.z.l.j.p.r.7.5.p.k.N.}._.V.x.l.l.j.h.y.q.5.e.j.l.].].D.v.l.l.l.h.i.c   4 D        X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  6 4     x k.v.[.'.A.c.l.l.k.h.u.w.5.q.j.l.`.[.F.v.l.l.l.h.i.e.7.5.h.l.G.{./.n.z.l.l.j.p.r.=   I.       X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    H     $ h.l.(.[.H.n.l.l.l.h.i.r.7.5.g.l.S.}.(.N.z.l.l.j.g.y.q.5.y.j.x.[.'.S.c.l.l.k.h.i.l   C 7        X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  & 4     5.k.M.{._.A.x.l.l.j.h.y.q.5.e.j.l.'.[.D.v.l.l.j.h.u.e.6.6.j.l.K.}.J.m.z.l.l.j.p.r.X   I.       X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  F     1 j.l._.[.G.v.l.l.l.h.i.e.7.5.h.l.F.}./.M.z.l.l.j.g.y.7.5.i.j.n.{.`.A.x.l.l.k.g.u.s   D o        X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    G     7.k.A.{.).N.x.l.l.j.g.y.q.5.y.j.z.[.].S.c.l.l.k.h.u.w.6.7.j.l.(.}.G.b.l.l.k.j.p.w.    P.       X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  & 5   s k.l.'.[.D.v.l.l.l.h.i.e.6.6.h.l.H.{./.n.z.l.l.j.p.r.7.5.g.j.N.{._.V.x.l.l.k.g.y.1   H          X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  S     x l.D.{./.M.x.l.l.j.g.y.7.5.i.k.v.[.'.A.c.l.l.k.g.y.w.5.q.j.l.`.[.F.v.l.l.k.h.i.5.  o H        X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  G     2 l.'.].S.c.l.l.k.h.u.w.6.7.h.l.(.{.G.b.l.l.k.j.p.r.7.5.h.l.S.{.).N.x.l.l.k.p.y.#   P.       X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    G     f N.[./.m.z.l.l.j.p.r.7.5.p.k.M.}._.A.x.l.l.k.g.y.q.5.e.j.l.'.[.D.v.l.l.k.h.i.c   4 D        X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    F     z D.`.S.c.l.l.k.g.u.w.6.7.j.l._.[.F.b.l.l.k.j.p.r.6.5.h.l.G.{./.m.z.l.l.j.p.r.=   I.       X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    D     2.S.K.m.z.l.l.j.p.e.7.5.g.k.A.}.).N.x.l.l.k.g.y.7.5.y.j.z.[.].S.v.l.l.k.h.i.l   C 6        X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    C     7.n.D.v.l.l.k.g.u.w.5.e.j.l.'.[.D.v.l.l.k.h.p.e.6.5.h.l.H.{.K.n.l.l.l.j.p.r.    I.       X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    5     r.l.M.l.k.k.h.i.e.6.5.g.l.D.}.(.M.z.l.l.k.p.r.7.5.i.k.v.[.'.A.c.l.l.k.h.y.d   F          X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  %       g.k.l.k.j.h.i.r.7.5.r.j.l.].].S.c.l.l.k.g.i.w.6.7.j.l.(.{.H.b.z.l.l.j.p.q.    P.       X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  5     = g.h.g.g.p.i.r.q.5.6.h.k.C.[.K.m.z.l.l.k.p.r.6.5.p.k.N.{.`.V.x.l.l.j.g.y.1   H          X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  C     < p.i.i.y.r.e.7.6.5.y.j.l.G.`.S.c.l.l.k.g.y.w.5.w.k.l.`.[.G.b.l.l.l.h.i.3.  % G        X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  S     2 y.r.e.w.7.6.6.5.8.g.h.l.A.L.m.l.l.k.j.p.r.7.5.g.k.C.{.(.N.z.l.l.j.g.u.#   P.       X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  D     d r.w.7.4.4.Q Q Q 9.i.h.k.z.V.x.l.l.j.g.u.q.5.r.h.k.'.[.F.c.l.l.l.h.i.x   5 S        X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    D     h 0.9.@.+.+.&.+.{  .t.h.h.k.l.l.k.j.h.u.e.7.5.g.k.F.}./.M.z.l.l.h.g.y.=   I.       X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    S     ~ -.-.=.*.=.@.&.O.| 9.i.h.h.j.j.h.g.u.e.7.5.r.k.l.'.].S.c.l.l.l.h.u.g   A 5        X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    C     [ -.-.-.=.&.&.@.O.{ o.y.u.g.p.i.u.y.e.7.6.5.k.k.D.}./.n.z.l.l.j.g.e.    I.       X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    4     $.-.-.-.=.-.=.@.%.O.} 8.u.u.y.e.e.q.7.5.5.u.k.k./.'.A.z.l.l.j.h.y.s   F          X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  &       f.s.s.s.s.=.=.d.&.O...9.t.e.w.7.8.5.3.! 8.h.k.k.K.G.l.l.l.j.h.u.6.  o H        X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  6     $ -.s.s.-.=.&.&.*.+.O.| o.8.8.4.W E b k k 4.a.h.k.M.k.l.j.j.h.i.r.<   P.       X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  C     , f.f.s.s.d.*.=.@.@.+.| } o.o.' ( ^ ^ V k E u.h.k.k.k.h.g.i.y.e.2.  D 5        X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  S   . 5 d.-.-.=.=.&.%.&.O.#...} ` ' ' / ( V V B b t.p.g.g.p.u.y.e.w.2.X 6 J        X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  D     p s.d.=.d.=.&.%.%.#.....} ' ' ] ' ( ( V m j 8.i.i.i.r.w.q.7.f   & I.         X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    D     n &.-.&.%.$.$.O.....X.} [ [ ) ( ( / ( V V N 4.y.r.r.7.6.v #   5 I.         X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    S     V =.=.=.&.@.@.@.+.+.| O.| } [ [ ' ' ' V N N Q 7.8.! v g X   C I.         X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    7     [ d.=.=.@.@.%.O.| | X.} } ' ) _ ( ^ V V N N b W k j 3     G F          X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    &     %.&.&.$.$.#.#.#.| | } } } } ] ) ^ ^ ^ V N N j j h @     I.4          X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  4       -.*.*.%.&.%.| | | } [ [ ' ' _ ^ V V N N N n n i     7 I.           X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  7     $ %.&.%.#.| ..[ { [ ` [ ) ' ( / ~ V M N M m n 3     H G          X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  S     , &.%.%.#.O.| { { [ ` ` ) ) ( / ^ B N N N n @   o I.%          X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X  F     u &.%.%.O.O.| | { [ } _ _ _ ( ( V V B N p     A I.           X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    F &   i *.+.+.| | { } [ ' ' / ^ ~ V M m m m ,     J D          X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    S S     ) #.{ { { ` ) ( ) / / V M M m m n X   % I.           X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    7 J       M ..{ { [ [ ) ) ' _ / V M m u     S P.           X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    & I.        h [ [ ` ) / / / ~ / M M ,     P.Z          X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X      I.          p ` [ ) _ _ _ ^ ^ h X   5 I.           X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X      J 7           i ' _ _ ^ ~ ~ u     D J            X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X      G C             3 / / M M $     P.7          X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X      F 7               , M n X   7 I.           X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X    o D 5                       D S            X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X      & D 5                                  X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X      5 D &                                X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X      6 S &                            X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X      7 S %                          X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X      7 Z                          X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X      7 7                      X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X      7 4                    X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X      4                    X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X                       X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X                     X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X                   X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X               X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X             X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X         X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X       X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X   X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X",
" X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X"
};
