/*
 * Embroidermodder 2.
 *
 * Copyright 2011-2024 The Embroidermodder Team
 * Embroidermodder 2 is Open Source Software, see LICENSE.md for licensing terms.
 *
 * Read the reference manual (https://www.libembroidery.org/downloads/emrm.pdf)
 * for advice on altering this file.
 */
/* XPM */
static char *views_3d[] = {
/* columns rows colors chars-per-pixel */
"128 128 230 2 ",
"   c black",
".  c #010101",
"X  c gray1",
"o  c #040404",
"O  c gray2",
"+  c #060606",
"@  c #070707",
"#  c gray3",
"$  c #090909",
"%  c gray4",
"&  c #0B0B0B",
"*  c #0C0C0C",
"=  c gray5",
"-  c #0E0E0E",
";  c gray6",
":  c #101010",
">  c #111111",
",  c gray7",
"<  c #131313",
"1  c gray8",
"2  c #151515",
"3  c #161616",
"4  c gray9",
"5  c #181818",
"6  c #191919",
"7  c gray10",
"8  c #1B1B1B",
"9  c gray11",
"0  c #1D1D1D",
"q  c #1E1E1E",
"w  c gray12",
"e  c #202020",
"r  c gray13",
"t  c #222222",
"y  c #232323",
"u  c gray14",
"i  c #252525",
"p  c gray15",
"a  c #272727",
"s  c #282828",
"d  c gray16",
"f  c #2A2A2A",
"g  c #2C2C2C",
"h  c #2D2D2D",
"j  c gray18",
"k  c gray19",
"l  c #323232",
"z  c gray20",
"x  c #343434",
"c  c #353535",
"v  c gray21",
"b  c #373737",
"n  c #393939",
"m  c #3A3A3A",
"M  c gray23",
"N  c gray24",
"B  c #3E3E3E",
"V  c #3F3F3F",
"C  c gray25",
"Z  c #414141",
"A  c gray26",
"S  c #434343",
"D  c #444444",
"F  c gray27",
"G  c #464646",
"H  c gray28",
"J  c #484848",
"K  c #494949",
"L  c gray29",
"P  c #4B4B4B",
"I  c #4C4C4C",
"U  c gray30",
"Y  c #4E4E4E",
"T  c gray31",
"R  c #505050",
"E  c #515151",
"W  c gray32",
"Q  c #535353",
"!  c #555555",
"~  c #565656",
"^  c gray34",
"/  c #585858",
"(  c gray35",
")  c #5A5A5A",
"_  c #5B5B5B",
"`  c gray36",
"'  c #5D5D5D",
"]  c gray37",
"[  c #5F5F5F",
"{  c #606060",
"}  c gray38",
"|  c #626262",
" . c gray39",
".. c #646464",
"X. c #656565",
"o. c gray40",
"O. c #676767",
"+. c #686868",
"@. c DimGray",
"#. c #6A6A6A",
"$. c gray42",
"%. c #6C6C6C",
"&. c #6D6D6D",
"*. c gray43",
"=. c #6F6F6F",
"-. c gray44",
";. c #717171",
":. c #727272",
">. c gray45",
",. c #747474",
"<. c gray46",
"1. c #767676",
"2. c #777777",
"3. c gray47",
"4. c #797979",
"5. c gray48",
"6. c #7B7B7B",
"7. c #7C7C7C",
"8. c gray49",
"9. c #7E7E7E",
"0. c gray50",
"q. c #808080",
"w. c #818181",
"e. c gray51",
"r. c #838383",
"t. c #848484",
"y. c #868686",
"u. c gray54",
"i. c gray55",
"p. c #8E8E8E",
"a. c gray56",
"s. c #909090",
"d. c #929292",
"f. c #939393",
"g. c gray58",
"h. c #959595",
"j. c gray59",
"k. c #979797",
"l. c #989898",
"z. c gray60",
"x. c #9A9A9A",
"c. c #9B9B9B",
"v. c gray61",
"b. c #9D9D9D",
"n. c gray62",
"m. c #9F9F9F",
"M. c #A0A0A0",
"N. c gray63",
"B. c #A2A2A2",
"V. c gray64",
"C. c #A4A4A4",
"Z. c #A5A5A5",
"A. c gray65",
"S. c #A7A7A7",
"D. c #A9A9A9",
"F. c #AAAAAA",
"G. c #ACACAC",
"H. c gray68",
"J. c #AEAEAE",
"K. c #AFAFAF",
"L. c #B1B1B1",
"P. c #B2B2B2",
"I. c gray70",
"U. c #B4B4B4",
"Y. c gray71",
"T. c #B6B6B6",
"R. c #B7B7B7",
"E. c gray72",
"W. c #B9B9B9",
"Q. c gray73",
"!. c #BBBBBB",
"~. c #BCBCBC",
"^. c gray74",
"/. c gray",
"(. c gray75",
"). c #C0C0C0",
"_. c #C1C1C1",
"`. c gray76",
"'. c #C3C3C3",
"]. c gray77",
"[. c #C5C5C5",
"{. c #C6C6C6",
"}. c gray78",
"|. c #C8C8C8",
" X c gray79",
".X c #CACACA",
"XX c #CBCBCB",
"oX c #CDCDCD",
"OX c #CECECE",
"+X c gray81",
"@X c #D0D0D0",
"#X c LightGray",
"$X c gray83",
"%X c #D5D5D5",
"&X c gray84",
"*X c #D7D7D7",
"=X c gray85",
"-X c #DADADA",
";X c gray86",
":X c gainsboro",
">X c #DDDDDD",
",X c #DFDFDF",
"<X c gray88",
"1X c #E1E1E1",
"2X c #E2E2E2",
"3X c gray89",
"4X c #E4E4E4",
"5X c gray90",
"6X c #E6E6E6",
"7X c #E7E7E7",
"8X c gray91",
"9X c #EAEAEA",
"0X c gray92",
"qX c #ECECEC",
"wX c gray93",
"eX c #EEEEEE",
"rX c #F1F1F1",
"tX c gray95",
"yX c #F3F3F3",
"uX c #F4F4F4",
"iX c gray96",
"pX c gray97",
"aX c #F8F8F8",
"sX c #F9F9F9",
"dX c gray98",
"fX c #FBFBFB",
"gX c #FDFDFD",
"hX c #FEFEFE",
"jX c white",
"kX c None",
/* pixels */
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX          kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX              kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX                  kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX      x ' y           kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX      ' 9.;.x             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    y ;.#.A *                 kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    Y ;.9                         kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    5.Q     9           *             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    9.:     y x.          o.:             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    q.      y `.M.          ;.j.1             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    9.      y `..Xx.          ;.F.j.1             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    9.      u `..X`.j.          ;.H.H.x.1             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    q.      y `..X~.!.d.          5.H.H.L.m.1             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    9.      y ]..X`.!.!.j.    o     5.L.L.!.~.F.1             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    q.      u `..X~.!.T.~.x.    *     5.T.T.!.]..XL.6             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    q.      y ]..X`.!.!.!.`.C.    :     9.T.T.~..X*X@XT.6             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    9.      u `..X~.!.T.!.`.+XH.    :     5.T.!.`.@X=X3X:X~.1             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    q.      y `..X~.!.!.!.`.+X*XL.    :     9.T.!.].@X:X4X4X4X~.6             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    9.      y `..X`.!.!.!.`.+X=X4X~.    :     9.T.!.`.*X4XqXqX0X4X~.1             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    9.      y `..X~.!.!.~.`.+X=X4XqX`.    :     9.T.!.`.*X3XqXpXtXqX3X~.1             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    q.      y `.].`.!.!.!.`.+X=X3XqXpX`.    :     9.T.T.].@X4XtXpXpXpXqX3X~.6             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    9.      y ]..X`.!.T.~.`.+X*X3XqXpXdX].    :     9.T.!.`.*X3XtXdXdXdXpXqX3X~.1             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    q.      u `..X~.!.!.~.`.+X=X4XqXpXdXgX.X    :     9.T.!.`.*X3XtXdXgXdXdXpXqX4X~.1             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    9.      y ]..X~.!.!.!.`.+X=X4XqXpXgXgXgX.X    :     9.T.!.`.*X4XtXdXgXgXgXgXpX0X3X~.6             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    q.      u `..X~.~.!.!.`.+X=X3XqXpXdXgXgXgX.X    :     9.T.T.`.*X3XtXdXgXgXgXgXdXpXqX4X~.6             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    9.      y `..X~.!.!.!.`.+X=X4XqXpXdXdXgXgXgX.X    :     9.T.!.`.@X4XtXdXgXgXgXgXgXdXpXqX3X~.1             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    q.      y `..X`.!.!.!.`.+X*X3XqXpXdXgXgXgXgXgX.X    :     9.T.!.`.*X4XtXdXgXgXgXgXgXgXdXpX0X3X~.1             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    9.      u `..X~.!.!.~.].+X=X4XqXpXdXdXgXgXgXgXgX.X    :     9.T.T.`.*X3XtXdXgXgXgXgXgXgXgXdXtX0X3X~.1             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    q.      y `..X`.!.!.!.`.+X=X3XqXpXdXgXgXgXgXgXgXgX.X    :     9.T.!.`.*X3XtXdXgXgXgXgXgXgXgXgXdXpX0X4X~.6             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    9.      y `..X~.!.T.~.`.+X*X3XqXpXgXgXgXgXgXgXgXgXgX.X    :     9.T.!.`.*X4XtXdXgXgXgXgXgXgXgXgXgXdXpXqX4X!.6             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    q.      y `..X`.!.!.~.`.+X=X4XqXpXdXgXgXgXgXgXgXgXgXgX.X    :     9.T.!.].@X4XtXdXgXgXgXgXgXgXgXgXgXgXdXpXqX3X!.6             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    q.      y `..X~.!.!.!.`.+X*X4XqXpXgXgXgXgXgXgXgXgXgXgXgX.X    9     9.T.!.`.*X3XqXdXgXgXgXgXgXgXgXgXgXgXgXdXpX0X3X~.6             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    9.      y `.].`.!.!.!.`.+X=X3XqXpXdXgXgXgXgXgXgXgXgXgXgXgX.X  * k     9.T.T.`.*X3XtXdXgXgXgXgXgXgXgXgXgXgXgXgXgXpX0X3X~.6             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    q.      u `..X`.!.T.~.`.+X=X4X0XpXdXgXgXgXgXgXgXgXgXgXgXgXgX.X  f A     9.T.!.`.*X4XtXdXgXgXgXgXgXgXgXgXgXgXgXgXgXdXpXqX3X~.6             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    9.      y `..X`.!.!.~.`.+X*X3X0XpXdXgXgXgXgXgXgXgXgXgXgXgXgXgX.X  D L     9.T.!.`.*X4XtXdXgXgXgXgXgXgXgXgXgXgXgXgXgXdXdXpXqX3X~.6             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    o.1     y `..X~.!.!.!.`.+X*X3X0XpXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXd.  { L     o.T.!.`.*X4XtXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXdXpXqX3X~.6     $       kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    V Y     y `..X~.!.!.!.`.+X=X4XqXpXdXdXgXgXgXgXgXgXgXgXgXgXgXgXgXT.o   1.M     $ d.!.`.@X3XtXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXdXpX0X3X~.6     f       kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX      9.    y ]..X`.!.!.!.`.+X=X3XqXpXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXT.$   A L         * j.`.*X3XqXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXdXpXqX3X!.6     V       kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX      L %.  o H..X~.!.!.!.`.+X*X3X0XpXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXT.$   { u             * j.@X:X0XpXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXpX0X3X~.6   #.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX      ! Y     9 F.!.T.!.~.+X=X3XqXpXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXT.o   q.$     o           * M.=X4XtXdXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXdXpXqX3X~.6 f o.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    x x       6 m.T.~.].*X3X0XpXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXT.o   q.      y C.6           * C.3X0XtXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXdXdXpXqX3X' $ 9.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    $ 6         6 C.`.+X:X0XtXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXT.$   q.      y `.].C.1           : F.3X0XtXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXdXpX1.  9 9.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX                  6 H.@X:X0XpXdXgXgXgXgXgXgXgXgXgXgXgXgXgXT.$   9.      u `..X`.!.M.1           * F.3X0XpXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgX5.    L 1.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX        o           6 !.=X0XtXdXgXgXgXgXgXgXgXgXgXgXgXgXT.o   q.      y `..X`.!.T.T.M.1           * F.3X0XtXpXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgX9.    x %.Y         kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX        A $           9 ~.3X0XpXdXgXgXgXgXgXgXgXgXgXgXT.$   q.      u `..X~.!.T.!.~.`.F.6           * F.3XqXpXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgX5.    L #.A           kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX        Q p.$           9 `.4X0XtXdXgXgXgXgXgXgXgXgX!.o   9.      u `..X~.!.!.!.`..X@X@XT.6           : H.3X0XtXdXgXgXgXgXgXgXgXgXgXgXgXgX9.    %./               kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX        Q T.y.$           6 ~.3XqXpXdXgXgXgXgXgXgX!.o   q.      u `..X~.!.!.!.`..X*X:X:X:X~.1           * C.3X0XpXdXgXgXgXgXgXgXgXgXgXgX9.  y 9.6     M           kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX  1     Q !.L.y.$           6 `.3X0XpXdXdXgXgXgX!.o   9.      y `..X`.!.!.!.`.+X=X3X4X0X4X3X!.6           * F.3X0XpXdXdXgXgXgXgXgXgXgX9.  u q.      L M.          kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX  g     Q T.L.L.u.*           6 `.3X0XpXdXgXgX!.$   q.      u `..X~.!.!.!.`.+X=X3XqXtXpXtX0X3X~.1           : F.3X0XtXdXgXgXgXgXgXgX9.  f q.      D +Xm.          kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX  M     Q !.L.T.!.d.$           6 `.3XqXpXdX!.o   q.      u `..X`.!.T.!.`.+X=X3XqXpXdXdXdXpXqX3X~.6           * F.3X0XtXdXgXgXgXgX9.  f 9.      D +X].x.          kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX  A     Q !.!.!.~.].x.*           6 `.3XqXL.o $ 9.      u `..X~.!.!.~.`.+X=X3X0XpXdXgXgXgXdXtXqX3X!.6           * F.3X0XpXdXgXgX9.  u q.      L +X].~.j.          kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX  D     Q ~.!.~.].+X@XM.*     9     6 `.C.o : q.      u `..X~.!.!.!.`.+X*X3XqXpXdXgXgXgXgXgXdXpX0X3X~.6           * H.3X0XtXdX9.  f 9.      L +X].`.!.d.          kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX  D     Q !.!.~.+X*X=X=XC.*     o.    1 o   L       u `..X~.!.!.!.`.+X=X3X0XpXdXgXgXgXgXgXgXgXdXpXqX3X~.1           * F.3X0X5.  x q.      D +X].~.T.!.j.    $     kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX  D     Q ~.~.`.+X=X3X4X3XC.*   9 9.A             u `..X`.!.!.!.`.+X=X4XqXpXdXgXgXgXgXgXgXgXgXgXgXpX0X3X!.1     u     * F.;.  x 1.      L +X].~.!.!.~.m.    *     kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX  D     Q !.!.`.+X:X0XqX4X3XC.*   ! 9.' *       y ~..X~.!.!.~.`.+X=X4XqXpXgXgXgXgXgXgXgXgXgXgXgXgXdXpX0X3X~.6     #.y   $   o x       D +X].`.!.!.!.`.C.    :     kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX  D     Q ~.~.`.@X3X0XtXtX0X:XC.* $ o.Q       9 T.`.~.!.T.~.`.+X=X3XqXpXdXgXgXgXgXgXgXgXgXgXgXgXgXgXdXpX0X4X~.1   $ 9.! :           D +X.X~.!.T.~.].+XH.    :     kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX  D     Q ~.~.`.@X3X0XpXpXpXqXM.o   :         6 C.!.!.!.~.`.+X=X4XqXpXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXdXdXpXqX4X~.6   L q.{         A .X].~.!.!.~.].+X:XT.    :     kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX  D     Q ~.~.`.@X3XqXdXdXdXL.o                 6 m.L.!.~..X*X3XqXpXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXdXpXqX4X~.* $ / V       x `.`.~.!.!.~.].@X=X4X~.    :     kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX  D     Q ~.~.`.@X:XqXdXgXT.o : A                 1 m.!.].@X3X0XtXdXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXdXpXqX;.              * d.T.T.T.~.].+X:X4XtX].    :     kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX  D     Q ~.~.`.@X3XqXpX!.$ $ 9.      6 $           6 F..X*X3XtXpXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXdX5.  $               * d.T.!.`.+X=X4XqXdX].    :     kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX  D     Q ~.~.`.@X3XqXL.$   9.      y T.p.$           6 L.*X3XtXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXq.  x x                 * p.!.].*X3X0XpXdX.X    :     kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX  D     Q ~.~.`.@X3XF.o   9.      y ~.`.!.u.$           6 ~.3X0XtXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgX9.  x 5.      M 1           * j..X=X4XtXpXgX].    :     kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX  L     Q ~.~.`.@XC.o   q.      y `..X~.T.T.u.$           6 ~.3X0XpXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXq.  f 9.      D `.M.1           * M.=X4XqXpXgX.X    :     kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX  Q     ! ~.~.`.x.o   q.      y `..X`.!.T.T.!.p.$           9 `.3X0XpXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXq.  u q.      L .X`.T.m.1           * F.:XqXtXdX].  : :     kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX  Q *   Q ~.~.p.o : q.      y `..X~.~.!.!.`.]..Xx.$           6 `.3XqXpXdXgXgXgXgXgXgXgXgXgXgXgXgXgXq.  u q.      L +X].~.T.T.m.6           * F.3X0XpX].  V *     kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX  D /   Q !.u.o A 9.      y `..X~.!.!.!.`..X@X*X*XM.*           6 ~.3X0XtXdXgXgXgXgXgXgXgXgXgXgXgXq.  f 9.      L @X.X~.!.T.!.~.C.1           * F.3X0X`.  %.      kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX  f 9.  Q p.o A {       y `..X`.!.T.!.`.+X=X:X3X3X:XC.*           9 `.3XqXpXgXgXgXgXgXgXgXgXgXgXy.  f q.      L @X].~.!.!.~.`.]..XL.6           : F.3X!.9 q.      kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    9.M V o *         y `..X`.!.!.!.`.+X=X3X0XqXqX0X3XC.*           9 `.3XqXpXdXdXgXgXgXgXgXgXq.  u q.      L @X].~.!.!.~.].+X*X=X=XT.6     o     * F.!./ 5.      kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    ;.o.o           y ~..X~.~.T.!.`.+X=X3XqXtXdXpXtX0X3XM.*           6 `.3X0XpXdXgXgXgXgXgXq.  f q.      L @X].`.!.!.!.`.@X=X3X4X4X3X!.6     y ! u k C.5.A       kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    ! '           y T.`.~.!.!.~.`.+X=X3X0XpXdXgXgXdXtX0X3XC.*           9 ~.3XqXpXgXgXgXgXy.  u q.      L @X.X`.!.!.~.].@X=X4XqXtXtX0X3X~.6     o 1.9.q.9.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX    k g         y F.~.!.!.T.~.`.+X=X4XqXpXdXgXgXgXgXdXtXqX3XC.*           9 `.3XqXpXdXgXq.  u q.      L @X].~.T.!.~.].@X:X4XtXpXdXpXpXqX4X~.6       D 1.#.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX              9 C.T.T.T.!.~.`.+X=X3XqXpXdXgXgXgXgXgXgXdXpX0X3XM.*           6 `.3X0XpX9.  g q.      L @X].`.T.!.!.].@X=X4XqXpXgXgXgXdXpX0X3X!.6       : V         kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX              9 M.H.H.L.T.~.`.+X=X3X0XpXdXgXgXgXgXgXgXgXgXdXtX0X3XC.*     o     6 `.3X5.  V 9.      L @X.X~.!.!.~.`.@X=X4XtXdXgXgXgXgXgXdXpX0X3X!.6       $         kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            o d.F.H.H.T.!.`.+X=X3XqXpXdXgXgXgXgXgXgXgXgXgXgXdXtX0X3XM.*     k     9 o.  V '       L @X.X~.!.!.~.].@X:X0XqXdXdXgXgXgXgXgXdXdXpX0X3X!.6               kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            1 x.H.H.T.~..X=X3XqXpXgXgXgXgXgXgXgXgXgXgXgXgXgXdXtX0X3XC.*     ' /     9         L @X.X~.!.!.~.].@X:X4XqXpXgXgXgXgXgXgXgXgXgXdXpXqX3X~.6             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            6 x.T.~.].*X3X0XpXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXdXpX0X3XM.*     ! %.u         D @X.X~.!.!.~.].@X:X0XqXdXgXgXgXgXgXgXgXgXgXgXgXgXpX0X4X'             kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            1 M.`.+X:X0XtXpXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXdXtX0X3XC.*     1         D .X].~.!.!.~.].@X:X4XqXpXdXgXgXgXgXgXgXgXgXgXgXgXgXdXpX1.  1           kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            6 H.@X:XqXpXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXpXpX0X3XM.o           A ~.~.!.!.!.~.].@X:X4XtXpXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgX5.  A           kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            6 !.:X4XtXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXdXtX0X3XQ         9 T.T.T.T.T.~.].@X=X4XtXdXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgX9.  A /         kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            9 ~.4XqXpXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXdXpX0X%.        Y L.L.T.T.!.].+X=X0XtXpXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgX9.  g 9.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            6 ~.4X0XpXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXdXtX;.        Y H.H.L.T.`.+X=X4XtXpXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgX9.  f q.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            9 `.3XqXpXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXdX;.  :     Y L.L.T.~.+X=X3XqXdXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgX9.  u 9.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            9 ~.4X0XpXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgX1.  x     Q T.L.!.].@X3X0XpXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgX9.  f q.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            6 `.3X0XpXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgX1.  A     Q T.T.~..X=X4XtXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgX9.  f q.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            6 ~.3XqXpXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgX5.  D     Q !.!.~.+X:XqXpXgXgXgXgXgXgXgXgXgXgXgXgXgXgX9.  u 9.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            9 `.3XqXpXdXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgX5.  D     Q !.!.`.@X:X0XdXgXgXgXgXgXgXgXgXgXgXgXgXgX9.  u q.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            9 ~.4X0XpXgXgXgXgXgXgXgXgXgXgXgXgXgXgXgX5.  D     Q !.~.`.@X3XqXdXgXgXgXgXgXgXgXgXgXgXgXgX9.  f q.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            6 `.3XqXpXdXgXgXgXgXgXgXgXgXgXgXgXgXgX5.  D     Q ~.~.`.@X3XqXdXgXgXgXgXgXgXgXgXgXgXgXq.  f 9.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            9 ~.4X0XpXdXgXgXgXgXgXgXgXgXgXgXgXgX5.  D     Q ~.~.`.@X:XqXdXgXgXgXgXgXgXgXgXgXgXq.  u q.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            6 `.3X0XpXdXgXgXgXgXgXgXgXgXgXgXgX5.  D     Q ~.~.`.@X3XqXpXgXgXgXgXgXgXgXgXgXq.  u q.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            9 ~.3X0XpXgXgXgXgXgXgXgXgXgXgXgX5.  D     Q ~.~.`.@X3XqXdXgXgXgXgXgXgXgXgXq.  f 9.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            9 `.3X0XpXdXdXgXgXgXgXgXgXgXgX5.  D     Q ~.~.`.@X:XqXdXgXgXgXgXgXgXgX9.  u q.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            9 `.3X0XpXdXgXgXgXgXgXgXgXgX5.  D     Q ~.~.`.@X3XqXdXgXgXgXgXgXgXq.  f q.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            6 `.3X0XpXdXgXgXgXgXgXgXgX5.  D     Q ~.~.`.@X3XqXdXgXgXgXgXgXq.  f 9.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            6 `.3X0XpXgXgXgXgXgXgXgX5.  D     ! ~.~.`.@X:XqXdXgXgXgXgX9.  u 9.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            6 `.3XqXpXdXgXgXgXgXgX5.  D     Q ~.~.`.@X3XqXdXgXgXgXq.  f q.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            9 ~.4X0XpXdXgXgXgXgX5.  D     Q ~.~.`.@X3XqXdXgXgXq.  f 9.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            6 `.3X0XpXdXgXgXgX5.  D     Q ~.~.`.+X3XqXpXgXq.  f 9.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            9 ~.3XqXpXdXgXgX5.  D     Q ~.~.`.+X3XqXdX9.  u q.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            6 `.3X0XpXdXgX5.  Y     Q ~.~.`.@X3XqX9.  f 9.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            9 `.3XqXtXdX1.  /     Q ~.~.`.+X3X1.  u q.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            6 `.3XqXpX1.  ;.    Q ~.~.`.+X;.  f 9.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            6 `.3XqX;.M 5.    Q ~.~.`.%.  u q.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX            9 `.3Xq.#.1.    ! ~.~.o.  V q.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX      1     9 `.p.1.{     Q ~.{   / 5.        kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX      M / k Q d.;.Y     ! {   D M         kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX      1 5.9.q.1.D 1   g               kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX        A %.#.L y                 kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX          g g                 kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX                          kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX                      kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX                  kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX              kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX          kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX",
"kXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkXkX"
};
