/*
 * Embroidermodder 2.
 *
 * Copyright 2011-2024 The Embroidermodder Team
 * Embroidermodder 2 is Open Source Software, see LICENSE.md for licensing terms.
 *
 * Read the reference manual (https://www.libembroidery.org/downloads/emrm.pdf)
 * for advice on altering this file.
 */
/* XPM */
static char *zoomprevious[] = {
/* columns rows colors chars-per-pixel */
"128 128 186 2 ",
"   c #000000",
".  c #090702",
"X  c #0B0B0B",
"o  c #04070B",
"O  c #1D1609",
"+  c #151006",
"@  c #141414",
"#  c #1C1C1C",
"$  c #241C0B",
"%  c #281F0C",
"&  c #2D220D",
"*  c #32260F",
"=  c #35280F",
"-  c #21201E",
";  c #362910",
":  c #3B2D12",
">  c #332B1C",
",  c #0B1322",
"<  c #0E182A",
"1  c #121C2F",
"2  c #111E34",
"3  c #131F38",
"4  c #14223B",
"5  c #1C2637",
"6  c #222222",
"7  c #2D2D2D",
"8  c #262729",
"9  c #3C3424",
"0  c #333333",
"q  c #3C3C3C",
"w  c #372F23",
"e  c #44361B",
"r  c #423721",
"t  c #473D28",
"y  c #493E2A",
"u  c #4B3E25",
"i  c #4C422D",
"p  c #4F4530",
"a  c #534730",
"s  c #554A36",
"d  c #51452E",
"f  c #162642",
"g  c #192946",
"h  c #1A2B4B",
"j  c #1C2F52",
"k  c #1D3155",
"l  c #1F345B",
"z  c #202F4B",
"x  c #24334D",
"c  c #29364F",
"v  c #223252",
"b  c #2C3A55",
"n  c #20365F",
"m  c #24395E",
"M  c #2C3D5C",
"N  c #2A3752",
"B  c #333F57",
"V  c #213760",
"C  c #243A62",
"Z  c #293D63",
"A  c #35425A",
"S  c #39465C",
"D  c #344057",
"F  c #2C4166",
"G  c #2E4369",
"H  c #344665",
"J  c #3D4B64",
"K  c #32466B",
"L  c #35496E",
"P  c #3A4D6E",
"I  c #364867",
"U  c #3B4E72",
"Y  c #3F5275",
"T  c #444444",
"R  c #4B4B4B",
"E  c #535353",
"W  c #5B5B5B",
"Q  c #635E54",
"!  c #414E65",
"~  c #44526C",
"^  c #4B5669",
"/  c #4D596C",
"(  c #4A5466",
")  c #545D6D",
"_  c #425474",
"`  c #445678",
"'  c #46597B",
"]  c #4B5C7C",
"[  c #4D5A75",
"{  c #535F76",
"}  c #5B667A",
"|  c #576277",
" . c #646464",
".. c #6A6A6A",
"X. c #636C7A",
"o. c #616976",
"O. c #6C727E",
"+. c #747474",
"@. c #7D7D7D",
"#. c #857D6B",
"$. c #948C7D",
"%. c #4D5F80",
"&. c #4F6181",
"*. c #546584",
"=. c #5B6985",
"-. c #5C6C89",
";. c #606F8A",
":. c #626E82",
">. c #63728E",
",. c #697386",
"<. c #727986",
"1. c #737C8B",
"2. c #667591",
"3. c #687792",
"4. c #6C7B95",
"5. c #707E98",
"6. c #717D96",
"7. c #7D828A",
"8. c #75829B",
"9. c #79869D",
"0. c #7D889E",
"q. c #7A8291",
"w. c #7D8AA2",
"e. c #7A87A0",
"r. c #838383",
"t. c #8C8C8C",
"y. c #82868D",
"u. c #9D9688",
"i. c #898F9A",
"p. c #878C97",
"a. c #8E9196",
"s. c #939495",
"d. c #93969D",
"f. c #9D9D9D",
"g. c #97999D",
"h. c #828EA5",
"j. c #8591A6",
"k. c #8591A8",
"l. c #8A95AB",
"z. c #8E99AE",
"x. c #8D97A7",
"c. c #9A9DA3",
"v. c #9399A4",
"b. c #939DB0",
"n. c #9EA2A9",
"m. c #9FA0A3",
"M. c #9AA3B2",
"N. c #9BA5B7",
"B. c #A5A5A5",
"V. c #A3A6AB",
"C. c #A6A9AE",
"Z. c #ACACAC",
"A. c #A7ABB4",
"S. c #ABB1BD",
"D. c #B4B4B4",
"F. c #B4B6B9",
"G. c #BCBCBC",
"H. c #ADB5C3",
"J. c #B8BECA",
"K. c #B3B9C6",
"L. c #BFC1C3",
"P. c #BAC1CC",
"I. c #BFC5D1",
"U. c #C3C3C3",
"Y. c #CBCBCB",
"T. c #C7C8CA",
"R. c #C1C7D1",
"E. c #C7CDD6",
"W. c #CDD1DA",
"Q. c #D4D4D4",
"!. c #D7DADF",
"~. c #DBDBDB",
"^. c #D2D6DE",
"/. c #D7DAE1",
"(. c #DADDE3",
"). c #DFE2E6",
"_. c #E3E3E3",
"`. c #E3E5EA",
"'. c #ECECEC",
"]. c #E6E8ED",
"[. c #ECEEF1",
"{. c #EFF1F3",
"}. c #F3F3F3",
"|. c #FFFFFF",
" X c #F6F7F9",
".X c None",
/* pixels */
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X              .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X                                            .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X            X 8 q 0 7 6 @ # 6 0 T E W E 0 X                 .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X          q W W q                                   # 0 8             .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X        @ W ..T                 - # 0 0 0 0 0 # #                 8 7             .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X        R ..0             # # 0 0 T t.Z.G.G.G.G.G.Z.r.T 7 w 0 # #           6 #           .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X      .  . .          # # 0 T t.Z.F.F.F.G.G.G.G.F.G.L.G.G.F.D.D.D.B.@.q 0 #           8           .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X      ..W         # 0 T t.D.G.G.G.G.G.D.G.D.G.G.G.G.G.G.G.U.G.G.G.G.G.G.D.Z.$.q w #         #           .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X      W ..        # D $.D.G.G.G.G.D.D.D.G.G.G.G.G.G.U.U.T.Y.Y.Y.Y.T.Y.U.L.G.G.G.S.G.C.+.q #         .         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X      T r.        - T t.G.L.G.G.D.D.D.G.G.G.G.U.U.U.Y.Y.Q.Q.Q.~.~.~.~.~.Q.Q.Q.T.T.T.U.L.G.G.D.@.q #                   .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X    @ r.q       # T t.G.L.G.G.D.D.G.G.G.G.U.U.Y.Y.Q.Q.~.~.~._._._.'._.'._._._._.~.~.Q.Q.Q.Y.Y.U.G.D.r.q #                 .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X    E @.        0 $.F.L.G.D.D.D.G.G.G.U.T.Y.Q.~.~._._._._.'.'.'.}.}.}.}.}.}.}.'.'.'.'._._._.~.~.Q.Y.T.L.D.r.q #       X         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X    +.T       # T Z.U.F.D.D.D.D.G.G.U.Y.Q.~.~._._.'.'.'.}.}. X X X X|. X|. X|. X X}. X}.}.'.'.'._._.~.Q.Q.T.U.D.@.q #               .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  . $.      - T s.G.G.D.D.D.G.G.G.U.Y.Q.~._._.'.'.}.}.}. X X|.|. X|.|.|.|.|.|.|.|.|. X|.|. X X|.}.}.{.'._._.~.Q.Y.U.D.+.7               .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X    @ <.      q r.L.L.G.D.D.D.G.G.U.Y.Q.~._.'.'.}. X X X X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X|.|. X}.}.'._._.~.Q.T.U.B.7               .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X    - #.      0 D.U.L.G.D.D.D.G.U.U.Q.~._.'.}.}.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X|.}.}.'.'._.~.Y.Y.Z.y #             .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X    6 <.o     0 Z.U.J.D.D.D.G.G.U.Q.Q._._.'.}.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X X}.{.'._.~.Q.U.<.7             .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  # #.o     0 Z.U.G.D.D.D.G.L.Y.Q.~._.'.}.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X}.}.{.'.~.~.Y.B.7     X       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X  X @.      0 Z.U.G.D.D.G.G.T.Q.~._.'.}.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X}.}.'.'.~.Q.Z.0     X       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X    r.      0 Z.G.G.D.D.G.G.Y.Q.~._.'.}. X X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X X'.'._.Q.Z.7             .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X    r.      0 Z.L.G.D.D.G.G.Y.Q._.'.{. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X X X'._.~.Z.7           .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X    ..6     0 Z.U.G.D.D.G.G.T.Q._.'.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X X{._.~.r.#           .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X  0  .    0 D.U.F.D.D.G.G.Y.Q._.'.}.|. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.}.}.'.Q.T     X       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X    @.    # $.U.G.D.D.D.G.Y.Q._.'.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.[.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X}._.U.0             .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X    +.      T U.G.D.D.D.G.Y.Q._.'.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.N.].|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X}.'.F.0           .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X  7 E     0 Z.G.G.D.G.G.Y.Q._.'.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.).Y b.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X{.].t.@   X       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X    @.    # r.G.G.D.D.G.U.Q._.'.}.|. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.K.V I _.|. X X X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X'.~.R .     o o o .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X    E .     T U.G.D.D.G.U.Q.~.'.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.l.G l 6. X}. X X X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.]./.!.S.} 5 1 4 4 f h j k k k k k k k k .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X    ..    0 Z.G.D.D.G.G.Y.~._.}. X X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.2.' l M _.'.'.}.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.[.[.].S.9.>.*.Z C F l l l l l l l l l l l l l l l l k k k k k .X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X     .    - r.U.F.D.D.G.Y.Q._.}.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.{.Y 2.l k v._._.'.'.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.E.A.h.-.Z k Z l l n F ] -.>.2.2.>.-.-.=.*.*.*.*.&.' K n n n l l k k j j .X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X    ..    T L.G.D.D.G.U.Q._.'.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.W.V 8.n h ( ~.~._.'.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.].M.;.` L l V V ] 3.8.4.*.F n l l l l l l l l k l l l l l l n n K ` Z n k k k h .X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X  E     # s.G.G.D.D.U.Y.~.'.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.h.n h.n h x L.Q.Q._.'.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.P.>.G V V n %.9.e.-.n l l l k k k j k h h h h h h h h h j h j j j k k l l l k k j h .X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X    +.    T L.G.D.D.G.Y.Q._.'. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|._ n l.n k h c.T.Y.~._.}. X|.|.|.|.|.|.|.|.|.|.}.z.P n l m 2.w.4.C l l k k j h v h g M S A D 1 < , , , 1 2 2 4 4 f f f h h h j j j j h h .X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X  0 #   @ $.L.G.D.G.U.Q._.'.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.W.n n z.n j h 1.U.T.Q._.'. X|.|.|.|.|.|.|.|.W.4.C n n *.k.3.V l l k j x h h S ) | <.d.g.f.D.s.8   X       .X.X.X.X.X.X.X.X2 3 f f g h h f .X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X    ..    0 D.G.D.D.G.Y.~._.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.h.k n z.n j g / F.U.Y.~.'.}.|.|.|.|.|.|.J.>.m l m 8.w.Z l k k h h b J / <.n.C.Z.G.F.D.D.D.D.B.q           .X.X.X.X.X.X.X.X.X.X.X.X.X4 4 .X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X    E     T J.G.D.G.U.Q._.'.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.}.=.l V b.l j h B D.F.T.~._.}.|.|.|.}.J.2.G n K w.5.m l j h h v / <.a.V.L.G.F.G.D.D.D.D.D.D.D.D.O.X           .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X  q     # t.G.D.D.G.Y.~._.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.W.P l G l.l j h N C.D.U.Q._.{. X XW.e.Y C G h.4.n k h h g J 1.C.F.F.G.G.D.D.D.D.D.D.G.G.G.G.G.U.D.q           .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X     .    T G.G.D.F.U.Q._.'. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.z.C n *.w.n j h v B.D.L.Q._.[. Xn.' n n w.8.n k j h h | n.T.U.G.G.F.D.D.D.D.G.G.L.L.U.T.T.Y.Q.Q.Y.$.X         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X    R   @ $.G.G.D.L.T.~._.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.}._ l V 8.3.l k h v B.Z.L.Y.~.K.=.l l 4.k.n k j h b X.Z.U.L.G.G.D.D.D.G.G.G.G.U.T.T.Q.Q.Q.~.~.~.)._.T.8         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X  8     # D.F.D.G.L.Y.~.'.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.H.n l L k.&.l k j k c.Z.G.H.e.P n ' z.K l j h B } n.L.G.G.D.D.D.D.G.G.L.T.Y.Y.Q.~.~.~._._.'.'.'.{.'.'.T   @       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X  R     0 G.G.D.G.T.Q._.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.[.*.k n >.k.U l k k k g.Z.n.| Z n 9.8.n j h h ^ p.D.L.G.D.D.D.G.G.G.U.T.Y.Q.~.~._._.'.'.{.}.}.}. X X}.}.B..         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X  W     T G.G.D.G.Y.~.'.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.R.I l V w.9.G n n k v | 6.I l C h.` k j h M q.F.U.G.D.D.D.G.G.G.U.Y.Q.~._._.'.'.'.}.}. X X X|.|.|.|.|. X~.X         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X    T   # t.G.D.G.U.Q._.'.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.k.V l ] k.2.C l n n n n C V V *.n k j m } F.U.G.G.D.D.D.G.G.U.Y.Q.~._._.'.'.}. X X|. X|.|.|.|.|.|.|.|.|.'.8   o     .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X    @   - Z.G.G.G.U.~._.{. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.] l V 5.w.&.C n n l l m n Z Z V l k J i.G.L.G.D.D.D.G.G.U.Y.Q.~._.'.'.}.}. X|. X|.|.|.|.|.|.|.|.|.|.|.|.{.0   #     .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X  #     0 G.G.G.G.T.~.'.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.J.V l K k.5.U n n n Z G L Y C V l k { C.U.G.F.D.D.G.G.L.T.Q.~._.'.'.}.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.}.R   @       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X  7     0 G.D.G.G.Y._.'. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X=.l n >.k.-.G V n C G L Y G n n n ' C.C.F.Z.C.D.G.L.U.Q.~.~._.'. X X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.B.. .       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X  0     T G.G.G.U.Q._.'. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.R.Z n n w.e.' C V V C C C C n l n l H ~ :.} [ 1.q.<.F.Z.Q._.'.}.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.~..         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X  7   # t.G.D.G.U.~._.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. Xw.l l *.l.2.K V n n V n n n n n l l l V m k n Z k M _ I h.9.~.). X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.'.@         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X  8   - D.G.G.G.Y.~._.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.).] l V e.w.&.F n n n n n V n V n n n l l l n l l n k k n m j =.=.!._. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.}.#         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X  8   0 G.G.G.U.Y.~.'.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.b.Z l &.z.4.U C n n n n n n n n n n n n n V V l V n n n n k n k j I x.S.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.}.6         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X  0   0 G.G.G.U.Q.~.'.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.^.H l n e.k.*.G V n n n n n n n n V n V n n V l v n n n k k k j j v j M ,.'.'. X X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.}.#   X     .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X  T   0 G.G.G.U.Q._.'. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. Xe.l l &.z.5.Y C V V n n n n n n n n l n l l n k j j h h h h x H P ! ~ 1.Z.~._.'.}. X X|.|.|.|.|.|.|.|.|.|.|.|.|.|.}.#   X     .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X  E   0 G.G.U.Y.Q._.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|./.L l n w.k.*.K V n n n V n n n n l n k n k j j h h h g f b ^ ,.7.p.g.F.T.Y.Q._._.}.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.}.6   .     .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X  W   # Z.G.G.Y.Q.'.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. Xj.m l *.z.8.Y C V n n n V V V l l l k v j j j h g g z ! o.a.m.B.B.Z.D.F.L.Y.Y.Q._.'.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.}.#         .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X   .  - t.G.G.Y.~._.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.).U l n w.k.*.G V n V n n n l l l k j j h g g h g S ) y.B.B.B.B.Z.Z.D.D.G.L.U.Y.Q._._.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|. X# #       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X  E     T F.L.Y.~._.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.}.4.m n -.l.5.Y C V V V l l l l k j j h g g N c ) +.s.B.B.B.B.Z.Z.D.D.D.G.U.U.Y.Q.~._.'.{. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.}.# 0       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X  0     0 G.G.U.~._.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.J.Z l V w.k.&.C V V n l l k k j j h g g c S X.7.f.B.B.B.Z.Z.D.D.D.G.U.U.Y.Y.Q.~.~._.'.'.}. X X|.|.|.|.|.|.|.|.|.|.|.|.|.~.X E       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X  X     7 D.G.Y.Q._.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.8.n l -.l.2.G l l l l k k j h h g h g ( O.s.B.B.B.B.Z.Z.D.D.G.L.T.Y.Y.Q.~._._._.'.'.}.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.Z..  .      .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X    .   0 D.G.U.Q._.'. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.^.P l n k.w.L n l l l k j h h g g c ) O.f.B.B.B.Z.Z.Z.D.G.G.U.U.Y.Q.~._._.'.'.'.{.}.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. XE   ..    .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X    8   # Z.G.L.Q.~.{. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X>.n n 2.k.` n l l l j h h f g D ) y.B.B.B.B.B.Z.Z.D.L.L.T.Y.Q.~.~._.'.'.}.}. X X X|.|. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.}.0   E     .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X    q   # r.F.G.Y.~.'.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.K.M n K k.&.n k k j h h g g b ) s.m.B.B.Z.Z.Z.D.G.G.U.T.Q.Q.~._._.'.'.}.}. X X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.}.8 @ 8     .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X  7     q D.G.Y.~.'.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.{.;.l l e.*.l k j j h g h B o.y.B.B.B.B.Z.Z.Z.G.G.U.Y.Q.~.~._.'.'.}. X|. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.~.@ T       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X        0 B.G.T.~._.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.M.Z l >.&.l k j h h h A ^ 7.B.f.B.B.Z.Z.D.G.U.U.Y.Q.~._._.'.}.}. X X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. XZ.X  .      .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X    8   @ $.G.U.~._.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|./.Y n ' ` n k h g z c ( @.t.f.B.B.Z.D.D.G.U.Y.Y.Q.~._.'.'.}.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. XE   ..      .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X    0     B D.L.Q._.'. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X5.V L P l h h g g ( o.p.B.B.Z.B.Z.D.G.G.T.Y.Q._._.'.{.}. X X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|._.7 6 0     .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X          7 B.L.Y.~.'.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.H.Z C Z k j g h S X.f.B.B.B.B.Z.D.G.U.U.Q.Q.~._.'.'. X X X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. Xf.@ ..      .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X    X   # #.G.U.~._.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.].-.V l k h h ! <.s.Z.B.B.Z.Z.D.D.G.U.Y.Q.~._.'.}.}. X X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.}.E   +.      .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X    #     q D.U.Q._.{. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.b.C V l n J } D.G.D.Z.B.Z.Z.D.G.U.Y.Q.~._.'.}.}. X X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.Z.# 0 7     .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X          7 B.L.Y.~.'.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.W.Y n k v | i.S.U.D.D.Z.D.D.G.L.Y.Q.~._.'.'.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. XE   +.      .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X    X   # +.G.T.~._.}. X|.|.|.|.|.|.|.|.|.|.|.|.|. X>.l v M ,.S.T.T.G.D.D.D.G.G.T.Q.~.~._.'.}.}.|. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X_.q    .      .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X          q D.U.Q._.}. X|.|.|.|.|.|.|.|.|.|.|.|. XN.n Z 3.n._.~.Y.U.G.G.G.G.T.Q.Q.~.'.'.}.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.f.@ W       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X        # @.G.Y.~.'. X|.|.|.|.|.|.|.|.|.|.|.|.`.2.] L.].'._.Q.Y.U.G.U.U.Y.Q._._.'.}.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.{.E   +.      .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X    X     q D.U.~._.}. X|.|.|.|.|.|.|.|.|.|.|.I.9.R. X}._.~.Q.Y.U.T.Y.Q.~._.'.}. X X X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. Xf.@ E .     .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X          # +.G.Q.~.'.}.|.|.|.|.|.|.|.|.|.|.|.W.W. X X}._.~.Q.Q.Y.Q.~._._.'.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.Q.q   @.      .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X    o     7 B.Y.~._.}. X|.|.|.|.|.|.|.|.|.|.|.|. X}.'._.~.~.~.~.~._.'.}.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.}.E    .      .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X      #     p G.Q.(.'. X|.|.|.|.|.|.|.|.|.|.|.|. X}.}._._._._._.'.}.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. XZ.- @ +.      .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X          # +.T.!._.}. X|.|.|.|.|.|.|.|.|.|.|.|.}.}.'._.'.'.{.}. X X X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.}.E   +.      .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X    X     7 V.Q.~.'.}.|.|.|.|.|.|.|.|.|.|.|.|. X}.}.}.}. X}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.f.# T q       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X            p G.~._.'.}.|.|.|.|.|.|.|.|.|.|. X|. X|. X X X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. XQ.q   @.      .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X          # +.Y.~.'.}. X|.|.|.|.|.|.|.|.|.|.|.|. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.~.q   @.        .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X          7 B.Q.~.'. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.}.E   W 0       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X            0 Z.Q._.{.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. Xf.# 7 ..      .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X            7 Z.Q._.{. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.Q.q . r.      .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X            0 Z.~.'.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. XQ.q   r.        .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X            0 D.~.'.}. X X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.Q.q    .7       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X              7 D.~.'.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. XQ.q   6  .      .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X            . 7 D.~.'.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. Xf.q     ..      .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X              0 D.~.'.}. X X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. XQ.E 6   X +.E     .X.X.X.X.X.X.X; ; .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X              0 r.Q.'.{. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.}.f.q      .@.E         .X.X.X.X.X: ; ; * .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X              - T g._.{. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. XQ.E -   E @.7               .X.X.Xu e : ; * .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X            . # R U.'.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.}.f.q   @ $.q                   . % a $.: ; & ; : ; .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X        @       0 t._.{. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X}.Z.E 6   ) +.          .X      6   + u u.: ; $ O ; : ; * .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X              . # R m._.'.}.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X}.Z.E -   0 @.+         .X.X.X.X    - Q i u.: ; $ O r e ; ; & .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X                  - R s.~.'. X X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.}.Z.E #   @ +.R           .X.X.X.X.X.X  + s u.: ; $ O t $.: ; & * ; * .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X                  # q R B.'. X X X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X X_.f.E 6   # +.W             .X.X.X.X.X.X.X$ t u.: ; 9 w i u.: ; $ O ; : ; & .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X            X         # R s.~.'.}. X|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|.|. X X}._.Z.E q 6   0 @.W             .X.X.X.X.X.X.X.X.Xa u.: ; 9 9 i u.: ; $ O r e ; ; & .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X              X       - # q R B.~.'.{. X X|.|.|.|.|.|.|. X X}.}.(.Z.E q 6 6     E @.0             .X.X.X.X.X.X.X.X.X.Xa u.: ; > t i u.: ; $ O i $.: ; & & ; * .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X                          6 # q q E Z.~.'.{.{.}.}._.Z.E q q 6 -     @ E ..R               .X.X.X.X.X.X.X.X.X.X.X: #.: ; $ > p u.: ; $ O u u.: ; $ $ ; : ; & .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X                  # @           # - q q q q q # #     . 0 W ..W 8                 .X.X.X.X.X.X.X.X.X.X.X.X: : : ; $ O t u.: : $ O t u.: ; $ O r e : ; & .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X                      o         . @ 0 R  .+.+. .B .                     .X.X.X.X.X.X.X.X.X.X.X.X.X; : : ; $ O y u.: ; $ O u u.: ; $ O t $.: ; & & ; * .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X                                          .                 .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X; ; ; $ : #.: ; $ O t u.: ; $ $ t u.: ; $ O ; : ; & .X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X                                              .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X; .X: : : ; $ O t u.: = $ O t u.: ; $ O r e : ; & .X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X                  .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X; ; ; ; $ O t u.: ; $ O t u.: ; $ $ t $.: ; & & ; * .X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X; ; & $ ; #.: ; % O t u.: ; $ O t u.: ; $ O ; ; ; & .X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X& & : : : ; $ O y u.: ; $ O t u.: ; $ O r e : ; & .X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X* : ; ; $ O t u.: ; $ $ t u.: = $ $ t $.: ; & * ; * .X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X* ; & $ ; #.: ; $ O t u.: ; $ O t u.: ; $ O ; : ; & .X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X& % : : : ; $ O y u.: ; $ O t u.: ; $ O r e : ; & .X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X* : ; ; $ O y u.: ; $ O t u.: = $ O t u.: ; & .X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X* ; & $ ; #.: ; $ O t u.: ; $ O u u.; ; $ .   .X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X& & : : : ; $ O t u.: ; $ $ t u.: ; $ .     .X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X* : ; ; $ O i u.: ; $ O t u.: ; $ .       .X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X* ; & $ ; #.: ; $ O t u.: ; $ .       .X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X& & ; : : ; $ O t u.: ; $ .       .X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X* ; ; ; $ O t u.: ; $ .       .X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X; ; & $ ; #.: ; $ .       .X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X* % : : : ; $ .       .X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X* ; ; ; $ .       .X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X; ; & .       .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X& .X.X    .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X",
".X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X"
};
