#!/bin/bash
#
# This file is part of Embroidermodder.
# Copyright 2025 The Embroidermodder Team
# Embroidermodder 2 is Open Source Software, see LICENSE.md for licensing terms.
#
# Read the reference manual (https://www.libembroidery.org/downloads/emrm.pdf)
# for advice on altering this file.
#

files=`ls images/*.png`
cat docs/copyright_message.txt > src/xpm.c

for file in $files
do
	echo "Converting $file to xpm..."
	stub=`basename $file`
	outf="${stub}.xpm"
	convert $file $outf
	cat $outf >> src/xpm.c
	rm $outf
done

echo "char **xpm_icons[] = {" >> src/xpm.c
for file in $files
do
	stub=`basename $file`
	echo "    ${stub::-4}_png," >> src/xpm.c
done
echo "};" >> src/xpm.c
echo "" >> src/xpm.c

echo "char *xpm_icon_labels[] = {" >> src/xpm.c
for file in $files
do
	stub=`basename $file`
	echo "    \"${stub::-4}\"," >> src/xpm.c
done
echo "    \"END\"" >> src/xpm.c
echo "};" >> src/xpm.c
