#!/bin/bash
#
# This file is part of Embroidermodder.
# Copyright 2025 The Embroidermodder Team
# Embroidermodder 2 is Open Source Software, see LICENSE.md for licensing terms.
#
# Read the reference manual (https://www.libembroidery.org/downloads/emrm.pdf)
# for advice on altering this file.
#

MAJOR="2"
MINOR="0"
PATCH="0"
TAG="alpha"
VERSION="$MAJOR.$MINOR.$PATCH-$TAG"
