/*
 * Embroidermodder 2
 * Copyright 2011-2025 The Embroidermodder Team
 *
 * Embroidermodder 2 is free and open software under the zlib license:
 * see LICENSE.md for details.
 *
 * ----------------------------------------------------------------------------
 *
 * THIS FILE IS GENERATED BY "bin/gen_headers.py". DO NOT ALTER DIRECTLY.
 *
 * The commands that are written in C which only act via the state variable.
 */

#ifndef __EM2_COMMANDS__
#define __EM2_COMMANDS__

#ifdef __cplusplus
extern "C" {
#endif

#include "core.h"

int about_command(State *state);
int arc_command(State *state);
int changelog_command(State *state);
int circle_command(State *state);
int clear_command(State *state);
int clear_rubber_command(State *state);
int copy_command(State *state);
int cut_command(State *state);
int day_command(State *state);
int delete_command(State *state);
int details_command(State *state);
int dim_leader_command(State *state);
int distance_command(State *state);
int ellipse_command(State *state);
int end_command(State *state);
int exit_command(State *state);
int fill_command(State *state);
int generate_command(State *state);
int get_command(State *state);
int help_command(State *state);
int horizontal_dim_command(State *state);
int icon_resize_command(State *state);
int image_command(State *state);
int infinite_line_command(State *state);
int line_command(State *state);
int macro_command(State *state);
int move_command(State *state);
int new_command(State *state);
int night_command(State *state);
int open_command(State *state);
int pan_command(State *state);
int paste_command(State *state);
int path_command(State *state);
int platform_command(State *state);
int play_command(State *state);
int point_command(State *state);
int polygon_command(State *state);
int polyline_command(State *state);
int print_command(State *state);
int ray_command(State *state);
int rectangle_command(State *state);
int redo_command(State *state);
int regular_polygon_command(State *state);
int repeat_command(State *state);
int rgb_command(State *state);
int rotate_command(State *state);
int rounded_rectangle_command(State *state);
int save_command(State *state);
int save_as_command(State *state);
int scale_command(State *state);
int script_command(State *state);
int select_all_command(State *state);
int set_command(State *state);
int settings_command(State *state);
int sleep_command(State *state);
int slot_command(State *state);
int stop_command(State *state);
int stub_command(State *state);
int text_multi_command(State *state);
int text_single_command(State *state);
int triangle_command(State *state);
int undo_command(State *state);
int updates_command(State *state);
int vertical_dim_command(State *state);
int whats_this_command(State *state);
int window_command(State *state);
int zoom_command(State *state);

#ifdef __cplusplus
}
#endif

#endif
