/*
 * Embroidermodder 2
 * Copyright 2011-2025 The Embroidermodder Team
 *
 * Embroidermodder 2 is free and open software under the zlib license:
 * see LICENSE.md for details.
 *
 * ----------------------------------------------------------------------------
 *
 * THIS FILE IS GENERATED BY "bin/gen_headers.py". DO NOT ALTER DIRECTLY.
 *
 * The designs that are written in C which only act via the state variable.
 */

#ifndef __EM2_DESIGNS__
#define __EM2_DESIGNS__

#ifdef __cplusplus
extern "C" {
#endif

#include "core.h"

int dolphin_design(State *state);
int heart_design(State *state);
int snowflake_design(State *state);
int star_design(State *state);

#ifdef __cplusplus
}
#endif

#endif
