/*
 * Embroidermodder 2
 * Copyright 2011-2025 The Embroidermodder Team
 *
 * Embroidermodder 2 is free and open software under the zlib license:
 * see LICENSE.md for details.
 *
 * ----------------------------------------------------------------------------
 *
 * THIS FILE IS GENERATED BY "bin/gen_headers.py". DO NOT ALTER DIRECTLY.
 *
 * The fills that are written in C which only act via the state variable.
 */

#ifndef __EM2_FILLS__
#define __EM2_FILLS__

#ifdef __cplusplus
extern "C" {
#endif

#include "core.h"

int brick_fill(State *state);
int gradient_fill(State *state);
int satin_fill(State *state);

#ifdef __cplusplus
}
#endif

#endif
