/*
 * Embroidermodder 2
 * Copyright 2011-2025 The Embroidermodder Team
 *
 * Embroidermodder 2 is free and open software under the zlib license:
 * see LICENSE.md for details.
 *
 * ----------------------------------------------------------------------------
 *
 * THIS FILE IS GENERATED BY "bin/gen_headers.py". DO NOT ALTER DIRECTLY.
 *
 * The generators that are written in C which only act via the state variable.
 */

#ifndef __EM2_GENERATORS__
#define __EM2_GENERATORS__

#ifdef __cplusplus
extern "C" {
#endif

#include "core.h"

int drawing_generator(State *state);
int guilloche_generator(State *state);
int knot_generator(State *state);
int photo_generator(State *state);
int qr_generator(State *state);

#ifdef __cplusplus
}
#endif

#endif
