#ifndef SCRIPT_H
#define SCRIPT_H

#include <QString>
#include <QRgb>

#include "scheme.h"
#include "scheme-private.h"

#define CONTEXT_MAIN                   0
#define CONTEXT_CLICK                  1
#define CONTEXT_CONTEXT                2
#define CONTEXT_MOVE                   3
#define CONTEXT_PROMPT                 4

typedef struct Command_ {
    const char icon[100];
    const char command[100];
    const char tooltip[1000];
    const char statustip[1000];
    const char shortcut[100];
    const char macos[100];
    unsigned char checkable;
    pointer (*function)(scheme *sc, pointer args);
} Command;


QString getSettingsGeneralLanguage();
QString getSettingsGeneralIconTheme();
int getSettingsGeneralIconSize();
bool getSettingsGeneralMdiBGUseLogo();
bool getSettingsGeneralMdiBGUseTexture();
bool getSettingsGeneralMdiBGUseColor();
QString getSettingsGeneralMdiBGLogo();
QString getSettingsGeneralMdiBGTexture();
QRgb getSettingsGeneralMdiBGColor();
bool getSettingsGeneralTipOfTheDay();
int getSettingsGeneralCurrentTip();
bool getSettingsGeneralSystemHelpBrowser();
bool getSettingsGeneralCheckForUpdates();
bool getSettingsDisplayUseOpenGL();
bool getSettingsDisplayRenderHintAA();
bool getSettingsDisplayRenderHintTextAA();
bool getSettingsDisplayRenderHintSmoothPix();
bool getSettingsDisplayRenderHintHighAA();
bool getSettingsDisplayRenderHintNonCosmetic();
bool getSettingsDisplayShowScrollBars();
int getSettingsDisplayScrollBarWidgetNum();
QRgb getSettingsDisplayCrossHairColor();
QRgb getSettingsDisplayBGColor();
QRgb getSettingsDisplaySelectBoxLeftColor();
QRgb getSettingsDisplaySelectBoxLeftFill();
QRgb getSettingsDisplaySelectBoxRightColor();
QRgb getSettingsDisplaySelectBoxRightFill();
quint8  getSettingsDisplaySelectBoxAlpha();
qreal   getSettingsDisplayZoomScaleIn();
qreal   getSettingsDisplayZoomScaleOut();
quint8  getSettingsDisplayCrossHairPercent();
QString getSettingsDisplayUnits();
QRgb getSettingsPromptTextColor();
QRgb getSettingsPromptBGColor();
QString getSettingsPromptFontFamily();
QString getSettingsPromptFontStyle();
quint8  getSettingsPromptFontSize();
bool getSettingsPromptSaveHistory();
bool getSettingsPromptSaveHistoryAsHtml();
QString getSettingsPromptSaveHistoryFilename();
QString getSettingsCustomFilter();
QString getSettingsOpenFormat();
bool getSettingsOpenThumbnail();
QString getSettingsSaveFormat();
bool getSettingsSaveThumbnail();
quint8  getSettingsRecentMaxFiles();
quint8  getSettingsOpenSaveTrimDstNumJumps();
QString getSettingsPrintingDefaultDevice();
bool getSettingsPrintingUseLastDevice();
bool getSettingsPrintingDisableBG();
bool getSettingsGridShowOnLoad();
bool getSettingsGridShowOrigin();
bool getSettingsGridColorMatchCrossHair();
QRgb getSettingsGridColor();
bool getSettingsGridLoadFromFile();
QString getSettingsGridType();
bool getSettingsGridCenterOnOrigin();
qreal   getSettingsGridCenterX();
qreal   getSettingsGridCenterY();
qreal   getSettingsGridSizeX();
qreal   getSettingsGridSizeY();
qreal   getSettingsGridSpacingX();
qreal   getSettingsGridSpacingY();
qreal   getSettingsGridSizeRadius();
qreal   getSettingsGridSpacingRadius();
qreal   getSettingsGridSpacingAngle();
bool getSettingsRulerShowOnLoad();
bool getSettingsRulerMetric();
QRgb getSettingsRulerColor();
quint8  getSettingsRulerPixelSize();
bool getSettingsQSnapEnabled();
QRgb getSettingsQSnapLocatorColor();
quint8  getSettingsQSnapLocatorSize();
quint8  getSettingsQSnapApertureSize();
bool getSettingsQSnapEndPoint();
bool getSettingsQSnapMidPoint();
bool getSettingsQSnapCenter();
bool getSettingsQSnapNode();
bool getSettingsQSnapQuadrant();
bool getSettingsQSnapIntersection();
bool getSettingsQSnapExtension();
bool getSettingsQSnapInsertion();
bool getSettingsQSnapPerpendicular();
bool getSettingsQSnapTangent();
bool getSettingsQSnapNearest();
bool getSettingsQSnapApparent();
bool getSettingsQSnapParallel();
bool getSettingsLwtShowLwt();
bool getSettingsLwtRealRender();
qreal   getSettingsLwtDefaultLwt();
bool getSettingsSelectionModePickFirst();
bool getSettingsSelectionModePickAdd();
bool getSettingsSelectionModePickDrag();
QRgb getSettingsSelectionCoolGripColor();
QRgb getSettingsSelectionHotGripColor();
quint8  getSettingsSelectionGripSize();
quint8  getSettingsSelectionPickBoxSize();
QString getSettingsTextFont();
qreal   getSettingsTextSize();
qreal   getSettingsTextAngle();
bool getSettingsTextStyleBold();
bool getSettingsTextStyleItalic();
bool getSettingsTextStyleUnderline();
bool getSettingsTextStyleStrikeOut();
bool getSettingsTextStyleOverline();

void setSettingsGeneralLanguage(const QString& newValue);
void setSettingsGeneralIconTheme(const QString& newValue);
void setSettingsGeneralIconSize(int newValue);
void setSettingsGeneralMdiBGUseLogo(bool newValue);
void setSettingsGeneralMdiBGUseTexture(bool newValue);
void setSettingsGeneralMdiBGUseColor(bool newValue);
void setSettingsGeneralMdiBGLogo(const QString& newValue);
void setSettingsGeneralMdiBGTexture(const QString& newValue);
void setSettingsGeneralMdiBGColor(QRgb newValue);
void setSettingsGeneralTipOfTheDay(bool newValue);
void setSettingsGeneralCurrentTip(int newValue);
void setSettingsGeneralSystemHelpBrowser(bool newValue);
void setSettingsGeneralCheckForUpdates(bool newValue);
void setSettingsDisplayUseOpenGL(bool newValue);
void setSettingsDisplayRenderHintAA(bool newValue);
void setSettingsDisplayRenderHintTextAA(bool newValue);
void setSettingsDisplayRenderHintSmoothPix(bool newValue);
void setSettingsDisplayRenderHintHighAA(bool newValue);
void setSettingsDisplayRenderHintNonCosmetic(bool newValue);
void setSettingsDisplayShowScrollBars(bool newValue);
void setSettingsDisplayScrollBarWidgetNum(int newValue);
void setSettingsDisplayCrossHairColor(QRgb newValue);
void setSettingsDisplayBGColor(QRgb newValue);
void setSettingsDisplaySelectBoxLeftColor(QRgb newValue);
void setSettingsDisplaySelectBoxLeftFill(QRgb newValue);
void setSettingsDisplaySelectBoxRightColor(QRgb newValue);
void setSettingsDisplaySelectBoxRightFill(QRgb newValue);
void setSettingsDisplaySelectBoxAlpha(quint8 newValue);
void setSettingsDisplayZoomScaleIn(qreal newValue);
void setSettingsDisplayZoomScaleOut(qreal newValue);
void setSettingsDisplayCrossHairPercent(quint8 newValue);
void setSettingsDisplayUnits(const QString& newValue);
void setSettingsPromptTextColor(QRgb newValue);
void setSettingsPromptBGColor(QRgb newValue);
void setSettingsPromptFontFamily(const QString& newValue);
void setSettingsPromptFontStyle(const QString& newValue);
void setSettingsPromptFontSize(quint8 newValue);
void setSettingsPromptSaveHistory(bool newValue);
void setSettingsPromptSaveHistoryAsHtml(bool newValue);
void setSettingsPromptSaveHistoryFilename(const QString& newValue);
void setSettingsCustomFilter(const QString& newValue);
void setSettingsOpenFormat(const QString& newValue);
void setSettingsOpenThumbnail(bool newValue);
void setSettingsSaveFormat(const QString& newValue);
void setSettingsSaveThumbnail(bool newValue);
void setSettingsRecentMaxFiles(quint8 newValue);
void setSettingsOpenSaveTrimDstNumJumps(quint8 newValue);
void setSettingsPrintingDefaultDevice(const QString& newValue);
void setSettingsPrintingUseLastDevice(bool newValue);
void setSettingsPrintingDisableBG(bool newValue);
void setSettingsGridShowOnLoad(bool newValue);
void setSettingsGridShowOrigin(bool newValue);
void setSettingsGridColorMatchCrossHair(bool newValue);
void setSettingsGridColor(QRgb newValue);
void setSettingsGridLoadFromFile(bool newValue);
void setSettingsGridType(const QString& newValue);
void setSettingsGridCenterOnOrigin(bool newValue);
void setSettingsGridCenterX(qreal newValue);
void setSettingsGridCenterY(qreal newValue);
void setSettingsGridSizeX(qreal newValue);
void setSettingsGridSizeY(qreal newValue);
void setSettingsGridSpacingX(qreal newValue);
void setSettingsGridSpacingY(qreal newValue);
void setSettingsGridSizeRadius(qreal newValue);
void setSettingsGridSpacingRadius(qreal newValue);
void setSettingsGridSpacingAngle(qreal newValue);
void setSettingsRulerShowOnLoad(bool newValue);
void setSettingsRulerMetric(bool newValue);
void setSettingsRulerColor(QRgb newValue);
void setSettingsRulerPixelSize(quint8 newValue);
void setSettingsQSnapEnabled(bool newValue);
void setSettingsQSnapLocatorColor(QRgb newValue);
void setSettingsQSnapLocatorSize(quint8 newValue);
void setSettingsQSnapApertureSize(quint8 newValue);
void setSettingsQSnapEndPoint(bool newValue);
void setSettingsQSnapMidPoint(bool newValue);
void setSettingsQSnapCenter(bool newValue);
void setSettingsQSnapNode(bool newValue);
void setSettingsQSnapQuadrant(bool newValue);
void setSettingsQSnapIntersection(bool newValue);
void setSettingsQSnapExtension(bool newValue);
void setSettingsQSnapInsertion(bool newValue);
void setSettingsQSnapPerpendicular(bool newValue);
void setSettingsQSnapTangent(bool newValue);
void setSettingsQSnapNearest(bool newValue);
void setSettingsQSnapApparent(bool newValue);
void setSettingsQSnapParallel(bool newValue);
void setSettingsLwtShowLwt(bool newValue);
void setSettingsLwtRealRender(bool newValue);
void setSettingsLwtDefaultLwt(qreal newValue);
void setSettingsSelectionModePickFirst(bool newValue);
void setSettingsSelectionModePickAdd(bool newValue);
void setSettingsSelectionModePickDrag(bool newValue);
void setSettingsSelectionCoolGripColor(QRgb newValue);
void setSettingsSelectionHotGripColor(QRgb newValue);
void setSettingsSelectionGripSize(quint8 newValue);
void setSettingsSelectionPickBoxSize(quint8 newValue);
void setSettingsTextFont(const QString& newValue);
void setSettingsTextSize(qreal newValue);
void setSettingsTextAngle(qreal newValue);
void setSettingsTextStyleBold(bool newValue);
void setSettingsTextStyleItalic(bool newValue);
void setSettingsTextStyleUnderline(bool newValue);
void setSettingsTextStyleStrikeOut(bool newValue);
void setSettingsTextStyleOverline(bool newValue);

/* NOTE: Try to keep this list alphabetical in the function name. */
pointer about_f(scheme *sc, pointer args);
pointer add_arc_f(scheme *sc, pointer args);
pointer add_to_menu_f(scheme *sc, pointer args);
pointer add_toolbar_seperator_f(scheme *sc, pointer args);
pointer add_to_selection_f(scheme *sc, pointer args);
pointer add_to_toolbar_f(scheme *sc, pointer args);
pointer alert_f(scheme *sc, pointer args);
pointer allow_rubber_f(scheme *sc, pointer args);
pointer append_prompt_history_f(scheme *sc, pointer args);
pointer blink_f(scheme *sc, pointer args);
pointer calculate_angle_f(scheme *sc, pointer args);
pointer calculate_distance_f(scheme *sc, pointer args);
pointer changelog_f(scheme *sc, pointer args);
pointer circle_f(scheme *sc, pointer args);
pointer clear_rubber_f(scheme *sc, pointer args);
pointer clear_selection_f(scheme *sc, pointer args);
pointer color_selector_f(scheme *sc, pointer args);
pointer copy_f(scheme *sc, pointer args);
pointer copy_selected_f(scheme *sc, pointer args);
pointer cut_f(scheme *sc, pointer args);
pointer cut_selected_f(scheme *sc, pointer args);
pointer day_f(scheme *sc, pointer args);
pointer debug_f(scheme *sc, pointer args);
pointer delete_selected_f(scheme *sc, pointer args);
pointer design_details_f(scheme *sc, pointer args);
pointer dim_leader_f(scheme *sc, pointer args);
pointer disable_move_rapid_fire_f(scheme *sc, pointer args);
pointer disable_prompt_rapid_fire_f(scheme *sc, pointer args);
pointer distance_f(scheme *sc, pointer args);
pointer dolphin_f(scheme *sc, pointer args);
pointer do_nothing_f(scheme *sc, pointer args);
pointer ellipse_f(scheme *sc, pointer args);
pointer enable_move_rapid_fire_f(scheme *sc, pointer args);
pointer enable_prompt_rapid_fire_f(scheme *sc, pointer args);
pointer end_command_f(scheme *sc, pointer args);
pointer erase_f(scheme *sc, pointer args);
pointer error_f(scheme *sc, pointer args);
pointer exit_program_f(scheme *sc, pointer args);
pointer freeze_all_layers_f(scheme *sc, pointer args);
pointer heart_f(scheme *sc, pointer args);
pointer help_f(scheme *sc, pointer args);
pointer hide_all_layers_f(scheme *sc, pointer args);
pointer horizontal_dimension_f(scheme *sc, pointer args);
pointer icon128_f(scheme *sc, pointer args);
pointer icon16_f(scheme *sc, pointer args);
pointer icon24_f(scheme *sc, pointer args);
pointer icon32_f(scheme *sc, pointer args);
pointer icon48_f(scheme *sc, pointer args);
pointer icon64_f(scheme *sc, pointer args);
pointer image_f(scheme *sc, pointer args);
pointer infinite_line_f(scheme *sc, pointer args);
pointer init_command_f(scheme *sc, pointer args);
pointer layer_previous_f(scheme *sc, pointer args);
pointer layer_selector_f(scheme *sc, pointer args);
pointer layers_f(scheme *sc, pointer args);
pointer line_f(scheme *sc, pointer args);
pointer line_type_selector_f(scheme *sc, pointer args);
pointer line_weight_selector_f(scheme *sc, pointer args);
pointer locate_point_f(scheme *sc, pointer args);
pointer lock_all_layers_f(scheme *sc, pointer args);
pointer make_layer_current_f(scheme *sc, pointer args);
pointer menu_seperator_f(scheme *sc, pointer args);
pointer messagebox_f(scheme *sc, pointer args);
pointer mirror_selected_f(scheme *sc, pointer args);
pointer mouse_f(scheme *sc, pointer args);
pointer move_f(scheme *sc, pointer args);
pointer move_selected_f(scheme *sc, pointer args);
pointer new_file_f(scheme *sc, pointer args);
pointer night_vision_f(scheme *sc, pointer args);
pointer num_selected_f(scheme *sc, pointer args);
pointer open_file_f(scheme *sc, pointer args);
pointer pan_down_f(scheme *sc, pointer args);
pointer pan_left_f(scheme *sc, pointer args);
pointer pan_point_f(scheme *sc, pointer args);
pointer pan_real_time_f(scheme *sc, pointer args);
pointer pan_right_f(scheme *sc, pointer args);
pointer pan_up_f(scheme *sc, pointer args);
pointer paste_f(scheme *sc, pointer args);
pointer paste_selected_f(scheme *sc, pointer args);
pointer path_f(scheme *sc, pointer args);
pointer perpendicular_distance_f(scheme *sc, pointer args);
pointer platform_f(scheme *sc, pointer args);
pointer point_f(scheme *sc, pointer args);
pointer polygon_f(scheme *sc, pointer args);
pointer polyline_f(scheme *sc, pointer args);
pointer preview_off_f(scheme *sc, pointer args);
pointer preview_on_f(scheme *sc, pointer args);
pointer print_area_f(scheme *sc, pointer args);
pointer print_f(scheme *sc, pointer args);
pointer qsnap_f(scheme *sc, pointer args);
pointer quickleader_f(scheme *sc, pointer args);
pointer ray_f(scheme *sc, pointer args);
pointer rectangle_f(scheme *sc, pointer args);
pointer redo_f(scheme *sc, pointer args);
pointer regular_polygon_f(scheme *sc, pointer args);
pointer rgb_f(scheme *sc, pointer args);
pointer rotate_f(scheme *sc, pointer args);
pointer rotate_selected_f(scheme *sc, pointer args);
pointer rounded_rectangle_f(scheme *sc, pointer args);
pointer rubber_f(scheme *sc, pointer args);
pointer saveas_f(scheme *sc, pointer args);
pointer save_f(scheme *sc, pointer args);
pointer scale_f(scheme *sc, pointer args);
pointer scale_selected_f(scheme *sc, pointer args);
pointer select_all_f(scheme *sc, pointer args);
pointer selectall_f(scheme *sc, pointer args);
pointer set_background_color_f(scheme *sc, pointer args);
pointer set_crosshair_color_f(scheme *sc, pointer args);
pointer set_cursor_shape_f(scheme *sc, pointer args);
pointer set_grid_color_f(scheme *sc, pointer args);
pointer set_prompt_prefix_f(scheme *sc, pointer args);
pointer set_rubber_mode_f(scheme *sc, pointer args);
pointer set_rubber_point_f(scheme *sc, pointer args);
pointer set_rubberText_f(scheme *sc, pointer args);
pointer set_text_angle_f(scheme *sc, pointer args);
pointer set_text_bold_f(scheme *sc, pointer args);
pointer set_text_font_f(scheme *sc, pointer args);
pointer set_text_italic_f(scheme *sc, pointer args);
pointer set_text_overline_f(scheme *sc, pointer args);
pointer set_text_size_f(scheme *sc, pointer args);
pointer set_text_strikeout_f(scheme *sc, pointer args);
pointer set_text_underline_f(scheme *sc, pointer args);
pointer settings_dialog_f(scheme *sc, pointer args);
pointer show_all_layers_f(scheme *sc, pointer args);
pointer singlelinetext_f(scheme *sc, pointer args);
pointer slot_f(scheme *sc, pointer args);
pointer snowflake_f(scheme *sc, pointer args);
pointer spare_rubber_f(scheme *sc, pointer args);
pointer star_f(scheme *sc, pointer args);
pointer syswindows_f(scheme *sc, pointer args);
pointer text_angle_f(scheme *sc, pointer args);
pointer text_bold_f(scheme *sc, pointer args);
pointer text_font_f(scheme *sc, pointer args);
pointer text_italic_f(scheme *sc, pointer args);
pointer text_multi_f(scheme *sc, pointer args);
pointer text_overline_f(scheme *sc, pointer args);
pointer text_single_f(scheme *sc, pointer args);
pointer text_size_f(scheme *sc, pointer args);
pointer text_strikeout_f(scheme *sc, pointer args);
pointer text_underline_f(scheme *sc, pointer args);
pointer thaw_all_layers_f(scheme *sc, pointer args);
pointer tip_of_the_day_f(scheme *sc, pointer args);
pointer todo_f(scheme *sc, pointer args);
pointer triangle_f(scheme *sc, pointer args);
pointer undo_f(scheme *sc, pointer args);
pointer unlock_all_layers_f(scheme *sc, pointer args);
pointer vertical_dimension_f(scheme *sc, pointer args);
pointer vulcanize_f(scheme *sc, pointer args);
pointer whats_this_f(scheme *sc, pointer args);
pointer window_cascade_f(scheme *sc, pointer args);
pointer window_close_all_f(scheme *sc, pointer args);
pointer window_close_f(scheme *sc, pointer args);
pointer window_next_f(scheme *sc, pointer args);
pointer window_previous_f(scheme *sc, pointer args);
pointer window_tile_f(scheme *sc, pointer args);
pointer zoom_all_f(scheme *sc, pointer args);
pointer zoom_center_f(scheme *sc, pointer args);
pointer zoom_dynamic_f(scheme *sc, pointer args);
pointer zoom_extents_f(scheme *sc, pointer args);
pointer zoom_in_f(scheme *sc, pointer args);
pointer zoom_out_f(scheme *sc, pointer args);
pointer zoom_previous_f(scheme *sc, pointer args);
pointer zoom_real_time_f(scheme *sc, pointer args);
pointer zoom_scale_f(scheme *sc, pointer args);
pointer zoom_selected_f(scheme *sc, pointer args);
pointer zoom_window_f(scheme *sc, pointer args);

void run(const char *command);

extern scheme *root;
extern unsigned char context_flag;
extern const Command command_map[];

extern QString settings_general_language;
extern QString settings_general_icon_theme;
extern int settings_general_icon_size;
extern bool settings_general_mdi_bg_use_logo;
extern bool settings_general_mdi_bg_use_texture;
extern bool settings_general_mdi_bg_use_color;
extern QString settings_general_mdi_bg_logo;
extern QString settings_general_mdi_bg_texture;
extern QRgb settings_general_mdi_bg_color;
extern bool settings_general_tip_of_the_day;
extern quint16 settings_general_current_tip;
extern bool settings_general_system_help_browser;
extern bool settings_general_check_for_updates;
extern bool settings_display_use_opengl;
extern bool settings_display_renderhint_aa;
extern bool settings_display_renderhint_text_aa;
extern bool settings_display_renderhint_smooth_pix;
extern bool settings_display_renderhint_high_aa;
extern bool settings_display_renderhint_noncosmetic;
extern bool settings_display_show_scrollbars;
extern int settings_display_scrollbar_widget_num;
extern QRgb settings_display_crosshair_color;
extern QRgb settings_display_bg_color;
extern QRgb settings_display_selectbox_left_color;
extern QRgb settings_display_selectbox_left_fill;
extern QRgb settings_display_selectbox_right_color;
extern QRgb settings_display_selectbox_right_fill;
extern quint8 settings_display_selectbox_alpha;
extern qreal settings_display_zoomscale_in;
extern qreal settings_display_zoomscale_out;
extern quint8 settings_display_crosshair_percent;
extern QString settings_display_units;
extern QRgb settings_prompt_text_color;
extern QRgb settings_prompt_bg_color;
extern QString settings_prompt_font_family;
extern QString settings_prompt_font_style;
extern quint8 settings_prompt_font_size;
extern bool settings_prompt_save_history;
extern bool settings_prompt_save_history_as_html;
extern QString settings_prompt_save_history_filename;
extern QString settings_opensave_custom_filter;
extern QString settings_opensave_open_format;
extern bool settings_opensave_open_thumbnail;
extern QString settings_opensave_save_format;
extern bool settings_opensave_save_thumbnail;
extern quint8 settings_opensave_recent_max_files;
extern QStringList settings_opensave_recent_list_of_files;
extern QString settings_opensave_recent_directory;
extern quint8 settings_opensave_trim_dst_num_jumps;
extern QString settings_printing_default_device;
extern bool settings_printing_use_last_device;
extern bool settings_printing_disable_bg;
extern bool settings_grid_show_on_load;
extern bool settings_grid_show_origin;
extern bool settings_grid_color_match_crosshair;
extern QRgb settings_grid_color;
extern bool settings_grid_load_from_file;
extern QString settings_grid_type;
extern bool settings_grid_center_on_origin;
extern qreal settings_grid_center_x;
extern qreal settings_grid_center_y;
extern qreal settings_grid_size_x;
extern qreal settings_grid_size_y;
extern qreal settings_grid_spacing_x;
extern qreal settings_grid_spacing_y;
extern qreal settings_grid_size_radius;
extern qreal settings_grid_spacing_radius;
extern qreal settings_grid_spacing_angle;
extern bool settings_ruler_show_on_load;
extern bool settings_ruler_metric;
extern QRgb settings_ruler_color;
extern quint8 settings_ruler_pixel_size;
extern bool settings_qsnap_enabled;
extern QRgb settings_qsnap_locator_color;
extern quint8 settings_qsnap_locator_size;
extern quint8 settings_qsnap_aperture_size;
extern bool settings_qsnap_endpoint;
extern bool settings_qsnap_midpoint;
extern bool settings_qsnap_center;
extern bool settings_qsnap_node;
extern bool settings_qsnap_quadrant;
extern bool settings_qsnap_intersection;
extern bool settings_qsnap_extension;
extern bool settings_qsnap_insertion;
extern bool settings_qsnap_perpendicular;
extern bool settings_qsnap_tangent;
extern bool settings_qsnap_nearest;
extern bool settings_qsnap_apparent;
extern bool settings_qsnap_parallel;
extern bool settings_lwt_show_lwt;
extern bool settings_lwt_real_render;
extern qreal settings_lwt_default_lwt;
extern bool settings_selection_mode_pickfirst;
extern bool settings_selection_mode_pickadd;
extern bool settings_selection_mode_pickdrag;
extern QRgb settings_selection_coolgrip_color;
extern QRgb settings_selection_hotgrip_color;
extern quint8 settings_selection_grip_size;
extern quint8 settings_selection_pickbox_size;
extern QString settings_text_font;
extern qreal settings_text_size;
extern qreal settings_text_angle;
extern bool settings_text_style_bold;
extern bool settings_text_style_italic;
extern bool settings_text_style_underline;
extern bool settings_text_style_overline;
extern bool settings_text_style_strikeout;

#endif

