# Postscript functions and configuration for the heart4 design.
# -------------------------------------------------------
# This file is part of Embroidermodder.
# Copyright 2013-2022 The Embroidermodder Team
# See LICENSE for details.
# -------------------------------------------------------
#

command = "heart4"
range = [0.0, 2.0]
num_points = 512
scale = [0.04, 0.04]
parameter = "t"
x = """
    /t exch def
    (*
        (cos t)
        ((sin(t)*sqrt(abs(cos(t))))/(sin(t)+7/5) - 2*sin(t) + 2)
    )
"""
y = """
    /t exch def
    (*
        (sin t)
        ((sin(t)*sqrt(abs(cos(t))))/(sin(t)+7/5) - 2*sin(t) + 2)
    )
"""
