site_name: Embroidermodder 2.0.0-alpha
site_description: Free machine embroidery software supporting a variety of formats.
copyright: Copyright (C) 2013-2024 The Embroidermodder Team
site_url: https://www.libembroidery.org/
repo_url: https://github.com/Embroidermodder/docs
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - Downloads: downloads.md
  - About: about.md
  - Documentation:
    - User Manual:
      - Introduction: user/em2/index.md
    - Reference Manual: https://www.libembroidery.org/refman
    - UNIX Manpage: https://www.libembroidery.org/embroider
  - Contact: contact.md
  - Donate: https://opencollective.com/embroidermodder
  - Github: https://github.com/Embroidermodder
theme:
  name: material
  custom_dir: theme
#plugins:
#  - search
#  - bibtex:
#      bib_file: "references.bib"
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
