name: build

on: [push]

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - name: package
      run: |
        curl https://raw.githubusercontent.com/Embroidermodder/Embroidermodder/master/build.sh
        bash build.sh --package-msi
        
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows Installer
        path: *.msi

  build_macos:
    runs-on: macos-latest
    steps:
    - name: package
      run: |
        curl https://raw.githubusercontent.com/Embroidermodder/Embroidermodder/master/build.sh
        bash build.sh --package-macos
        
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MacOS
        path: embroidermodder*.tar

  build_linux:
    runs-on: ubuntu-latest
    steps:
    - name: package
      run: |
        curl https://raw.githubusercontent.com/Embroidermodder/Embroidermodder/master/build.sh
        bash build.sh --package-macos
        
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: GNU/Linux Archive
        path: embroidermodder*.tar

