name: build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: build the linux version
      run: |
        git clone https://github.com/embroidermodder/embroidermodder
        cd embroidermodder
        sh scripts/dependencies_apt.sh
        sh scripts/package.sh
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: embroidermodder-2.0.0-alpha-linux
        path: embroidermodder/build

  build-macos:
    runs-on: macos-latest
    steps:
    - name: build the mac os version
      run: |
        git clone https://github.com/embroidermodder/embroidermodder
        cd embroidermodder
        sh scripts/package.sh
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: embroidermodder-2.0.0-alpha-macos
        path: embroidermodder/build

  build-windows:
    runs-on: windows-latest
    steps:
    - name: build the windows version
      run: |
        git clone https://github.com/embroidermodder/embroidermodder
        cd embroidermodder
        .\scripts\package.bat
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: embroidermodder-2.0.0-alpha-windows
        path: embroidermodder/build
