name: Build and Test

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: build the linux version
      run:  curl https://gist.githubusercontent.com/robin-swift/2050bcfaa2426a91c42977b6d9559904/raw/0a8dd17d41e0814febe5d4500044447515ad43d4/em2_debug.sh | bash
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: embroidermodder-2.0.0-alpha-linux
        path: Embroidermodder
    - name: archive testing results
      uses: actions/upload-artifact@v3
      with:
        name: em2-2.0.0-alpha-linux-test-results
        path: Embroidermodder/test_results.txt
  build-macos:
    runs-on: macos-latest
    steps:
    - name: build the macos version
      run:  curl https://gist.githubusercontent.com/robin-swift/2050bcfaa2426a91c42977b6d9559904/raw/0a8dd17d41e0814febe5d4500044447515ad43d4/em2_debug.sh | bash
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: embroidermodder-2.0.0-alpha-macos
        path: Embroidermodder
    - name: archive testing results
      uses: actions/upload-artifact@v3
      with:
        name: em2-2.0.0-alpha-macos-test-results
        path: Embroidermodder/test_results.txt
  build-windows:
    runs-on: windows-latest
    steps:
    - name: build the windows version
      run:  curl https://gist.githubusercontent.com/robin-swift/2050bcfaa2426a91c42977b6d9559904/raw/0a8dd17d41e0814febe5d4500044447515ad43d4/em2_debug.sh | bash
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: embroidermodder-2.0.0-alpha-windows
        path: Embroidermodder
    - name: archive testing results
      uses: actions/upload-artifact@v3
      with:
        name: em2-2.0.0-alpha-windows-test-results
        path: Embroidermodder/test_results.txt
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: build dependencies and the software
      run: |
        git clone https://github.com/Embroidermodder/Embroidermodder
        cd Embroidermodder
        ./gradlew
    - name: archive android build
      uses: actions/upload-artifact@v3
      with:
        name: embroidermodder-2.0.0-alpha-android
        path: .
  build-iOS:
    runs-on: macos-latest
    steps:
    - name: build dependencies and the software
      run: |
        git clone https://github.com/Embroidermodder/Embroidermodder
        cd Embroidermodder
        ./build_ios.sh
    - name: archive iOS build
      uses: actions/upload-artifact@v3
      with:
        name: embroidermodder-2.0.0-alpha-ios
        path: .
