name: Build

on:
  schedule:
    - cron: '10 6 * * *'
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v6
        with:
          ref: 'current'
      - name: Build
        run: bash bin/build.sh "Ubuntu"
      - uses: action/upload-artifact@v7
        with:
          path: embroidermodder/build/embroidermodder*.zip.gz

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: action/checkout@v6
        with:
          ref: 'current'
      - name: Build
        run: bash bin/build.sh "MacOS"
      - uses: action/upload-artifact@v7
        with:
          path: embroidermodder/build/embroidermodder*.app

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: action/checkout@v6
        with:
          ref: 'current'
      - name: Build
        run: bash bin/build.sh "Windows"
      - uses: action/upload-artifact@v7
        with:
          path: embroidermodder/build/embroidermodder*.exe
