name: build

on: [push]

jobs:
  build_windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Install Qt
      run: |
        python -m pip install -U pip --upgrade pip
        pip install aqtinstall
        aqt install-qt windows desktop 6.2.0 win64_msvc2019_64

    - name: build
      run: |
        git clone https://github.com/embroidermodder/embroidermodder
        cd embroidermodder
        mkdir build
        cd build
        cmake -G "MinGW Makefiles" ..
        cmake --build .
        windeployqt embroidermodder2.exe
        cpack -G WIX
        cd ../..
        
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows Installer
        path: embroidermodder/embroidermodder_*

  build_macos:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Install Qt
      run: |
        brew install qt6 qwt

    - name: build
      run: |
        git clone https://github.com/embroidermodder/embroidermodder
        cd embroidermodder
        bash build.sh --macos
        mv build/embroidermodder2 embroidermodder2
        rm embroidermodder2/*.cpp embroidermodder2/*.h
        mv *manual*pdf embroidermodder2
        tar cf embroidermodder_2.0.0-alpha_macos.tar embroidermodder2
        
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MacOS
        path: embroidermodder/embroidermodder_2.0.0-alpha_macos.tar

  build_linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Install Qt
      run: |
        sudo apt install qt6-base-dev libqt6gui6 libqt6widgets6 libqt6printsupport6 libqt6core6 libgl-dev libglx-dev libopengl-dev

    - name: build
      run: |
        git clone https://github.com/embroidermodder/embroidermodder
        cd embroidermodder
        bash build.sh --linux
        mv build/embroidermodder2 embroidermodder2
        rm embroidermodder2/*.cpp embroidermodder2/*.h
        mv *manual*pdf embroidermodder2
        tar cf embroidermodder_2.0.0-alpha_linux.tar embroidermodder2
        
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: GNU/Linux Archive
        path: embroidermodder/embroidermodder_2.0.0-alpha_linux.tar

