name: Test building on major systems

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "15 3 * * 2"

jobs:
  os_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build
        run: |
          git clone https://github.com/embroidermodder/embroidermodder
          cd embroidermodder
          bash build.sh
