name: Build (Windows)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: bash build.sh --windows
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows Archive
        path: em2

