name: Build (GNU/Linux)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_gnu_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: bash build.sh --gnu-linux
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: GNU-Linux Archive
        path: em2

