name: Build (Windows)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - name: package
      run: |
        curl https://raw.githubusercontent.com/Embroidermodder/Embroidermodder/main/build.sh > build.sh
        bash build.sh --gnu-windows

    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows Archive
        path: embroidermodder/em2

