name: Build (experimental)

on:
#  push:
#    branches:
#      - experimental
  workflow_dispatch:
#  schedule:
#    - cron: "30 6 * * *"

jobs:
  build-libembroidery:
    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
    name: "Build on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build
        run: |
          git clone https://github.com/embroidermodder/libembroidery
          cd libembroidery
          mkdir build
          cd build
          cmake ..
          cmake --build .
      - uses: actions/upload-artifact@v4
        with:
          name: libembroidery-${{ matrix.os }}
          path: ./libembroidery

  test-libembroidery:
    needs: build-libembroidery
    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
    name: "Test on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: libembroidery-${{ matrix.os }}
      - name: Test
        run: ./embroider --test

  build-em2:
    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
    name: "Build on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build main
        run: |
          git clone https://github.com/embroidermodder/embroidermodder em2_main
          cd em2_main
          git checkout main
          ./build.sh ${{ matrix.os }}
      - uses: actions/upload-artifact@v4
        with:
          name: embroidermodder-${{ matrix.os }}-main
          path: ./em2_main

  build-em2-exp:
    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
    name: "Build on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build experimental
        run: |
          git clone https://github.com/embroidermodder/embroidermodder em2_exp
          cd em2_exp
          git checkout experimental
          ./build.sh ${{ matrix.os }}
      - uses: actions/upload-artifact@v4
        with:
          name: embroidermodder-${{ matrix.os }}-experimental
          path: ./em2_exp

  test-em2_main:
    needs: build-em2
    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
    name: "Test on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: embroidermodder-${{ matrix.os }}-main
      - name: Test
        run: timeout 10 ./embroidermodder --test

  test-em2_exp:
    needs: build-em2-exp
    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
    name: "Test on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: embroidermodder-${{ matrix.os }}-experimental
      - name: Test
        run: timeout 10 ./embroidermodder --test
