name: build

on: [push]

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64     

    - name: package
      run: |
        curl https://raw.githubusercontent.com/Embroidermodder/Embroidermodder/master/build.sh > build.sh
        bash build.sh --package-msi

    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows Installer
        path: embroidermodder/

  build_macos:
    runs-on: macos-latest
    steps:
    - name: package
      run: |
        curl https://raw.githubusercontent.com/Embroidermodder/Embroidermodder/master/build.sh > build.sh
        bash build.sh --package-macos
        
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MacOS Archive
        path: embroidermodder/

  build_linux:
    runs-on: ubuntu-latest
    steps:
    - name: package
      run: |
        curl https://raw.githubusercontent.com/Embroidermodder/Embroidermodder/master/build.sh > build.sh
        bash build.sh --package-linux
        
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: GNU Linux Archive
        path: embroidermodder/

  daily:
    name: Update latest release
    runs-on: ubuntu-latest
    needs: [build_windows, build_linux, build_macos]
    steps:
    - name: Get Windows MSI
      uses: actions/download-artifact@v2
      with:
        name: Windows Installer

    - name: Get MacOS Archive
      uses: actions/download-artifact@v2
      with:
        name: MacOS Archive

    - name: Get GNU Linux Archive
      uses: actions/download-artifact@v2
      with:
        name: GNU Linux Archive

    - name: daily
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          *.zip
