name: build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: build the linux version
      run: |
        sudo apt-get update
        sudo apt-get install libglew-dev cmake git build-essential libxrandr-dev libxinerama-dev libgl1-mesa-dev libxcursor-dev libxi-dev
        git clone https://github.com/embroidermodder/embroidermodder
        cd embroidermodder
        bash build.sh
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: embroidermodder-2.0.0-alpha-linux
        path: embroidermodder

  build-macos:
    runs-on: macos-latest
    steps:
    - name: build the mac os version
      run: |
        git clone https://github.com/embroidermodder/embroidermodder
        cd embroidermodder
        sh build.sh
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: embroidermodder-2.0.0-alpha-macos
        path: embroidermodder

  build-windows:
    runs-on: windows-latest
    steps:
    - name: build the windows version
      run: |
        git clone https://github.com/embroidermodder/embroidermodder
        cd embroidermodder
        .\build.bat
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: embroidermodder-2.0.0-alpha-windows
        path: embroidermodder
