name: Build

on:
  schedule:
    - cron: '10 6 * * *'
  push:
    branches:
      - 'current'
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: 'current'
      - name: Build
        run: bash build.sh --ci Ubuntu
      - name: archive production artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Ubuntu
          path: build

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: 'current'
      - name: Build
        run: bash build.sh --ci MacOS
      - name: archive production artifacts
        uses: actions/upload-artifact@v7
        with:
          name: MacOS
          path: build

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: 'current'
      - name: Build
        run: bash build.sh --ci Windows
      - name: Deploy
        run: |
          # This fails on translations but still functions,
          # so we use always() on subsequent steps and call it
          # here not in build.sh.
          cd build
          ./6.5.0/mingw_64/bin/windeployqt6.exe
          cd ..
      - name: Tidy
        if: always()
        run: rm -fr build/6.5.0
      - name: archive production artifacts
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: Windows
          path: build
