name: Build (Mac OS)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: bash build.sh --macos
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MacOS Archive
        path: em2

