name: Build and Test

on: [push]

jobs:
  build-pc:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: build the software
      run: |
        git clone https://github.com/Embroidermodder/Embroidermodder
        cd Embroidermodder
        bash em2.bash build
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: build dependencies and the software
      run: |
        git clone https://github.com/Embroidermodder/Embroidermodder
        cd Embroidermodder
        ./em2.bash android
  build-iOS:
    runs-on: macos-latest
    steps:
    - name: build dependencies and the software
      run: |
        git clone https://github.com/Embroidermodder/Embroidermodder
        cd Embroidermodder
        ./em2.bash ios
