name: Build (Windows, exp)

on:
  push:
    branches:
      - experimental

jobs:
  build:
    name: "Build on Windows"
    runs-on: windows-latest
    steps:
      - name: Get repository
        run: git clone https://github.com/embroidermodder/embroidermodder
      - name: Build
        run: cd embroidermodder; ./build.sh windows-latest
      - uses: actions/upload-artifact@v4
        with:
          name: embroidermodder-windows
          path: ./embroidermodder

