name: Nightly

on:
  workflow_dispatch:

jobs:
  nightly-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: 'current'
      - name: Build
        run: bash bin/build.sh "Ubuntu"
      - uses: actions/upload-artifact@v7
        with:
      - name: Update nightly release
        uses: eine/tip@master
        with:
         tag: nightly
         rm: true
         token: ${{ secrets.GITHUB_TOKEN }}
         files: embroidermodder/build/embroidermodder*.zip.gz

  nightly-macos:
    needs: nightly-linux
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: 'current'
      - name: Build
        run: bash bin/build.sh "MacOS"
      - uses: actions/upload-artifact@v7
        with:
          path: embroidermodder/build/embroidermodder*.app

  nightly-windows:
    needs: linux
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: 'current'
      - name: Build
        run: bash bin/build.sh "Windows"
      - uses: actions/upload-artifact@v7
        with:
          path: embroidermodder/build/embroidermodder*.exe
