name: Build (experimental)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-libembroidery:
    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
    name: "Build on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Build
        run: |
          git submodule init
          git submodule update
          cd extern/libembroidery
          mkdir build
          cd build
          cmake ..
          cmake --build .
      - uses: actions/upload-artifact@v4
        with:
          name: libembroidery-${{ matrix.os }}
          path: ./libembroidery

  test-libembroidery:
    needs: build-libembroidery
    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
    name: "Test on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: libembroidery-${{ matrix.os }}
      - name: Test
        run: ./embroider --test
