name: Windows

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: build the windows version
      run: |
        git clone https://github.com/embroidermodder/embroidermodder
        cd embroidermodder
        .\build.bat
    - name: archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: embroidermodder-2.0.0-alpha-windows
        path: embroidermodder/bin
